### ISSUE TITLE
RMarkdown overwrites images from python plots when using R und Python

### ISSUE THREAD

**Issue by TobiSonne** [rstudio/reticulate#1003]
I have a problem when I use Python and R in R Markdown. The numbering of plots that are saved in the folder `...-files/figure-latex` starts from 1 if there are R chunks between two Python chunks. The resulting files of the plots are also named after the first python chunk, I'm wondering about this. I'm not sure if this is a bug in rmarkdown or in reticulate but a creator of rmarkdown thinks that the problem is related to reticulate (see this issue https://github.com/rstudio/rmarkdown/issues/2134). I've attached a reproducible example. Thank you very much!
[minimal.zip](https://github.com/rstudio/reticulate/files/6465138/minimal.zip)

**Comment by cderv** [comment]
I believe this could be related to #1010 and could have been fixed by https://github.com/rstudio/reticulate/commit/a7e9a3af6d8f84e55a3663032e99e4d8f222105d

**Comment by kevinushey** [comment]
Yes, this should indeed be resolved in the development version of `reticulate`. Please try installing it with:

```
remotes::install_github("rstudio/reticulate")
```
