### ISSUE TITLE
Support for pipenv?

### ISSUE THREAD

**Issue by cboettig** [rstudio/reticulate#1006]
Would your team consider implementing more direct support for users using `pipenv` to manage the python environment?  

[Pipenv](https://github.com/pypa/pipenv) is a widely used approach maintained by the Python Packaging Authority, PyPa, for managing virtualenvs for different projects automatically by using a simple `Pipfile` in the project directory.  It is built on the virutalenv system, so we can still access pipenv environments with `reticulate` already, but it is cumbersome and lacks the syncing features we get from using pipenv directly, such as:

- You no longer need to use pip and virtualenv separately. They work together.
- Managing a requirements.txt file can be [problematic](https://kenreitz.org/essays/2016/02/25/a-better-pip-workflow)
- Hashes are used everywhere, always. Security. Automatically expose security vulnerabilities.

- pipenv also lets us install & switch between different python versions via pyenv, and a given project can be set to use a specific python version easily.

I know this also overlaps a bit with your `renv` package, and I'd be happy to transfer this issue there if you think that's better.  In general I think `pipenv` approach with a `Pipfile` is very much in the same spirit as `renv`, and is a bit cleaner way to do what `renv` tries to do with regards to python via `requirements.txt`.  Another nice feature of the `pipenv` approach is that you have consistent behavior in 'pure python' in the project, which automatically loads the Pipenv file, as you would in the R environment, instead of having to manually do something like `source renv/python/bin/activate` in the shell to make renv's python env accessible on the terminal.  Anyway I think @kevinushey would like `pipenv` and so just wanted to toss it out there!

**Comment by kevinushey** [comment]
The impression I get is that [poetry](https://python-poetry.org/) is a fair bit more popular than Pipenv nowadays though.

That said, I would be open to supporting both, depending on what "supporting" means -- what exactly would that entail? What are you hoping `reticulate` and / or `renv` could do for you here?

**Comment by cboettig** [comment]
Thanks @kevinushey , I'll take a closer look at `poetry`.  It doesn't seem to support a way to initialize with an arbitrary version of python though, like `pipenv --python 3.7`.  (My students and I are often switching between projects that require different versions of python, principally since we have some stuff that we want to run on the latest python and some stuff like tensorflow 1.x-based modules that don't support it!)   

To me, "supporting" just means a convenient way to activate the environment.  I could see this working automatically, based on the presence of a `Pipfile`, just as `renv` does with the presence of a `renv.lock`.  Ideally this would run on the trigger `reticulate` uses to activate the python environment, rather than happening automatically at the start of the R session (i.e. would be activated by `reticulate::py_config()` and would show up as the first/default option from `reticulate::py_discover_config()`, but not 'lock' the user in.  

Currently we have to activate a pipenv rather more manually, e.g.

```r
venv <- system("pipenv --venv", inter = TRUE)
reticulate::use_virtualenv(venv, required = TRUE) 
```



Would be curious to hear your thoughts on `poetry` too, it looks slick and sounds like it might be a little faster.  Am I right in understanding that unlike `pipenv`, it's not just building on existing `virutalenv` tools but doing it's own approach entirely?

**Comment by kevinushey** [comment]
> It doesn't seem to support a way to initialize with an arbitrary version of python though, like pipenv --python 3.7.

Looks like you're right -- the official documentation for poetry shows how to select an existing Python environment (https://python-poetry.org/docs/managing-environments/#switching-between-environments) but it doesn't appear to automagically download Python as `pipenv` does (which uses `pyenv` under the hood).

> To me, "supporting" just means a convenient way to activate the environment. I could see this working automatically, based on the presence of a Pipfile, just as renv does with the presence of a renv.lock. Ideally this would run on the trigger reticulate uses to activate the python environment, rather than happening automatically at the start of the R session (i.e. would be activated by reticulate::py_config() and would show up as the first/default option from reticulate::py_discover_config(), but not 'lock' the user in.

That sounds like a good idea to me. I'll re-summarize just to make sure I understand: if `reticulate` sees a `Pipfile` in the project folder, then it could use a virtual environment derived from that `Pipfile`. That virtual environment can be created and queried on-demand via `pipenv --venv`.

> Would be curious to hear your thoughts on poetry too, it looks slick and sounds like it might be a little faster. Am I right in understanding that unlike pipenv, it's not just building on existing virutalenv tools but doing it's own approach entirely?

I think poetry still uses virtual environments under the hood; it's just providing its own front-end to Python dependency management. In that end, I think they're basically two different tools trying to do roughly the same thing.

**Comment by cboettig** [comment]
> I'll re-summarize just to make sure I understand: if reticulate sees a Pipfile in the project folder, then it could use a virtual environment derived from that Pipfile. That virtual environment can be created and queried on-demand via pipenv --venv.

precisely.  :+1: 

I suppose more sophisticated support would wrap more functions from the `pipenv` CLI, such as the ability to create a new pipenv.  But I'm fine if you see that as out of scope, I'd be happy with `reticulate` at least just recognizing a Pipfile if it exists.  

(Not sure if I ever quite grokked the lookup chain for the default environment `reticulate` uses, I believe the rule is that unless it's forced by `RETICULATE_PYTHON_VENV`  it's alphabetically the first virtual env it finds in the `WORKON_HOME` dir?

**Comment by kevinushey** [comment]
Thanks -- this has now been implemented. If you're working within a project that uses `pipenv` (that is, has a `Pipfile` located at the project root), then `reticulate` will by default use the pipenv-configured virtual environment.

```
> list.files()
[1] "Pipfile"
> reticulate::py_config()
python:         /Users/kevinushey/.local/share/virtualenvs/pipenv-2H58zYvm/bin/python
libpython:      /Users/kevinushey/.pyenv/versions/3.7.9/lib/libpython3.7m.dylib
pythonhome:     /Users/kevinushey/.local/share/virtualenvs/pipenv-2H58zYvm:/Users/kevinushey/.local/share/virtualenvs/pipenv-2H58zYvm
virtualenv:     /Users/kevinushey/.local/share/virtualenvs/pipenv-2H58zYvm/bin/activate_this.py
version:        3.7.9 (default, Jan 26 2021, 10:21:11)  [Clang 12.0.0 (clang-1200.0.32.28)]
numpy:           [NOT FOUND]

NOTE: Python version was forced by Pipfile
```

Note that `RETICULATE_PYTHON` and `use_python(..., required = TRUE)` usages will still take precedence. Let me know how this works in your case.
