### ISSUE TITLE
regression Reticulate 1.20 and RMarkdown ? 

### ISSUE THREAD

**Issue by JohnLeM** [rstudio/reticulate#1010]
Hello, I added this [entry ](https://community.rstudio.com/t/knitr-reticulate-and-rstudio-problem-with-figure-labelling/105594) to RStudio community. As a rmarkdown user, I had to roll-back to reticulate V 1.16. I don't know however if this problem come from reticulate or rmarkdown.

**Comment by kevinushey** [comment]
Just to copy the relevant context in... when rendering this document, the figure associated with the final chunk is rendered in both chunks:

`````
---
output: html_document
---

```{r setup, include=FALSE}
library(reticulate)
```

```{python}
import matplotlib.pyplot as plt
plt.plot([1, 2])
```

```{r}
x <- 2
``` 

```{python}
plt.plot([7, 8])
```
`````

I'll take a look.

**Comment by kevinushey** [comment]
Should now be fixed via https://github.com/rstudio/reticulate/commit/a7e9a3af6d8f84e55a3663032e99e4d8f222105d -- sorry for the trouble.

Are you able to download the development version of `reticulate` to test? You can do so with `remotes::install_github("rstudio/reticulate")`.

**Comment by JohnLeM** [comment]
Hello,
[I installed the dev version and tested it. It seems to work finely](https://drive.google.com/file/d/1B9xSgs0Lv_gQqUfySoece8XU9UnEfrcY/view?usp=sharing)
Thank you for your quick and efficient answer.

**Comment by kevinushey** [comment]
Glad to hear it! Thanks for taking the time to verify.
