### ISSUE TITLE
When using Python ,I find help() or '?' cannot work effectively

### ISSUE THREAD

**Issue by suye0620** [rstudio/reticulate#1011]
Dear developers,
    When I use Python in Rstudio, I find that help() or '?' cannot work effectively. The function hasn't been supported, has it?

![图片](https://user-images.githubusercontent.com/71215104/119758400-12f29300-bed9-11eb-8b22-61f18556275f.png)
![图片](https://user-images.githubusercontent.com/71215104/119758835-ca87a500-bed9-11eb-869d-64838f8aad12.png)

**Comment by kevinushey** [comment]
I believe this is a bug in reticulate 1.20, and should be resolved in the development version of reticulate. Can you try installing it with:

```
remotes::install_github("rstudio/reticulate")
```

**Comment by whipson** [comment]
Was having the same issue with version 1.20. Using the development version fixed it.

**Comment by suye0620** [comment]
Thanks a lot! It works now.
