### ISSUE TITLE
Wrong miniconda architecture use by `reticulate::install_miniconda`

### ISSUE THREAD

**Issue by dipterix** [rstudio/reticulate#1012]
Linux ARM installation goes wrong by default. Possibly installing x64 version. I ended up installing miniconda by myself

OS info: (Raspberry PI 4 B)
```
R version 4.1.0 (2021-05-18)
Platform: aarch64-conda-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)
```

Lines with issues:
```r
> reticulate:::miniconda_installer_url()
[1] "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
```
which should be https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-armv7l.sh instead.

Here is my R version info in case you don't have arm linux in hand. Check `arch` item

```r
> R.Version()
$platform
[1] "aarch64-conda-linux-gnu"

$arch
[1] "aarch64"

$os
[1] "linux-gnu"

$system
[1] "aarch64, linux-gnu"

$status
[1] ""

$major
[1] "4"

$minor
[1] "1.0"

$year
[1] "2021"

$month
[1] "05"

$day
[1] "18"

$`svn rev`
[1] "80317"

$language
[1] "R"

$version.string
[1] "R version 4.1.0 (2021-05-18)"

$nickname
[1] "Camp Pontanezen"


```

**Comment by dipterix** [comment]
Also after installing conda, reticulate complaint `No non-system installation of Python could be found.` but python3 is available with the system

```r
> reticulate::py_config()
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: n
Installation aborted.
python:         /home/pi/miniconda3/bin/python3
libpython:      /home/pi/miniconda3/lib/libpython3.9.so
pythonhome:     /home/pi/miniconda3:/home/pi/miniconda3
version:        3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:03:40)  [GCC 9.3.0]
numpy:          /home/pi/miniconda3/lib/python3.9/site-packages/numpy
numpy_version:  1.20.3

```

**Comment by kevinushey** [comment]
This is where we construct the Miniconda URL -- unfortunately we don't handle arm64 yet.

https://github.com/rstudio/reticulate/blob/a7e9a3af6d8f84e55a3663032e99e4d8f222105d/R/miniconda.R#L93-L109

The fact that your miniconda installation wasn't discovered is a bit surprising, though -- it should be part of the paths we check...

https://github.com/rstudio/reticulate/blob/a7e9a3af6d8f84e55a3663032e99e4d8f222105d/R/conda.R#L436

I don't have access to an arm64 machine so I'm not able to debug further yet.

**Comment by kevinushey** [comment]
Could you also share the output of `Sys.info()`?

**Comment by dipterix** [comment]
@kevinushey Sure, here you go

```r
> Sys.info()
                                         sysname 
                                         "Linux" 
                                         release 
                                   "5.10.17-v8+" 
                                         version 
"#1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021" 
                                        nodename 
                                   "raspberrypi" 
                                         machine 
                                       "aarch64" 
                                           login 
                                            "pi" 
                                            user 
                                            "pi" 
                                  effective_user 
                                            "pi" 
```

**Comment by dipterix** [comment]
@kevinushey any updates?

**Comment by kevinushey** [comment]
Sorry for taking so long to get to this. It looks like things should work with the development version of reticulate, as Miniconda now publishes their installer script at:

https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh

Please re-open if you see any other issues.

**Comment by dipterix** [comment]
Thanks for the good news
