### ISSUE TITLE
Wrong Architecture on M1 chip (R 4.1.0 ARM)

### ISSUE THREAD

**Issue by dipterix** [rstudio/reticulate#1019]
I installed R 4.1.0 (ARM) that supports Apple M1 chip natively. However, reticulate cannot launch python

```
 Error in py_initialize(config$python, config$libpython, config$pythonhome,  : 
  /Users/dipterix/Library/r-ravepy/ravepy-conda-env/lib/libpython3.9.dylib - dlopen(/Users/dipterix/Library/r-ravepy/ravepy-conda-env/lib/libpython3.9.dylib, 10): no suitable image found.  Did find:
	/Users/dipterix/Library/r-ravepy/ravepy-conda-env/lib/libpython3.9.dylib: mach-o, but wrong architecture
	/Users/dipterix/Library/r-ravepy/ravepy-conda-env/lib/libpython3.9.dylib: mach-o, but wrong architecture 
```

After some debugging, I found the conda installed by `reticulate` was `x86_64` arch while R is arm64:

R session information:

```r
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Big Sur 11.4
```

Reticulate download message:
```
* Downloading 'https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh' ...
trying URL 'https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh'
Content type 'application/x-sh' length 57112343 bytes (54.5 MB)
==================================================
downloaded 54.5 MB
```

In case you need system information:

```
> Sys.info()
                                                                                                sysname 
                                                                                               "Darwin" 
                                                                                                release 
                                                                                               "20.5.0" 
                                                                                                version 
                                                                                                "XXXXX" 
                                                                                               nodename 
                                                                                                "XXXXXX" 
                                                                                                machine 
                                                                                                "arm64" 
                                                                                                  login 
                                                                                                 "root" 
                                                                                                   user 
                                                                                             "dipterix" 
                                                                                         effective_user 
                                                                                             "dipterix" 
```

This is similar to a previous issue #1012 , but that one was on linux. This is on mac

**Comment by dipterix** [comment]
Just noticed that miniconda is unavailable to osx arm. This might take a while to fix. 

For those who tracked this issue, you might need to install your own version of miniconda via https://github.com/conda-forge/miniforge

Make sure you set your conda folder during the installation to be `~/miniconda3`

**Comment by dipterix** [comment]
Any updates?

**Comment by kevinushey** [comment]
Not yet; I think we're basically waiting for Anaconda to release an M1 build of Anaconda. For now, I'd recommend users on M1 macOS to use Python virtual environments instead of Anaconda with reticulate.

**Comment by dipterix** [comment]
I found `conda-forge`'s version works pretty well on M1 chip. I got a work-around for function `miniconda_installer_url` 

Also for the previous issue on ARM linux, the arch name should be `armv71` or `armv61` instead of `x86(_64)`

Is there any reasons why `conda-forge`'s build may be bad? (just want to know if there's any potential issue I should take care of.)

```
  base <- "https://repo.anaconda.com/miniconda"
  rver <- R.version
  if( isTRUE(rver$arch == "aarch64") ){
    arch <- "armv71"
    if( startsWith(rver$os, 'darwin') ){
      return("https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh")
    }
  } else {
    arch <- ifelse(.Machine$sizeof.pointer == 8, "x86_64", "x86")
  }
```

Source:
https://github.com/dipterix/ravepy/blob/84b71d081a79525afdf1f63a277327d9954eb3c0/R/download.R#L3-L12

**Comment by kevinushey** [comment]
My main worry is that (if I understand correctly) conda forge is more of a moving target, so I worry that if we build integrations for that in reticulate we might end up putting ourselves (or users) in a place where they're struggling to maintain that installation. Feel free to correct me if I'm wrong, though.

Either way though, it seems like users should still be able to install and manage Conda / Miniconda installations separate of reticulate, and then simply ask reticulate to point at their newly-installed Conda installation.

**Comment by dipterix** [comment]
So maybe in `miniconda_installer_url`, get installation url from `options`? 

Here are several issues on osx M1 chip

1. M1 with x86 R installed
The virtualenv is buggy because the compilers might be arm build from the system, but R request x86 libraries

2. M1 with ARM R installed
This is probably the most recommended way because many packages need `brew install` libraries, and by default, brew is ARM-built.
However, it requires non-trivial work to find out how to install ARM conda.

What could be worse is that users might find that conda is unavailable on their machine, so they install conda from reticulate. Reticulate will show that conda is installed, but when they try to load python, it fails because the arch does not match.


There is no general solutions on Mac, so I guess it's probably the best to allow users to override where to download `miniconda.sh` from.

(Also this will fix the issues on ARM Linux)

**Comment by kevinushey** [comment]
I've made a couple changes on master now:

- `install_miniconda()` prefers installing the arm64 builds from miniforge, as described in https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/
- `miniconda_path()` uses a separate path for arm64 miniconda, to avoid collisions with x86_64 miniconda

Hopefully this will smooth the transition for users on M1 macOS.
