### ISSUE TITLE
kerasR not available.

### ISSUE THREAD

**Issue by cosmos2006** [rstudio/reticulate#102]
While installing KerasR through devtools, I get the following error:
>devtools::install_github("statsmaths/kerasR",repos="http://www.vps.fmvz.usp.br/CRAN/")
keras not available

See reticulate::use_python() to set python path, 
then use kerasR::keras_init() to retry
* DONE (kerasR)

Even after setting path to python, problem persists, i.e.,
> reticulate::use_python("/usr/bin/python")
> kerasR::keras_init()

keras not available

Problem similar to above problem is reported in 
https://github.com/statsmaths/kerasR/issues/20

How to get away with this problem?

**Comment by jjallaire** [comment]
You need to ensure that the Keras python package has been installed and is verified to be working correctly within the Python environment you are using (in this case the system default /usr/bin/python).
