### ISSUE TITLE
Mathematical Operation for Numpy Array in R are not possible?

### ISSUE THREAD

**Issue by FlyImagi** [rstudio/reticulate#1029]
So I have a data that I like to transform using PaCMAP in Python, with this reproducable example:

```
import pandas as pd
import pacmap

fraud_data = pd.read_csv(r'C:/Users/User/Desktop/Open Source Dataset/fraud_data.csv')
embedding = pacmap.PaCMAP(n_dims=2, n_neighbors=None, MN_ratio=0.5, FP_ratio=2.0) 
X_transformed = embedding.fit_transform(fraud_data.values, init="pca")
fraud_transformed = pd.DataFrame(X_transformed)
```

I recreated this in R using reticulate:

```
python_pandas <- import("pandas")
python_pacmap <- import("pacmap")
python_numpy <- import("numpy")
fraud_pandas <- reticulate::r_to_py(fraud_data)
nparray <- fraud_pandas$values
nparray <- nparray$astype(python_numpy$float)

embedding <- python_pacmap$PaCMAP(n_dims=2, n_neighbors="None", MN_ratio=0.5, FP_ratio=2.0) 
X_transformed <- embedding$fit_transform(nparray, init="pca")
fraud_transformed = python_pandas$DataFrame(X_transformed)
```

But when I recreated this in R, it triggered a following error near the `embedding$fit_transform(fraud_pandas, init="pca")`: 
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: can't multiply sequence by non-int of type 'float'
```

I too also found that doing mathematical operation to numpy array, such as this:

`nparray[1] + 1`

Will produce an error of: `Error in nparray[1] + 1 : non-numeric argument to binary operator`

I feel like these errors are somewhat linked, and as the title says, are mathematical operation for Numpy Array in R are not really possibles?

(Note: I am using this sample dataset to reproduce the error: https://drive.google.com/file/d/1Yt4V1Ir00fm1vQ9futziWbwjUE9VvYK7/view?usp=sharing)

**Comment by kevinushey** [comment]
Before I take a closer look: does setting `n_dims=2L` instead of `n_dims=2` help? Often, when calling Python APIs from `reticulate`, you need to be explicit about whether you're passing a double (float) or an integer.

(Also note; in R, plain literals are parsed as doubles; you need to add an `L` suffix to force them to be parsed as integers.)

**Comment by FlyImagi** [comment]
@kevinushey Now that you mention the `embedding` parameters, I found the culprit which is `n_neighbors="None"` I honestly didnt know what to write None in R, so when I change it using NULL, the problem is fixed! Thanks also for some note of converting  using `L` suffix to integers
