### ISSUE TITLE
the non-standard evaluation done by 'dict()' leads to unexpected behavior

### ISSUE THREAD

**Issue by kevinushey** [rstudio/reticulate#103]
Small example I bumped into while using `tfestimators`:

```R
library(reticulate)
library(tfestimators)

age <- column_numeric("age")
height <- column_numeric("height")

train_data <- data.frame(
  age = c(29, 38, 42),
  height = c(180, 190, 170)
)

dict(train_data)
```

This gives:

```R
> dict(train_data)
{_NumericColumn(key='height', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None): [180.0, 190.0, 170.0], _NumericColumn(key='age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None): [29.0, 38.0, 42.0]}
```

when I expected the keys would remain as-is as named strings.

This seems like a relatively dangerous landmine. I recall this behavior was implemented as arbitrary Python objects can be keys within a Python dictionary, but I wonder if we should instead consider a more explicit mechanism for requesting this behavior?

**Comment by terrytangyuan** [comment]
Wow that's a good found. I wonder whether it might be better if we use the with_columns() syntax to explicitly define feature columns.

**Comment by kevinushey** [comment]
Probably, but the danger is that really _any_ variable defined in the parent environment that happens to be a Python object and clashes with a name of the input dataset will cause this issue -- that is, although this example is demonstrated with `tfestimators` it's really an issue with `dict()` itself.

**Comment by jjallaire** [comment]
The feature was actually put in so that we could use tensors as keys (which
is required for feed_dict). We could change the behavior so that we look
for only specific types or so that types can explicitly register for this
treatment.

**Comment by kevinushey** [comment]
Where do we take advantage of this behavior? I wonder if we should just encourage using a two-argument form of `dict()` accepting both keys and values, e.g. `dict(keys, vals)`, to better handle the case where keys might be non-string elements?

**Comment by terrytangyuan** [comment]
Here below is the list of acceptable signatures of `dict()`. There isn't one for `dict(k, v)` though. It would be better without inventing new syntax in my opinion.

```
class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |
```

**Comment by jjallaire** [comment]
Users take advantage of it whenever they train a TF model using the core
API (anytime you evaluate a tensor you need to pass a dictionary of
placeholder = value where the placeholder is also a tensor).

**Comment by jjallaire** [comment]
If users pass a single R list then we can safely assume that the keys are
not Python objects (because there is no way to have an R list with objects
as keys). So for this particular case I could just not do the scan of the
parent frame and you'd get the behavior you expect.

I agree this is a field of potential landmines. When implementing the
feature I wanted the syntax on the R side to match as closely as possible
that of the Python side (thus dict providing keys and values inline). I'm
hopeful that if we handle this case we'll be mostly out of the woods.

**Comment by jjallaire** [comment]
PR here: https://github.com/rstudio/reticulate/pull/105

**Comment by kevinushey** [comment]
That sounds like the right compromise to me.

**Comment by terrytangyuan** [comment]
Nice!
