### ISSUE TITLE
Error with reticulate when submitting an R package to CRAN

### ISSUE THREAD

**Issue by vonnwalter23** [rstudio/reticulate#1051]
Hi Everyone,

I am trying to submit an R package (mypackage in the text below) that uses reticulate to call a single Python script (myscript.py in the text below).  The vignette is written in RMarkdown, and the vignette compiles without any problems when I used RStudio.  I get no errors when I run devtools::check() on my desktop (Windows 10) or a computing cluster running Red Hat Linux Enterprise 7.  Similarly, I had no problems with devtools::check_rhub() or devtools::check_win_devel().

However, I got the following WARNING when I tried to use devtools:release() to submit mypackage to CRAN.

Quitting from lines 95-101 (mypackage_vignette.Rmd)
Error: processing vignette 'mypackage_vignette.Rmd' failed with diagnostics:
Error 2 occurred running C:/Users/XXXX/AppData/Local/r-miniconda/envs/r-reticulate/python.exe 
--- failed re-building 'mypackage_vignette.Rmd'

As a guess, the problem is with one of the following two lines of code:

path = paste(system.file(package = "mypackage"), "python", "myscript.py", sep = "/")
reticulate::source_python(path)

Any thoughts would be greatly appreciated.

Thanks,

Vonn

**Comment by turgut090** [comment]
@vonnwalter23 try to set the code evaluation to FALSE.
```
```{r, eval = FALSE}
plot(cars)
```
```

**Comment by vonnwalter23** [comment]
Thanks for your response, @turgut090 .  Unfortunately, this does not work.  The code chunk that includes the two lines of code in my original message needs to be evaluated because it creates a simulated null distribution that is used later in the vignette.

**Comment by turgut090** [comment]
@vonnwalter23 maybe you could try to save the data, keep the code without evaluation and load the hidden data.

**Comment by vonnwalter23** [comment]
I appreciate the suggestion, @turgut090 , and that very well may work.  However, given the choice between that and creating a static vignette, I think I'll go with the static vignette.

**Comment by kevinushey** [comment]
I would also strongly suggest creating a static vignette and avoid running any code on CRAN that might depend on Python / reticulate directly (as unfortunately I have no real control over what version of Python is installed or used on CRAN and I doubt there is any CRAN policy that really allows reticulate to install or manage its own Python distributions)

**Comment by vonnwalter23** [comment]
Thanks, @kevinushey .  I think that seals the deal... static vignette is the way to go.  I'll close this thread now.
