### ISSUE TITLE
reticulate::conda_install(pip=TRUE) broken for 1.21

### ISSUE THREAD

**Issue by andrew-christianson** [rstudio/reticulate#1052]
With the recently-released reticulate 1.21, `conda_install` fails if pip=TRUE e.g.

```r
install.packages('reticulate')
reticulate::conda_create("r-test-broken", packages=c('python=3.8'))
reticulate::conda_install("tqdm", pip=TRUE, envname="r-test-broken")
```
returns the error: 

```r
Error in conda_dll_paths() : conda environment r-reticulate not found
```

with traceback

```
4: stop("conda environment ", envname, " not found")
3: conda_dll_paths()
2: pip_install(python = python, packages = packages, pip_options = pip_options,
       ignore_installed = pip_ignore_installed)
1: reticulate::conda_install("tqdm", pip = TRUE, envname = "r-test-broken")
```

AFAICT, the issue is that  1.21 adds a call to [conda_dll_paths](https://github.com/rstudio/reticulate/blob/e48fb8cf09989fe7c3e7e708ece4058fdfd7cbfa/R/conda.R#L403) in [pip_install](https://github.com/rstudio/reticulate/blob/e48fb8cf09989fe7c3e7e708ece4058fdfd7cbfa/R/pip.R#L33), without passing the environment name, so it ultimately falls back to the [default](https://github.com/rstudio/reticulate/blob/4967abddb35865a1be6ad839298695f1481bcade/R/python-environments.R#L5) case of python_environment_resolve, which reports ‘r-reticulate’ unless the user has set RETICULATE_PYTHON_ENV.  That environment is not guaranteed to exist, so the following subset returns a 0-row data frame and falls back to the 'environment not found' error condition.

I'm not close enough to reticulate's development to know the right fix, but seems like, at least, pip_install should take an envname to pass to conda_dll_paths, and conda_install should provide the env set by the user? 

For completeness, session and system info, but I've replicated this on a few systems, including Databricks and the one below (a local dev machine)
sessionInfo:
```
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 11 (bullseye)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.13.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] compiler_4.1.1  Matrix_1.3-4    tools_4.1.1     parallel_4.1.1
 [5] rappdirs_0.3.3  Rcpp_1.0.7      reticulate_1.21 grid_4.1.1
 [9] jsonlite_1.7.2  png_0.1-7       lattice_0.20-44
```

Sys.info:
```
                               sysname                                release
                               "Linux"                       "5.10.0-8-amd64"
                               version                               nodename
"#1 SMP Debian 5.10.46-4 (2021-08-03)"                snip
                               machine                                  login
                              "x86_64"                               snip
                                  user                         effective_user
                              snip                               snip```

**Comment by kevinushey** [comment]
Thanks for the bug report. I'll take a look and re-submit soon. cc: @bnaras

**Comment by kevinushey** [comment]
A workaround, I believe, would be to set the `RETICULATE_PYTHON_ENV` environment variable to the desired environment, if you needed a short-term workaround.

**Comment by andrew-christianson** [comment]
@kevinushey Yup, that's working for my needs right now.  Sorta brittle though, if the user doesn't completely control the name of the environment, so hopefully this can be fixed quickly? 

For reference, the my proximate issue is that this breaks `mlflow::install_mlflow()` on clean systems (new Databricks clusters in my instance).  Running

```r
install.packages('mlflow')
mlflow::install_mlflow()
````

fails with the same error and traceback as above.

This can be resolved (as you note) by setting RETICULATE_PYTHON_ENV to the conda environment mlflow creates for itself e.g.

```r
Sys.setenv(RETICULATE_PYTHON_ENV="r-mlflow-1.20.2")
```

before running `install_mlflow`.  This of course depends on the name of the environment mlflow picks, which as of the current version is as above, but will change with new versions.

**Comment by kevinushey** [comment]
I tried submitting a fix to CRAN but they were unhappy to see a CRAN submission in such quick succession from the previous release.

**Comment by kevinushey** [comment]
I believe this should now be fixed in the development version of `reticulate`, as well as the version currently on CRAN.
