### ISSUE TITLE
provide mechanism for submitting incomplete lines to Python console

### ISSUE THREAD

**Issue by kevinushey** [rstudio/reticulate#106]
Motivation: I'm trying to write a `knitr` engine for `reticulate` that allows for the interleaving of code input and outputs. To that end, I think it's necessary to be able to submit code line-by-line to the Python session -- for example:

    ```{python}
    x = 1
    print(x)

    y = 2
    print(y)
    ```

It would be great if we were able to run code line-by-line here, capturing outputs as lines are executed, so that the output of each `print` statement is shown immediately below the associated statement. (This would hopefully include generated images down the line as well; not just console output)

One thing that makes this a bit trickier is multi-line statements, e.g.

```{python}
x = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Is there any way for us to submit a line to the Python console, and get a console 'status' back (e.g. incomplete input vs. complete input and so on)? It seems like this isn't provided by `py_run_string()` so I'm wondering if there's a somewhat lower-level / more nuanced API we can use here.

**Comment by kevinushey** [comment]
One potential route is for us to submit code line-by-line with `py_run_string`, catch the generated syntax errors, and then 'grow' the code we're sending to the console when we hit those cases, but that feels a little gross.

**Comment by jjallaire** [comment]
I don't know if there is analogous C API for Python that submits to the Python REPL (as there is with R). Here is the entire C API: https://docs.python.org/2/c-api/index.html. It may be that Python REPLs are just built on top of the equivalent of py_run_string (along with some parsing to detect complete statements).

**Comment by kevinushey** [comment]
It looks like you're right -- all of the Python APIs expect complete statements; there isn't a way to submit incomplete statements to Python without a terminal emulator on top of the main interpreter loop.

Perhaps we can use [Py_CompileString](https://docs.python.org/2/c-api/veryhigh.html#c.Py_CompileStringFlags) and [PyEval_EvalCode](https://docs.python.org/2/c-api/veryhigh.html#c.PyEval_EvalCode). We can iteratively attempt to compile and grow a block of Python code, and only submit it after that compilation has succeeded.

**Comment by jjallaire** [comment]
Py_CompileString looks like just what we need!

**Comment by kevinushey** [comment]
Closing this as we accomplished this by using the Python AST module (a Python AST has source references that map statements back to the lines they were found on)
