### ISSUE TITLE
Problem with reticulate on shiny-server inside Docker 

### ISSUE THREAD

**Issue by mranjos** [rstudio/reticulate#1072]
Hello everyone

I encounter some problems when using reticulate in the Docker environment when I run shiny-server.

Below is the creation of the Docker:

>FROM rocker/shiny:4.1.1

>RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libssl-dev \
	libv8-dev
	
>RUN apt-get install -y r-base python3 python3-dev python3-pip python3-venv

>RUN R -e "install.packages('shinydashboard', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('devtools', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('DT', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('shinyjs', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('data.table', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('ggplot2', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('dplyr', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('jsonlite', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('stringr', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('plotly', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('V8', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('httr', dependencies = TRUE, warning = function(w) stop(w))" && \ 
	R -e "install.packages('memoise', dependencies = TRUE, warning = function(w) stop(w))" && \ 
	R -e "install.packages('shiny', dependencies = TRUE, warning = function(w) stop(w))" && \ 
	R -e "install.packages('shinydashboardPlus', dependencies = TRUE, warning = function(w) stop(w))" && \ 
	R -e "install.packages('shinyBS', dependencies = TRUE, warning = function(w) stop(w))" && \ 
	R -e "install.packages('shinybusy', dependencies = TRUE, warning = function(w) stop(w))" && \ 
	R -e "install.packages('shinyWidgets', dependencies = TRUE, warning = function(w) stop(w))" && \ 
	R -e "install.packages('shinyMobile', dependencies = TRUE, warning = function(w) stop(w))" && \ 
	R -e "install.packages('shinycssloaders', dependencies = TRUE, warning = function(w) stop(w))" && \ 
	R -e "install.packages('sass', dependencies = TRUE, warning = function(w) stop(w))" && \ 
	R -e "install.packages('ggiraph', dependencies = TRUE, warning = function(w) stop(w))" && \ 
	R -e "install.packages('tidyr', dependencies = TRUE, warning = function(w) stop(w))" && \ 
	R -e "install.packages('janitor', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('lubridate', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('reticulate', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "reticulate::virtualenv_create('myEnvironment')" && \
	R -e "reticulate::virtualenv_install('myEnvironment', packages = c('numpy','pandas'))" && \
	R -e "reticulate::use_virtualenv('myEnvironment')" && \
	R -e "install.packages('waiter', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('colourpicker', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('sampling', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('callr', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('InformationValue', dependencies = TRUE, warning = function(w) stop(w))" && \
	R -e "install.packages('pROC', dependencies = TRUE, warning = function(w) stop(w))"
	
>ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
ENV RETICULATE_PYTHON="/root/miniconda3/bin/python"
RUN apt-get update

>RUN apt-get install -y wget && rm -rf /var/lib/apt/lists/*

>RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh  \
	&& conda install anaconda -y

>RUN sudo chown -R shiny:shiny /srv/shiny-server

>COPY "Dash/Modulos/" /srv/shiny-server/

When I open R via bash, using
docker run -it --rm -p 3838:3838 shinyserver bin/bash

And I run R in cmd, including using Reticulate functions, everything works perfectly

> R
> library(reticulate)
> py_config()
python: /root/miniconda3/bin/python
libpython: /root/miniconda3/lib/libpython3.9.so
pythonhome: /root/miniconda3:/root/miniconda3
version: 3.9.4 (default, Apr 9 2021, 16:34:09) [GCC 7.3.0]
numpy: /root/miniconda3/lib/python3.9/site-packages/numpy
numpy_version: 1.20.1

NOTE: Python version was forced by RETICULATE_PYTHON

But the problem occurs when I run the shiny-server application

`docker run -it --rm -p 3838:3838 -v C:/shiny_log/:/var/log/shiny-server/ shinyserver`

When running app.R inside /srv/shiny-server address
R just can't find Python, including py_config() the settings are different:

> R
> library(reticulate)
> py_config()
python: /usr/bin/python3
libpython: /usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.so
pythonhome: //usr://usr
version: 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
numpy:
numpy_version:

When I try to set RETICULATE_PYTHON, through Sys.setenv(RETICULATE_PYTHON = "/root/miniconda3/bin/python") it just doesn't find the python that appears in bash

`Warning: Error in py_discover_config: Python specified in RETICULATE_PYTHON (/root/miniconda3/bin/python) does not exist
  59: stop
  58: py_discover_config
  57: initialize_python
  56: ensure_python_initialized
  55: reticulate::py_config
  47: server [/srv/shiny-server/app.R#401]
Error in py_discover_config(required_module, use_environment) :
  Python specified in RETICULATE_PYTHON (/root/miniconda3/bin/python) does not exist
`

And when I run cond_list() the return is this:

`Warning: Error in : Unable to find count binary. Is Anaconda installed?
  57: stop
  56: count_binary
  55: reticulate::conda_list
  47: server [/srv/shiny-server/app.R#401]
Error : Unable to find count binary. Is Anaconda installed?
`

Does anyone know why this happens and how to solve it?

**Comment by kevinushey** [comment]
The following works fine for me (rendered via `rmarkdown::render()`):

`````
---
title: "Untitled"
output: html_document
---

```{r}
library(reticulate)
token <- 42
```

```{python}
print(r.token)
```
`````

 What version of `reticulate` are you using? Can you provide a more minimal reproducible example?

**Comment by Biaggio74** [comment]
@kevinushey doest it work for you in Docker too? ...in Rstudio this works fine for me too. But once Dockerized, it stops working.

**Comment by kevinushey** [comment]
My only guess is that your Docker container is installed a different version of `reticulate` that doesn't handle this correctly.

**Comment by Biaggio74** [comment]
Thank @kevinushey for the suggestion. It was very promising as my local install of `reticualte` was 1.22, the latest but in the container it as `1.18`. With new docker image of `rocker/verse` I got finally the `1.22` but unfortunately still not workig. However, I have a new error message, so it might already passing the issue with the variables. It seems that it is quitting when establish the network connection. The error looks like this:

```bash
Quitting from lines 73-90 (MASTER_REPORT_LATTICE_EN.Rmd) 

<Rcpp::exception in py_call_impl(callable, dots$args, dots$keywords): ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/get-structure (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0888d77670>: Failed to establish a new connection: [Errno 111] Connection refused'))

Detailed traceback:
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
>
```

Doing all things outside the container, so on a local server it works perfectly. Do you have a suggestion what can be the issue?

**Comment by kevinushey** [comment]
Sorry, but as far as I can see this error is likely unrelated to reticulate and is just a plain issue in the Python `requests` package, or with your Docker container's ability to communicate with your server.

**Comment by Biaggio74** [comment]
Hi @kevinushey you were right, this wasn't a reticulate issue. ...finally I got it work through a lots of back and forth, and by isolating the issue. The solution was to push to production the services which I was running locally (i.e on port:8000) and call those production endpoints from the Rmarkdown document. It works both with the `httr` package with `R` and `reticulate + requests` from `Python`. ...I am still not sure why the connection fails with a localhost if running as a Docker container.
