### ISSUE TITLE
Feature Request: `reticulate::uninstall_miniconda()`

### ISSUE THREAD

**Issue by njtierney** [rstudio/reticulate#1077]
Hi there!

I was wondering if there could be scope for a `reticulate::uninstall_miniconda`? There is currently `reticulate::install_miniconda()` and having the option to uninstall it would help with debugging certain python issues.

**Comment by t-kalinowski** [comment]
I think typically this will do what you want:
```r
unlink(reticulate::miniconda_path(), recursive = TRUE)
```

**Comment by richelbilderbeek** [comment]
I second the desire for `uninstall_miniconda`! Sure, @t-kalinowski, that it can already be done in a way is great, yet it is nicer to find it in the documentation or pop-up-list when looking in the `reticulate` functions.

As it is so easy, I'd be happy to volunteer to contribute this as a pull request:

```
uninstall_minicoda <- function() {
  unlink(reticulate::miniconda_path(), recursive = TRUE)
}
```

I also want to add, is that this solution does not work when Miniconda is installed to a custom location. I'd definitely enjoy an example in the documentation of `uninstall_miniconda` in which Miniconda is installed and then uninstalled to/from a custom location!
