### ISSUE TITLE
`py_install(pip_ignore_installed = TRUE)` ignored when `method="virtualenv"`

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/reticulate#1079]
When running `py_install(pip=TRUE)`, what is the preferred way to always include `--ignore-installed` in the pip invocation? 
 `pip_ignore_installed = TRUE` is ignored when the method resolves to `"virtualenv"`, and `ignore_installed = TRUE` is ignored when the method resolves to `"conda"`.

Should I pass both options? `py_install(..., pip = TRUE, pip_ignore_installed=TRUE, ignore_installed=TRUE)`?

**Comment by kevinushey** [comment]
I think we should respect `ignore_installed` in both "conda" and "virtualenv" invocations; that is, setting `ignore_installed` should imply `pip_ignore_installed`.
