### ISSUE TITLE
Support for datatable type conversion

### ISSUE THREAD

**Issue by fdetsch** [rstudio/reticulate#1081]
Are there any plans to support **datatable** type conversion? The following piece of code creates a Python `datatable.Frame` object that is currently not converted back to an R type. 

```r
library(reticulate)

py_run_string(
  code = "import datatable as dt; dat = dt.Frame(r.iris)"
)

py$dat
```

 I would need something like this to make it available as "true" `data.frame`, or better still, `data.table` object in R.

```r
py$
  dat$
  to_pandas() |> # creates `data.frame`
  data.table::data.table() # optional
```

**Comment by kevinushey** [comment]
Thanks! Now implemented in the development version of `reticulate`. (Note that these are currently converted as plain data.frame objects)

**Comment by fdetsch** [comment]
Thanks, much appreciated!
