### ISSUE TITLE
find_conda() miniforge location on M1 Mac

### ISSUE THREAD

**Issue by d-bohn** [rstudio/reticulate#1082]
It may be useful to add `/opt/homebrew/Caskroom/miniforge` and `/opt/homebrew/miniforge` to the default search paths of `reticulate::find_conda()`. These are currently the default install paths when [installing miniforge via homebrew](https://docs.brew.sh/Installation). [`reticulate::find_conda()`](https://github.com/rstudio/reticulate/blob/dd6d6e8139dcfc4ce19e6b7150406a6f4e1af747/R/conda.R#L447-L452) only searches combinations of:

```
  prefixes <- c("~/opt/", "~/", "/opt/", "/")
  names <- c("anaconda", "miniconda", "miniforge")
  versions <- c("", "2", "3", "4")
  combos <- expand.grid(versions, names, prefixes, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
  combos <- combos[rev(seq_along(combos))]
  conda_locations <- unlist(.mapply(paste0, combos, NULL))
```
Alternatively, allow option to symlink from `/opt/homebrew/miniforge` to `/opt/miniforge` or alert user that they should do so if such installation path is detected.

**Comment by kevinushey** [comment]
Thanks! Implemented in https://github.com/rstudio/reticulate/commit/4da33563157f0b0ef50d1f4d267839627d5425fc.
