### ISSUE TITLE
Windows-installed python is not correctly detected

### ISSUE THREAD

**Issue by cderv** [rstudio/reticulate#1083]
I am on a Windows 10 computer and I have the version of python installed through Windows Store. 
This is from here: https://docs.python.org/3/using/windows.html#the-microsoft-store-package 

This is what works on my system and where it is located
```powershell
❯ py.exe -0p
Installed Pythons found by C:\Windows\py.exe Launcher for Windows
 -3.9-64        C:\Users\chris\AppData\Local\Programs\Python\Python39\python.exe *
```

Having this version works in terminal and also with Quarto 
````powershell
❯ quarto check jupyter

[>] Checking Python 3 installation....OK
      Version: 3.9.5
      Path: C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe
      Jupyter: 4.7.1
      Kernels: python3

[>] Checking Jupyter engine render....OK
````

However, with reticulate, this version is not correctly found
````r
> reticulate::py_discover_config()
Error: could not find a Python environment for C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Error: could not find a Python environment for C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe
Backtrace:
 1. reticulate::py_discover_config()
 2. reticulate:::python_config(python_version, required_module, python_versions)
 3. reticulate:::python_munge_path(python)
 4. reticulate:::python_info(python)
 5. reticulate:::stopf(...)
Run `rlang::last_trace()` to see the full context.
````

It seems like `python_info()` expect an environment or else, and in any case doesn't know how to retrieve information on this one. 

Creating a virtualenv  manually and activating it solve the issue with the installation 
```r
# reticulate::virtualenv_create("r-reticulate")
> reticulate::use_virtualenv("r-reticulate")
master* > reticulate::py_discover_config()
python:         C:/Users/chris/Documents/.virtualenvs/r-reticulate/Scripts/python.exe
libpython:      C:/Users/chris/AppData/Local/Programs/Python/Python39/python39.dll
pythonhome:     C:/Users/chris/Documents/.virtualenvs/r-reticulate
version:        3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/chris/Documents/.virtualenvs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.21.4

python versions found: 
 C:/Users/chris/Documents/.virtualenvs/r-reticulate/Scripts/python.exe
 C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe
```

**Comment by cderv** [comment]
A quick debug on `python_info()` I can share this 

Python selected in the function 
```r
> python
[1] "C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe"
```

It seems though that was the function does is looking 
* for a virtualenv 
https://github.com/rstudio/reticulate/blob/4967abddb35865a1be6ad839298695f1481bcade/R/python-tools.R#L66-L67

* for a condaenv
https://github.com/rstudio/reticulate/blob/4967abddb35865a1be6ad839298695f1481bcade/R/python-tools.R#L69-L75

* or fail 
https://github.com/rstudio/reticulate/blob/4967abddb35865a1be6ad839298695f1481bcade/R/python-tools.R#L83

So it seems that it is expected that `python_info()` fails if the python detected is not from a virtualenv, right ? 
Don't know if `python_info()` is the culprit here... 🤔 

Maybe I am missing something in how that is expected to work

**Comment by cderv** [comment]
Let's note that 1.22 CRAN version is working fine 
```r
> reticulate::py_discover_config()
python:         C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe
libpython:      C:/Users/chris/AppData/Local/Programs/Python/Python39/python39.dll
pythonhome:     C:/Users/chris/AppData/Local/Programs/Python/Python39
version:        3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/chris/AppData/Local/Programs/Python/Python39/Lib/site-packages/numpy
numpy_version:  1.20.3
```

So this is something from dev version only 🤔 I'll try to find the issue.

**Comment by cderv** [comment]
A git bisect lead me to this commit as the first bad commit
https://github.com/rstudio/reticulate/commit/d98c60eb818a01a61251aa44f29bda699e6f96f1

**Comment by cderv** [comment]
I am not sure #1093 fixes the issue correctly. 

I have now this error 
```
> reticulate::py_discover_config()
Error: invalid version specification '. 3.9.5'
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Error: spécification de version incorrecte ‘. 3.9.5’
Backtrace:
 1. reticulate::py_discover_config()
 2. reticulate:::python_config(python_version, required_module, python_versions)
 3. reticulate:::python_munge_path(python)
 4. reticulate:::numeric_conda_version(info$conda)
 5. base::numeric_version(v)
 6. base::.make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version)
Run `rlang::last_trace()` to see the full context.
```

`python_info()` which seems to be the cause is now in a `tryCatch`, but when catch it will wrongly detect a conda install
https://github.com/rstudio/reticulate/blob/9dd33489eb26f3751ee8786ef6dd3a1f6d3fa1e1/R/config.R#L516-L526

Here are the step for the Windows installed python

```
# version of python found that entered `python_munge_path`
python <- "C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe"

python_home <- dirname(python) # C:/Users/chris/AppData/Local/Programs/Python/Python39
python_dirs <- c(normalizePath(python_home)) # C:\\Users\\chris\\AppData\\Local\\Programs\\Python\\Python39
```

Then info will try to be resolved
```
info <- tryCatch(python_info(python), error = function(e) {
    conda <- tryCatch(conda_binary(python), error = function(e) NULL)
    if (is.null(conda) || !file.exists(conda)) 
      return(list())
    list(python = python, type = "conda", root = "base", 
      conda = conda)
  })
```

but 
```
> python_info(python)
Error: could not find a Python environment for C://Scripts/python.exe
```
so the tryCatch applies and (oddly ?) 
```
> conda_binary(python)
[1] "C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe"
```
meaning 
```
> info
$python
[1] "C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe"

$type
[1] "conda"

$root
[1] "base"

$conda
[1] "C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe"
```

Which will then lead to 
https://github.com/rstudio/reticulate/blob/9dd33489eb26f3751ee8786ef6dd3a1f6d3fa1e1/R/config.R#L528

and

``` r
reticulate:::numeric_conda_version("C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe")
#> Error: invalid version specification '. 3.9.5'
```

So there is probably still something not right. Maybe just the conda binary detection. I can open a new issue or we can reopen this one as the topic is the same: "Windows-installed python is not correctly detected"

**Comment by cderv** [comment]
The issue is just probably that `conda_binary()` is passed a fulle path with `python`
https://github.com/rstudio/reticulate/blob/9dd33489eb26f3751ee8786ef6dd3a1f6d3fa1e1/R/config.R#L522

if `"auto"` was passed, it would error as no conda is found. 
https://github.com/rstudio/reticulate/blob/d9be037e8d41a65c732ec95d7d2001b59532364a/R/conda.R#L504-L510
It means `info` would be NULL and then this part would correctly execute and worked
https://github.com/rstudio/reticulate/blob/9dd33489eb26f3751ee8786ef6dd3a1f6d3fa1e1/R/config.R#L544-L561

Maybe `"auto"` is not passed for a reason, but  that means that `conda_binary()` will not error, and the tryCatch will not catch. `conda_binary(conda = <path>)` is used, it won't check that this is really a conda binary and return anyway, as long as the path exist

``` r
reticulate:::conda_binary(file.path(R.home("bin"), "Rscript.exe"))
#> [1] "C:/Program Files/R/R-4.1.1/bin/x64/Rscript.exe"
```

Not sure that is expected.

**Comment by t-kalinowski** [comment]
Thank you @cderv. I had forgotten that on windows `python.exe` isn't always in the same folder as the `conda` executable.

Seems like `conda_binary()` should be able to accept the path to a python binary that was installed by conda python, and return the path to the conda that installed it. I'll boot into Windows later today and work on this. 

Probably the approach will be to first look for a conda binary under the python's home (e.g, on *nix under `bin`, windows `condabin`, and if that doesn't exist, then consult `conda-meta/history` for the path to the conda binary that created that environment.

**Comment by cderv** [comment]
Thanks @t-kalinowski ! 

Just to be clear here as I am unsure: this is not a python.exe installed by conda. There is no conda installation. It is just Windows Python installed through Windows Store, using the `py.exe` manager on Windows. 

Was that ok to you ?

**Comment by t-kalinowski** [comment]
Thank you for clarifying. Then in that case, `conda_binary()` should error.

**Comment by cderv** [comment]
Ok that is what I thought. Currently, as shown in https://github.com/rstudio/reticulate/issues/1083#issuecomment-986631454 `conda_binary()` returns what ever path is passed as argument without erroring if not conda. 

Should `python_info()` handles this Windows install in `AppData/Local/Programs/Python/`?

**Comment by t-kalinowski** [comment]
@kevinushey what do you think? Would it be better to expand `python_info()` to work on non-env python installations too?

**Comment by kevinushey** [comment]
I made that change to `python_info()` here:

https://github.com/rstudio/reticulate/blob/master/R/python-tools.R#L80-L85

**Comment by kevinushey** [comment]
Finally, please don't use Python from the Windows store -- use the official binaries from https://www.python.org/downloads/.

**Comment by kevinushey** [comment]
(sorry, this is my PTSD talking from prior bad experiences finding out that Windows puts a "fake" python on the PATH that auto-opens the Microsoft store, and us needing to detect and work around that rather annoying case...)
