### ISSUE TITLE
Function to create new Conda environment from environment.yml file

### ISSUE THREAD

**Issue by GitHunter0** [rstudio/reticulate#1088]
Hi folks,

Having a function to create a new Conda environment from an environment.yml file would be really useful, specially to build Docker images with R + Python.

The function would be equivalent to:
`conda env create -n <env_name> -f environment.yml`

Also, since Conda command sometimes freezes or takes a very long time to complete the operation, it would be very handy to have an option to create the environment using [Mamba](https://github.com/mamba-org/mamba) instead, the equivalent code would be:
```
conda install mamba -n base -c conda-forge
mamba env create -n <env_name> -f environment.yml
```

What do you think?

Thank you

**Comment by kevinushey** [comment]
This has now been implemented in the development version of `reticulate` -- for example:

```
> reticulate::conda_export("r-reticulate")
* Environment 'r-reticulate' exported to 'environment.yml'.
> reticulate::conda_create("r-reticulate-copy", environment = "environment.yml")
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
[1] "C:\\Users\\kevin\\AppData\\Local\\r-miniconda\\envs\\r-reticulate-copy/python.exe"
```
