### ISSUE TITLE
Inconsistent messages about python.exe base environment from reticulate... 

### ISSUE THREAD

**Issue by genobobeno** [rstudio/reticulate#1091]
In Windows 10, I installed Anaconda3, and I followed the directions to activate the "base" environment ... then after installing reticulate, despite showing "Anaconda3" in the `conda_list()` output, the command  `conda_list()[[1]] %>% use_condaenv()`  refused to load the base environment saying that it can't find a Python environment for `C:\ProgramData\Anaconda3\python.exe`, which really doesn't make any intuitive sense. So after scouring tickets for people with similar problems, someone suggesting forcing the `use_python()` command. Here is the output of:
`> py_config()
python:         C:/ProgramData/Anaconda3/python.exe
libpython:      C:/ProgramData/Anaconda3/python39.dll
pythonhome:     C:/ProgramData/Anaconda3
version:        3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/ProgramData/Anaconda3/Lib/site-packages/numpy
numpy_version:  1.20.3`

But now, to test, I tried to install a package using `py_install()`... and here's the output:
`> reticulate::py_install(packages = "inspect")
Error: could not find a Python environment for C:/ProgramData/Anaconda3/python.exe`

So... what in the world could this mean? This is a brand new laptop, fresh installations of everything... I'm not manipulating PATH variables, and I'm brute forcing the directions... so what's going on?

**Comment by genobobeno** [comment]
I chose to follow a different approach, creating a new environment that is not system dependent, then brute forcing the choice of that secondary python environment. I still don't understand why R couldn't find the base environment of Anaconda3 after system installation.

**Comment by kevinushey** [comment]
I'm re-opening this because I think this is a genuine bug in `reticulate` -- you should be able to use the base Anaconda installation if you want without issue.

**Comment by kevinushey** [comment]
With the development version of `reticulate`, I see:

```
> reticulate::use_condaenv("base", required = TRUE)
> reticulate::py_config()
python:         C:/Users/kevin/AppData/Local/r-miniconda/python.exe
libpython:      C:/Users/kevin/AppData/Local/r-miniconda/python39.dll
pythonhome:     C:/Users/kevin/AppData/Local/r-miniconda
version:        3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

NOTE: Python version was forced by use_python function
```

so it looks like this should be functioning as expected now.
