### ISSUE TITLE
Got an error runing a python function with Reticulate. Seems like not all arguments are correctly read.

### ISSUE THREAD

**Issue by PauloPerna** [rstudio/reticulate#1092]
Hi! I'm trying to convert a pdf file to image. I have the following python code:
```
from pdf2image import convert_from_path
pdf_file= 'C:\\path\\to\\file.pdf'
pages = convert_from_path(pdf_file, poppler_path = "O:\\path\\to\\poppler-0.68.0\\bin")
```
Which works fine when running in the terminal, even with the same python as the Reticulate:
![image](https://user-images.githubusercontent.com/41304883/144431310-27843623-c6dc-4287-8149-50df6b05ef2e.png)

When I try to run the same code, sourcing as a function in a python script or with py_eval or in the R Console via repl_python(), I always got the following error `PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?`
![image](https://user-images.githubusercontent.com/41304883/144432373-1af4e0cc-d5af-4f84-9f02-fb0cbed640f4.png)

Am I doing some mistake?

Sorry for reporting as a bug, I'm kinda newbie and I'm not sure about what's going on.

**Comment by kevinushey** [comment]
The following works for me on macOS, from the R console:

```
library(reticulate)
install_python(version = "3.9.9")

virtualenv_create("pdf2image", version = "3.9.9")
use_virtualenv("pdf2image", required = TRUE)
py_config()

py_install("pdf2image")
pdf2image <- import("pdf2image")

url <- "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"
destfile <- file.path(tempdir(), basename(url))
download.file(url, destfile = destfile, method = "curl")

pdf2image$convert_from_path(destfile)
```

Based on the output, you might need to explicitly change the PATH environment variable so that `poppler` can be found.
