### ISSUE TITLE
`py_install()` sometimes finds wrong python on osx-arm64

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/reticulate#1095]
I'm not sure what the best fix is yet, but want to file the issue so it's not lost.
To reproduce, make sure reticulate's miniconda is not installed, and manually install miniforge python to the default location `~/miniforge3`:
```sh
curl -OL  https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh
chmod +x Miniforge3-MacOSX-arm64.sh
sh Miniforge3-MacOSX-arm64.sh -b
```

then in R run:
```R
reticulate::py_install("tensorflow-deps", channel = "apple", method = "conda")
```
Gives output:
```
DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
  target directory: /usr


 Error: one or more Python packages failed to install [error code 1]
```
In a cursory investigation I saw that 
+ `py_discover_config()` is called, and it resolves the system python at `/usr/bin/python`. (which is especially odd because that's not the default python on my PATH).
+ `conda_list()` and `conda_binary()` do the right thing and find the conda installation at ~/miniforge3.

**Comment by kevinushey** [comment]
Thanks! I'll take a look.

**Comment by kevinushey** [comment]
I think the problem here is that `py_discover_config()` only wants to use an environment called `r-reticulate` in a discovered Anaconda installation; it won't prefer the "base" Anaconda installation to whatever might happen to be on the PATH.

In addition, we try searching a bunch of hard-coded locations here:

https://github.com/rstudio/reticulate/blob/master/R/config.R#L334-L350

And those are tried in order until something "good enough" is found. We might want to place Anaconda Python earlier on that list than the "system" installations.

**Comment by kevinushey** [comment]
(And, more to the point, we should only use the output of `py_discover_config()` if it is indeed a Conda-associated Python)

**Comment by kevinushey** [comment]
Another issue here is that `conda_list()` doesn't call the "base" environment "base" for Miniforge3:

```
> conda_list()
                name                                                    python
1         miniforge3                        /Users/kevin/miniforge3/bin/python
2       r-reticulate      /Users/kevin/miniforge3/envs/r-reticulate/bin/python
3               test              /Users/kevin/miniforge3/envs/test/bin/python
4        test-export       /Users/kevin/miniforge3/envs/test-export/bin/python
5  test-export-clone /Users/kevin/miniforge3/envs/test-export-clone/bin/python
6            test123           /Users/kevin/miniforge3/envs/test123/bin/python
7            test456           /Users/kevin/miniforge3/envs/test456/bin/python
8         test456151        /Users/kevin/miniforge3/envs/test456151/bin/python
9           test4565          /Users/kevin/miniforge3/envs/test4565/bin/python
10         test45651         /Users/kevin/miniforge3/envs/test45651/bin/python
```

Although the situation is a little weird if you have multiple Anaconda installations since you could have multiple "base" environments, one for each Anaconda installation...

**Comment by kevinushey** [comment]
Another reason why we're not using Miniforge3 here (at least, in my case) is because `numpy` doesn't come installed by default.
