### ISSUE TITLE
Provide 'as.dict' helper for explicitly constructing dictionary from list / environment?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/reticulate#11]
Some Python code I'm translating to R looks like this:

```python
def feature_columns_to_placeholders(feature_columns, batch_size=None):
  return {
    column.name: tf.placeholder(tf.float32, [batch_size])
    for column in feature_columns
  }
```

Note that the dictionary key `column.name` is actually evaluated and its result is used as the key, which is out-of-line with how R does things. For that reason, it would be useful to be able to construct a dictionary directly from an R list or environment, so we could write the roughly equivalent R code:

```R
placeholders <- lapply(feature_columns, function(column) {
  tf$placeholder(tf$float32, list(batch_size))
})
as.dict(placeholders)
```

**Comment by jjallaire** [comment]
what about if the dict function could take arguments which are un-named lists or environments and use them to initialized. i.e., what you suggested except you could just write `dict(placeholders)`

Actually, I'm surprised that this can't just work automatically as we currently convert R named lists to python dicts.

**Comment by kevinushey** [comment]
You're right that we can just pass R named lists wherever dictionaries are expected -- I guess the minor bit of trouble here is simply the difference in how keys are handled vs. R and Python. Perhaps there's nothing to be done here.
