### ISSUE TITLE
Integration with numpy is not optional

### ISSUE THREAD

**Issue by ianfiske** [rstudio/reticulate#110]
Although the README states that numpy is not required, reticulate fails to load environments that are missing numpy.  Here's any example:
```
library(reticulate)
conda_create('nonumpy')
use_condaenv('nonumpy')
py_discover_config()
```
prints this:
```
python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Feb  7 2017, 00:08:15)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
numpy:          /Users/ifiske/Library/Python/2.7/lib/python/site-packages/numpy
numpy_version:  1.13.1

python versions found: 
 /Users/ifiske/anaconda/envs/nonumpy/bin/python
 /usr/bin/python
 /usr/local/bin/python3
 /Users/ifiske/anaconda/bin/python
 /Users/ifiske/anaconda/envs/testenv/bin/python
```

The system python is used despited specifying the conda env 'nonumpy'.  I have verified that installing numpy in the environment lets reticulate choose the env.  The culprit appears to be a line in `py_discover_config` that explicitly checks for numpy within the env.

**Comment by jjallaire** [comment]
It's not required but it's preferred (i.e. if we find a Python with numpy we'll use that in preference to one without). If don't do this then there is no conversion for R matrices which is a pretty debilitating limitation :-)

**Comment by ianfiske** [comment]
Thanks for the fast reply. It seems that if the user specifies an env explicitly, that that env should be preferred above all.  Sometimes we might want to use python just for some util libraries like boto3 and not require numpy dependencies.

**Comment by jjallaire** [comment]
The use_* family of functions are advisory (they are hints). This is done
because it's imperative that the R user get the Python package they are
requesting via import, and in the presence of potentially dozens of Python
environments on a system searching for one which satisfies the import is
considered the highest priority. That said, there is a RETICULATE_PYTHON
environment variable that can be set to force a version (the forcing
behavior currently only works on the dev branch of reticulate)

**Comment by kenahoo** [comment]
Doesn't the `required=TRUE` parameter to the `use_*` family of functions also force it?  Or is the `RETICULATE_PYTHON` variable the only way?

**Comment by ianfiske** [comment]
No, `required=TRUE` does not force reticulate to enforce the `use_*` function, instead prioritizing numpy.

**Comment by kenahoo** [comment]
Oh!  So it dies if the python env doesn't exist, but it still might not use it.  Good to know.

@jjallaire I'd be interested in a way to force the configuration more easily without relying on environment variables.  I'd rather have it die than pick up a python I wasn't expecting it to use.

**Comment by jjallaire** [comment]
As a result of this discussion I just changed the behavior of `required = TRUE` to always use the specified environment: https://github.com/rstudio/reticulate/commit/d23ff496a2da261489bc964aa6e9afb57c4180b1

**Comment by ianfiske** [comment]
Thank you @jjallaire!  Looking forward to the new behavior.  Thanks for your work on this incredibly useful package also!
