### ISSUE TITLE
support some subset of ipython magic in reticulate REPL

### ISSUE THREAD

**Issue by kevinushey** [rstudio/reticulate#1101]
Here's an example of tools that would be useful and should likely be simple to implement:

https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-cd
https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-conda
https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-env
https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-load
https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-pip
https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-pwd
https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-system

**Comment by kevinushey** [comment]
We already do some special handling of inputs here:

https://github.com/rstudio/reticulate/blob/4da33563157f0b0ef50d1f4d267839627d5425fc/R/repl.R#L206-L236

We could have a similar extension for commands beginning with `%`.

**Comment by t-kalinowski** [comment]
Something like this works surprisingly well:
```R
repl_ipython <- function() {
  ensure_python_initialized("IPython")
  import("IPython")$start_ipython()
}
```
What do you think about taking this approach, offloading the work to IPython? 
To feel comfortable with this approach I'd want to read through [this](https://github.com/ipython/ipython/blob/master/IPython/terminal/ipapp.py), and maybe also define a some macros/hooks/callbacks to ensure the buffers are flushed so output is always visible from R, and modify the startup banner.

**Comment by kevinushey** [comment]
Does this work with RStudio as well?

**Comment by t-kalinowski** [comment]
Yup.

**Comment by t-kalinowski** [comment]
Rstudio's autocompletion and history logging is still active for the R session, we'd want to disable it while we're in the ipython shell.

**Comment by t-kalinowski** [comment]
Actually, there is one issue I'm not sure how to fix yet, IPython is doing it's own buffering of output that doesn't seem to work well within RStudio. I haven't found where to inject an additional callback to flush the buffer.
In Rstudio: 
<img width="338" alt="image" src="https://user-images.githubusercontent.com/8462255/146093661-015ffa87-93de-448e-af3c-32150456bc12.png">
In terminal:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/8462255/146093719-d0ae4b1e-b00f-427d-b6e2-7c57834ba601.png">

**Comment by t-kalinowski** [comment]
Closed via https://github.com/rstudio/reticulate/pull/1103
