### ISSUE TITLE
Warning when `find_conda()` returns multiple conda locations

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/reticulate#1102]
I'm now seeing a warning when there are multiple conda's installed on a system:
```R
Warning in if (!grepl("^conda", basename(conda))) stop("Supplied path is not a conda binary: ",  :
  the condition has length > 1 and only the first element will be used
Warning in if (file.exists(altpath)) return(normalizePath(altpath, winslash = "/",  :
  the condition has length > 1 and only the first element will be used
```
I think this is because `find_conda()` can now return a character vector of length > 1:
https://github.com/rstudio/reticulate/blob/4da33563157f0b0ef50d1f4d267839627d5425fc/R/conda.R#L731

There are two uses I found where `find_conda()` is assumed to return a length 1 vector or NULL, in `py_discover_config_fallbacks()` and `conda_binary()`, which are both called during python initialization.

Should `find_conda()` be returning the `conda_locations[1]` here?

**Comment by kevinushey** [comment]
Should be fixed now: https://github.com/rstudio/reticulate/commit/35ac4a79f18a24c2d7b34c2981f33cc4e9b28710
