### ISSUE TITLE
conda_create "module 'colorama' has no attribute 'init'"

### ISSUE THREAD

**Issue by charlielogan** [rstudio/reticulate#1110]
I am trying to load a conda environment in reticulate from a .yml file but am stopped by `AttributeError: module 'colorama' has no attribute 'init'`. In trying to figure out more about why this is occurring, I found that the same error happens when trying to create any conda environment with conda_create.

I uninstalled reticulate and tried these steps to reproduce from the beginning:
`devtools::install_github("rstudio/reticulate")`
`library(reticulate)`
`conda_create("test_export", packages="python=3.7")`

Error:

Traceback (most recent call last):
  `File "C:\Users\clogan\AppData\Local\R-MINI~1\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())`
  `File "C:\Users\clogan\AppData\Local\R-MINI~1\lib\site-packages\conda\cli\main.py", line 151, in main
    from ..exceptions import conda_exception_handler`
  `File "C:\Users\clogan\AppData\Local\R-MINI~1\lib\site-packages\conda\exceptions.py", line 25, in <module>
    from .common.io import dashlist, timeout`
  `File "C:\Users\clogan\AppData\Local\R-MINI~1\lib\site-packages\conda\common\io.py", line 33, in <module>
    from .._vendor.tqdm import tqdm`
  `File "C:\Users\clogan\AppData\Local\R-MINI~1\lib\site-packages\conda\_vendor\tqdm\__init__.py", line 13, in <module>
    from .cli import main  # TODO: remove in v5.0.0`
  `File "C:\Users\clogan\AppData\Local\R-MINI~1\lib\site-packages\conda\_vendor\tqdm\cli.py", line 9, in <module>
    from .std import TqdmKeyError, TqdmTypeError, tqdm`
  `File "C:\Users\clogan\AppData\Local\R-MINI~1\lib\site-packages\conda\_vendor\tqdm\std.py", line 22, in <module>
    from .utils import (`
  `File "C:\Users\clogan\AppData\Local\R-MINI~1\lib\site-packages\conda\_vendor\tqdm\utils.py", line 45, in <module>
    colorama.init(strip=False)`
`AttributeError: module 'colorama' has no attribute 'init'`
`Error: Error creating conda environment 'test_export' [exit code 1]`

Any help would be appreciated

**Comment by kevinushey** [comment]
https://github.com/jupyterlab/jupyterlab/issues/3671 seems related, but I don't have any great ideas. The issue appears to be independent of reticulate, though.

**Comment by charlielogan** [comment]
> [jupyterlab/jupyterlab#3671](https://github.com/jupyterlab/jupyterlab/issues/3671) seems related, but I don't have any great ideas. The issue appears to be independent of reticulate, though.

Do you think its an issue with conda? Or with colorama?

**Comment by RParkerE** [comment]
I was having an issue with colorama.init() as well in a different external library. [Issue 370](https://github.com/tartley/colorama/issues/370) solved this for me. You will have to import colorama using `from colorama import initialise` at least with `colorama 0.4.6` that worked for me.

**Comment by t-kalinowski** [comment]
Thanks for reporting. This doesn't seem to be a reticulate issue.
