### ISSUE TITLE
Show python exception message by default

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/reticulate#1113]
Consider a simple misconfigured keras model like this:
```R
model <- keras_model_sequential(input_shape = c(28 * 28)) %>%
  layer_dense(units = 512, activation = "relu") %>%
  layer_dense(units = 10, activation = "softmax")

model %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("accuracy"))


model %>% fit(k_random_uniform(c(4, 28*29)), 
              k_random_uniform(c(4,10)))
```
In Rstudio, this is what's visible after evaluating this chunk:
![image](https://user-images.githubusercontent.com/8462255/148588455-9429c9cd-3970-4bc1-83e4-111526f15176.png)

This is problematic because it gives a lot of output, but nothing useful to the user about what caused the error. Expanding the stacktrace helps a little, but the actual message is in a big unformatted and unevaluated jumble of a template string (which is sometimes also truncated, though not in this example) 

![image](https://user-images.githubusercontent.com/8462255/148588678-71257e3a-ea4e-45f3-8d41-6db1ec411ce8.png)

Printing the actual exception shows a different message, which I'm guessing was generated by the IDE overwriting the original python error:
![image](https://user-images.githubusercontent.com/8462255/148588819-d589bb29-4289-4928-8434-7d0d2f4216ff.png)

Note the actionable information that should be shown prominently to the user is usually available 
by running `for(m in reticulate::py_last_error()) cat(m)`, which would show this as a standalone, prominent line: 
```
ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 784), found shape=(None, 812)
```

It might even make sense to show the full python stack track as well (e.g., from a different example of an error message):

![image](https://user-images.githubusercontent.com/8462255/148586373-db0181b4-0a07-435d-b0d2-7d9b6a00ae8b.png)

**Comment by kevinushey** [comment]
This sounds a bit similar to this R bug:

https://bugs.r-project.org/show_bug.cgi?id=17576

What version of R are you using? Do we know why this truncation is occurring?

**Comment by kevinushey** [comment]
I guess this affects long error messages in `stop()`...

```
long <- paste(sample(letters, 10000, TRUE), collapse = "")
stop(long)
```

**Comment by t-kalinowski** [comment]
I like option 3 the most. We would probably need a custom error handler in reticulate for all exceptions passing through Rcpp. (The error messages from R functions that are called by Python are also not pretty). 

I wonder if we can use some of the recent error handling enhancements in rlang. @lionel-, what do you think?

**Comment by lionel-** [comment]
The maximum error and warning length is controlled by the `warning.length` global option. It's initialised to 1000 bytes and can be increased to 8170 max, which could explain the truncation here.

To avoid hitting this limit, `rlang::abort()` uses a trick that @gaborcsardi came up with:

- Signal the condition using `signalCondition()`
- Print the message manually
- Call `stop()` with the `show.error.messages` global option set to `FALSE` temporarily

Being in control of the entire error message also enabled us to implement new features like chained errors (see https://www.tidyverse.org/blog/2021/12/rlang-1-0-0-errors/).

If reticulate can afford an rlang dependency, the easiest would be to use `rlang::abort()` instead of `stop()`. Otherwise see the implementation here: https://github.com/r-lib/rlang/blob/9632b868bde7da370e23d86a5880d253de610a14/R/cnd-abort.R#L523

**Comment by kevinushey** [comment]
I think it should be easy for us to take a dependency on `rlang`. I also like the idea of standardizing our error handling / message output based on the tools provided by `rlang` for the long term.

**Comment by t-kalinowski** [comment]
Calling `rlang::abort()` instead of `Rcpp::stop()` to get the nice printout turned out to be a little more involved—Rcpp still catches and truncates the raised R error condition message, and rlang never prints the condition.

In lieu of bypassing the Rcpp exception handler, I went for a more narrow change in #1142. I fix-up the error message so it's more useful, but still let Rcpp catch and handle the exception.

Perhaps on a future iteration we can revisit this, e.g., introduce a “py_exception” R condition / C++ exception, print the python and R tracebacks interleaved nicely, etc. This PR however gets us 80% of the way there for giving a mostly useful error message for most raised python exceptions.

Here is what it looks like now:
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/8462255/150864861-cca319e7-8b6a-46a1-bccf-42f5731ac089.png">

**Comment by t-kalinowski** [comment]
As an aside, the issue of `py_last_error()` incorrectly returning 'TypeError: object of type 'Sequential' has no len()' was resolved in https://github.com/rstudio/rstudio/pull/10384 and https://github.com/rstudio/reticulate/pull/1137
