### ISSUE TITLE
error in conda documentation?

### ISSUE THREAD

**Issue by ijlyttle** [rstudio/reticulate#1115]
`conda-tools` is no longer showing up in the index:

![image](https://user-images.githubusercontent.com/2800934/148657131-098ae5d8-6c1b-400d-bf1c-b6569415c205.png)

Stuff that used to look like this:

```r
 #' @family conda-tools 
```

now looks like this:

https://github.com/rstudio/reticulate/blob/172790f308eb7cdbbd5f102991187dce97fba616/R/conda.R#L53

Happy to submit a PR, if you like. Thanks!

**Comment by kevinushey** [comment]
Thanks for the bug report! I fixed this up.
