### ISSUE TITLE
possible typo

### ISSUE THREAD

**Issue by ijlyttle** [rstudio/reticulate#1116]
I came across this in the course of a different bug search; I don't know if this is a problem or not, but I thought I should note it here:

https://github.com/rstudio/reticulate/blob/172790f308eb7cdbbd5f102991187dce97fba616/R/conda.R#L785-L794

Should this be:

```r
resolve = function(envname) {
```

I compared it with this:

https://github.com/rstudio/reticulate/blob/d15b9e95a3e51249fb23e34065cf90470111c1fd/R/virtualenv.R#L312-L319

Happy to make a PR, if you like.

**Comment by kevinushey** [comment]
Thanks! I'll fix that up.
