### ISSUE TITLE
Python lists containing (complex? classed?) objects not printed correctly

### ISSUE THREAD

**Issue by kevinushey** [rstudio/reticulate#112]
If I have this Python code:

```python
import ast
node = ast.parse("x = 1\ny = 2\n")
print node.body
```

The following is printed:

    [<_ast.Assign object at 0x10d084710>, <_ast.Assign object at 0x10d0847d0>]

However, within `reticulate` I only see the class of the first object:

```R
> ast <- import("ast", convert = FALSE)
> node <- ast$parse("x = 1\ny = 2\n")
> print(node$body)
Assign
```

It looks like this is because `reticulate` somewhat aggressively strips the printed representation:

https://github.com/rstudio/reticulate/blob/b24eb085185272e5b14b0325d8cf37a03df37674/R/python.R#L838-L841

Could the stripping of `object at <...>` be refined? Also worth noting that `_` is valid for use in Python identifiers.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/rstudio/reticulate/commit/07e1f8de6cad450b28df23d12a92984ed0436e28
