### ISSUE TITLE
`length()` overwrites `py_last_error()`

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/reticulate#1134]
With the recent addition of a default `length()` for python objects, `py_last_error()` is no longer useful in the IDE now if a python object that doesn't define a `len` method is in the active R environment (e.g., a keras model). This is because the IDE calls `length` on objects to populate the environment pane, and that in turn will set the last python exception to "object has no len() method", overwriting whatever exception was actually generated by user code.

Some ideas for how to fix: 
+ Temporarily remove `length.python.builtin.object` method until the the error handling refactoring discussed in #1113 is completed; 
+ add something like a `s_lastError.restore_previous()` method call [here in `py_len_impl`](https://github.com/rstudio/reticulate/blob/21fd315a422a46fd820d7d4bac4426f16072f54c/src/python.cpp#L3042); 
+ do something in the IDE to not call `length` on python objects.

**Comment by t-kalinowski** [comment]
I'll submit a patch that uses [PyErr_Restore](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_Restore) in `py_len_impl()`

**Comment by kevinushey** [comment]
Closed by https://github.com/rstudio/reticulate/pull/1137.
