### ISSUE TITLE
how to set width and height of matplotlib images in python Rmd chunks?

### ISSUE THREAD

**Issue by tdhock** [rstudio/reticulate#1140]
hi thanks very much for this package which is very useful for including python chunks in Rmd documents.
Is there a way to control the height and width of the images produced in the chunks? I would like to make Rmd beamer slides with images from matplotlib which have reduced height, but full slide width (so you can write a few lines of commentary above/below the figure). 
The fig.width and fig.height have no effect on the image size, and that is documented as R-specific: https://bookdown.org/yihui/rmarkdown-cookbook/figure-size.html says The size of plots made in R can be controlled by the chunk option fig.width and fig.height (in inches).
Is there another way to control matplotlib figure height and width?
The out.height='25%' chunk option works for proportionally reducing the image size (both height and width), but I would like to reduce the height but maintain full width. is that possible?
Thanks and here is a zip file with MRE as Rmd source code with rendered PDF.
[slides.zip](https://github.com/rstudio/reticulate/files/7907758/slides.zip)

**Comment by tdhock** [comment]
Also would it be possible to output PNG instead of PDF? Slides with PDF/vector graphics take up a lot of disk space (>10MB) so it would be nice to be able to switch to PNG graphics to reduce slide file size.
Looking at the source code I see an option (reticulate.engine.matplotlib.show) which defaults to a function (eng_python_matplotlib_show) that has `plt$savefig()` so should I write a custom function here? Is this hook documented anywhere? I did not find any documentation from a web search for "r option reticulate.engine.matplotlib.show"
```r
    hook <- getOption("reticulate.engine.matplotlib.show", eng_python_matplotlib_show)
```

**Comment by jwalton3141** [comment]
> Is there another way to control matplotlib figure height and width?

You could use the `figsize` argument of matplotlib's `plt.figure()` command.

So where you have: 

    ```{python}
    plt.plot([1, 2, 3, 4]) 
    plt.ylabel('some numbers')
    plt.show()
    ```
replace with:

    ```{python}
    plt.figure(figsize=(6, 2))
    plt.plot([1, 2, 3, 4])
    plt.ylabel('some numbers')
    plt.show()
    ```

**Comment by jwalton3141** [comment]
> would it be possible to output PNG instead of PDF?

Yes. You can do using the `dev` figure option of Rmarkdown, as such:
```yaml
title: "matplotlib test"
author: "Toby Dylan Hocking"
output: 
  beamer_presentation:
    dev: png 
```

**Comment by tdhock** [comment]
Great, thanks for the advice. Going forward for other people who have these kinds of questions, can these tips please be documented in some obvious place? For example,
- https://github.com/rstudio/reticulate#python-in-r-markdown
- https://rstudio.github.io/reticulate/articles/versions.html

For the record I was trying to get this to work with plotnine so the final code I used looks like this,
- dev: png in header
- knitr::opts_chunk$set(dpi=500) in R chunk
- plotnine.options.figure_size = (5, 3) in python chunk to set default fig size, can be overridden for specific figures via p9.theme(figure_size=(4.5,2.5))
- p9.theme(subplots_adjust={"left":0.15, "right":0.75, "bottom":0.2, "top":1}) to adjust borders so axis label and legend do not get cut off.

**Comment by t-kalinowski** [comment]
The standard knitr chunk options `fig.width` and `fig.height` should work:

````
```{python}
#| fig.width: 8
#| fig.height: 2
import matplotlib.pyplot as plt
plt.plot([1,2,3,4], [1,4,9,16])
```
````

**Comment by fkgruber** [comment]
Hi
I just try this and, while it works with matplotlib plots it does not work with other frameworks like plotnine, and seaborn

````
---
title: Simple test
author: Me
engine: knitr
---

```{python}
#| fig.width: 20
#| fig.height: 2
import matplotlib.pyplot as plt
plt.plot([1,2,3,4], [1,4,9,16])
```

In plotnine it does not work
```{python}
#| fig.width: 20
#| fig.height: 2
from plotnine import *
from plotnine.data import mpg

ggp=(
    ggplot(mpg, aes("cty", "hwy"))
    # to create a scatterplot
    + geom_point()
    # to fit and overlay a loess trendline
    + geom_smooth(method="lm", color="blue")
    + ggtitle("Plotnine plot")
)
ggp.show()
```
or seaborn:
```{python}
#| fig.width: 20
#| fig.height: 2
import seaborn as sns
import matplotlib.pyplot as plt

# Load sample dataset
df = sns.load_dataset("tips")  # Dataset of restaurant tips

# Create a scatter plot with regression line
tmp=sns.lmplot(data=df, x="total_bill", y="tip")

# Add a title
plt.title("Tip vs. Total Bill with Regression Line")

plt.show()

```
````
