### ISSUE TITLE
python_info_condaenv_find() breaks on conda-meta/history file paths that contain spaces

### ISSUE THREAD

**Issue by philiporlando** [rstudio/reticulate#1149]
I am trying to interface R with a [proprietary conda environment](https://pro.arcgis.com/en/pro-app/latest/arcpy/get-started/what-is-arcpy-.htm) maintained by [Esri](https://en.wikipedia.org/wiki/Esri). This environment includes the ArcPy site package which contains a bunch of geospatial operations that I am unfortunately dependent on for work.

I have created a cloned conda environment of this site package, but I'm getting the following error whenever I try to interface with `reticulate`.

```r
library(reticulate)
use_condaenv(condaenv = "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone", required = T)
```

```
Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="C:/conda.exe": The system cannot find the file specified
```

I understand that this is not a complete reproducible example due to the dependency on this proprietary software, but I'm hoping that it will still be possible to troubleshoot to some degree. 

### Edit:

This bug appears to be specific to `reticulate_1.24`. Specifically, [this commit](https://github.com/rstudio/reticulate/commit/4f4699f7b845e5689e7a5c163fb31d4e43002126#diff-d471e62749e21aceb08e8b748ed9f063a15a0346049031390a025267aaee7a00) is breaking things for me. After downgrading to `reticulate_1.22` I am able to configure my ArcGIS Pro conda environment using the following parameters:

```r
# Specifying full path to conda env
reticulate::use_condaenv(condaenv = "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone", required = T)

# Specifying condaenv name, and path to conda.bat
reticulate::use_condaenv(condaenv = "arcgispro-py3-clone", conda = "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone/Scripts/conda.bat", required = T)
```

**Comment by t-kalinowski** [comment]
Sorry you're encountering issues.
Do you know where the error is being raised?
Can you please run
```
options(error = function(e) print(rlang::trace_back()))
```
 reproduce the error and then report the output?

**Comment by philiporlando** [comment]
Thanks for the suggestion. Please see the output below:

```r
options(error = function(e) print(rlang::trace_back()))
use_condaenv(Sys.getenv("DEFAULT_CONDA_ENV"))
```
```
Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="C:/conda.exe": The system cannot find the file specified
    x
 1. +-reticulate::use_condaenv(Sys.getenv("DEFAULT_CONDA_ENV"))
 2. | \-reticulate::use_python(python, required = required)
 3. |   \-reticulate:::python_config(python)
 4. |     \-reticulate:::python_munge_path(python)
 5. |       \-reticulate:::get_python_conda_info(python)
 6. |         \-base::normalizePath(conda, winslash = "/", mustWork = TRUE)
 7. \-global `<fn>`()
```

**Comment by philiporlando** [comment]
### Update:

I completely uninstalled and reinstalled R, RTools, and RStudio. I also completely removed any lingering config files by following [this guide](https://stackoverflow.com/a/61187094/6736902) before re-installing. 

I am still getting the same error when trying to use the `arcgispro-py3-clone` conda environment. However, I'm also getting a new error when calling `reticulate::py_config()`:

```r
reticulate::py_config()
# No non-system installation of Python could be found.
# Would you like to download and install Miniconda?
# Miniconda is an open source environment management system for Python.
# See https://docs.conda.io/en/latest/miniconda.html for more details.
```

**Comment by t-kalinowski** [comment]
It's difficult to debug remotely like this; here are some questions that might help:
+ Where is conda.exe? `reticulate:::find_conda()` might help here. 
+ How did you create the cloned environment?

Some quick fixes that might get you to a solution the fastest:
+ Does pointing reticulate directly at the python binary via `RETICULATE_PYTHON` work?
E.g., in a fresh session:
```R
Sys.setenv(RETICULATE_PYTHON = normalizePath("C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3/python.exe")
reticulate::py_config()
```
+ Does pointing reticulate directly at the conda binary via `options()` make things work?
```R
options(reticulate.conda_binary = normalizePath("C:/path/to/conda.exe/or/conda.bat")
```

**Comment by philiporlando** [comment]
I understand that remotely debugging a proprietary conda environment is unnecessarily difficult. Thanks for sticking with me and providing these suggestions!

- It looks like `reticulate::find_conda()` is an [internal method](https://github.com/rstudio/reticulate/blob/a6d2c44e372cf889ee57cd28fb598f90d9181528/R/conda.R#L623). I'm getting the following error trying to call it:

```r
reticulate::find_conda()
# Error: 'find_conda' is not an exported object from 'namespace:reticulate'
```

- I am cloning the `arcgispro-py` conda environment that is included with the installation of the ArcGIS Pro software. This default conda environment lives here: `C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3`. I need to install additional python packages to this environment, so I first create a clone called `arcgispro-py3-clone` which lives here: `C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3-clone`. This is the conda environment that I need to interface with `reticulate`. I using a "Python Command Prompt" that is included with the ArcGIS Pro installation to carry out the cloning. From what I can tell, this is essentially opening a command prompt with the default `arcgispro-py3-clone` activated. From this prompt I am simply entering the following commands to create `arcgispro-py3-clone`:

```
conda create --clone arcgispro-py3 --name arcgispro-py3-clone
activate arcgispro-py3-clone
conda install requests -y
... 
conda install usaddress -y
```

What I find interesting is that I'm not seeing `conda.exe` anywhere within the subdirectories of the `arcgispro-py3` or `arcgispro-py3-clone` parent directories... The only version of `conda.exe` that I have found on my machine is within a different directory within my ArcGIS Pro installation: `C:\Program Files\ArcGIS\Pro\bun\Python\Scripts\conda.exe`

- Pointing directly to the python binary via `RETICULATE_PYTHON` in a fresh session returns the following error:
```r
Sys.setenv(RETICULATE_PYTHON = normalizePath("C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3/python.exe"))
reticulate::py_config()
# Error in path.expand(path) : invalid 'path' argument
```
- Pointing reticulate directly at the conda binary via `options()` returns the following:
```r
options(reticulate.conda_binary = normalizePath("C:/Program Files/ArcGIS/Pro/bin/Python/Scripts/conda.exe"))
reticulate::py_config()
# Error: Installation of Python not found, Python bindings not loaded.
# Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.
```
```r
options(reticulate.conda_binary = normalizePath("C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone/Scripts/conda.bat"))
reticulate::py_config()
# Error: Installation of Python not found, Python bindings not loaded.
# Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.
```
I was surprised to see that the `conda.exe` and `conda.bat` files have completely different paths... I'm wondering if this the root of the problem with `reticulate`... I was really hoping that pointing reticulate towards one of these binaries would do the trick! Please let me know if there is anything else I can try. Thanks again for the help!

**Comment by philiporlando** [comment]
@t-kalinowski, apologies in advance for the essay, but I think I've discovered the root cause of this issue. Please take a look at these results below and let me know if I can do anything to continue troubleshooting and get a pull request submitted. Thank you for your support!

**Update:**

I have cloned `rstudio/reticulate` to my local machine and I've been trying to troubleshoot by jumping inside of some of its internal methods and running checks line by line. 

1. I started by calling `find_conda()` which returns `NULL`
2. I then tried calling `use_condaenv()`. This fails [here](https://github.com/rstudio/reticulate/blob/a6d2c44e372cf889ee57cd28fb598f90d9181528/R/use_python.R#L174) when calling `conda_binary()`:
```r
condaenv <- "arcgispro-py3-clone"
conda <- "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone/python.exe"
required <- T

required <- required %||% use_python_required()

if (grepl("[/\\]", condaenv) &&
    grepl("^python[0-9.]*(exe)?", basename(condaenv))) {
  # path to python binary provided
  python <- condaenv
  if (!is_conda_python(python))
    warning("path supplied to use_condaenv() is not a conda python:\n\t",
            python)
  use_python(python, required = required)
  return(invisible(NULL))
}

# check for condaenv supplied by path
condaenv <- condaenv_resolve(condaenv)
if (grepl("[/\\]", condaenv) && is_condaenv(condaenv)) {
  python <- conda_python(condaenv)
  use_python(python, required = required)
  return(invisible(NULL))
}

conda <- conda_binary(conda)
```
```
# Error in conda_binary(conda) : 
#  Supplied path is not a conda binary: ‘C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone/python.exe’
```
3. Jumping inside of the `conda_binary()` method, I'm getting an error when calling `grepl()` [here](https://github.com/rstudio/reticulate/blob/a6d2c44e372cf889ee57cd28fb598f90d9181528/R/conda.R#L504).
```r
conda <- "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone/python.exe"

# automatic lookup if requested
if (identical(conda, "auto")) {
  conda <- find_conda()
  if (is.null(conda))
    stop("Unable to find conda binary. Is Anaconda installed?", call. = FALSE)
  conda <- conda[[1]]
}

conda <- normalizePath(conda, winslash = "/", mustWork = FALSE)
if (!grepl("^conda", basename(conda)))
  stop("Supplied path is not a conda binary: ", sQuote(conda))
``` 
```
Error: Supplied path is not a conda binary: ‘C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone/python.exe’
```
So it appears that the root of the problem is that `conda_binary()` is looking for a `conda.exe` but I have been passing a path to `python.exe`. Should the pattern within this call to `grepl()` be modified to `"^conda|^python"` to account for different types of conda installations (e.g. ArcGIS Pro)? I have discovered the location of a `arcgispro-py3-clone/Scripts/conda.bat` file, but there is no `arcgispro-py3-clone/Scripts/conda.exe` within my ArcGIS Pro installation of python... When assigning the path to `conda.bat` to my `conda` parameter, I am able to call `conda_binary()` without any errors! This is promising!

```r
condaenv <- "arcgispro-py3-clone"
# conda <- "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone/python.exe"
conda <- "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone/Scripts/conda.bat"
required <- T

required <- required %||% use_python_required()

if (grepl("[/\\]", condaenv) &&
    grepl("^python[0-9.]*(exe)?", basename(condaenv))) {
  # path to python binary provided
  python <- condaenv
  if (!is_conda_python(python))
    warning("path supplied to use_condaenv() is not a conda python:\n\t",
            python)
  use_python(python, required = required)
  return(invisible(NULL))
}

# check for condaenv supplied by path
condaenv <- condaenv_resolve(condaenv)
if (grepl("[/\\]", condaenv) && is_condaenv(condaenv)) {
  python <- conda_python(condaenv)
  use_python(python, required = required)
  return(invisible(NULL))
}
conda <- conda_binary(conda)
```
```
[1] "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone/Scripts/conda.bat"
```
4. While `conda_binary()` and `conda_list()` are behaving as expected with the updated parameters, I am still running into an error when trying to call `use_python()` [here](https://github.com/rstudio/reticulate/blob/a6d2c44e372cf889ee57cd28fb598f90d9181528/R/use_python.R#L205). This is the same error that I initially highlighted when filing this issue.

```r
condaenv <- "arcgispro-py3-clone"
conda <- "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone/Scripts/conda.bat"
required <- T

required <- required %||% use_python_required()

if (grepl("[/\\]", condaenv) &&
    grepl("^python[0-9.]*(exe)?", basename(condaenv))) {
  # path to python binary provided
  python <- condaenv
  if (!is_conda_python(python))
    warning("path supplied to use_condaenv() is not a conda python:\n\t",
            python)
  use_python(python, required = required)
  return(invisible(NULL))
}

# check for condaenv supplied by path
condaenv <- condaenv_resolve(condaenv)
if (grepl("[/\\]", condaenv) && is_condaenv(condaenv)) {
  python <- conda_python(condaenv)
  use_python(python, required = required)
  return(invisible(NULL))
}

conda <- conda_binary(conda)
if (identical(condaenv, "base")) {
  bin <- dirname(conda)
  suffix <- if (is_windows()) "../python.exe" else "python"
  python <- file.path(bin, suffix)
  return(use_python(python, required = required))
}

# list all conda environments
conda_envs <- conda_list(conda)

# look for one with that name
matches <- which(conda_envs$name == condaenv)

# if we had no matches, then either fail or return early as appropriate
if (length(matches) == 0) {
  if (required)
    stop("Unable to locate conda environment '", condaenv, "'.")
  return(invisible(NULL))
}

# check for multiple matches (this could happen if the user has multiple
# Conda installations, or multiple environment paths)
envs <- conda_envs[matches, ]
if (nrow(envs) > 1) {
  output <- paste(capture.output(print(envs)), collapse = "\n")
  warning("multiple Conda environments found; the first-listed will be chosen.\n", output)
}

# we now have a copy of Python to use -- add it to the list
python <- envs$python[[1]]
use_python(python, required = required)

``` 
```
# Error in normalizePath(path.expand(path), winslash, mustWork) : 
#  path[1]="C:/conda.exe": The system cannot find the file specified
```

5. Now, I'm jumping into the `use_python()` method to better understand what's happening with my ArcGIS Pro python path... This is failing when calling `python_config()` [here](https://github.com/rstudio/reticulate/blob/a6d2c44e372cf889ee57cd28fb598f90d9181528/R/use_python.R#L97). 

```r
python <- "C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3-clone/python.exe"
required <- T

required <- required %||% use_python_required()
if (required && !file_test("-f", python) && !file_test("-d", python))
  stop("Specified version of python '", python, "' does not exist.")

# if required == TRUE and python is already initialized then confirm that we
# are using the correct version
if (required && is_python_initialized()) {

  if (!file_same(py_config()$python, python)) {

    fmt <- paste(
      "ERROR: The requested version of Python ('%s') cannot be used, as",
      "another version of Python ('%s') has already been initialized.",
      "Please restart the R session if you need to attach reticulate",
      "to a different version of Python."
    )

    msg <- sprintf(fmt, python, py_config()$python)
    writeLines(strwrap(msg), con = stderr())

    stop("failed to initialize requested version of Python")

  }
}

# validate that this copy of python has libpython available
if (required) {
  config <- python_config(python)
  if (is.null(config$libpython)) {

    fmt <- heredoc("
      '%s' was not built with a shared library.
      reticulate can only bind to copies of Python built with '--enable-shared'.
    ")

    stopf(fmt, python)
  }
}
```
```
# Error in normalizePath(path.expand(path), winslash, mustWork) : 
#  path[1]="C:/conda.exe": The system cannot find the file specified
``` 
6. Exploring `python_config()` further, I'm getting an error when trying to call `python_munge_path()` [here](https://github.com/rstudio/reticulate/blob/a6d2c44e372cf889ee57cd28fb598f90d9181528/R/config.R#L647).

```r
python <- "C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3-clone/python.exe"
python_versions <- python
required <- T

# normalize and remove duplicates
python <- canonical_path(python)
python_versions <- canonical_path(python_versions)
python_versions <- unique(python_versions)

# update and restore PATH when done
oldpath <- python_munge_path(python)
```
```
# Error in normalizePath(path.expand(path), winslash, mustWork) : 
#  path[1]="C:/conda.exe": The system cannot find the file specified
```

7. Looking into `python_munge_path()` I'm getting an error when trying to call `get_python_conda_info()` [here](https://github.com/rstudio/reticulate/blob/a6d2c44e372cf889ee57cd28fb598f90d9181528/R/config.R#L562).

```r
python <- "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone/python.exe"

python_home <- dirname(python)
python_dirs <- c(normalizePath(python_home))

# fix rpath for anaconda libmkl
if (is_osx()) {
  libmkl <- file.path(python_home, "../lib/libmkl_intel_thread.dylib")
  if (file.exists(libmkl)) {
    libmkl <- normalizePath(libmkl)
    args <- c("-add_rpath", shQuote(dirname(libmkl)), libmkl)
    system2("install_name_tool", args, stdout = FALSE, stderr = FALSE)
  }
}



if (is_conda_python(python)) {
  conda_info <- get_python_conda_info(python)

  if (numeric_conda_version(conda_info$conda) >= "4.9") {

    new_path <- conda_run(
      "python",
      c("-c", shQuote("import os; print(os.environ['PATH'])")),
      conda = conda_info$conda,
      envname = conda_info$root,
      stdout = TRUE
    )

    old_path <- Sys.getenv("PATH")
    Sys.setenv("PATH" = new_path)
    return(old_path)
  }

}
```
```
# Error in normalizePath(path.expand(path), winslash, mustWork) : 
#  path[1]="C:/conda.exe": The system cannot find the file specified
``` 
8. Exploring `get_python_conda_info()`, we FINALLY arrive at the root cause of this issue!!! This method attempts to build a path to `condabin/conda.bat`. However, because my installation of python/conda is non-standard, my `conda.bat` binary is not nested within a `condabin` directory!!! Therefore, `dir.exists(file.path(root, "condabin"))` returns `FALSE` and `python_info_condaenv_find(root)` is called. This method erroneously assigns  `C:/conda.exe`  to the `conda` object because it cannot find my ArcGIS conda environment!!! This occurs [here](https://github.com/rstudio/reticulate/blob/a6d2c44e372cf889ee57cd28fb598f90d9181528/R/conda.R#L911).

```r
python <- "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone/python.exe"

stopifnot(is_conda_python(python))

root <- if (is_windows())
  dirname(python)
else
  dirname(dirname(python))

if (dir.exists(file.path(root, "condabin"))) {
  # base conda env
  conda <- if (is_windows())
    file.path(root, "condabin/conda.bat")
  else
    file.path(root, "bin/conda")
} else {
  # not base env, parse conda-meta history to find the conda binary
  # that created it
  conda <- python_info_condaenv_find(root)
}

conda

list(
  conda = normalizePath(conda, winslash = "/", mustWork = TRUE),
  root = normalizePath(root, winslash = "/", mustWork = TRUE)
)
```
```
# [1] "C:/conda.exe"
# Error in normalizePath(path.expand(path), winslash, mustWork) : 
#  path[1]="C:/conda.exe": The system cannot find the file specified
```
9. Finally, after exploring `python_info_condaenv_find()` there are a couple things of interest. The first is that this method searches for a `conda.exe` that lives within `condabin`. The ArcGIS Pro installation of python/conda does not contain a `condabin/conda.exe`! However, this doesn't throw any errors because `python_info_condaenv_find()` is handling a missing file exception. Moving further into this method, we can see that it attempts to read the `conda-meta/history` file. This is essentially a log file containing metadata about the conda environments creation/configuration. This path does exist on the ArcGIS Pro installation of python/conda, however, due to a space in the absolute path (e.g. `C:\Program Files`, things start breaking when `strsplit()` is called. The net result is that this method erroneously builds a path to a non-existent conda executable (`C://conda.exe`)... This issue is contained [here](https://github.com/rstudio/reticulate/blob/a6d2c44e372cf889ee57cd28fb598f90d9181528/R/python-tools.R#L168-L175).

```r
root <- "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3-clone"
path <- root

# first, check if we have a condabin
exe <- if (is_windows()) "conda.exe" else "conda"
conda <- file.path(path, "condabin", exe)
if (file.exists(conda))
  return(conda)

# read history file
histpath <- file.path(path, "conda-meta/history")
if (!file.exists(histpath))
  return(NULL)

history <- readLines(histpath, warn = FALSE)

# look for cmd line
pattern <- "^[[:space:]]*#[[:space:]]*cmd:[[:space:]]*"
lines <- grep(pattern, history, value = TRUE)
if (length(lines) == 0)
  return(NULL)

# get path to conda script used
line <- gsub(pattern, "", lines[[1]])
parts <- strsplit(line, "[[:space:]]+")[[1]]
script <- parts[[1]]

# on Windows, a wrapper script is recorded in the history,
# so instead attempt to find the real conda binary
conda <- file.path(dirname(script), exe)
normalizePath(conda, winslash = "/", mustWork = FALSE)
```
```
# [1] "C:/conda.exe"
```

**Next Steps:** 

I am requesting that the `python_info_condaenv_find()` method is modified to better account for edge cases and non-standard installations of python/conda. I am still exploring a solution to this problem but I can try to submit a pull request if I come up with anything. That being said, my use case is specific to the ArcGIS version of python/conda, and I would hope that a more generic solution can be identified within the community to avoid this issue for other non-standard versions of python/conda. Please let me know how we can proceed to remedy this issue. My entire geospatial data infrastructure at my job is dependent on interfacing reticulate with ArcPy. I'm happy to dedicate as much time as necessary to document and debug this issue further.

**Comment by t-kalinowski** [comment]
Thank you for the thorough investigation and write-up!

It sounds like the root cause is that when reticulate parses the `conda-meta/history` file of a condaenv, it doesn't handle spaces in the file path correctly.

Perhaps a fix is just to parse the history a little more carefully, e.g,

in `python_info_condaenv_find()` replace:

``` R
line <- gsub(pattern, "", lines[[1]])
parts <- strsplit(line, "[[:space:]]+")[[1]]
script <- parts[[1]]
```

with something like:

``` R
line <- sub("cmd: (.+)\\s+create\\s+.*", "\\1", lines[[1]])
```

Would you like to submit a PR?

**Comment by philiporlando** [comment]
@t-kalinowski, thanks for summarizing the root cause of the issue. I have modified the `python_info_condaenv_find()` method to correctly parse the file paths containing spaces within the `conda-meta/history` file. I will submit a pull request addressing this issue today.
