### ISSUE TITLE
Cannot import installed modules in virtual environments

### ISSUE THREAD

**Issue by melissa-barca** [rstudio/reticulate#1150]
This issue originally came up in an RStudio Workbench support issue: https://rstudioide.zendesk.com/agent/tickets/71039

**Update:**

The issue here is that `reticulate::use_virtualenv` can without displaying an error.`use_virtualenv` should either set the requested virtual environment or display an error that a different environment is already in use. See issue comments for more details. 

**Outdated/original issue text:**

Reticulate seems to not find packages when their import name is different from the name they were installed with.

@jgutman attempted to reproduce At first we thought the issue was related to the R version (could reproduce with 4.0.5, 4.1.2, and 4.2 but things worked as expected with R 4.1.0) - but digging further it appears to be related to when the environment gets created. I was able to inconsistently import the module after restarting R after creating the virtualenv. 

When things work as expected:
![image](https://user-images.githubusercontent.com/5323711/152202279-57cd818f-0309-4770-bf8e-470ad817484f.png)

When things do not work as expected:
![image](https://user-images.githubusercontent.com/5323711/152206710-c24e67a7-ecf1-485b-9876-437978c2f23c.png)

**Comment by jgutman** [comment]
I see the same behavior if I created the virtualenv directly in Python. 

In python:

```
python -m venv ~/.virtualenvs/test
pip install scikit-learn
```

In R with reticulate (tried with 1.24 and 1.24.9000 from Github):
```
> library(reticulate)
> use_virtualenv("test")
> import("joblib")
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'joblib'
 
> import("sklearn")
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'sklearn'
  
 > reticulate::py_list_packages("test")
         package  version             requirement
1        joblib    1.1.0           joblib==1.1.0
2         numpy   1.22.1           numpy==1.22.1
3 opencv-python 4.5.5.62 opencv-python==4.5.5.62
4  scikit-learn    1.0.2     scikit-learn==1.0.2
5         scipy    1.7.3            scipy==1.7.3
6 threadpoolctl    3.1.0    threadpoolctl==3.1.0

> reticulate::virtualenv_python("test")
[1] "/Users/jacquelinegutman/.virtualenvs/test/bin/python"

> import_from_path("joblib", "~/.virtualenvs/test/lib/python3.9/site-packages/")
Module(joblib)
> import("sklearn")
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'sklearn'
> import_from_path("sklearn", "~/.virtualenvs/test/lib/python3.9/site-packages/")
Module(sklearn)
 
 

```

**Comment by jgutman** [comment]
Notably, I think the fact that the install names are different from the package import names (e.g. `scikit-learn` vs `sklearn`, `opencv-python` vs `cv2`) is a red herring. This seems to be the root of the problem:

```
> library(reticulate)
> use_python(virtualenv_python("test"))
> import("sklearn")
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'sklearn'
> py_exe()
[1] "/Users/jacquelinegutman/Library/miniconda3/bin/python3.9"
```

If I run `use_python(virtualenv_python("test"))` or equivalently `use_virtualenv("test")`, I expect the python executable to point to `virtualenv_python("test")`, which in my case is `~/.virtualenv/test/bin/python`

Instead, it points to the miniconda python. The module import fails because those modules don't exist in my miniconda python, even though they do exist in my virtual env, as evidenced by `py_list_packages("test")` as well as the message indicating they are already installed if I run `virtualenv_install("test", "sklearn")`

**Comment by jgutman** [comment]
Update: I realized that I had `RETICULATE_PYTHON` set in my `~/.Renviron`. Once I removed it, I was able to successfully run 

```
> library(reticulate)
> use_virtualenv("test")
> import("sklearn")
Module(sklearn)
> py_exe()
[1] "/Users/jacquelinegutman/.virtualenvs/test/bin/python"
```
whereas previously, the import failed and the `py_exe()` returned the wrong python (meaning, it returned the one set by my RETICULATE_PYTHON, and not by my call to `use_virtualenv("test")`.

Ideally, I would **expect the explicit call to `use_virtualenv("test")` to override the environment variable** in `RETICULATE_PYTHON`, or if that's not possible, **for an error or warning message to indicate that I am not able to use the virtualenv** I've requested.

Awaiting additional information as to whether this solves Melissa's issue as well as the original customer support issue

**Comment by t-kalinowski** [comment]
Thank you for filing!

I just pushed https://github.com/rstudio/reticulate/commit/cbab2f0957b3091029e2ee9b32e8e2d0febb8bfc. `use_python()` will now issue a warning if the request for a specific python will be ignored, so hopefully this will be easier to catch in the future.
