### ISSUE TITLE
`mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'` possible erroneous architecture expectation on MacOXS Monterrey 12.1 with Apple M1 chip 

### ISSUE THREAD

**Issue by ncoston-virga** [rstudio/reticulate#1159]
We are debugging the `initialize_python` and were at the 

```
newpythonpath <- Sys.getenv("RETICULATE_PYTHONPATH", 
      unset = paste(config$pythonpath, system.file("python", 
        package = "reticulate"), sep = .Platform$path.sep))
```

which results in 

```
"/Users/nataliecoston/opt/anaconda3/lib/python39.zip:/Users/nataliecoston/opt/anaconda3/lib/python3.9:/Users/nataliecoston/opt/anaconda3/lib/python3.9/lib-dynload:/Users/nataliecoston/opt/anaconda3/lib/python3.9/site-packages:/Users/nataliecoston/opt/anaconda3/lib/python3.9/site-packages/aeosa:/Users/nataliecoston/opt/anaconda3/lib/python3.9/site-packages/locket-0.2.1-py3.9.egg:/Users/nataliecoston/repos/crsspierViz/renv/library/R-4.1/aarch64-apple-darwin20/reticulate/python"
```

We noticed the `aarch64-apple-darwin20` which matches the R architecture but not the Python architecture. My friend debugging with a machine with identical hardware has `x86_64-apple-darwin17.0` and he does not experience the error.

The full error is below 

```
Error in py_initialize(config$python, config$libpython, config$pythonhome,  : 
  /Users/nataliecoston/opt/anaconda3/lib/libpython3.9.dylib - dlopen(/Users/nataliecoston/opt/anaconda3/lib/libpython3.9.dylib, 0x000A): tried: '/Users/nataliecoston/opt/anaconda3/lib/libpython3.9.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/libpython3.9.dylib' (no such file)
```

I think this is related to issues #1014 and #995.

These are the machine details.
![Screen Shot 2022-02-10 at 10 13 19 AM](https://user-images.githubusercontent.com/97978701/153460597-8b33b394-8c9e-40c0-87b6-230b75b376f1.png)

<details> 
<summary> sessionInfo </summary>

```
R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8           compiler_4.1.2       later_1.3.0          prettyunits_1.1.1    remotes_2.4.2        tools_4.1.2         
 [7] testthat_3.1.1       digest_0.6.29        pkgbuild_1.3.1       pkgload_1.2.4        jsonlite_1.7.3       lattice_0.20-45     
[13] memoise_2.0.1        lifecycle_1.0.1      png_0.1-7            rlang_1.0.1          Matrix_1.4-0         shiny_1.7.1         
[19] cli_3.1.1            curl_4.3.2           fastmap_1.1.0        withr_2.4.3          desc_1.4.0           fs_1.5.2            
[25] devtools_2.4.3       grid_4.1.2           rprojroot_2.0.2      reticulate_1.24-9000 glue_1.6.1           R6_2.5.1            
[31] processx_3.5.2       sessioninfo_1.2.2    callr_3.7.0          purrr_0.3.4          magrittr_2.0.2       ps_1.6.0            
[37] promises_1.2.0.1     ellipsis_0.3.2       htmltools_0.5.2      usethis_2.1.5        mime_0.12            xtable_1.8-4        
[43] renv_0.14.0          httpuv_1.6.5         cachem_1.0.6         crayon_1.4.2

```

</details>

**Comment by ncoston-virga** [comment]
@kevinushey Any ideas on the above?

**Comment by kevinushey** [comment]
The architecture of the Python installation you want to load needs to match the architecture of the running copy of R.

My best guess is that, since this is an x86_64 installation of Python, you need to install + use an x86_64 build of R.

Or, alternatively (and preferredly), install an arm64 build of R, and install an arm64 build of Python. With the latest releases of `reticulate`, you can use:

```
reticulate::install_miniconda()
```

and on arm64 builds of R, this will install an arm64 build of miniconda from conda-forge.

**Comment by ncoston-virga** [comment]
I see, I think its my version of python that was automatically configured from downloading anaconda that is causing the problem. Let me see if I can get that working. Tagging @yogat3ch for context.

**Comment by SheahLinLee** [comment]
Spent the whole day trying to figured out whats wrong until I read this thread. 
Turns out: Architecture for Mac with M1 chip is arm64. 
So you need to make sure that the R you installed is the correct R. I installed the R version for Mac intel chip, which was not the right one. Installed **([R-4.2.1-arm64.pkg].**  instead and now its working absolutely fine.

**Comment by FedererKK** [comment]
confirming the above, using the proper R for M1 solved the issue without touching miniconda

**Comment by NicoBarti** [comment]
Thanks a lot! This did the trick for me too!

**Comment by floswald** [comment]
I just had to tell conda to install a x64 env on my silicon mac: 

`conda create --platform osx-64 --name environment_name python `
