### ISSUE TITLE
Clarify `condaenv` use in `use_condaenv`

### ISSUE THREAD

**Issue by achimgaedke** [rstudio/reticulate#1164]
I'm using reticulate version 1.24 and am pleased that #1155 is solved.

I accidentally (and for this report intentionally) have two conda environments with the same name

```bash
mamba create -n test python
mamba create -p ~/test python
```

That's the result

```bash
mamba info -eq
# conda environments:
#
                         /home/achim.gaedke/test
data-processing          /opt/conda-envs/envs/data-processing
test                     /opt/conda-envs/envs/test
base                  *  /opt/tljh/user
```

Now I use `reticulate::use_condaenv(condaenv="test")`
```
Warning message in reticulate::use_condaenv(condaenv = "test"):
“multiple Conda environments found; the first-listed will be chosen.
   name                                python
1 test    /home/achim.gaedke/test/bin/python
3 test  /opt/conda-envs/envs/test/bin/python”
```

but I want to select the second one, so I try out `reticulate::use_condaenv(condaenv="/opt/conda-envs/envs/test/bin/python")` - and it works! 🎉 

Reading the reference: https://rstudio.github.io/reticulate/reference/use_python.html I wonder whether it is intended and if so, is it worth mentioning that the environment prefix can be used as well (and when a name is a prefix).

**Comment by t-kalinowski** [comment]
Hi, thanks for filing! This is a recent new feature. There was a [NEWS item](https://github.com/rstudio/reticulate/blob/214b90af4177969c4403187ddcb7e67b2c492d25/NEWS.md?plain=1#L52), but the docs still need to be updated. Would you like to submit a PR?

**Comment by achimgaedke** [comment]
Yeah, will do - I tried a bit more:

* `/opt/conda-envs/envs/test` (the env prefix) works and 
*`/opt/conda-envs/envs/test/bin/python` (the env executable) works
