### ISSUE TITLE
[ERROR] use_condaenv not working as expected

### ISSUE THREAD

**Issue by WaterKnight1998** [rstudio/reticulate#1176]
Good afternoon,

I tried to update reticulate to version 1.24 and R 4.1.1. `use_condaenv` function is not working as earlier versions ( < 1.20 ).

The `conda` parameter to specify the path to conda binary is ignored. 

In earlier versions you could use it for example if you were working with micromamba instead of conda.

The error is:

```R
use_condaenv(condaenv="micromamba/envs/test", conda="micromamba/bin/micromamba");
Error in normalizePath(conda, winslash = "/", mustWork = TRUE) : 
  path[1]="./conda": No such file or directory
```

You are getting the path from `python_info_condaenv_find `

**Comment by philiporlando** [comment]
@WaterKnight1998, I think your issue was addressed in this PR #1154 which will be resolved with the release of [reticulate_1.25](https://github.com/rstudio/reticulate/pull/1154/commits/46f31754fae1e62203c8a139425cf5de8228571b#diff-51920e95310ebfbc1ae31709f3b95f89afffbf4f1a6e38e8b2b406e2fb6197ea). 

You could try installing the latest development version of `reticulate` via `remotes::install_github()`. Downgrading to `reticulate_1.22` should also resolve your issue until the newest version has been officially released.

**Comment by mortunco** [comment]
Hello. I am afraid this problem hasnt solved in 1.26. I was able to get around with downgrading to 1.22 and restarting the kernel.

Thank you very much for your suggestion!

```
install.packages("https://cran.r-project.org/src/contrib/Archive/reticulate/reticulate_1.22.tar.gz",repos=NULL, type="source")
use_condaenv(condaenv="~/micromamba/envs/singlecell", conda="~/.local/bin/micromamba");
```

**Comment by t-kalinowski** [comment]
@mortunco The current release version of reticulate is 1.27. do you encounter the same issue with 1.27?

**Comment by minhkhul** [comment]
Letting you know that I'm seeing this issue in 1.27 still.

**Comment by mortunco** [comment]
> @mortunco The current release version of reticulate is 1.27. do you encounter the same issue with 1.27?

Sorry just saw it. In addition to this, my workaround was install mambaforge. I know this is not very possible for the folks who has stable system but mambaforges basically uses conda infastructure (at least reticulate was happy with it).

**Comment by XilinMao** [comment]
I'm seeing this issue in 1.28 still.

**Comment by gaospecial** [comment]
Try my branch and to see whether it can solve your problems.

`devtools::install_github("gaospecial/reticulate", ref = "patch-1")`

It solved my problem. 

See #1375

**Comment by t-kalinowski** [comment]
Fix from @gaospecial's branch has been merged into main. Thank you!
