### ISSUE TITLE
multiple pkgs for installation fails

### ISSUE THREAD

**Issue by turgut090** [rstudio/reticulate#1177]
Hi there,

Did you update the installation of python packages???

I cannot pass multiple ones... ;/

```
reticulate::py_install(c('numpy pandas'),pip = T)
Activated conda python: /home/turgut/.local/share/r-miniconda/envs/r-reticulate/bin/python
ERROR: Invalid requirement: 'numpy pandas'
```

However, one can install them one by one.

EDIT, the following helped me:

```
require(devtools)
install_version("reticulate", version = "1.21", repos = "http://cran.us.r-project.org")
```

**Comment by t-kalinowski** [comment]
Hi, we started quoting them to protect from the shell interpreting package requests like `"numpy<1.23"`.
You can pass in an R character vector:
```R
reticulate::py_install(c('numpy', 'pandas'), pip = T)
```

**Comment by t-kalinowski** [comment]
it might still be reasonable to `strsplit(pkgs, "[[:space:]]")` before quoting.

**Comment by t-kalinowski** [comment]
You can pass a `pip_options` argument to `py_install()`, like

```R
reticulate::py_install('torch',
  pip_options = '-f https://download.pytorch.org/whl/cu113/torch_stable.html',
  pip = TRUE)
```
This could also work:
```
reticulate::py_install(
  c('torch', '-f', 'https://download.pytorch.org/whl/cu113/torch_stable.html'), 
  pip = T)
```

Also, if you install the development version of reticulate you'll see the actual system command being run, which should help diagnose issues like this where arguments aren't being quoted the way you expect.

**Comment by turgut090** [comment]
Thanks!
