### ISSUE TITLE
Invalid version specification

### ISSUE THREAD

**Issue by utkarshOffice** [rstudio/reticulate#1182]
In my shiny app, whenever I'm referring to the python files or environment following error is occurring and the app is crashing. Specifically, it is happening when "source_python" function is being used. reticulate::py_config() has also failed similarly. The error is 
"> reticulate::py_config()
**_Error: invalid version specification ‘'.' is not recognized as an internal or external command,’, ‘. program or batch file.’
In addition: Warning message:
In if (grepl("\\.$", v)) v <- paste0(v, "9000") :
  the condition has length > 1 and only the first element will be used_**"

> utils::sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252   
[3] LC_MONETARY=English_India.1252 LC_NUMERIC=C                  
[5] LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods  
[7] base     

other attached packages:
[1] reticulate_1.24

loaded via a namespace (and not attached):
 [1] BiocManager_1.30.16 compiler_4.1.2      Matrix_1.4-0       
 [4] tools_4.1.2         Rcpp_1.0.8.3        grid_4.1.2         
 [7] jsonlite_1.7.2      renv_0.15.4         png_0.1-7          
[10] lattice_0.20-45

Please suggest if you can think of some reason for the same...

**Comment by sarathsund** [comment]
following.

**Comment by dfalbel** [comment]
Hi, 

This probably indicates that reticulate has issues in finding a suitable python installation.
Given the error message it seems to be coming from, so a problem with the conda installation is likely.

https://github.com/rstudio/reticulate/blob/383d4e7085a541b8f46e9e8d9abb415247400df1/R/conda.R#L599-L601

We now suggest using virtualenvs if possible, see more [info](https://rstudio.github.io/reticulate/articles/python_packages.html#virtualenv-installation).
