### ISSUE TITLE
How to change numpy version for pytorch

### ISSUE THREAD

**Issue by dslate** [rstudio/reticulate#119]
I think this issue is related to "Integration with numpy is not optional #110".  I am running R on an x86_64 machine under Ubuntu Linux 16.04 LTS.  I have pytorch installed and would like to use it from R via reticulate.  I am able to run pytorch directly from python3, but when I try to do so via reticulate it gets the wrong (system) version of numpy and complains.  From python3 I can modify sys.path to point to a set of packages, including numpy, that pytorch installed so as to override the system versions.  But reticulate ignores this version (1.13.1) of numpy, presumably because it has already configured itself to use the system version (1.11.0), which is rejected by torch.  I was unable to find a workaround using one of the "use_*" functions in reticulate.  I know that I could probably "fix" the problem by installing a new python3, either using conda or virtual environment, or just in /usr/local, and then rebuilding pytorch, but that seems like a lot of work just to get
reticulate to do what python3 can already do by itself.  I also don't want to mess with the system installation of python3 by overwriting its version of numpy with one that pytorch likes.

Am I missing a simple fix to this issue?  Here is a log illustrating the problem:

Script started on Thu Oct 26 23:10:23 2017
dave@pixel: ~/porto dave@pixel:~/porto$ ./pytorch-tst.sh

Thu Oct 26 23:10:35 CDT 2017
Linux pixel 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

cat pytorch-tst.py:
------------------------------------------------------
#!/usr/bin/env python3

import sys
print( sys.version)
sys.path.insert( 0, '/home/dave/.local/lib/python3.5/site-packages')    # to get latest numpy for torch
import numpy
print( numpy.__version__)
import torch
print( torch.__version__)
------------------------------------------------------

./pytorch-tst.py:
------------------------------------------------------
3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
1.13.1
0.2.0_3
------------------------------------------------------

cat pytorch-tst.R:
------------------------------------------------------
#!/usr/local/bin/Rscript

library( reticulate)
sessionInfo()
use_python( "/usr/bin/python3", required = T)
py_run_string(
"
import sys
print( sys.version)
sys.path.insert( 0, '/home/dave/.local/lib/python3.5/site-packages')    # to get latest numpy for torch
import numpy
print( numpy.__version__)
import torch
print( torch.__version__)
")
------------------------------------------------------

./pytorch-tst.R:
------------------------------------------------------
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/local/lib/R/lib/libRblas.so
LAPACK: /usr/local/lib/R/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  base     

other attached packages:
[1] reticulate_1.2

loaded via a namespace (and not attached):
[1] compiler_3.4.2 Rcpp_0.12.13   methods_3.4.2  jsonlite_1.5  
3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
1.11.0
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Error in py_run_string_impl(code, local, convert) : 
  ImportError: numpy.core.multiarray failed to import

Detailed traceback: 
  File "<string>", line 7, in <module>
  File "/home/dave/.local/lib/python3.5/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
Calls: py_run_string -> py_run_string_impl -> .Call
Execution halted
------------------------------------------------------
Thu Oct 26 23:10:37 CDT 2017
dave@pixel: ~/porto dave@pixel:~/porto$ exit
exit

Script done on Thu Oct 26 23:10:38 2017

**Comment by jjallaire** [comment]
The problem is that reticulate needs to load numpy during it's initialization (to get access to the NumPy C APIs) and this is happening before you interact with `sys.path`. It may work to try to set the sys.path via an environment variable instead, see https://stackoverflow.com/questions/897792/where-is-pythons-sys-path-initialized-from.

If that doesn't work then I don't think that reticulate's initialization / numpy binding semantics are compatible with this scenario.

**Comment by dslate** [comment]
Thanks jjallaire for your response.  I tried setting PYTHONPATH and exporting it from the shell before executing my script, but that didn't help.  Would it be possible for reticulate to query PYTHONPATH as part of its initialization?  Or perhaps, since it already has a use_python function, might it also provide a use_pythonpath function that specifies an initial sys.path as its argument?

**Comment by dslate** [comment]
I have resolved my problem by installing python 3.6, which seems to work ok with pytorch and reticulate.

**Comment by jjallaire** [comment]
Okay, that's good to hear. I played with attempting to defer the initialization of NumPy but at least in our current design we need it to get past square 1.
