### ISSUE TITLE
Mamba Support : Invalid Version specifications

### ISSUE THREAD

**Issue by sarathsund** [rstudio/reticulate#1202]
**Unable to load any packages with the latest reticulate package.**

**Below are the additional details..
I am trying to reuse the custom python package previously created as R compatible with reticulate
R is provided in jupyter notebook environment
this environment is restricted from internet access
mamba packages are pre loaded shared drive to install on demand
R & Python are provided by jupyter notebook abstraction -default
Not a root user
Python
Python 3.9.12
/opt/mamba/bin/python**

> library(reticulate)
> reticulate::py_config()
Error: invalid version specification ‘. 0.23.0’
In addition: Warning message:
In if (grepl("\\.$", v)) v <- paste0(v, "9000") :
  the condition has length > 1 and only the first element will be used
> utils::sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS/LAPACK: /opt/mamba/lib/libopenblasp-r0.3.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] reticulate_1.24

loaded via a namespace (and not attached):
[1] compiler_4.1.3  Matrix_1.4-1    tools_4.1.3     Rcpp_1.0.8.3
[5] grid_4.1.3      jsonlite_1.8.0  png_0.1-7       lattice_0.20-45
>
> os <- import("os")
Error: invalid version specification ‘. 0.23.0’
In addition: Warning message:
In if (grepl("\\.$", v)) v <- paste0(v, "9000") :
  the condition has length > 1 and only the first element will be used

**Comment by t-kalinowski** [comment]
Thanks for filing! This should be fixed in main now.

**Comment by sarathsund** [comment]
hi @t-kalinowski  fyi. its failing in the pckdown pipeline in git.. 

Writing 'authors.html'
Writing 'LICENSE-text.html'
Error: Error in readRDS(con) : error reading from connection
Calls: <Anonymous> ... <Anonymous> -> as.data.frame -> read_CRAN_object -> readRDS
Execution halted
Error: Process completed with exit code 1.

But let me download and try this fix. thanks again
