### ISSUE TITLE
Mamba Support : Error in system2t

### ISSUE THREAD

**Issue by sarathsund** [rstudio/reticulate#1204]
**CONTINUATION: Unable to load any packages with the latest reticulate package.
@t-kalinowski 

Below are the additional details..
I am trying to reuse the custom python package previously created as R compatible with reticulate
R is provided in jupyter notebook environment
this environment is restricted from internet access
mamba packages are pre loaded shared drive to install on demand
R & Python are provided by jupyter notebook abstraction -default
Not a root user
Python
Python 3.9.12
/opt/mamba/bin/python**

> library(reticulate)
> os <- import("os")
Error in system2t(conda, c("run", in_env, run_args, shQuote(cmd), args),  :
  could not find function "system2t"

**Comment by t-kalinowski** [comment]
@sarathsund Can you perhaps provide a docker image with your environment so I can reproduce the error?

**Comment by sarathsund** [comment]
@t-kalinowski  it took some time to prepare a skeleton for our docker image. I have attached the docker file+directory this will help to reproduce the issue we have with reticulate with mamba. let me know for any further details. 
[mambaR.zip](https://github.com/rstudio/reticulate/files/8630548/mambaR.zip)

**Comment by t-kalinowski** [comment]
```
$ docker run 2f53fbff7843
[FATAL tini (7)] exec start-notebook.sh failed: No such file or directory
```

**Comment by sarathsund** [comment]
@t-kalinowski  I have used the notebook with mamba installation and attached the source below. 

Steps 
1. navigate to  docker-stacks-master\base-notebook 
2. Build docker file and run it 
3. access localhost:8888 for notebook bring up
4. use token from server command line outputs to login
5. you have jupyterlab bring up and access terminal 
6. install reticulate (the difference is to install from mamba & in our actual bring up we download this from our local conda-forge)
7. try to execute reticulate commands. 

attached the source and error I received from local bring up. 
you can install latest reticulate from source with the conda.R file fixes to reproduce the system2t issue

[docker-stacks-master.zip](https://github.com/rstudio/reticulate/files/8643768/docker-stacks-master.zip)


![mamba install issue 1 1](https://user-images.githubusercontent.com/6964886/167220726-0a0cb697-202b-49dd-938e-d6fccc25c9ea.JPG)

![mamba install issue 1 2](https://user-images.githubusercontent.com/6964886/167220730-16c3f9e5-df54-48f6-a3d0-fe9f9bd318f0.JPG)

**Comment by t-kalinowski** [comment]
Thanks for the updated dockerfile, I see your environment is substantially customized.
I unfortunately still encounter an error when attempting to run the dockerfile:
```bash
tomasz@horse:~/r-pkgs/reticulate/issues/1204-mamba/docker-stacks-master/base-notebook
$ docker build -t reticulate-issue-1204-mamba .
< .... lots of output ...>
Successfully built 491c1ddef45e
Successfully tagged reticulate-issue-1204-mamba:latest

$ docker run -t reticulate-issue-1204-mamba
[FATAL tini (7)] exec start-notebook.sh failed: Permission denied
```

**Comment by sarathsund** [comment]
@t-kalinowski  I did execute this in my local and able to run smoothly.. 
am trying to retest this again with other machine to check for any issue. will update you shortly 
fyi using wsl and dockerdesktop for this testing

below is the code output


sarath@LNGRDUL-7016350:/springtestapp/docker-stacks-master/base-notebook$ docker build -t dockerstacks .
[+] Building 33.1s (21/21) FINISHED
 => [internal] load build definition from Dockerfile                                                                          0.1s
 => => transferring dockerfile: 7.01kB                                                                                        0.0s
 => [internal] load .dockerignore                                                                                             0.1s
 => => transferring context: 34B                                                                                              0.0s
 => [internal] load metadata for docker.io/library/ubuntu:focal                                                               4.0s
 => [internal] load build context                                                                                             0.0s
 => => transferring context: 185B                                                                                             0.0s
 => [1/16] FROM docker.io/library/ubuntu:focal@sha256:47f14534bda344d9fe6ffd6effb95eefe579f4be0d508b7445cf77f61a0e5724        0.0s
 => CACHED [2/16] RUN apt-get update --yes &&     apt-get upgrade --yes &&     apt-get install --yes --no-install-recommends  0.0s
 => CACHED [3/16] COPY fix-permissions /usr/local/bin/fix-permissions                                                         0.0s
 => CACHED [4/16] RUN chmod a+rx /usr/local/bin/fix-permissions                                                               0.0s
 => CACHED [5/16] RUN sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc &&    echo 'eval "$(comm  0.0s
 => CACHED [6/16] RUN echo "auth requisite pam_deny.so" >> /etc/pam.d/su &&     sed -i.bak -e 's/^%admin/#%admin/' /etc/sudo  0.0s
 => CACHED [7/16] RUN mkdir "/home/jovyan/work" &&     fix-permissions "/home/jovyan"                                         0.0s
 => CACHED [8/16] WORKDIR /tmp                                                                                                0.0s
 => CACHED [9/16] RUN set -x &&     miniforge_arch=$(uname -m) &&     miniforge_installer="Mambaforge-Linux-${miniforge_arch  0.0s
 => CACHED [10/16] RUN mamba install conda-mirror -y                                                                          0.0s
 => [11/16] RUN mamba clean --all -f -y &&     rm -rf /opt/mamba/share/jupyter/lab/staging &&     rm -rf /home/jovyan/.cache  3.6s
 => [12/16] RUN rm  /opt/mamba/bin/conda &&     ln -s /opt/mamba/bin/mamba /opt/mamba/bin/conda                               0.8s
 => [13/16] COPY start.sh start-notebook.sh start-singleuser.sh /usr/local/bin/                                               0.1s
 => [14/16] COPY jupyter_server_config.py /etc/jupyter/                                                                       0.1s
 => [15/16] RUN sed -re "s/c.ServerApp/c.NotebookApp/g"     /etc/jupyter/jupyter_server_config.py > /etc/jupyter/jupyter_not  0.7s
 => [16/16] WORKDIR /home/jovyan                                                                                              0.0s
 => exporting to image                                                                                                       23.6s
 => => exporting layers                                                                                                      23.5s
 => => writing image sha256:3b5ed4e081c88b5ffcb3ae4adfe02bdbc1066f8750b2416813b9fbcb3aa2f5c5                                  0.0s
 => => naming to docker.io/library/dockerstacks                                                                               0.0s
sarath@LNGRDUL-7016350:~/springtestapp/docker-stacks-master/base-notebook$ docker run -p 8888:8888 dockerstacks
Entered start.sh with args: jupyter lab
Executing the command: jupyter lab
[I 2022-05-06 21:37:07.178 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-05-06 21:37:07.182 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-05-06 21:37:07.183 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-05-06 21:37:07.183 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-05-06 21:37:07.193 ServerApp] nbclassic | extension was successfully linked.
[I 2022-05-06 21:37:07.195 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2022-05-06 21:37:07.362 ServerApp] notebook_shim | extension was successfully linked.
[I 2022-05-06 21:37:07.418 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-05-06 21:37:07.420 LabApp] JupyterLab extension loaded from /opt/mamba/lib/python3.9/site-packages/jupyterlab
[I 2022-05-06 21:37:07.420 LabApp] JupyterLab application directory is /opt/mamba/share/jupyter/lab
[I 2022-05-06 21:37:07.425 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-05-06 21:37:07.430 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-05-06 21:37:07.430 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2022-05-06 21:37:07.430 ServerApp] Jupyter Server 1.17.0 is running at:
[I 2022-05-06 21:37:07.430 ServerApp] http://399ac27a3561:8888/lab?token=9a00a3cae0ebb85cfbebf9e675c2ee36fcc8da83d48a1148
[I 2022-05-06 21:37:07.430 ServerApp]  or http://127.0.0.1:8888/lab?token=9a00a3cae0ebb85cfbebf9e675c2ee36fcc8da83d48a1148
[I 2022-05-06 21:37:07.430 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2022-05-06 21:37:07.435 ServerApp]

    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-6-open.html
    Or copy and paste one of these URLs:
        http://399ac27a3561:8888/lab?token=9a00a3cae0ebb85cfbebf9e675c2ee36fcc8da83d48a1148
     or http://127.0.0.1:8888/lab?token=9a00a3cae0ebb85cfbebf9e675c2ee36fcc8da83d48a1148
[I 2022-05-06 21:37:21.419 ServerApp] 302 GET / (172.17.0.1) 0.79ms
[I 2022-05-06 21:37:21.429 LabApp] 302 GET /lab? (172.17.0.1) 1.24ms
[W 2022-05-06 21:37:59.200 ServerApp] 401 POST /login?next=%2Flab%3F (172.17.0.1) 1.21ms referer=http://localhost:8888/login?next=%2Flab%3F
[W 2022-05-06 21:38:14.129 ServerApp] 401 POST /login?next=%2Flab%3F (172.17.0.1) 1.71ms referer=http://localhost:8888/login?next=%2Flab%3F
[W 2022-05-06 21:38:15.636 ServerApp] 401 POST /login?next=%2Flab%3F (172.17.0.1) 1.97ms referer=http://localhost:8888/login?next=%2Flab%3F
[I 2022-05-06 21:38:58.757 ServerApp] Wrote hashed password to /home/jovyan/.jupyter/jupyter_server_config.json
[I 2022-05-06 21:38:58.757 ServerApp] 302 POST /login?next=%2Flab%3F (172.17.0.1) 42.75ms
[I 2022-05-06 21:39:02.008 LabApp] Build is up to date
[I 2022-05-06 21:39:15.156 ServerApp] Kernel started: 7110f3f7-36e8-41c0-bbe5-2cfa1009d4b7
[W 2022-05-06 21:39:16.168 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7fe313edbf70>
[I 2022-05-06 21:39:38.082 ServerApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
sarath@LNGRDUL-7016350:~/springtestapp/docker-stacks-master/base-notebook$

**Comment by sarathsund** [comment]
@t-kalinowski  I verified again. It works without any startup issue. could you help to retry with force builds and no cache ?

**Comment by sarathsund** [comment]
It was related to the conda vs mamba lib path issue.. Need to support correct python3 lib path or try to set it with RETICULATE_PYTHON variable in environment
