### ISSUE TITLE
`PIP_USER=true` interferes with use of conda (and venv?) in reticulate

### ISSUE THREAD

**Issue by mtmorgan** [rstudio/reticulate#1209]
A 'cloud-based' RStudio instance I use has `PIP_USER=true` as an environment variable. I cannot control how the instance is started. Consequently, conda installs packages into the user library, rather into the conda environment. For instance, assuming `install_miniconda(); conda_create('pip_user_true')` has been run, then
```
## $ PIP_USER=true R
library(reticulate)
conda_install('pip_user_true', 'bgzip', pip = TRUE)
```
appears to 'work', but actually bgzip has been installed in the user location
```
system2("find", c("/home/rstudio", "-name", "bgzip"))
## /home/rstudio/.local/lib/python3.8/site-packages/bgzip
```
instead of the conda environment.

A workaround is to create an `~/.Renviron` file with
```
PIP_USER=false
```
but since reticulate is advertising that it is using the conda environment, perhaps this could be set for the user automatically?

**Comment by t-kalinowski** [comment]
@mtmorgan Thank you for reporting! I just pushed a commit fixing this.

Please let us know if you run into other issues :)

**Comment by mtmorgan** [comment]
Thanks so much for the fast (and correct :)) fix Tomasz, this is great!
