### ISSUE TITLE
Transfer R objects from R session to py_run_file('script.py')

### ISSUE THREAD

**Issue by IrinaGoloshchapova** [rstudio/reticulate#121]
Dear Colleagues, 
Does reticulate provide the transfer of objects from the R session directly to Python to use them through py_run_file('script.py') or py_run_string('...')?

**Comment by jjallaire** [comment]
The `py` object (available in the development version of reticulate) allows you to assign objects into the Python main module, e.g.

```r
library(reticulate)
py$x <- 10
py_run_string("print(x)")
```

You can do this in the CRAN version by explicitly aliasing the main module:

```r
library(reticulate)
py <- import_main()
py$x <- 10
py_run_string("print(x)")
```
