### ISSUE TITLE
`py_id()` overflows in R-4.2 on Windows

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/reticulate#1216]
```
library(reticulate)
py_id(py_eval("object()"))
[1] -1
```

Maybe it makes sense to change the return type of `py_id()` to be a string, rather than some flavor of an R numeric.

(originally encountered with failing keras tests, only on windows w/ R 4.2. Workaround here: https://github.com/rstudio/keras/commit/254bf6946c9a8e03e665a82574d6ea5d470bd693)

**Comment by kevinushey** [comment]
Or perhaps this is our opportunity to start using / depending on `bit64` for 64-bit integers?

(I don't have a super strong opinion either way, but this has been a relatively long-standing pain point.)

**Comment by elong0527** [comment]
After reading discussions on ‘bit64’ in previous issues, I would vote a global option to allow user force long int to string.

**Comment by t-kalinowski** [comment]
I don't think reticulate should take a hard dependency on bit64, but we should think about how reticulate users can opt-in to bit64. Maybe by explicitly registering an S3 method for `py_to_r.python.builtin.int()`?

In any case, users probably will only compare `py_id()`s, not do math on them, so strings are probably OK.
