### ISSUE TITLE
What is the slice operator ':' in python in reticulate?

### ISSUE THREAD

**Issue by jeonghyunwoo** [rstudio/reticulate#122]
Belows are examples from pandas homepage.
How can I convert `series[::2]` into r in reticulate?
```
In [93]: series = pd.Series(np.random.randn(1000))
In [94]: series[::2] = np.nan
In [95]: series.describe()
```

**Comment by jjallaire** [comment]
It looks like maybe you can use the `iloc` function: http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.iloc.html

**Comment by jeonghyunwoo** [comment]
I tried subsetting with `reticulate`, but I couldn't find the same thing as `[` of python in `reticulate`.   
For example : 
```
library(reticulate)
pd = import('pandas')
np = import('numpy')
df = pd$DataFrame(dict(a = ,
                                       b = c('a','b','c'))
df
##    x  y
## 0  1 a
## 1  2 b
## 2  3 c

df$iloc(2) 
## LocIndexer 
## but, expected answer : 3 c

df$iloc[2, : ]
## Error: unexpected ':' in  "df$iloc[2,:"
```

**Comment by jjallaire** [comment]
We don't currently have the slice operator implemented for NumPy arrays. You can however use the `take` method to do extraction: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.take.html

Note that NumPy array indexes are 0-based!

**Comment by kovla** [comment]
This is rather convoluted, but works in this example and perhaps can be improved:
 
```
df <- r_to_py(data.frame(a = 1:3, b = letters[1:3]))
df$transpose()$iloc$`__getitem__`(0L)
```

**Comment by ArtemSokolov** [comment]
This is an old question, but one possible solution is to use `reticulate::py_run_string()` to perform slicing directly in Python. Two caveats:
* R objects should be prefixed with `r.`
* Result should be stored to a variable that can then be accessed via `py$` in R

Example:
``` r
df <- r_to_py(data.frame(a = 1:3, b = letters[1:3]))
py_run_string("result = r.df[::2]")
py$result
#   a b
# 1 1 a
# 3 3 c
```

The latter part can be wrapped into a simple function for convenience:
``` r
pyeval <- function(cmd) {py_run_string(paste("__res =", cmd)); py$`__res`}
pyeval("r.df[r.df.a > 1]")
#   a b
# 1 2 b
# 2 3 c
```

**Comment by t-kalinowski** [comment]
In python, `:` creates a `slice()` object, and `[` calls `__getitem__` or `__setitem__`. 

With reticulate, you can create a `slice()` object by calling the builtin function directly, and you can invoke `__getitem__` and `__setitem__` by using `[` in R, or invoking the methods with `py_set_item()` or `py_get_item()`. For example:
``` r
library(reticulate)
py_slice <- import_builtins()$slice
x <- np_array(array(seq(20), c(4, 5)))
x
#> array([[ 1,  5,  9, 13, 17],
#>        [ 2,  6, 10, 14, 18],
#>        [ 3,  7, 11, 15, 19],
#>        [ 4,  8, 12, 16, 20]], dtype=int32)
x[py_slice(NULL, NULL, 2L)] # e.g., x[::2]
#> array([[ 1,  5,  9, 13, 17],
#>        [ 3,  7, 11, 15, 19]], dtype=int32)
# x[py_slice(NULL, NULL, 2L)] <- 0L
py_set_item(x, py_slice(NULL, NULL, 2L), 0L) # e.g., x[::2] = 0
x
#> array([[ 0,  0,  0,  0,  0],
#>        [ 2,  6, 10, 14, 18],
#>        [ 0,  0,  0,  0,  0],
#>        [ 4,  8, 12, 16, 20]], dtype=int32)
```

**Comment by t-kalinowski** [comment]
The current version of reticulate brings slice support to `[` and `[<-`. (Added in #1432). 

This now works:
```r
## slice a NumPy array
x <- np_array(array(1:64, c(4, 4, 4)))

# R expression | Python expression
# ------------ | -----------------
  x[0]         # x[0]
  x[, 0]       # x[:, 0]
  x[, , 0]     # x[:, :, 0]

  x[NA:2]      # x[:2]
  x[`:2`]      # x[:2]

  x[2:NA]      # x[2:]
  x[`2:`]      # x[2:]

  x[NA:NA:2]   # x[::2]
  x[`::2`]     # x[::2]

  x[1:3:2]     # x[1:3:2]
  x[`1:3:2`]   # x[1:3:2]
```

See `?py_get_item` for examples.
