### ISSUE TITLE
Operators for python objects not dispatched

### ISSUE THREAD

**Issue by david-cortes** [rstudio/reticulate#1225]
Some python objects have custom methods for operators such as `+`. These are not preserved when imported through reticulate.

Example:
```python
from sklearn.gaussian_process.kernels import WhiteKernel, RBF
k = WhiteKernel() + RBF()
```

The equivalent through reticulate doesn't work:
```r
library(reticulate)
kernels <- import("sklearn.gaussian_process.kernels")
kernels$WhiteKernel() + kernels$RBF()
```

**Comment by t-kalinowski** [comment]
Thanks for reporting. Linked to: #1187.

**Comment by t-kalinowski** [comment]
This is now implemented in the current release version.
