### ISSUE TITLE
Time-out error when RStudio IDE Env Pane generates summary for some Python objects

### ISSUE THREAD

**Issue by zackarno** [rstudio/reticulate#1227]
I am curious if anyone here has any experience with the following error : `Error in .Call(_reticulate_py_str_impl, x) : reached elapsed time limit`. We are hitting  this error when wrapping some `rgee`  functions (Google Earth Engine package for R which relies on reticulate). The main 2 odd things about the error are that a.) it does not actually prevent the creation of the object so its not like typical R error (but it does cause considerable lag in the output object creation), b.) the error is not called/flagged outside of R-studio in the base `RGui` that comes with R. The same code runs perfectly fine without lag/error.

As the code runs outside of `R-studio` it seems like this is a bug, just unclear where the bug lies exactly and if there is a solution or work around.

Here is a link to our issue where we have attempted to interrogate and document our trouble shooting of the error:
https://github.com/r-tidy-remote-sensing/tidyrgee/issues/17#issue-1258869220 

We also saw the same error and behaviour pop up in the issue by another team here:
https://github.com/Azure/azureml-sdk-for-r/issues/281#issue-579435662

Below is a reprex which is also used in the `tidyrgee` issue linked above:

```r
library(dplyr)
# this is the package we are working on and facing the error with
# devtools::install_github("r-tidy-remote-sensing/tidyrgee")
library(tidyrgee)
library(rgee) # this requires some set up and GEE account
ee_Initialize()

# load image collection
chirps <- ee$ImageCollection("UCSB-CHG/CHIRPS/DAILY")
# transform to our tidyee class object
chirps_tidy <- as_tidyee(chirps)

# summarise imageColection temporally by year and month
chirps_monthly_per_year <- chirps_tidy |>
  group_by(year,month) |>
  summarise(
    stat="sum"
  )


# add new season attribute
chirps_monthly_with_season <- chirps_monthly_per_year |>
  mutate(
    seasons= case_when(
      month %in% c(12,1,2)~"winter",
      month %in% c(3,4,5)~"spring",
      month %in% c(6,7,8)~"summer",
      month %in% c(9,10,11)~"fall"
    )
  )

# here we are breaking down part of our summarise method it's building blocks
tidyee_list <- chirps_monthly_with_season |>
  filter(year %in% c(1981:1990)) |> 
  group_by(year,seasons) |>
  group_split() |> # split the imagecollection by year and season
# summarise/composite each component of the collection
  purrr::map(~ee_composite(.x |> group_by(year, seasons),stat="mean"))

# from the newly created tidyee list lets take just the image collections
ic_list <- tidyee_list |> 
  purrr::map(~.x$ee_ob)

# and just associate vrt data.frames
vrt_list <- tidyee_list |> 
  purrr::map(~.x$vrt)

# bind together
vrt_together <- bind_rows(vrt_list)
# merge imageCollections
ic_together <- ee$ImageCollection(ee$List(ic_list))

```
Normally in the next steps we would create a list like : `list(ee_ob= ic_together, vrt=vrt_together)`  which causes an error. However below, we have further isolated the issue and you can see the error is just flagged by putting `ic_together` object in a list. Interestingly there is no error if you do not try to store the output as an object and just run `list(ee_ob=ic_together)`
```r
tidyee_together <- list(ee_ob=ic_together)
#> Error in .Call(`_reticulate_py_str_impl`, x) : reached elapsed time limit
````

**Comment by kevinushey** [comment]
Most likely, this is caused by RStudio calling `str()` on these objects to build a representation of the object for the Environment pane. Can you replicate the slowness by trying to call `str(object)` by hand?

https://github.com/rstudio/rstudio/blob/9ab60a7b67570e0b0497b76afb8daab0b291421b/src/cpp/session/modules/SessionEnvironment.R#L45-L51

**Comment by zackarno** [comment]
Thanks @kevinushey for the reply - interesting idea! However, I could not replicate the slowness/lag by running the `str()` function. Below I have posted the continuation of the reprex with some explanatory comments to see if I did what you had in mind:


```r
vrt_together <- bind_rows(vrt_list)
ic_together <- ee$ImageCollection(ee$List(ic_list))


# run str - it does lag for a second or 2, but i think that is just because it is a large and deeply nested return...
# for the reprex i am just copy pasting in the tail of the `str()` return since it is too big to post
str(ic_together)
#>> }
#> }
#> }
#> }
#> }
#> }
#> },
#> "value": {
#>   "functionInvocationValue": {
#>     "functionName": "Date.millis",
#>     "arguments": {
#>       "date": {
#>         "functionInvocationValue": {
#>           "functionName": "Date.fromYMD",
#>           "arguments": {
#>             "day": {
#>               "constantValue": 1
#>             },
#>             "month": {
#>               "constantValue": 12.0
#>             },
#>             "year": {
#>               "constantValue": 1990.0
#>             }
#>           }
#>         }
#>       }
#>     }
#>   }
#> }
#> }
#> }
#> }
#> ]
#> }
#> }
#> }
#> }
#> })
```

```r
# try to save str object
ic_together_str <- str(ic_together)
ic_together_str
#>NULL

# run list - works
list(ic_together)

# save list - error...
ic_together_list <- list(ic_together)
#> Error in .Call(_reticulate_py_str_impl, x) 


# eventually after a couple minutes it does get created though
ic_together_list
#> [[1]]
#> EarthEngine Object: ImageCollection

```

**Comment by t-kalinowski** [comment]
@kevinushey Does `str()` actually get called by the IDE here? I think that for python objects, the IDE, at least in the current release, has a separate code path that calls Python's `pprint` module instead:
https://github.com/rstudio/rstudio/blob/9ab60a7b67570e0b0497b76afb8daab0b291421b/src/cpp/session/modules/SessionReticulate.R#L1650

@zackarno You can try defining a custom `str()` method for the Python objects that are giving you trouble, like this:

```r
@export
str.py_module_name.py_object_name <- function(x) "A short description of x"
```
where `class(x)` would return `py_module_name.py_object_name`, 

Though I don't think this will fix the issue.

@kevinushey I wonder what the best approach here is. There should probably be a generic that users can write methods for to control what's shown in the IDE Environment Pane. Some candidates:

- `str()`
- `reticulate::py_str()`
- `rstudioapi::describeObjectValue()`

**Comment by zackarno** [comment]
In this case,, the custom `str()` method worked- how exciting! 

So I guess that means Rstudio is respecting the custom `str()` method?
```
#' @export
str.ee.imagecollection.ImageCollection <- function(object) {
  "A short description of x"
  }
```
Thank you both so much for your help, this work-around certainly works great for our use-case for the time being, but nonetheless, I am curious to see where this goes and what you think is the best strategy/potential new functionality to allow users to handle environment pane rendering/ these `str()` related issues

**Comment by t-kalinowski** [comment]
A little diagnostic investigation: I don't see R's `str()` being invoked anywhere, but it looks like its Python's `__repr__` that is invoked by the IDE Environment pane. @zackarno I'm very glad that you have a fix, but I admit I don't quite understand why it works 😅.

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/8462255/174315219-ef46d54c-bf72-4fc0-96e2-d88665e199e3.png">

**Comment by t-kalinowski** [comment]
@kevinushey What do you think about having a dedicated generic for the RStudio IDE environment pane, maybe living in `rstudioapi::describeObject()`?

I'm hesitant to standardize on `str()` for a few reasons:

1. The use case is a little different. Usually `str()` gives a compact representation, but not always. E.g., right now the IDE has special handling for long R lists.
2. No easy way for user-defined `str()` methods to infer if it's being run for the env pane, or get constraints like the env pane width.
3. No easy way for users to opt-in to collapsable entries in the envpane.
4. We still have the legacy `utils::str()` -> `py_str()` -- mapping, which I'm trying to move away from (i.e., defaulting to using `repr()`)

If we add it to {rstudioapi}, we can still have `describeObject.default()` be `str()` perhaps.
