### ISSUE TITLE
sorry，Thank you for reporting! I just merged a PR, this should be fixed now. Please try with the development version of reticulate and let me know if you still run into this issue.

### ISSUE THREAD

**Issue by liyifan-hub** [rstudio/reticulate#1228]
Thank you for reporting! I just merged a PR, this should be fixed now. Please try with the development version of reticulate and let me know if you still run into this issue.
```r
remotes::install_github("rstudio/reticulate")
```

_Originally posted by @t-kalinowski in https://github.com/rstudio/reticulate/issues/1155#issuecomment-1030632728_

**Comment by t-kalinowski** [comment]
Hi @liyifan-hub please open a new issue describing the error you're encountering. Thank you!
