### ISSUE TITLE
Error in py_config when using a py2 conda env

### ISSUE THREAD

**Issue by Jfortin1** [rstudio/reticulate#1229]
I cannot use conda env using python 2.7 with the latest version of reticulate (1.25);
this used to run fine with 1.24.

Minimal reproducible example:

```
conda create -n testEnv python=2.7
```

```
library(reticulate)
path <- "/Users/fortinj2/miniconda3/envs/testEnv"
use_condaenv(path)
```

and getting the following error when initializing the env via `py_config`:

```
py_config()
Error in py_initialize(config$python, config$libpython, config$pythonhome,  : 
  PyException_SetTraceback - dlsym(0x7fc8766b6750, PyException_SetTraceback): symbol not found
```

**Comment by kevinushey** [comment]
Python 2.7 reached EOL in 2020; consequently, we no longer support Python 2.7.

**Comment by Jfortin1** [comment]
OK, thank you

**Comment by KyleHaynes** [comment]
@kevinushey - Glad I found this issue, I was going a little insane. Same behaviour on Windows 10 64-bit. 

If that's the case, could it be worth updating the readme to be a bit more explicit what reticulate? Cheers!

# R Interface to Python 3.X?
