### ISSUE TITLE
Passing an array of tuples

### ISSUE THREAD

**Issue by abresler** [rstudio/reticulate#123]
I have some code that requires an array of tuples.  Been trying to figure out how to recreate this in R to no avail.  I just need to wrap the list of nuples with an array but cannot seem to do that correctly when converting trying to use JSON to do it.  

```
[
  ('hid_borough', '1'),
  ('hid_borough_name', 'MANHATTAN / NEW YORK'),
  ('hid_block', '1291'),
  ('hid_block_value', '1291'),
  ('hid_lot', '10'),
  ('hid_lot_value', '10'),
  ('hid_unit', ''),
  ('hid_selectdate', ''),
  ('hid_datefromm', ''),
  ('hid_datefromd', ''),
  ('hid_datefromy', ''),
  ('hid_datetom', ''),
  ('hid_datetod', ''),
  ('hid_datetoy', ''),
  ('hid_doctype', ''),
  ('hid_doctype_name', 'All Document Classes'),
  ('hid_max_rows', '9999999999'),
  ('hid_page', '1'),
  ('hid_ReqID', ''),
  ('hid_SearchType', 'BBL'),
  ('hid_ISIntranet', 'N'),
  ('hid_sort', ''),
]
```

Creating the tuples works fine just cannot figure out the array part

**Comment by jjallaire** [comment]
Do you mean a Python list of tuples or do you mean literally a NumPy array of tuples?

**Comment by abresler** [comment]
I was having a hard time passing the list of tuples as an np array but for the specific use case I realized you could just pass the pass the array of tuples as a dictionary which was an easy fix. 

That said a bit of documentation on how to pass an np.array of tuples may be helpful for hard uses cases.

**Comment by jjallaire** [comment]
Okay, thanks for the clarification. I'll try to add some docs on that.
