### ISSUE TITLE
Is there a way to print objects with len > 10?

### ISSUE THREAD

**Issue by jonocarroll** [rstudio/reticulate#124]
I am trying to build up a call to pass to `py_eval()` using some `R` data. This worked fine when the data was small but broke when I tried larger data. I am using `glue()` but this holds just the same for `paste()`.

It is failing because `py_collection_str()` won't print an object longer than length 10 (instead it prints a summary). 

<details><summary>Expand for MRE:</summary>

```r
library(reticulate)
library(glue) ## paste would work, but I like this syntax

## create a short and a long sequence
short <- as.character(1:10)
long <- as.character(1:11)

## convert to tuples
short_tuple <- tuple(as.list(short))
long_tuple <- tuple(as.list(long))

## paste expressions
glue("{short_tuple}")
#> ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10')
glue("{long_tuple}")
#> Tuple (11 items)

## this makes working with pasted data tricky
## the first of these evaluates fine, the second
## doesn't because it doesn't contain the data
glue("['val' + x for x in {short_tuple}]")
#> ['val' + x for x in ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10')]
glue("['val' + x for x in {long_tuple}]")
#> ['val' + x for x in Tuple (11 items)]

## reason is that py_collection_str(), which is
## where print() leads for a python.builtin.tuple,
## treats len > 10 different
##
# py_collection_str <- function(name, object) {
#   len <- py_collection_len(object)
#   if (len > 10)
#     paste0(name, " (", len, " items)")
#   else
#     py_str.python.builtin.object(object)
# }

## best workaround I can find:
glue("['val' + x for x in {reticulate:::py_str_impl(long_tuple)}")
#> ['val' + x for x in ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11')
```

</details><br>

Question: Is there an exported/clean way to print a 'long' object so that it can be pasted into a string?

**Comment by jonocarroll** [comment]
This is a vastly less elegant way, but it does work

```
tupple_string <- function(x) {
  paste0('("', paste0(x, collapse = '", "'), '")')
}

glue("['val' + x for x in {tupple_string(1:11)}]")
#> ['val' + x for x in ("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11")]

py_eval(glue("['val' + x for x in {tupple_string(1:11)}]"))
#>  [1] "val1"  "val2"  "val3"  "val4"  "val5"  "val6"  "val7"  "val8" 
#>  [9] "val9"  "val10" "val11"
```

**Comment by jjallaire** [comment]
I don't recall why we put in that cap but it's similar to the way R and Python handle printing of other object types that can grow infinitely large (e.g. max rows for printing matrices and data frames, etc.). In other words, even if we make the cap 100 or 1000 printing is never a guaranteed way to access the entire data structure programatically.

You could try calling the `py_str.python.builtin.object` method directly for the tuple? That will at least give you Python's default `str` implementation (but note it too isn't guaranteed to get the entire data structure).

**Comment by jonocarroll** [comment]
I wasn't suggesting raising the cap; the issue would remain at some point. As far as I can tell there is no exported way to print the entire object. Could `py_str_impl()` be exported without causing harm?

**Comment by jjallaire** [comment]
`py_str.python.builtin.object()` is exported and effectively gives you the same thing as `py_str_impl()`

**Comment by jonocarroll** [comment]
The `NAMESPACE` has `S3method(py_str,python.builtin.object)` so it's available but not exported per se. I'd still need to use `reticulate:::py_str.python.builtin.object()`

```r
py_str.python.builtin.object()
#> Error in py_str.python.builtin.object() : 
#>   could not find function "py_str.python.builtin.object"
```

```
reticulate::py_str.python.builtin.object
#> Error: 'py_str.python.builtin.object' is not an exported object from 'namespace:reticulate'
```

I suppose I'm asking for a fully exported `py_str_impl()` or similar raw `str` that can be used in CRAN-compliant packages.

**Comment by jjallaire** [comment]
The issue is that even Python `str()` is not guaranteed to return text that you can pass to `eval`, see https://docs.python.org/2/library/functions.html#str. So we could work around the 10 limitation but then there will likely be another limitation inside Python.

In those docs it suggests using the `repr` function instead, so how about this:

```r
library(reticulate)
x <- tuple(1,2,3,4,5,6,7,8,9,10,11)
builtins <- import_builtins()
builtins$repr(x)

## [1] "(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0)"
```

**Comment by jonocarroll** [comment]
That's perfect, thank you! I was not aware of `repr` (my python-fu is very slowly coming along) but that certainly looks to be what I'm after.
