### ISSUE TITLE
Python 2.7 broken in reticulate 1.25

### ISSUE THREAD

**Issue by cmarquardt** [rstudio/reticulate#1241]
Hello.

Thank you for reticulate - it's awesome.

With `reticulate` v1.24, this works:

```
library(reticulate)
use_virtualenv("devel", required = TRUE)
np      <- import("numpy")
```

With `reticulate` v1.25, this error shows up (for the same commands):

```
Error in py_initialize(config$python, config$libpython, config$pythonhome,  : 
  PyException_SetTraceback - dlsym(0x7fca14e5e380, PyException_SetTraceback): symbol not found
```

Caveat: The virtual environment uses Python 2.7.17 (and numpy v1.16.6, the last version supporting python2). I assume that's related. I'm aware of #1232 and I fully understand that Python 2 is way beyond its EOL. Unfortunately, that doesn't help people like my teammates and me who are still stuck with legacy code.

The `reticulate` [ChangeLog](https://rstudio.github.io/reticulate/news/index.html) for v1.25 also doesn't announce the end of support for Python 2, and the [CRAN page](https://cloud.r-project.org/web/packages/reticulate/index.html) still states Python >= 2.7.0 as a requirement.  So is this a bug?

Many thanks,

   Christian

**Comment by t-kalinowski** [comment]
Thanks for reporting. I just pushed a commit that restores Python 2 compatibility, and sets the stage for announcing end of support for Python 2.

**Comment by cmarquardt** [comment]
Thank you.
