### ISSUE TITLE
reticulate::configure_environment() work not same on windows and linux

### ISSUE THREAD

**Issue by mrchypark** [rstudio/reticulate#1247]
I try to build package with reticulate using `Config/reticulate:`.
on Window machine, does not work package installation process.
So I find out why.

https://github.com/rstudio/reticulate/blob/v1.25/R/python-packages.R#L64
```
  config <- py_config()
  root <- dirname(dirname(config$python))
  ok <- is_virtualenv(root) || is_condaenv(root)
```

with this code, I share `py_config()` windows and linux.

```
# windows
> library(reticulate)
> py_config()
python:         C:/Users/mrchypark/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/mrchypark/AppData/Local/r-miniconda/envs/r-reticulate/python38.dll
pythonhome:     C:/Users/mrchypark/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/mrchypark/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.23.1

# linux 
> library(reticulate)
> py_config()
python:         /root/.local/share/r-miniconda/envs/r-reticulate/bin/python
libpython:      /root/.local/share/r-miniconda/envs/r-reticulate/lib/libpython3.8.so
pythonhome:     /root/.local/share/r-miniconda/envs/r-reticulate:/root/.local/share/r-miniconda/envs/r-reticulate
version:        3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)  [GCC 10.3.0]
numpy:          /root/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/numpy
numpy_version:  1.23.1
```

window and linux don't same location conda root path.

So maybe because of that, on window machine, does not work package installation process.

**Comment by kevinushey** [comment]
If I understand correctly, then that's expected; Windows and Linux have different filesystems and conventions for where files are located.

> on Window machine, does not work package installation process.

It would be helpful to see what error message you are seeing.

**Comment by mrchypark** [comment]
@kevinushey Thank you for reply!


with this code:
https://github.com/rstudio/reticulate/blob/v1.25/R/python-packages.R#L64
```
  config <- py_config()
  root <- dirname(dirname(config$python))
  ok <- is_virtualenv(root) || is_condaenv(root)
  if (!ok)
    return(FALSE)
```

just return FALSE without install python packages.

So, when install r package using reticulate `Config/reticulate:` on DESCRIPTION, install process just pass the python packages set on `Config/reticulate:` on DESCRIPTION.

**Comment by t-kalinowski** [comment]
Hi, I'm not sure I follow. Are you saying that reticulates auto-configure behavior specified via an R packages DESCRIPTION file is not working on Windows in a conda environment? Can you please provide instructions for me to reproduce the error locally on my machine?

**Comment by kevinushey** [comment]
Ah, I think I understand the issue... on Unix, the python binary is located within `<env>/bin/python`, but on Windows it's located in `<env>/python.exe`.

So, on Windows, we should only be taking a single `dirname()` call here:

>   root <- dirname(dirname(config$python))

```
> library(reticulate)
> reticulate::use_condaenv("r-reticulate", required = TRUE)
> py_config()
python:         C:/Users/kevin/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/kevin/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/kevin/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.13 (default, Sep 23 2021, 07:38:49) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/kevin/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.19.5

NOTE: Python version was forced by use_python function
> python <- py_exe()
> reticulate:::is_condaenv(dirname(python))
[1] TRUE
```

**Comment by mrchypark** [comment]
thank you @kevinushey !

That's what I guess. But I'm not sure it is the only reason.

I think adding warning message about why return FALSE will help me understand that package setting process not work.
For now, just not work.
