### ISSUE TITLE
NVidia GPU not found from reticulate but is found from Python interpreter in shell (outside of R)

### ISSUE THREAD

**Issue by ericjb** [rstudio/reticulate#1251]
My system has a GPU NVidia Quadro P400 GPU installed in a Windows 11 PC with WSL2 running. I am working on the Ubuntu (linux) side. The python script script1.py contains the single line 
import pycuda.autoinit

I installed pycuda and hacked the file autoinit.py to add some debugging trace. 
A python virtual environment, say envA, is activated. From an ubuntu shell, the command:
$ python script1.py
produces the output 

autoinit.py: entered
autoinitpy: about to call cuda.init()
autoinitpy: back from calling cuda.init))

All good. (I can add extra lines to script1.py that query the GPU, identify it and even run some calculations on it, but the error encountered below will already appear at this one line.)

I modify ~/.Rprofile to have the one line 
Sys.setenv(RETICULATE_PYTHON="/path/to/envA/bin/python")

tmp1.R consists of 2 lines

library(reticulate)
source_python("script1.py")

From the ubuntu shell 

$ Rscript tmp1.R 

gives the following output

autoinit.py: entered
autoinitpy: about to call cuda.init()
Error in py_run_file_impl(file, local, convert) : 
  pycuda._driver.RuntimeError: cuInit failed: no CUDA-capable device is detected
Calls: source_python -> py_run_file -> py_run_file_impl
Execution halted

On the assumption that the difference was caused by environment variables in envA I also modified the python script to script2.py which removes the environment variables. 

import os
def clear_env():
    for item, value in os.environ.items():
        os.environ.pop(item)

clear_env()
import pycuda.autoinit

This has no effect. The 'pure' python version succeeds. The reticulate version fails.

Python version is 3.10.5

R SessionInfo

R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.25

loaded via a namespace (and not attached):
[1] compiler_4.2.1  Matrix_1.4-1    Rcpp_1.0.9      grid_4.2.1     
[5] jsonlite_1.8.0  png_0.1-7       lattice_0.20-45

**Comment by t-kalinowski** [comment]
If the python you're binding to is a venv or conda installation, then the environment is "activated" as part of reticulate's initialization routine. Activation will involve modifying or setting environment variables, possibly ones that effect GPU visibility. 

You can try to track this down by running `Sys.getenv()` after reticulate has finished initializing python
```R
library(reticulate)
py_config() # initializes python
Sys.getenv()
```
It's possible that as part of python initialization, an environment variable like `CUDA_VISIBLE_DEVICES` is set, or `LD_LIBRARY_PATH` or `PATH` is modified such that an NVIDIA binary that is incompatible with your GPU is the one that python then finds.

It is difficult to know without additional information.

**Comment by ericjb** [comment]
Solution / workaround found.
The CUDA code needed to find the shared object libcuda.so.1. It found it in /usr/lib/wsl/lib/libcuda.so.1.
(/usr/lib/wsl/lib was not part of any environment variable such as LD_LIBRARY_PATH).
The R/Reticulate code could not find libcuda.so.1.
Local dev ops created a symbolic link
ln -s /usr/lib/wsl/lib/libcuda.so.1 /usr/lib/x86_64-linux-gnu/libcuda.so.1
and now the R/reticulate works.

I still think there's an odd discrepancy in behavior between what should have been identical python environments (after I modified the R/reticulate python environment to match exactly that of python, it still failed.)

Feel free to close this issue.

**Comment by t-kalinowski** [comment]
Thanks for reporting back. I agree this is an odd discrepancy. In particular I'd be interested in knowing how it is that python finds `libcuda.so.1` in wsl. I took a glance at the pycuda github repo but didn't see any special branches for WSL, though there were some custom workarounds for windows machines, and it does look for the `CUDA_ROOT` and a few other `CUDA_*` variables.
