### ISSUE TITLE
import reprexpy does not work

### ISSUE THREAD

**Issue by psads-git** [rstudio/reticulate#1254]
I have installed `reprexpy` with

`py_install("reprexpy")`

The installation went fine. However, when on `reticulate::repl_python()`, I get the following error:

```
>>> import reprexpy as rp 
ImportError: cannot import name 'contextfilter' from 'jinja2' (/home/x/r_reticulate/lib64/python3.10/site-packages/jinja2/__init__.py)
>>>
```

Do you confirm this as a bug?

**Comment by t-kalinowski** [comment]
Thanks for reporting. This looks to be an issue with the reprexpy python package. I get the same error attempting to import the package in python directly, outside of reticulate.

**Comment by psads-git** [comment]
Thanks, Tomasz.
