### ISSUE TITLE
Why can't only 'Pandas' library be imported in 'Python'?

### ISSUE THREAD

**Issue by wbk123** [rstudio/reticulate#1260]
R code:
> library('reticulate')
> use_virtualenv("...:\\Python\\virtual environment\\myvenv")
> use_python('...:\\Python\\virtual environment\\myvenv\\Scripts')
> py_discover_config()
result:
  python:         ...:/Python/virtual environment/myvenv/Scripts/python.exe
  libpython:      ...:/Python/python38.dll
  pythonhome:     ...:/Python/virtual environment/myvenv
  version:        3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit     

 (AMD64)]
  Architecture:   64bit
  numpy:          ...:/Python/virtual environment/myvenv/Lib/site-packages/numpy
  numpy_version:  1.23.1
  NOTE: Python version was forced by use_python function
R code:
> import('numpy')
result:
  Module(numpy)
R code:
> import('matplotlib')
result:
  Module(matplotlib)
R code:
> import('pandas')
result:
  Error in py_module_import(module, convert = convert) : 
  ValueError: embedded null byte
My problem:
  I have successfully installed the 'pandas' Library in Python, and can successfully import 

and call functions. Only the' pandas' Library cannot be imported in rstudio, and there are 

no problems with other libraries in rstudio. In addition, there is no problem with using 

the 'pandas' Library in other IDEs.I have tried several versions of 'pandas'', which are 

all like this.The earliest version is 1.3.0.What can I do to solve this problem?

**Comment by t-kalinowski** [comment]
@wbk123 I think you inadvertently opened the same issue twice, closing this one and we'll track #1261.
