### ISSUE TITLE
Different behavior finding python binary on windows in IDE and in console

### ISSUE THREAD

**Issue by cderv** [rstudio/reticulate#1263]
Take this document

<details>
<summary>Details</summary>

````markdown
---
output: html_document
---

Python won't be found correctly in IDE when knitting as a `.exe` is added.

```{r, error = TRUE}
reticulate::py_discover_config()
```

However, it is ok when rendered in console. 

It seems to be because this variable is set 

```{r}
Sys.getenv("RETICULATE_PYTHON_FALLBACK")
```

If I set it explicitly, we can reproduce in rendering in the console too.

```{r, error = TRUE}
Sys.setenv(RETICULATE_PYTHON_FALLBACK = "C:/Users/chris/scoop/persist/pyenv/pyenv-win/shims/python3.bat")

reticulate::py_discover_config()
```

````

</details>

When doing knitting with the Knit button we get 

![image](https://user-images.githubusercontent.com/6791940/186221584-86a8885d-085a-445a-aff8-6a653118ef96.png)

When rendering in Console we get: 

![image](https://user-images.githubusercontent.com/6791940/186221878-299546d5-c5b9-4be5-99af-08d86bdccd8b.png)

The `.exe` part seems to be added from
https://github.com/rstudio/reticulate/blob/a4c7184fbb0bb0fa40af340bd3c2d5a16b34b323/R/config.R#L957-L959

Maybe it should not be added if an extension is already present like with the `.bat` ? 

I know this issue is also quite specific to windows with pyenv-win which uses shims to handle python version. I could also resolve the shims to the exe and set `RETICULATE_PYTHON` for it to work

**Comment by t-kalinowski** [comment]
Thank you @cderv for the nice bug report! Should be fixed on main now.
