### ISSUE TITLE
support for AsIs I() for single element vectors

### ISSUE THREAD

**Issue by t-samuelg** [rstudio/reticulate#1275]
I want to have an array with a single element e.g. `c(1) => [1]`. However, there is currently no way to achieve that. 

In the jsonlite package they have the same problem with auto unboxing but solve it using the AsIs operator in R (https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/AsIs)

see https://www.rdocumentation.org/packages/jsonlite/versions/1.8.0/topics/toJSON,%20fromJSON

it would be great if this would also work for reticulate. 

e.g.
```R
r_to_py(1) => 1
r_to_py(c(1,2)) => [1,2]
r_to_py(c(1)) => 1
# new
r_to_py(I(1)) => [1]
r_to_py(I(c(1))) => [1]
```

**Comment by t-kalinowski** [comment]
To get a size 1 numpy array:
```r
> r_to_py(array(1))
array([1.])
```
To get a length 1 list:
```R
> r_to_py(as.list(1))
[1.0]
```

**Comment by t-samuelg** [comment]
thx for the workarounds. I do still think it would be a valuable addition.
