### ISSUE TITLE
Reticulate appears to be related to Seg Fault when called from rpy2

### ISSUE THREAD

**Issue by russellpierce** [rstudio/reticulate#128]
Minimal Python Script
```
import os
import rpy2
from rpy2.robjects import r
from rpy2.robjects.packages import importr
reticulate = importr('reticulate')
reticulate.py_eval('1')
```

R Session Info
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] reticulate_1.2

loaded via a namespace (and not attached):
[1] compiler_3.4.1 Rcpp_0.12.13   jsonlite_1.5
```

Python version 3.4.3
Rpy2 2.9.1
Python version invoked by reticulate 2.7.6

... I can hear 'oh why would you ever want to do such a horrible thing'.  Yes, yes, that is probably a very valid point.  Be that as it may, it seems like it ought to work, but doesn't so I thought I'd make the report and see if anybody had any ideas.

**Comment by jjallaire** [comment]
I believe that we've now got this scenario worked out, see this discussion: https://github.com/rstudio/reticulate/issues/98

The new CRAN release of reticulate (v1.3) has this code, not sure whether it's yet in the rpy2 release version or still in the dev version.

**Comment by russellpierce** [comment]
I'm sorry to have not having found that for myself. @jjallaire thank you!
