### ISSUE TITLE
__file__ is not defined in 'sourced' Python scripts

### ISSUE THREAD

**Issue by kevinushey** [rstudio/reticulate#1283]
For example, with the script:

```
print(__file__)
```

One can run the script in a standalone Python instance and see e.g.

```
$ python3 abc.py
/Users/kevin/scratch/abc.py
```

However, `__file__` doesn't get defined for scripts sourced by `reticulate`:

```
> reticulate::source_python('~/scratch/abc.py')
Error in py_run_file_impl(file, local, convert) : 
  NameError: name '__file__' is not defined
```

Maybe `py_run_file()` should go through https://docs.python.org/3/c-api/veryhigh.html#c.PyRun_SimpleFile rather than https://docs.python.org/3/c-api/veryhigh.html#c.PyRun_StringFlags?

**Comment by kevinushey** [comment]
In case it's relevant:

https://github.com/python/cpython/blob/c5140945c723ae6c4b7ee81ff720ac8ea4b52cfd/Python/pythonrun.c#L392-L404

**Comment by t-kalinowski** [comment]
[`PyRun_SimpleFile`](https://docs.python.org/3/c-api/veryhigh.html#c.PyRun_SimpleFile) unfortunately doesn't expose the `locals` and `globals` arguments, which we will need I think to maintain support for `py_run_file(local = TRUE)` usage.

[`PyRun_File`](https://docs.python.org/3/c-api/veryhigh.html#c.PyRun_File) does expose the `globals` and `locals` arguments, but it doesn't set `__file__` and `__cached__` for us. It looks like we'll have to do that manually. ([`PyRun_FileExFlags`](https://github.com/python/cpython/blob/da5727a120e426ffaf68bf3a8016491205bd2f80/Python/pythonrun.c#L1640-L1654) just reads compiles and goes straight to eval, with some error handling along the way. The only attr it ensures is `__builtins__` if globals is main)

Something that's interesting is that in `PyRun_SimpleFile`, the `__file__` item is [deleted](https://github.com/python/cpython/blob/da5727a120e426ffaf68bf3a8016491205bd2f80/Python/pythonrun.c#L450-L460) from the dictionary before returning. `__file__` is only available during code execution. I think that makes sense if code is being evaluated in `__main__`, but I think that would be odd in a local dict.
