### ISSUE TITLE
object "_reticulate_write_stderr" not found.

### ISSUE THREAD

**Issue by mg64ve** [rstudio/reticulate#129]
Hi all,

I have just installed reticulate 1.3 and then keras.
I am getting the following:

`> devtools::install_github("rstudio/keras", force=TRUE)`
`Downloading GitHub repo rstudio/keras@master`
`from URL https://api.github.com/repos/rstudio/keras/zipball/master`
`Installing keras`
`"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD `INSTALL  \`
`  "C:/Users/marcog/AppData/Local/Temp/RtmpW0pNx2/devtools27fc4cf41422/rstudio-keras-cda721e" --library="C:/Users/marcog/Documents/R/win-library/3.3" --install-tests `
`* installing *source* package 'keras' `
`** R`
`** inst`
`** tests`
`** preparing package for lazy loading`
`** help`
`*** installing help indices`
`** building package indices`
`** installing vignettes`
`** testing if installed package can be loaded`
`*** arch - i386`
`*** arch - x64`
`* DONE (keras)`
`Reloading installed keras`
`Error : .onLoad failed in loadNamespace() for 'keras', details:`
`  call: py_module_import(module, convert = convert)`
`  error: RuntimeError: Evaluation error: object "_reticulate_write_stderr" not found.`

how can I fix it?

Thanks. 
Best regards.

**Comment by jjallaire** [comment]
The problem here is almost certainly that when you installed reticulate the DLL was in use so it failed to copy the new package's DLL over the old one. The solution is to quit all R sessions on your system, then start a fresh session and install reticulate within it.

**Comment by mg64ve** [comment]
Problem is solved.
Thanks a lot.
