### ISSUE TITLE
Syntax error with first line comment pattern #...#?

### ISSUE THREAD

**Issue by JMLuther** [rstudio/reticulate#1295]
When adapting someone else's code, I discovered that any command with a comment pattern of `# something #?` at the end of the first line will error. 

This seems to be a `reticulate` bug to be aware of, easily fixable by avoiding this comment pattern.
This behavior does not occur in the python REPL.

Examples:
```
test = {"A": 1,  # Invalid comment pattern #?
            "B":2}
    # Error in py_run_string_impl(code, local, convert) : 
    #     File "<string>", line 1
    #     help("test = {"A": 1,  #  Invalid comment pattern  #")
    #          ^^^^^^^^^^^
    # SyntaxError: invalid syntax. Perhaps you forgot a comma?
    
[1,2,3] # test #?
    # No Python documentation found for '[1,2,3] # test #'.
    # Use help() to get the interactive help utility.
    # Use help(str) for help on the str class.
```

If on a multiline command, this only occurs if the comment is on the first line. The following commands work fine, no error, so it seems to be the "?" character after a second #:

```
test = {"A": 1,  # valid comment #X
        "B":2}
test = {"A": 1,  # valid comment #/
        "B":2}


test = {"A": 1,  # valid comment 
        "B":2}   #?

test = {"A": 1,  # valid comment 
        "B":2}   # #?

[1,2,3] # test
[1,2,3] # ? test

```

Running on Windows, R 4.2.1, python 3.10.6, reticulate 1.26

**Comment by kevinushey** [comment]
Most likely coming from here:

https://github.com/rstudio/reticulate/blob/a1d7f7f573f652212bc2c72c39317340e6d8b511/R/repl.R#L252-L258

We should be stricter in detecting + handling postfix `?` usages.

**Comment by dfalbel** [comment]
I can no longer reproduce this with v1.31. I believe this has been fixed in reticulate v1.29 as it's the last version I can observe this behavior.

**Comment by t-kalinowski** [comment]
This was fixed with https://github.com/rstudio/reticulate/issues/1070#issuecomment-1490470388 I think.

**Comment by JMLuther** [comment]
I confirmed on my computer it no longer errors. Thanks!
