### ISSUE TITLE
Incomplete pyenv install instructions for Windows

### ISSUE THREAD

**Issue by aalexandersson** [rstudio/reticulate#1296]
The Rstudio installation instructions for Python at [https://solutions.rstudio.com/python/minimum-viable-python/installing-python/](https://solutions.rstudio.com/python/minimum-viable-python/installing-python/) recommends 

> To make sure the version of Python you install will work with reticulate, add PYTHON_CONFIGURE_OPTS="--enable-shared" to your pyenv install command

But the `pyenv` instructions are not valid for Windows, see this issue comment 
[https://github.com/pyenv-win/pyenv-win/issues/341#issuecomment-1302322040](https://github.com/pyenv-win/pyenv-win/issues/341#issuecomment-1302322040)

The `reticulate` instructions at
[https://rstudio.github.io/reticulate/articles/versions.html](https://rstudio.github.io/reticulate/articles/versions.html) also do not mention the installation issue for Windows. 

It begs the larger question: Does `reticulate` work with Python for Windows? If so, what are the installation instructions since the instructions for *nix do not work **on Windows**?

**Comment by t-kalinowski** [comment]
Hi, welcome. Python installation should work on Windows. Please try `reticulate::install_python()` and report back if you encounter errors (or opportunities to improve help page for [`install_python()`](https://rstudio.github.io/reticulate/reference/install_python.html)

**Comment by t-kalinowski** [comment]
Welcome! Python installation should work on Windows. Please try `reticulate::install_python()` and report back if you encounter errors, or opportunities to improve help page for [`install_python()`](https://rstudio.github.io/reticulate/reference/install_python.html)

**Comment by kevinushey** [comment]
The documentation here should be amended; the `PYTHON_CONFIGURE_OPTS` bit is only necessary on Linux / macOS , and that's only if you're installing Python from sources by yourself; if installing through `reticulate`, we take care of setting it for you.

https://github.com/rstudio/reticulate/blob/a1d7f7f573f652212bc2c72c39317340e6d8b511/R/pyenv.R#L148-L149
