### ISSUE TITLE
Confusing questions about inital numpy selected by reticulate

### ISSUE THREAD

**Issue by HelloWorldLTY** [rstudio/reticulate#1299]
Hi, I found that reticulate will automatically select on numpy from my system, and even if I load new numpy, it will still use it:
![image](https://user-images.githubusercontent.com/43333475/204168956-b79f391c-8d29-4a3d-8e5f-75b57e319add.png)
I do not understand why, and how to change this numpy? I think my other packages, because of this numpy, cannot be loaded into this environment,like scanpy.
Could you please help me? Thanks a lot.

**Comment by aqlina** [comment]
Hi,
did you try to restart R session after reinstalling another version of numpy (=to clean up an R env)?

**Comment by HelloWorldLTY** [comment]
Hi, I used a cluster, not rstudio. But I do restart many times. I wonder how can I adjust the location of numpy here.

**Comment by aqlina** [comment]
I believe it is better to create some virtual environment and install python packages there. Then adjust .Renviron file with  RETICULATE_PYTHON variable which is pointing at your python from that environment (or with Sys.setenv, but you will need to do it every time). After restarting the session, it should point at the correct numpy version. 

When you run reticulate::py_config() you should see that the python which is being used is from that environment (=RETICULATE_PATH path), also numpy path should be adjusted. At least, it worked for me.

![Screenshot 2022-11-30 at 09 54 32](https://user-images.githubusercontent.com/24864872/204752414-9b669d67-37ec-4a15-a7c7-d66ba43f3cc0.png)

**Comment by t-kalinowski** [comment]
@HelloWorldLTY This article might be helpful, it goes over the different ways you can point reticulate at python installations. https://rstudio.github.io/reticulate/articles/versions.html

**Comment by HelloWorldLTY** [comment]
> I believe it is better to create some virtual environment and install python packages there. Then adjust .Renviron file with RETICULATE_PYTHON variable which is pointing at your python from that environment (or with Sys.setenv, but you will need to do it every time). After restarting the session, it should point at the correct numpy version.
> 
> When you run reticulate::py_config() you should see that the python which is being used is from that environment (=RETICULATE_PATH path), also numpy path should be adjusted. At least, it worked for me.
> 
> ![Screenshot 2022-11-30 at 09 54 32](https://user-images.githubusercontent.com/24864872/204752414-9b669d67-37ec-4a15-a7c7-d66ba43f3cc0.png)

Hi, I tried this method, but it did not work. I think my requirement is like allowing me to assign numpy package arbitrarily rather than let it search the environment automatically.

**Comment by HelloWorldLTY** [comment]
I solved this problem by modifying Sys.setenv(PYTHONPATH). I can remove my current numpy path. Many thanks for your help!
