### ISSUE TITLE
eng_python does not respect echo

### ISSUE THREAD

**Issue by otommod** [rstudio/reticulate#130]
R does it like [this](https://github.com/yihui/knitr/blob/87789284d153f8ef36fe4f098a037d012af009db/R/block.R#L195-L204).  The rest of the engines [rely](https://github.com/yihui/knitr/blob/33a3ba65771e2ebc37a403cb37f941f2c6660bfb/R/engine.R#L81) on `knitr::engine_output()`.

`eng_python` is not using `engine_output()` yet, however even when it will, that won't help since it will [bypass the "echo" logic](https://github.com/yihui/knitr/blob/33a3ba65771e2ebc37a403cb37f941f2c6660bfb/R/engine.R#L63)

Currently, as a workaround I've defined
```r
eng_python <- function(opts) {
  out <- reticulate::eng_python(opts)
  if (opts$echo) {
    out
  } else if (length(out) > 1) {
    out[seq(2, length(out), 2)]
  }
}
```
in my Rmds, though it's not particularly pretty.

**Comment by jjallaire** [comment]
@kevinushey Could you take a look at this?

**Comment by kevinushey** [comment]
Will take a look next week (will be back in office then).

**Comment by jjallaire** [comment]
Okay, thanks!

**Comment by jjallaire** [comment]
@kevinushey I know you are neck deep in QWebEngine right now, but I'm hoping to do a CRAN release of reticulate very soon and it would be good to have this issue resolved. It looks on the surface to be something pretty easily addressed, can you take a look early next week?

**Comment by eddelbuettel** [comment]
Reminder of clock ticking with CRAN closing for Xmas break on Dec 22.

**Comment by jjallaire** [comment]
Thanks! I was wondering if/when there would be a holiday break. Do you know when they will resume accepting submissions in January?

**Comment by eddelbuettel** [comment]
Incoming will be down Dec 22 to Jan 3.  Uwe posted it to r-devel and r-package-devel, and it is on the CRAN submission page but I wasn't sure you'd seen it.   

Not a terribly long time.   So I am probably just releasing some lighter-weight fare -- a littler update is kinda overdue -- and resume with "normal" uploads in January.  Not sure where you are with with reticulate.  It has been montly to bi-monthly so either way fits the bill...

**Comment by jjallaire** [comment]
Okay, I am going to try get a few submissions in next week then!

On Sat, Dec 16, 2017 at 3:11 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by kevinushey** [comment]
I'll try to get some of the basic knitr options working as well early next week.

**Comment by jjallaire** [comment]
Great, thanks! I'll try to submit sometime late Tuesday just to be sure to make it in prior to Friday.

**Comment by otommod** [comment]
This is fixed.  Thank you very much!
