### ISSUE TITLE
[Error Reporting] Extract the RuntimeError R exception traceback from Python

### ISSUE THREAD

**Issue by pvieito** [rstudio/reticulate#1304]
Hi! Currently with Reticulate when an exception is thrown inside R code and is captured by Python, you only recibe a very basic `RuntimeError` exception with the error message:

```
Traceback (most recent call last):
  File "**/process_support.py", line 277, in run_process
    entry_point(**parameters)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/call.py", line 21, in python_function
    raise RuntimeError(res[kErrorKey])
RuntimeError: Evaluation error: botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 10:28: mismatched input 'date'. Expecting: ',', 'EXCEPT', 'FROM', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'ORDER', 'UNION', 'WHERE', <EOF>.
```

Is there any way to obtain detailed info about the exception like the R traceback?

**Comment by t-kalinowski** [comment]
Hi @pvieito, thanks for reporting.

Unfortunately, right now the stacktrace can be lost when R code raises an error while R and python frames are intermingled in the call stack. Until this is fixed, here are some strategies you can use:

1. If you're passing an R function as a callback to Python, drop into the R debugger closest to where you suspect the R error is being emitted from. `browser()` or `debugonce()` should do. Then continue execution and the full R error should be visible. 
2. Use `reticulate::py_last_error()` to avoid truncation of the python stack.
3. Set `options(warning.length = 8170)` (the max).

**Comment by pvieito** [comment]
Hi! Thanks for the info. The main problem is that I want to have proper logging in production (ie. consider that the R debugger is not available) and yes, I am passing an R function to the Python runtime. So if any error from R o Python is thrown inside the passed R function all I get is the generic `RuntimeError` with the description.

I have tried the `reticulate::py_last_error()` approach but the error seems to be the same `RuntimeError` as before.

---

Simple example case:

`Process.R` file:
```
library("reticulate")
DataTools <- reticulate::import("DataTools")

execute_process <- function(...) {
  # Something here Python or R, throws an error…
  stop("example error!")
}

DataTools$r_support$run_process(execute_process)
```

`r_support.py` inside the `DataTools` module:
```
def run_process(entry_point):
    try:
        parameters = _load_r_interoperability_parameters()
        entry_point(**parameters)
    except Exception as e:
        message = f"Error executing process: {repr(e)}."
        r_traceback = _load_r_interoperability_traceback()
        if r_traceback:
            message += f"\nR Traceback:\n{r_traceback}"
        logging.error(message, exc_info=True)
```

What should I add in the `_load_r_interoperability_traceback()` function to extract the full traceback from R. I am ok with having to add some extra initialization in the `Process.R` code.

**Comment by t-kalinowski** [comment]
This has been fixed in https://github.com/rstudio/reticulate/pull/1343

The R condition caught by `tryCatch()`, as well as the object returned by `py_last_error()`, now contain `r_traceback` and `r_call`.

**Comment by pvieito** [comment]
@t-kalinowski That's great, thanks! There is any easy way to install the reticulate development way easily so I can try this?

**Comment by pvieito** [comment]
@t-kalinowski Any suggestion about how to pretty-format both the r_traceback and / or r_call with R?

Currently what I am doing is capturing the exception in Python and passing it to R code so it gets formatted on a string that I can log along the detailed error in Python:

```python
    try:
        r_function(**kwargs)
    except Exception as e:
        message = f"Error executing process: {repr(e)}."
        if r_support._is_running_in_r_interoperability_runtime():
            try:
                r_traceback = r_support._convert_r_object_to_string(e.r_traceback)
                message += f"\nR Traceback:\n{r_traceback}"
            except AttributeError:
                pass
        logging.error(message, exc_info=True)
```

The `r_support._convert_r_object_to_string()` function call to this R fuction:

```r
.DataTools._convert_to_string <- function(object) {
  object_description <- capture.output(object)
  return(object_description)
}
```

But I am not not getting very good results:
```
2023-03-02 10:10:39,490 ERROR - process_support.run_process: Error executing process: RuntimeError('__ERROR__').
R Traceback:
['[[1]]', '[1] "(function (...) "        "{"                      ', '[3] "    stop(\\"__ERROR__\\")" "})()"                   ', '', '[[2]]', '[1] "do.call(fn, args)"', '', '[[3]]', '[1] "withCallingHandlers(expr = return(list(do.call(fn, args), NULL)), "', '[2] "    python.builtin.BaseException = function(e) {"                  ', '[3] "        invokeRestart(\\"raise_py_exception\\", e)"                  ', '[4] "    }, error = function(e) {"                                      ', '[5] "        e$traceback <- .traceback(4)"                              ', '[6] "        invokeRestart(\\"raise_py_exception\\", e)"                  ', '[7] "    })"                                                            ', '', '[[4]]', '[1] "doWithOneRestart(return(expr), restart)"', '', '[[5]]', '[1] "withOneRestart(expr, restarts[[1L]])"', '', '[[6]]', '[1] "withRestarts(expr = withCallingHandlers(expr = return(list(do.call(fn, "', '[2] "    args), NULL)), python.builtin.BaseException = function(e) {"        ', '[3] "    invokeRestart(\\"raise_py_exception\\", e)"                           ', '[4] "}, error = function(e) {"                                               ', '[5] "    e$traceback <- .traceback(4)"                                       ', '[6] "    invokeRestart(\\"raise_py_exception\\", e)"                           ', '[7] "}), raise_py_exception = function(e) {"                                 ', '[8] "    list(NULL, e)"                                                      ', '[9] "})"                                                                     ', '', '[[7]]', ' [1] "(function (fn, args) "                                                      ', ' [2] "{"                                                                          ', ' [3] "    withRestarts(expr = withCallingHandlers(expr = return(list(do.call(fn, "', ' [4] "        args), NULL)), python.builtin.BaseException = function(e) {"        ', ' [5] "        invokeRestart(\\"raise_py_exception\\", e)"                           ', ' [6] "    }, error = function(e) {"                                               ', ' [7] "        e$traceback <- .traceback(4)"                                       ', ' [8] "        invokeRestart(\\"raise_py_exception\\", e)"                           ', ' [9] "    }), raise_py_exception = function(e) {"                                 ', '[10] "        list(NULL, e)"                                                      ', '[11] "    })"                                                                     ', '[12] "})(function (...) "                                                         ', '[13] "{"                                                                          ', '[14] "    stop(\\"__ERROR__\\")"                                                    ', '[15] "}, list())"                                                                 

Traceback (most recent call last):
  File "/Users/pvieito/Documents/Work/ShopFully/Projects/DataTools/DataTools/Modules/process_support.py", line 283, in run_process
    entry_point(**entry_point_kwargs)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/call.py", line 16, in python_function
    raise error
RuntimeError: __ERROR__
```

**Comment by t-kalinowski** [comment]
It looks like the full traceback returned in your example is quite short, only 7 frames, with 6 of them introduced by reticulate internal functions. The only user frame shows the the error is from an anonymous function that calls `stop("__ERROR__")`.
```
['[[1]]',
 '[1] "(function (...) "        "{"                      ',
 '[3] "    stop(\\"__ERROR__\\")" "})()"                   ',
```

Does that seem right to you, or are we missing R frames in our capture?

I think the reason it's hard to see in your example is because the python logging is printing a `repr` of the captured output, rather than printing the output directly. Printing would show newlines as newlines, which will greatly enhance readability.

If `stop("__ERROR__")` is a unique R call in your code, hopefully it gives a hint on where to look. It's generally useful to write unique error messages, to make it easy to search a code base for where an error is emitted from.

I would caution against writing code that depends on any specific printed representation of the R error or traceback. That's meant for human consumption, not programmatic consumption, and it's something that's likely to change in the future. (e.g., I just pushed a commit tweaking the printed output of a `python.builtin.BaseException` in R slightly).

**Comment by pvieito** [comment]
@t-kalinowski Hey!

> I would caution against writing code that depends on any specific printed representation of the R error or traceback. That's meant for human consumption, not programmatic consumption, and it's something that's likely to change in the future. (e.g., I just pushed a commit tweaking the printed output of a python.builtin.BaseException in R slightly).

Sure! But they are a lot less human friendly than Python ones. I finally did some formatting in the Python side and got something more readable:

```
Error executing process 'R': RuntimeError('there was an error in: get_campaign_info_engage(order_id, end_date) module, please check it:Error in doTryCatch(return(expr), name, parentenv, handler): GG\n').
R Traceback:
- - value[[3L]](cond)
  - '...'
- tryCatchOne(expr, names, parentenv, handlers[[1L]])
- tryCatchList(expr, classes, parentenv, handlers)
- tryCatch({
- get_campaign_info_engage(order_id = order_id, end_date = end_date)
- '(function (country = "IT", order_id = "2349167", end_date = "2021-12-26", '
- do.call(fn, args)
- 'withCallingHandlers(expr = return(list(do.call(fn, args), NULL)), '
- doWithOneRestart(return(expr), restart)
- withOneRestart(expr, restarts[[1L]])
- 'withRestarts(expr = withCallingHandlers(expr = return(list(do.call(fn, '
- '(function (fn, args) '
- py_call_impl(callable, dots$args, dots$keywords)
- DataTools$r_support$run_process(execute_process)
```
