### ISSUE TITLE
`use_miniconda` doesn't work if miniconda wasn't installed in the default location

### ISSUE THREAD

**Issue by chainsawriot** [rstudio/reticulate#1308]
The documentation of `use_miniconda` states that:

https://github.com/rstudio/reticulate/blob/a1d7f7f573f652212bc2c72c39317340e6d8b511/man/use_python.Rd#L34-L36

But it won't work

```r
reticulate::install_miniconda("/tmp/Rtmp6Z1dcm/gfx", update = TRUE, force = TRUE)
### the absolute prefix path 
reticulate::use_miniconda("/tmp/Rtmp6Z1dcm/gfx/envs/r-reticulate")
### the absolute path to the python binary
reticulate::use_miniconda("/tmp/Rtmp6Z1dcm/gfx/envs/r-reticulate/bin/python")
```

The reason for it is that only the default path is checked

https://github.com/rstudio/reticulate/blob/a1d7f7f573f652212bc2c72c39317340e6d8b511/R/use_python.R#L238

**Comment by t-kalinowski** [comment]
Hi, Thanks for reporting.
`use_miniconda()` is meant to be a companion to `install_miniconda()`, it will only resolve  reticulated-managed installations.

If you want reticulate to use conda installations installed through other means, (including miniconda installations), you can use `use_condaenv("my-env-name", conda = "/path/to/conda")`, or by setting `options(reticulate.conda_binary = "/path/to/conda")` or the env var `RETICULATE_CONDA`.
