### ISSUE TITLE
Integration of reticulate with argparse

### ISSUE THREAD

**Issue by rargelaguet** [rstudio/reticulate#132]
I have a Python module which I call with arguments from the command line using the argparse module. 

For example:
inside a python script (asd.py) I define my arguments
```
def entry_point():
p = argparse.ArgumentParser()
p.add_argument( '-a')
p.add_argument( '-b')
```
Which I can call from the command line using
```
python asd.py -a 1 -b 2
```

How can I perform this with the reticulate package?

**Comment by jjallaire** [comment]
I think you need to define a Python function which takes the same arguments and invoke it that way. To import the .py script you can just use the `import_from_path()` function.

**Comment by harryprince** [comment]
A better way in R is use Rmarkdown params with knitr
python argparse.ArgumentParser is a little bit redundant
