### ISSUE TITLE
allow py_install / vitualenv_install to take a requirements.txt file?

### ISSUE THREAD

**Issue by cboettig** [rstudio/reticulate#1321]
Apologies if there is already a way to do this but I haven't found it. 

It would be great if there were simply a way to do the equivalent of `pip install -r requirements.txt` from reticulate, e.g. `virtualenv_install(requirements = "requirements.txt")` or such.  (I know renv already supports something like this, and I know reticulate has support for pipenv.  But many python projects simply have a requirements.txt floating around in their repo, and it would be nice to just clone a repo into RStudio and install these without having to switch over to the bash shell)

**Comment by t-kalinowski** [comment]
This is a great idea! We should have a more explicit API for this. 

Currently you can do something like this:
```r
reticulate::virtualenv_install("my-env", c("-r", "requirements.txt"))
# or 
reticulate::virtualenv_create("my-env", packages = c("-r", "requirements.txt"))
```

**Comment by cboettig** [comment]
Nice! I will definitely be using this!  

Yeah I actually puzzled over this and tried to hack something with the `pip_options` argument unsuccessfully. So a more explicit API (or at least an example with this clever trick!) would be sweet.  Thanks for the amazing work.

**Comment by kevinushey** [comment]
(Or, do we want to consider something like `virtualenv_restore()`, which would take as an argument the path to a lockfile of some flavor?)

**Comment by cboettig** [comment]
sorry dropped the ball on this thread.  

I think `virtualenv_install(requirements = "requirements.txt")` is a good starting point.  I like the idea of the 'smart' behavior in supporting other files (I think renv is already doing something if it sees Pipfiles? maybe I miss-remember).  I'm a bit worried that the fancier toolkits like poetry, pipenv/pipfile etc assume additional dependencies that might not be there?  `requirements.txt` seems like a decent baseline.  I'm not sure if there is prior art on selecting the virtualenv automatically, though VSCode's jupyter notebook interface seems to handle this rather well?)

**Comment by cboettig** [comment]
any updates?
