### ISSUE TITLE
Finding python3 on Windows from Msys2 shell

### ISSUE THREAD

**Issue by kalibera** [rstudio/reticulate#1325]
Reticulate does not work with the msys build of Msys2 python3, which is however part of a minimal Msys2 installation, which is part of Rtools43. The problem is that the msys build of python3 does not accept mixed path, e.g. "c:/Users/.../config.py", that is, the drive letter is a problem when specified this way. Reticulate passes such argument to it and fails (I am testing by R CMD check of package RGF but several other have failed their checks as well).

I used to "solve" this by installing a native build of python, recently from https://www.python.org/ftp/python/3.11.0/python-3.11.0-amd64.exe, and placing at the beginning of PATH.

This solution worked for me in the past, but no longer does. I am not sure why it worked before, but the problem is that the official native Windows build from the link above does not have a "python3" executable. It only has "python". Apparently reticulate looks (now) for "python3", finding the Msys2 version which does not work. Simply copying "python.exe" to "python3.exe" under C:\Program Files\Python311 makes reticulate work again, as expected, but that is perhaps too much to ask a user to do. Please note this problem exists for anyone running R CMD check or similar from an Msys2 shell, so also from Rtools43.

I was wondering if the discovery of python on Windows could be improved so that it would work with the official build of python, but when invoked from Msys2. In other words, why preferring python3.exe when such executable does not exist in the official build, over python.exe which does.

Ideally, in addition, reticulate would work also with the msys build of python (e.g. it could pass the file name in a compatible way, or detect msys build and pass in msys way). It should, however, still be possible to ensure the official build of Python is used by placing it first on PATH, so that e.g. R CMD check executed from msys2 shell can be made representative of a usual end-user setup.

**Comment by t-kalinowski** [comment]
Hello @kalibera!

I just pushed a commit to main--placing a "python.exe" on the `PATH` should make things work as expected now. Note that reticulate will still prefer "python3.exe" over "python.exe" if you have both on the `PATH`. If you know in advance which python you want reticulate to use, I recommend setting the environment variable `RETICULATE_PYTHON`.

Making reticulate work with msys2 python (that is, python installed with `pacman -S python` in the msys2 bash shell) is going to require a more involved fix, potentially a full refactoring of how reticulate resolves python configuration information.

The issue of a "mixed path" in the config.py file is just the tip of the iceberg. Overcoming that hurdle, you next encounter issues with resolving the path to the python.dll, then module scripts, PYTHONPATH and `sys.path`, etc. I'm not very familiar with msys2, so please correct me if I'm wrong, but it appears that translation of paths needs to be done going both ways, from outside to inside msys2 the way you described "C:\foo\bar" -> "/c/foo/bar", and also from inside msys back out: "/foo/bar" -> "C:\rtools43\foo\bar".

Contributions and suggestions are welcome :).

**Comment by kalibera** [comment]
> I just pushed a commit to main--placing a "python.exe" on the `PATH` should make things work as expected now. Note that reticulate will still prefer "python3.exe" over "python.exe" if you have both on the `PATH`.

Thanks, but the problem is that both will be on `PATH`, because, I cannot easily remove the Msys2 one, it will always be there in the Msys2 shell. And hence in (default) Rtools43 installs, where it gets pulled by some base packages (possibly package tools, I didn't investigate). 

> If you know in advance which python you want reticulate to use, I recommend setting the environment variable `RETICULATE_PYTHON`.

Thanks, but right, it means all users who run into this would have to find out as well...
> 
> Making reticulate work with msys2 python (that is, python installed with `pacman -S python` in the msys2 bash shell) is going to require a more involved fix, potentially a full refactoring of how reticulate resolves python configuration information.
> 
> The issue of a "mixed path" in the config.py file is just the tip of the iceberg. Overcoming that hurdle, you next encounter issues with resolving the path to the python.dll, then module scripts, PYTHONPATH and `sys.path`, etc. I'm not very familiar with msys2, so please correct me if I'm wrong, but it appears that translation of paths needs to be done going both ways, from outside to inside msys2 the way you described "C:\foo\bar" -> "/c/foo/bar", and also from inside msys back out: "/foo/bar" -> "C:\rtools43\foo\bar".

I see. I don't know all the places where you would need to translate the paths. If this were only on the "outside", invoking python, perhaps you could still support it using cygpath (a tool for the conversions both ways). But if the cygwin paths would be also "inside", in python scripts, possibly then propagating outside in text files, when interacting with R, that would be a show stopper. The paths supported by the python scripts need to be the same as in R.

So say people using Rtools would still have to install Python for Windows, and it is their responsibility to put it on PATH before Msys2 stuff. But, I still think that reticulate in that case should automatically use then that Python for Windows installation (even though it doesn't have "python3.exe", while Msys2 does). One way to do this would be to prefer "python.exe" over "python3.exe" on Windows (possibly checking that python.exe is python 3). Another would be to detect that the python found is msys/cygwin python and skip it in the search.

**Comment by t-kalinowski** [comment]
Thank you for clarifying, I understand the issue better now and just pushed another commit.

In the case where the user has not specified a specific Python executable, and reticulate is
attempting to find an appropriate default Python to use, reticulate will now 
avoid selecting a cygwin python, even if it's the first on the PATH.

**Comment by kalibera** [comment]
Thanks. Works fine on my system.
