### ISSUE TITLE
Warning message:   running command had status 1 in rstudio

### ISSUE THREAD

**Issue by JF888666** [rstudio/reticulate#1337]
Dear, friends

I'm using a package for R to open the doc via the system command, and despite being able to read the result, the code still reports an error. I have tried many times but failed, please give me some advice, thank you!

![aaa](https://user-images.githubusercontent.com/103365891/219295527-8d9cd925-87ba-474b-b287-968f6b1a3dcf.png)

**Comment by dfalbel** [comment]
Hi @JF888666, sorry, 

I don't see how this is related to reticulate. 
Can you provide additional information?
