### ISSUE TITLE
`Sys.setenv()` in R doesn't update `os.environ` in Python.

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/reticulate#1339]
``` r
reticulate::py_available(TRUE) # initialize python
#> [1] TRUE
Sys.setenv("FOO" = "bar")
reticulate::import("os")$environ$get("FOO", "nope")
#> [1] "nope"
```

<sup>Created on 2023-02-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dfalbel** [comment]
Unfortunatelly we can't find a reliable way of doing this without adding unnecessary overhead.
We had ideas of:

- Monkey patching `os.environ.get` to sync with R `Sys.getenv()` or syncing in the language barrier. But this would add an R call to every `os.environ.get()` which is probably too much overhead.
- Adding a `trace` to `Sys.setenv()`. This would only affect calls to `Sys.setenv()` after reticulate is loaded - which misses a common scenario where env vars are set in the beggining of the program. It also adds overhead to every `Sys.setenv()` call, which could be problematic for R only env vars.

Even though, it's unexpected that env vars are not propagated, we believe implementing it is not worth the problems that it might introduce.
