### ISSUE TITLE
RStudio doesn't load sklearn   Python modules via reticulate call

### ISSUE THREAD

**Issue by wa2003** [rstudio/reticulate#134]
I use sklearn in my .py file

  library(reticulate)

  py_run_file("Iforest_Train_m20_m3_V1.py", local = FALSE, convert = F)

> py_run_file("Iforest_Train_m20_m3_V1.py", local = FALSE, convert = F)
None

# -*- coding: utf-8 -*-
print(__doc__)

def Iforest_Train():
    
    import numpy as np
    import pandas as pd
    from sklearn.ensemble import IsolationForest
    from sklearn.externals import joblib
    
    paths='D:/Rpjts/DTWtest/data/iForest_Test/1205ZZ800/IForest_Online_V2/'
    d17_Train=pd.read_csv(paths+'d17_Train_m20_m3_V1.csv')
   
    d17_Train=d17_Train.iloc[:,23:36];  #列选择
   
    rng = np.random.RandomState(123)
    clf = IsolationForest( contamination=0.1, max_samples=10000, n_estimators=100,random_state=rng, n_jobs=3, verbose=1);  # random_state=123,
    
    joblib.dump(clf, paths+"Iforest_Train_m20_m3_model_V1.m")
        
    clf.fit(d17_Train)
    
    y_pred_Train = clf.predict(d17_Train)
    y_pred_Train=pd.DataFrame(y_pred_Train)
    
    scores_pred_Train = clf.decision_function(d17_Train)
    scores_pred_Train = pd.DataFrame( scores_pred_Train)
    
    y_pred_Train.to_csv(paths+'y_pred_Train_V1_01.csv')
    scores_pred_Train.to_csv(paths+'scores_pred_Train_V1_01.csv')   
  
if __name__ == "__main__":
    Iforest_Train()

**Comment by jjallaire** [comment]
This might be because the version of Python being used don't have sklearn. You can see what version of Python is in use via:

```{r}
reticulate::py_config()
```

You could try specifying an explicit version of Python (as documented here: https://rstudio.github.io/reticulate/articles/versions.html).

Alternatively you could import sklearn at the R level which will force reticulate to use the version of Python that has sklearn, e.g.

```{r}
library(reticulate)
sklearn <- import("sklearn")

```

**Comment by wa2003** [comment]
Thank you  for your  advice.
I have make it , it's about the parallel parameter n_jobs, when n_jobs=1, it works, but when n_jobs=2,3 or -1, it report error. I think it as a bug, maybe you can make it.

clf = IsolationForest( contamination=0.1, max_samples=10000, n_estimators=100,random_state=rng, n_jobs=1, verbose=1);  # R里调用py时，不支持py中并行，因此改为单核

**Comment by wa2003** [comment]
More and more algorithm in Python  can config  n_jobs=-1 to fully utilize CPUs, it will be powerful if  reticulate can make it.

**Comment by jjallaire** [comment]
There is probably an issue with multiprocessing that isn't handled well with embedded versions of the Python interpreter. Not sure if there is anything I can do about that, but certainly welcome input / PRs that overcome this limitation.

**Comment by dfalbel** [comment]
Related to #1288
