### ISSUE TITLE
reticulate crashes when using linalg.lstsq from numpy version 1.23.5

### ISSUE THREAD

**Issue by ltcamara** [rstudio/reticulate#1345]
**reticulate** crashes with **numpy** version 1.23.5 when using the following code:
```
reticulate::repl_python()
import numpy as np
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])
A = np.vstack([x, np.ones(len(x))]).T
m, c = np.linalg.lstsq(A, y, rcond=None)[0]
```
Crash details:
![image](https://user-images.githubusercontent.com/98260709/222089174-b46d8ddc-3ea9-4c33-8760-5c64b5056c68.png)

Workaround: An upgrade to **numpy** version 1.24.2 fixes the issue.

**Comment by t-kalinowski** [comment]
Hi, this is a binary incompatibility issue related to R and NumPy pre-built binaries having different BLAS requirements. As you mentioned, this has been resolved already and the easiest fix today is to upgrade NumPy. If for some reason you are pinned to an older version of NumPy, the 2nd easiest fix is to build NumPy from source, with an invocation like this in R:

```R
  reticulate::py_install(
    "numpy", envname = envname, pip = TRUE,
    pip_options = c("--force-reinstall", "--no-binary numpy"))
```

or the equivalent in your shell:

```bash
/path/to/python -m pip install --no-user --force-reinstall --no-binary numpy numpy
```
