### ISSUE TITLE
Import local module fails in repl_python

### ISSUE THREAD

**Issue by cboettig** [rstudio/reticulate#1347]
I continue to see the issue reported in #340, i.e. if I have a directory called `my_utils/utils.py` containing some python functions and try to import them in RStudio via repl_python() terminal:

```
from my_utils import *
```

I get the error:

```
ModuleNotFoundError: No module named `my_utils`.
```

I can confirm that the empty string is on the path `''` , but the empty string doesn't seem to mean "current working directory'. Note that if I have a python file that contains:

```
import sys
for path in sys.path: print("'"+path+"'")
```

and I run this in python, it _does not show_ the empty `''` being on the path, but rather gives me the absolute path to the current working directory:

![image](https://user-images.githubusercontent.com/222586/222525025-0396b226-61d6-4aff-9943-22cc3cd6c804.png)

(Note this is in an project in RStudio using `renv` -- note the renv-based paths, and I've run this in the terminal tab in RStudio, where import also works as expected).  Running the same script in `repl_python()` shows that the empty string has been added, but it does no good, can't import from the local path.

![image](https://user-images.githubusercontent.com/222586/222525436-ba40c06a-bb8f-4000-ab00-2a6d35408693.png)

(Aside, but curious why it has also picked up a bunch of additional paths that I don't see from the terminal -- note that both are using the same python virtualenv created by `renv`).  

This problem is resolved if I manually add the current path using the notation `"."`, like so, at the top of my python code:

```
import sys
sys.path.insert(0, ".")
```

**Comment by cboettig** [comment]
I do see in https://docs.python.org/3/library/sys.html#sys.path that an empty string ought to be the current working dir:

> python -c code and python (REPL) command lines: prepend an empty string, which means the current working directory.

it just seems that doesn't appear to be the case for `reticulate::repl_python()`, where for some reason I need `"."` as shown above.  :thinking:

**Comment by t-kalinowski** [comment]
@cboettig Can you please provide a minimal reproducible example? Ideally something that I can copy and paste into the R console or bash to create a skeleton project with files that reproduce the issue.

**Comment by cboettig** [comment]
thanks @t-kalinowski , it looks like I'll have to dig a bit more first but probably ought to close this for now.  

I tried this minimal setup below, and it actually seems to work fine as is.  (I still get the error in my current active project though I haven't been able to pinpoint more precisely...)

```
## Optionally with renv, maybe not necessary?
library(renv)
renv::init()
renv::use_python()
install.packages(c("fs", "readr", "reticulate", "rstudioapi"))
renv::snapshot()

## Set up the stuff
fs::dir_create("carl_utils")
readr::write_lines(
"
def add_stuff(x,y):
  return x + y
", "carl_utils/utils.py")
readr::write_lines(
"
from carl_utils import utils
z = utils.add_stuff(1,1)
print(z)
", "test.py")

# Restart R and run test.py in repl
rstudioapi::restartSession()
reticulate::source_python("test.py")
```

**Comment by cboettig** [comment]
ah ok, the source of the problem appears to be a difference between what is considered the working directory.  

Run this in a clean RStudio project to reproduce the error:

```r
## Set up the stuff
fs::dir_create("src")
fs::dir_create("src/carl_utils")

readr::write_lines(
"
def add_stuff(x,y):
  return x + y
", "src/carl_utils/utils.py")
readr::write_lines(
"
from carl_utils import utils
z = utils.add_stuff(1,1)
print(z)
", "src/test.py")

# Restart R and run test.py in repl
rstudioapi::restartSession()
reticulate::source_python("src/test.py")
```

Note that running:

```bash
python src/test.py
```

in the RStudio bash terminal works just fine though.  


The reason for the error is that in bash, `python src/test.py`, the "current working directory" is interpreted as a path relative to `src/`, and not relative to the actual current working directory we were in when we called python.  (In a way this is nice, as it matches the behavior we see in RStudio notebooks where relative paths are relative to the location of the _rmarkdown_, not the working directory listed at the top of the R console, i.e. the project root).    

Anyway, not sure what the right choice is here, maybe nothing needs to be fixed, but it is a bit tricky!

**Comment by cboettig** [comment]
i.e. more concisely, 

The equivalent reticulate command to the following bash command from the repo root: 

```bash
python src/test.py
```

is not, as one might think,

```r
reticulate::source_python("src/test.py")
```

but instead:

```r
setwd("src")
reticulate::source_python("test.py")
```

owing to how a sys.path of `''` is interpreted by reticulate (I think).

**Comment by t-kalinowski** [comment]
I think we're encountering a feature of python session initialization.
 
At the command line:
```bash
python src/test.py
``` 
works, but
```bash
python -c 'exec(open("src/test.py").read())'
```
and 
```bash
python -c 'import runpy; runpy.run_path("src/test.py")'
```
do not. The latter two raise the same error as `reticulate::source_python()`.

The reason is that when sourcing a script at the command line, Python will by default include the script directory in `sys.path`. Note that this feature can be turned off with some flags, like `-I`, `-P`, presence of a `python._pth` file (https://docs.python.org/3/using/cmdline.html#cmdoption-P, https://docs.python.org/3/using/cmdline.html#cmdoption-I, `<script>` field etc.)

It might make sense to add a feature to `reticulate::source_python()` to prepend `dirname(<script_path>)` to `sys.path`, but I'm not entirely convinced that this is the best workflow we should be encouraging for complex projects like this. It seems to me that the happy path is to make sure `carl_utils` is a proper python module, and import it as such.

E.g., `reticulate::import("src.carl_utils")` or `reticulate::import_from_path("carl_utils", "./src")` 

That's a workflow that will work across all contexts; with `python <src/test.py>`, `python -m <src.test>`, and `runpy.run_path("src/test.py)` in an interactive session, both in R and Python.

**Comment by t-kalinowski** [comment]
Note, you could simulate the `python <script>` behavior in R by adding the dirname entry to `sys.path` like this: 
```R
source_python_with_script_dir_on_path <- function(file, ...) {
  file <- normalizePath(file)

  sys <- import("sys", convert = FALSE)
  sys$path$insert(0L, dirname(file))
  on.exit(sys$path$remove(dirname(file)), add = TRUE)

  source_python(file, ...)
}
```

**Comment by cboettig** [comment]
Thanks so much for this @t-kalinowski , I really appreciate your insights here.  I work with a multi-language (R/python) team, and as an academic am keen to be able to share work that is easily reproducible by readers/users of either language in a way that feels as ergonomic and native as possible.

My goal here is that a user/reader/reviewer can clone a GitHub repo into RStudio and run `.py` code with limited/no gotchas.  I don't think the user would actually call `source_python()`, I was just using that as illustration since the behavior is the same as running `repl_python()` with regards to how local paths are interpreted.  In practice, I just want a user who opens the `.py` script in RStudio and hits the ctrl+enter commands (it's so lovely how RStudio now automatically detects python and switches the "Console" tab over to python via repl_python) to have the the python code work without error, while also supporting a user who goes over to the bash terminal and types `python src/test.py`.

I've never seen a python user run scripts using 

```
python -c 'exec(open("src/test.py").read())'
```

I'm not in favor of doing `from .carl_utils import utils` in my `test.py` because it breaks `python src/test.py`, and also isn't how python users are going to expect the python code to work.  I am very keen that my Python colleagues see familiar and simple best practices (a `src/` dir for python script in a repo) that looks just the way they already write python scripts and doesn't have any weird failure modes if they have a nested folder in `src/` and doesn't involve writing the python code in some special way for compatibility with RStudio / reticulate users.  I want to write a repo that will run the way a python dev expects it to run if they open it in terminal or VSCode, while also running just fine in RStudio if someone clicks to open the python file and clicks the "run" or "source script" button.  

Note that opening the test.py file as written above in VSCode and hitting the run button will also _just work_, because like `python src/test.py`, it interprets sys.path relative to where the file is.  open file + hit play just works in VSCode, but fails in RStudio when a python file imports another python file.  

RStudio is _so close_ to this wonderful python + R experience.  It simply breaks as soon as folders are involved because the empty string on the path in `reticulate::repl_python()` is interpreted relative to the working directory while in `python src/test.py` is interpreted relative to the source file, as you have said.   I don't think users should have to hack around it or just use VSCode if they want to be able to open a python file in an IDE and hit a play button and have it work.

**Comment by t-kalinowski** [comment]
Thanks so much for that, I'm convinced.

As a further data point, the [`%run`](https://github.com/ipython/ipython/blob/b47f7f81f1575d1866aab3f77de22c6661fdcc1f/IPython/core/magics/execution.py#L510-L512) magic [default runner](https://github.com/ipython/ipython/blob/b47f7f81f1575d1866aab3f77de22c6661fdcc1f/IPython/core/magics/execution.py#L813) in ipython also [prepends the script directory to the `sys.path`](https://github.com/ipython/ipython/blob/fd34cf5f1f6e243243c738c6e0cf62eb682c4d68/IPython/core/interactiveshell.py#L2810-L2815).
