### ISSUE TITLE
tilde as home directory not recognized

### ISSUE THREAD

**Issue by astronaut-chris** [rstudio/reticulate#1359]
Short reprex below!

```r
library(reticulate)
os <- import("os")
# works on my MacOS
os$listdir("/Users/chriscardillo/Desktop/")
# Does not work
os$listdir("~/Desktop/")
# Error produced: Error: FileNotFoundError: [Errno 2] No such file or directory: '~/Desktop/'
```

**Comment by eddelbuettel** [comment]
Try 

    os$listdir( Sys.glob("~/Desktop") )

which invokes the so-called globbing function to example `~` before handing it down via reticulate.  Globbing is one of those things done by the shell or application so you may need to help here.

**Comment by kevinushey** [comment]
Yes, Python does not support shell-style tilde path expansion in paths, as R / typical shells do.
