### ISSUE TITLE
module not found with reticulate used in a rstudio project

### ISSUE THREAD

**Issue by fvalenduc** [rstudio/reticulate#1362]
If I use reticulate and the module SasPy (installed with anaconda on windows), it doesn't work. This is the code I use:

library(reticulate)
saspy <- import("saspy")

It gives this error:
Error: ModuleNotFoundError: No module named 'saspy'

This works well if I run this code in Rstudio outside of a project.

Does anybody have an idea about this ?

Thanks in advance.

**Comment by SHogenboom** [comment]
Have you been able to solve the issue? If so, how? :)

**Comment by fvalenduc** [comment]
Unfortunately no, the problem still occurs. Do you also have this problem ?

**Comment by SHogenboom** [comment]
Not the exact some issue no. I have trouble importing some, but not all, `langchain` modules. Am just googling franticly for a clue on what to do. So far no luck unfortunately.

**Comment by fvalenduc** [comment]
I am only using the SASPy module to access data stored on a SAS server. This works perfectly outside a project, but not in a Rstudio project . I am interested to know if you find a solution.

**Comment by SHogenboom** [comment]
Alright I have a potential solution - no idea what is happening but perhaps it helps you as well.

Check the versions of the installed packages:
```{python}
!pip list
```

The package I was using - even though freshly installed in a virtual environment - was extremely outdated! This can be fixed by:

```{python}
!pip install <package_name> --upgrade
```

The package is now updated and the module I was trying to import now exists (ie no more errors). Hope this helps you as well!

**Comment by jonjoncardoso** [comment]
I have this exact same problem (https://github.com/latentnetworks/vimure/issues/85) and I have not even a clear idea of what's going on. It seems like RStudio changes the way the environment variables associated with Python are read?

**Comment by SHogenboom** [comment]
I wonder if perhaps it can be something to do with virtualenvironments. I feel like I read somewhere that reticulate automatically creates a new virtual environment.. which may be why the modules ‘do not exist’? 

In my troubleshooting of the slightly different problem I also encountered the solution:
```
# Force reticulate to look for virtual env. Python executable
Sys.setenv(RETICULATE_PYTHON = "./env/bin/python”)
```

Where `env` is my virtualenvironment where the modules are installed. Perhaps something like this can help?

**Comment by dfalbel** [comment]
You can find which python environent reticulate is using with `py_config()`. There are [multiple ways](https://rstudio.github.io/reticulate/articles/versions.html#order-of-discovery) to influence which Python version reticulate is going to use, but by default, it will try to create a virtualenv called `r-reticulate`. It's possible thaat in your case when calling Python outside reticulate you are using a different environment than what reticulate is using.

You can also use `py_install`, to install a Python package directly into the Python environment that reticulate is using. You can find more information [here](https://rstudio.github.io/reticulate/articles/python_packages.html).

Additionally, the new CRAN release v1.31 has made substantial changes to how reticulate finds Python and it would be great if you could try it out.

**Comment by fvalenduc** [comment]
Thanks for your help. The new version of reticulate did not change anything. However running py_config gives the cause of the problem. When using a project, it gives this result:

> py_config()
python:         C:/Users/Francois.Valenduc/Anaconda3/python.exe
libpython:      C:/Users/Francois.Valenduc/Anaconda3/python39.dll
pythonhome:     C:/Users/Francois.Valenduc/Anaconda3
version:        3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Francois.Valenduc/Anaconda3/Lib/site-packages/numpy
numpy_version:  1.21.5

When working outside of a project, it gives this:

> py_config()
python:         C:/Users/Francois.Valenduc/Anaconda3/envs/r-reticulate/python.exe
libpython:      C:/Users/Francois.Valenduc/Anaconda3/envs/r-reticulate/python39.dll
pythonhome:     C:/Users/Francois.Valenduc/Anaconda3/envs/r-reticulate
version:        3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:28:38) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Francois.Valenduc/Anaconda3/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.25.0

So it uses the r-reticulate virtual environment only when working outside of a project in rstudio. As suggested, I installed saspy using py_install an now it also works in a project. But the problem is thus that the r-reticulate environment is not always used.

**Comment by fvalenduc** [comment]
I also notice this when working in a project:

NOTE: Python version was forced by RETICULATE_PYTHON_FALLBACK

Indeed, the RETICULATE_PYTHON_FALLBACK environment variable is set to "C:/Users/Francois.Valenduc/Anaconda3/python.exe" only when working in a project. Outside of a project, this variable is not defined.
Using sys.unsetenv(" RETICULATE_PYTHON_FALLBACK") and Sys.setenv(RETICULATE_PYTHON = "C:/Users/Francois.Valenduc/Anaconda3/envs/r-reticulate/python.exe") does not help.
Any idea how the RETICULATE_PYTHON_FALLBACK variable is set and how to avoid it ?

**Comment by t-kalinowski** [comment]
`RETICULATE_PYTHON_FALLBACK` is being set by the RStudio IDE when the "Automatically activate project-local Python environments" setting is enabled. Uncheck this checkbox:
<img width="588" alt="image" src="https://github.com/rstudio/reticulate/assets/8462255/99486469-c5e5-4e57-97ad-d11717afc84e">

**Comment by t-kalinowski** [comment]
Also, it appears that reticulate is still finding the `r-reticulate` conda environment. That's fine if you have a preference for conda, but if not, I would suggest creating a virtual environment with `virtualenv_create("r-reticulate")`.

**Comment by fvalenduc** [comment]
Indeed unchecking "Automatically activate project-local Python environments" solved the problem. I am indeed using anaconda as python interpreter and it now works fine.

Thanks for your help.
