### ISSUE TITLE
py_config() interferes use_condaenv()

### ISSUE THREAD

**Issue by flde** [rstudio/reticulate#1368]
Hellor reticulate Team,

I work on JupyterLab using R v.4.1.0 (reticulate v.1.28). I just want to report that if I call py_config() first then use_condaenv() fails with an error. 

`Error in use_python(python, required = required): failed to initialize requested version of Python`

However, if I do use_condaenv() alone it works perfeclty. I can then call py_config(). Not sure if that is expected but if you want I can try providing more information. 

Many thanks for the great tool! 

Best, 
Florian

**Comment by t-kalinowski** [comment]
Hi @flde and welcome. This is expected; calling `py_config()` causes reticulate to initializes Python. Once Python is initialized, it is not longer possible in that R session to initialize a different Python.

**Comment by flde** [comment]
Hi @t-kalinowski, 

sorry for my delayed response and many thanks for taking time to explain! 

All the best, 
Florian
