### ISSUE TITLE
_reticulate_py_initialize  Incorrect number of arguments (8), expecting 7 for '_reticulate_py_initialize'

### ISSUE THREAD

**Issue by wzy221** [rstudio/reticulate#137]
Hi, I updated my Keras in R, and the error occurs. I am not sure why it is expecting 7 while in the code it is actually 8? should I reinstall my keras library or something else to figure it out?

 library(keras)
> library(tensorflow)
> library(reticulate)
>  
> py_config()
Error in .Call(`_reticulate_py_initialize`, python, libpython, pythonhome,  : 
  Incorrect number of arguments (8), expecting 7 for '_reticulate_py_initialize'

**Comment by jjallaire** [comment]
Your reticulate DLL was in use during the update. Try closing all R sessions then re-installing from a fresh R session

**Comment by wzy221** [comment]
thanks, it works now

**Comment by AkhilJain2018** [comment]
@jjallaire i got a similar (but opposite) error when trying to create a model using keras_model_sequential(). The error i got was:
 `Error in .Call(_reticulate_py_initialize, python, libpython, pythonhome, : Incorrect number of arguments (7), expecting 8 for _reticulate_py_initialize'`.
As you can see, the numbers are reversed..following is the code i used:
model = keras_model_sequential() %>%
    layer_dense(units = 144,  input_shape = c(13170)) %>%
    layer_activation(activation = 'relu') %>%
    layer_batch_normalization()  %>%
    layer_dropout(rate = 0.1) %>%
    layer_dense(units = 144) %>%
    layer_activation(activation = 'relu') %>%
    layer_batch_normalization()  %>%
    layer_dropout(rate = 0.1) %>%
    layer_dense(units = 2) %>%
    layer_activation(activation = 'sigmoid')

**Comment by jjallaire** [comment]
This always comes from a mismatch between the Keras R code and C/C++ code. Re-installing Keras from CRAN or GitHub in a completely fresh R session (with no other R sessions running on the machine) will fix the problem.

**Comment by AkhilJain2018** [comment]
i just did that..ran the command `devtools::install_github("rstudio/keras")` which will install keras from github..and got the following message: `Skipping install of 'keras' from a github remote, the SHA1 (e55cd5b1) has not changed since last install. Use `force = TRUE` to force installation`

**Comment by jjallaire** [comment]
I can't say this any more clearly: this error comes from a mismatch between the R code and C/C++ code so you need to make sure both install correctly (R package installations on Windows will still succeed even if the DLL containing C/C++ code cannot be updated because it is in use).

**Comment by axiomoixa** [comment]
I don't know if it is a related issue, but I have a similar error

[> TypeError: update() takes from 2 to 3 positional arguments but 4 were given](https://github.com/rstudio/keras/issues/285)

Trying to reinstall `reticulate` and `keras` from github on a fresh R session did not help.
