### ISSUE TITLE
different loop behavior between python chunk in Rmd and python script depending on indentation of blank lines

### ISSUE THREAD

**Issue by s3raga** [rstudio/reticulate#1371]
Depending on the indentation of blank lines, the behavior of a loop will be different in a python chunk of an .Rmd file.

Using reticulate 1.20, within RStudio 2022.02.1 with R 3.6.2 and Python 3.8

# Correct behavior
Chunk 1 has a "following" indentation for the blank line between the two prints and a new line at the end of the chunk.

```{python}
#python chunk 1
for i in range(10):
  print(i)
  
  print("//"+str(i))

```

Chunk 1 results in 
`0
//0
1
//1
2
//2
3
//3
4
//4
5
//5
6
//6
7
//7
8
//8
9
//9`

# Wrong behavior

## blank lines in the middle of the loop

Chunk 2 has a "reset" indentation for the blank line between the two prints and a new line at the end of the chunk

```{python}
#python chunk 2
for i in range(10):
  print(i)

  print("//"+str(i))

```
Chunk 2 results in
 
`0
1
2
3
4
5
6
7
8
9
//9`

It's as if the interpreter exits the loop after the first print and executes the second print with only the last value of i (here 9)

## no new line at the end

Chunk 3 has a "following" indentation for the blank line between the two prints and but no new line at the end of the chunk
```{python}
#python chunk 3
for i in range(10):
  print(i)
  
  print("//"+str(i))
```
Chunk 3 doesn't run until the enter key is pressed in the console

# Expected Behavior

All three "variations" of the loop give the exact same result (those of the chunk 1) when run directly with Python interpreter (in PyCharm for instance).

**Comment by t-kalinowski** [comment]
Hi, Thanks for filing.

I tried and can't reproduce with either the release nor development version of reticulate. What version of reticulate are you using?

You can try setting the knitr chunk option `hold=TRUE`, to force reticulate to treat a code chunk as a single code block, rather than the default which evaluats the code chunk in a pseudo-repl, where expressions are interleaved with their autoprinted evaluated outputs.

**Comment by s3raga** [comment]
Hi,

Sorry for the delay. As given above, reticulate is in version 1.20.

The `knitr::opts_chunk$set(hold=TRUE)` option doesn't change anything. Just to clarify, the issue only appears when I run chunks individually (using the "Run current chunk" button in RStudio editor panel): when knitting an .Rmd with the 3 chunks, the output of the 3 chunks is correct.

**Comment by t-kalinowski** [comment]
@kevinushey can you please point me the IDE source code where the "Run current chunk" button in an Rmd document sends the chunk to reticulate?

**Comment by kevinushey** [comment]
This works for me with the latest RStudio release. We basically ignore empty lines when submitting those to the R console / reticulate, so both of the cases above do what you expect.

**Comment by t-kalinowski** [comment]
Thanks!
