### ISSUE TITLE
RStudio: venv packages not found if restoring from .RData

### ISSUE THREAD

**Issue by ncollier** [rstudio/reticulate#1376]
With RStudio 2023.03.1 Build 447, and R  4.1.2, reticulate can't seem to use my virtual environment and find packages installed there when RStudio loads a workspace from .RData.  For example,

```R
library(reticulate)
use_virtualenv('~/.venv/py3.10', required = T)
py_config()
np <- import('numpy')
```

yields

```
python:         /usr/bin/python3
libpython:      /usr/lib/python3.10/config-3.10-aarch64-linux-gnu/libpython3.10.so
pythonhome:     //usr://usr
version:        3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
numpy:           [NOT FOUND]
> np <- import('numpy')
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'numpy'
```

If I delete my .RData file in which the workspace is saved, restart RStudio and then do the above, the virtual environment is correctly identified, and the packages installed there are found. 

```
python:         /home/nick/.venv/py3.10/bin/python
libpython:      /usr/lib/python3.10/config-3.10-aarch64-linux-gnu/libpython3.10.so
pythonhome:     /home/nick/.venv/py3.10:/home/nick/.venv/py3.10
version:        3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
numpy:          /home/nick/.venv/py3.10/lib/python3.10/site-packages/numpy
numpy_version:  1.23.4

NOTE: Python version was forced by use_python function
> np <- import('numpy')
```

Note that ` /home/nick/.venv/py3.10/bin/python` is a symlink to `/usr/bin/python3`.

**Comment by t-kalinowski** [comment]
What objects are in `.RData`? What would be the best way for me to reproduce this locally?

Can you also please try with the latest RStudio dailies? Recently we just fixed a similar, maybe even the same issue: https://github.com/rstudio/rstudio/pull/13108
