### ISSUE TITLE
Creating Conda-Environment with Python 3.10 fails, because reticulate translates it as Python 3.1

### ISSUE THREAD

**Issue by albert180** [rstudio/reticulate#1377]
When trying to create a conda-environment with the following Code:
````{r}
env_path <- conda_create(
  envname = "muster",
  packages = NULL,
  forge = TRUE,
  channel = character(),
  environment = NULL,
  conda = "auto",
  python_version = 3.10
)
````
it fails with the following error message:
`Error: Error creating conda environment 'muster' [exit code 1]
3.
stop(sprintf(fmt, ...), call. = call.)
2.
stopf(fmt, envname, result, call. = FALSE)
1.
conda_create(envname = "muster", packages = NULL, forge = TRUE,
channel = character(), environment = NULL, conda = "auto",
python_version = 3.1)
`

When replacing python_version=3.10 with 3.9 it works without an error.

**Comment by t-kalinowski** [comment]
This was a bug with older versions of conda. Please update conda and it should fix the issue.

**Comment by t-kalinowski** [comment]
Apoligese, rereading your snippet, it looks like you need to pass in `3.10` as a string. Right now you're passing in an R numeric, which is then implicitly converted back to a character string "3.1"

**Comment by albert180** [comment]
Yes that's what happened :+1: . Maybe it should be clarified that python_version should be a string
