### ISSUE TITLE
[Request] Include `^micromamba` in grepl check in `conda_binary` to allow direct use of micromamba

### ISSUE THREAD

**Issue by fitzgeraldja** [rstudio/reticulate#1378]
Including `^micromamba` here should allow reticulate to use micromamba in place of conda / mamba -- version checks are in different form, and some commands are missing, but I don't think this should be an issue for base functionality (i.e. activating a micromamba env for use)
https://github.com/rstudio/reticulate/blob/7a48c3a8466af1baa3ae0d431d30523f7a0a889c/R/conda.R#L511

**Comment by t-kalinowski** [comment]
PR welcome!

**Comment by zia1138** [comment]
@t-kalinowski 
Looks like you'll also have to update the activate command as well to support micromamba.
https://github.com/rstudio/reticulate/blob/3dc671b71bbc066842bb6a74ad6845aeacb91c58/R/conda.R#L887
e.g. to use
`micromamba activate` 
 A little short on time to suggest changes, but I thought this might help.
