### ISSUE TITLE
clarify that Python must be compiled with shared library support

### ISSUE THREAD

**Issue by copernican** [rstudio/reticulate#138]
@jjallaire's comment [here](https://github.com/rstudio/reticulate/issues/98#issuecomment-334960171) states that **`reticulate`** needs to bind to the Python shared library, which implies that the shared library needs to exist. If Python is compiled from source without the `--enable-shared` flag, this will not be the case. I was not able to find this shared library requirement explicitly mentioned in the **`reticulate`** documentation, so it might be helpful to add it, possibly in the [Python Version Configuration](https://rstudio.github.io/reticulate/articles/versions.html) vignette.

**Comment by jjallaire** [comment]
Thanks for the feedback , done here: https://github.com/rstudio/reticulate/commit/23a61ecff8569a5547d4db2257416c94e4d1d81f
