### ISSUE TITLE
installation error "call of overloaded vector is ambiguous"

### ISSUE THREAD

**Issue by kelbstf** [rstudio/reticulate#1381]
Possibly related:
-  installation error in centos R #1292 
-  install reticulate occurs issue #1301 

Hello,

i am really sorry to show up here in context of a CentOS7 system, which is a loaded topic, but unfortunately, i am still forced to using it.
I am fully aware of the compiler implications, so i believe to have compensated it properly, but still...

## Error:

<pre>
&gt; 
&gt; withr::with_makevars( new = c("CXX17"="/opt/rh/devtoolset-9/root/usr/bin/g++", "CXX17FLAGS"="-g -O2 $(LTO)", "CXX17PICFLAGS"="-fpic", CXX17STD = "-std=gnu++17"), code = { install.packages("reticulate") },  path = file.path("~", ".R", "Makevars")trying URL 'https://packages.othr.de/cran/src/contrib/reticulate_1.28.tar.gz'
Content type 'text/plain' length 1551312 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

* installing *source* package ‘reticulate’ ...
** package ‘reticulate’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/opt/R/4.2.3/lib/R/include" -DNDEBUG  -I'/opt/R/4.2.3/lib/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/opt/R/4.2.3/lib/R/include" -DNDEBUG  -I'/opt/R/4.2.3/lib/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c event_loop.cpp -o event_loop.o
g++ -std=gnu++11 -I"/opt/R/4.2.3/lib/R/include" -DNDEBUG  -I'/opt/R/4.2.3/lib/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c libpython.cpp -o libpython.o
g++ -std=gnu++11 -I"/opt/R/4.2.3/lib/R/include" -DNDEBUG  -I'/opt/R/4.2.3/lib/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c output.cpp -o output.o
g++ -std=gnu++11 -I"/opt/R/4.2.3/lib/R/include" -DNDEBUG  -I'/opt/R/4.2.3/lib/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c python.cpp -o python.o
python.cpp: In function ‘SEXPREC* py_id(PyObjectRef)’:
python.cpp:3125:36: error: call of overloaded ‘Vector(&lt;brace-enclosed initializer list&gt;)’ is ambiguous
   return CharacterVector({id.str()});
                                    ^
python.cpp:3125:36: note: candidates are:
In file included from /opt/R/4.2.3/lib/R/library/Rcpp/include/Rcpp/Vector.h:52:0,
                 from /opt/R/4.2.3/lib/R/library/Rcpp/include/Rcpp.h:40,
                 from python.cpp:7:
/opt/R/4.2.3/lib/R/library/Rcpp/include/Rcpp/vector/Vector.h:101:5: note: Rcpp::Vector&lt;RTYPE, StoragePolicy&gt;::Vector(const string&) [with int RTYPE = 16; StoragePolicy = Rcpp::PreserveStorage; std::string = std::basic_string&lt;char&gt;]
     Vector( const std::string& st ){
     ^
/opt/R/4.2.3/lib/R/library/Rcpp/include/Rcpp/vector/Vector.h:63:5: note: Rcpp::Vector&lt;RTYPE, StoragePolicy&gt;::Vector(const Rcpp::Vector&lt;RTYPE, StoragePolicy&gt;&) [with int RTYPE = 16; StoragePolicy = Rcpp::PreserveStorage]
     Vector( const Vector& other){
     ^
make: *** [python.o] Error 1
ERROR: compilation failed for package ‘reticulate’
* removing ‘/opt/R/4.2.3/lib/R/library/reticulate’

The downloaded source packages are in
	‘/tmp/RtmpX4kcOb/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("reticulate") :
  installation of package ‘reticulate’ had non-zero exit status
&gt; 
</pre>

## Environment:
<pre>
&gt; 
&gt; sessionInfo()
R version 4.2.3 (2023-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.3
&gt; 
&gt; 
&gt; Sys.getenv()[ grep("LIB|PATH", names(Sys.getenv())) ]
GOPATH                  /root/go
INFOPATH                /opt/rh/devtoolset-9/root/usr/share/info
LD_LIBRARY_PATH         /opt/hdf5-1.12.0/lib:/opt/R/4.2.3/lib/R/lib::/lib:/usr/local/lib:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.292.b10-1.el7_9.x86_64/jre/lib/amd64/server
MANPATH                 /opt/rh/devtoolset-9/root/usr/share/man:
PATH                    /opt/R/4.2.3/bin:/usr/local/go/bin:/opt/hdf5-1.12.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PKG_CONFIG_PATH         /opt/rh/devtoolset-9/root/usr/lib64/pkgconfig
R_LIBS_SITE             /opt/R/4.2.3/lib/R/site-library
R_LIBS_USER             /root/R/x86_64-pc-linux-gnu-library/4.2
R_STRIP_SHARED_LIB      strip --strip-unneeded
R_STRIP_STATIC_LIB      strip --strip-debug
&gt; 
</pre>

## Method:

I used two versions of the toolchains (devtools-9 and devtools-10; X={9|10}),
and tried two methods:

1) Failing method 1:
<pre>
scl enable devtoolset-X bash
gcc --version =&gt; gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
g++ --version =&gt; g++ (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
R
install.packages("reticulate")
</pre>

2) Failing method 2:
<pre>
scl enable devtoolset-X bash
gcc --version =&gt; gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
g++ --version =&gt; g++ (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
R
withr::with_makevars(  new = c(CXX17 = "g++", CXX17FLAGS = "-g -O2 $(LTO)", CXX17PICFLAGS = "-fpic", CXX17STD = "-std=gnu++17"), code = {  install.packages("reticulate")  })
withr::with_makevars( new = c(CXX17 = "/opt/rh/devtoolset-9/root/usr/bin/g++", CXX17FLAGS = "-g -O2 $(LTO)", CXX17PICFLAGS = "-fpic", CXX17STD = "-std=gnu++17"), code = { install.packages("reticulate") })
</pre>

3) Failing method 3:
<pre>
R
withr::with_makevars(  new = c(CXX17 = "g++", CXX17FLAGS = "-g -O2 $(LTO)", CXX17PICFLAGS = "-fpic", CXX17STD = "-std=gnu++17"), code = {  install.packages("reticulate")  })
withr::with_makevars( new = c(CXX17 = "/opt/rh/devtoolset-9/root/usr/bin/g++", CXX17FLAGS = "-g -O2 $(LTO)", CXX17PICFLAGS = "-fpic", CXX17STD = "-std=gnu++17"), code = { install.packages("reticulate") })
</pre>

Also i tested the above with all permutations of having a "~/.R/Makevars" or not.

## Successful similar application:

Oddly i managed to install RcppTOML with the following method successfully:
<pre>
withr::with_makevars( new = c(CXX17 = "g++", CXX17FLAGS = "-g -O2 $(LTO)", CXX17PICFLAGS = "-fpic", CXX17STD = "-std=gnu++17"), code = {  BiocManager::install("RcppTOML")  })
</pre>

So all C++ related packages are onboard actually:

<pre>
Rcpp                           Rcpp     1.0.10
RcppAnnoy                 RcppAnnoy     0.0.20
RcppArmadillo         RcppArmadillo 0.12.4.0.0
RcppEigen                 RcppEigen  0.3.3.9.3
RcppProgress           RcppProgress      0.4.2
RcppTOML                   RcppTOML      0.2.2
</pre>

## Conclusion:
Since this method worked for RcppTOML, i wonder whether it might actually not be compiler related?
Although "installation error in centos R #1292" is definitely indicating that, i know...

Any idea would help a lot...

Best

**Comment by kelbstf** [comment]
Hello again,
i just found, that apparently this is a problem with R picking up the specification for the compiler to use from Makevars:

This failed for me:
<pre>
CXX_STD = CXX14
CXX14 = g++
CXX14FLAGS = -g -O2 $(LTO)
CXX14PICFLAGS = -fpic
CXX14STD = -std=gnu++14
</pre>
This succeeded for me:
<pre>
CXX_STD = CXX14
CC=/opt/rh/devtoolset-9/root/usr/bin/gcc
CXX=/opt/rh/devtoolset-9/root/usr/bin/g++
</pre>
Having set that, a straight "install.packages("reticulate")" will, do.
None of the attempted shenanigans tried above required.
Maybe it works for someone else as well.

Best

**Comment by t-kalinowski** [comment]
Thank you for reporting and then thank you again for posting the solution!

**Comment by kelbstf** [comment]
At this occasion: thank you and your collaborators very much for developing and maintaining this software ;-)

**Comment by fredust** [comment]
I met the same error and your save my day!!! Thank you so much!!!!!
