### ISSUE TITLE
Python environment persistance across chunks

### ISSUE THREAD

**Issue by JoeJoe1313** [rstudio/reticulate#1385]
I am not able to understand if the issue of using variables/libraries from one python chunk in another when knitting is resolved or not. I am unable to use a variable from a previous chunk or use an imported library. If there is a solution for this, what is it? Is there any official documentation?

My current first chunk is:

```{r setup, include=FALSE}
library(reticulate)
reticulate::use_condaenv("r-reticulate", required = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = TRUE)
```

For example, first chunk:

```{python}
from typing import List

import matplotlib.pyplot as plt
import numpy as np
import scipy.special as sp
```

everything is fine, but in the second chunk if I want to directly use  

```
 k = np.prod(x)
```

this would fail with `NameError: name 'np' is not defined`.

**Comment by t-kalinowski** [comment]
This should definitely work, in both quarto and Rmd documents. Also, manually calling `knitr::knit_engines$set(python = reticulate::eng_python)` shouldn't be necessary.

I just tried locally with a qmd document and this is rendered correctly:

`````
---
title: "Untitled"
format: html
editor: visual
---

## Quarto
```{r}
Sys.unsetenv("RETICULATE_PYTHON")
library(reticulate)
reticulate::use_condaenv("r-reticulate", required = TRUE)
# py_install(c("matplotlib", "scipy"))
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, 
                      message = FALSE, cache = TRUE)
```

```{python}
from typing import List

import matplotlib.pyplot as plt
import numpy as np
import scipy.special as sp
```


```{python}
k = np.prod([1,2,3])
```


`````
