### ISSUE TITLE
reticulate-1.29 compilation error with R-3.5; missing Rf_installTrChar

### ISSUE THREAD

**Issue by aronatkins** [rstudio/reticulate#1388]
reticulate-1.29 fails to compile from source with R-3.5.

Here is a `Dockerfile` to recreate the problem:

```dockerfile
FROM rstudio/r-base:3.5-focal

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y libpng-dev \
    && rm -rf /var/lib/apt/lists/*

RUN R -e 'install.packages("reticulate", repos = c(CRAN="https://cran.rstudio.com/"))'
```

```bash
docker build --progress=plain .
```

Output from compilation:

```
#6 70.49 python.cpp: In function ‘SEXPREC* py_get_formals(PyObjectRef)’:
#6 70.49 python.cpp:1470:21: error: ‘Rf_installTrChar’ was not declared in this scope; did you mean ‘Rf_installNoTrChar’?
#6 70.49  1470 |     SEXP name_sym = Rf_installTrChar(Rf_mkCharCE(name_char, CE_UTF8));
#6 70.49       |                     ^~~~~~~~~~~~~~~~
#6 70.49       |                     Rf_installNoTrChar
#6 70.89 make: *** [/opt/R/3.5.3/lib/R/etc/Makeconf:172: python.o] Error 1
#6 70.89 ERROR: compilation failed for package ‘reticulate’
```

**Comment by kevinushey** [comment]
I think we should consider:

- Bumping the minimum required version of R for reticulate (what's an appropriate minimum now; maybe 3.4?)
- Make sure we build + test reticulate with the oldest-supported version of R on CI.

**Comment by t-kalinowski** [comment]
I'll update tests and track this down. At first glance, it's not obvious why this is failing, `Rf_installTrChar` is present in the 3.5 branch ... https://github.com/wch/r-source/blob/da8c12a93c8c9dd43ac992a3e1ffc06725a2fa1b/src/include/Defn.h#L1334

**Comment by t-kalinowski** [comment]
I can reproduce the issue with the Dockerfile (Thank you!). 

In R 3.5.3, [`installChar`](https://github.com/wch/r-source/blob/7497eeba51f39fcecbfcb8c79e0f16fa3803bded/src/main/sysutils.c#L976-L980) / [`Rf_installChar`](https://github.com/wch/r-source/blob/0ba66a2bc236ae5b009af910688575aa4adddd2c/src/include/Rinternals.h#L1377) is just a wrapper around `installTrChar` / `Rf_installTrChar`. The same wrapper is present in [R 4.3.0](https://github.com/wch/r-source/blob/47436d82fd1fe601ff3828c638d847ae2ee6552b/src/main/sysutils.c#L1141-L1148). I'll update reticulate to use `Rf_installChar()`
