### ISSUE TITLE
reticulate::install_python() with parameter "3.10:latest" fails on Windows    

### ISSUE THREAD

**Issue by amaendle** [rstudio/reticulate#1390]
Calling `reticulate::install_python("3.10:latest")   `  returns
> Error in setwd(root) : cannot change working directory
on Windows, User has no admin rights and the user directory is mapped to R_USER = H:/Documents.

I tried to trace down where the error happens:

`reticulate:::pyenv_find()` is called within  `install_python()` and produces the error.

Within thatg function it is the call on `reticulate:::pyenv_find_impl()` which produces the error.

Therein `reticulate:::pyenv_bootstrap()` calls `pyenv_bootstrap_windows()` which finally seems to be the cause of the error.

The variable `root` has the value `"C:/Users/myusername/AppData/Local/r-reticulate/r-reticulate/pyenv"`.

Then the system call `system2("git", c("clone", shQuote(url), shQuote(root)))` returns 127.

The following `setwd(root)` fails, because there is no directory named `pyenv` in "C:/Users/myusername/AppData/Local/r-reticulate/r-reticulate/"

**Comment by amaendle** [comment]
As ist seems `install_python` fails only when using somethin like "3.10:latest" as parameter.

However it works, if you specify the version exactly:
`reticulate::install_python("3.10.11")`

**Comment by t-kalinowski** [comment]
Thank you for the excellent diagnosis, it was very helpful! This should be fixed on main now, and a better error message is now shown if `git` is not installed.
