### ISSUE TITLE
Issue with source_python function for .ipynb files in Databricks

### ISSUE THREAD

**Issue by elohbeck87** [rstudio/reticulate#1395]
When testing the functionality mentioned below in Databricks, there is an error message.  The file 'Shiny_Python_Defs.ipynb' exists in the same directory as this current notebook running the function.  With several variations tried, this is still not possible in our Databricks environment.

![image](https://github.com/rstudio/reticulate/assets/103961543/ec20ddff-727b-4632-abaf-9b1069d2bbb6)

![image](https://github.com/rstudio/reticulate/assets/103961543/9077132b-5dcd-42da-9917-bdccf841ca89)

**Comment by t-kalinowski** [comment]
`source_python()` accepts a python script, not a ipynb notebook. You can convert the jupyter notebook to a script and then it should work.
