### ISSUE TITLE
Figure option for size in python chunk are taken into account once 

### ISSUE THREAD

**Issue by cderv** [rstudio/reticulate#1398]
Following a report at https://github.com/quarto-dev/quarto-cli/issues/6008

````markdown
---
title: "fig-width test"
output: html_document
---

## Make a Wide Python Plot

```{python}
#| fig.width: 8
#| fig.height: 2
import matplotlib.pyplot as plt
plt.plot([1,2,3,4], [1,4,9,16], 'ro')
plt.show()
```

## Make a Square Python Plot

```{python}
#| fig.width: 3
#| fig.height: 3
plt.plot([1,2,3,4], [1,4,9,16], 'ro')
plt.show()
```
`````
![image](https://github.com/rstudio/reticulate/assets/6791940/60637eb6-74fc-4d33-94ee-15909766fcc8)

Possibly related to https://github.com/rstudio/reticulate/issues/1140

It seems the options are taken into account once only. Is there a specific way to reset the matplotlib initialization ? 
https://github.com/rstudio/reticulate/blob/9163ac38a731b72dc68fea69a9bcad2933e5b079/R/knitr-engine.R#L476-L477

Is this a limitation ? Or something we can improve ?

**Comment by t-kalinowski** [comment]
Thanks for reporting @cderv! A fix is in the works (on a PR branch currently), should be merged into main soon.

**Comment by cderv** [comment]
Thanks !
