### ISSUE TITLE
Reticulate + JPype causes Seg Fault

### ISSUE THREAD

**Issue by hielsber-tamu** [rstudio/reticulate#1399]
With the following setup:

R 4.2
Python 3.9
JPype1-1.4.1
Java 11.0.19.0.7
~/.Renviron contains the following:

JAVA_HOME=/usr/lib/jvm/jre-11-openjdk/
RETICULATE_PYTHON=/usr/local/bin/python3.9

The following produces a segmentation fault:

$ R
> library("reticulate")
> source_python("test.py")
Segmentation fault

Contents of test.py:

import jpype
jpype.startJVM()

Can anyone else verify/reproduce this?  Also, any insight as to the cause or fix would be appreciated.

**Comment by t-kalinowski** [comment]
Hi, I just tried and was unable to reproduce the error. 

My best guess is that R startup preloads some shared libraries that are then incompatible with the version of java you're specifying in `JAVA_HOME`. E.g., on my machine, on startup R will append `"/usr/lib/jvm/default-java/lib/server"` to `LD_LIBRARY_PATH`.

**Comment by hielsber-tamu** [comment]
Thank you for the reply.  I believe your guess is right on, however as I did not verify all items on the LD_LIBRARY_PATH prior to reinstalling/upgrading so I cannot say for certain.  It appears the issue is resolved with at least a correct LD_LIBRARY_PATH, but in my case also an upgrade to R v4.3.0 and reinstallation of reticulate.  

Thank you again.
