### ISSUE TITLE
extra newline appended when capturing python output

### ISSUE THREAD

**Issue by kevinushey** [rstudio/reticulate#142]
It seems like this behavior might be intentional, but just wanted to be sure. Given the following script:

```
library(reticulate)
py_run_string("print 1 + 1")
cat(py_capture_output(py_run_string("print 1 + 1")))
```

A single newline follows `py_run_string("print 1 + 1")`, but two newlines follow `cat(py_capture_output(py_run_string("print 1 + 1")))`. Is that intended?

This question is primarily motivated by Notebook work -- I'm wondering if I should explicitly trim a trailing newline from any captured output from running a line of Python code.

**Comment by jjallaire** [comment]
It looks like we append the newline here: https://github.com/rstudio/reticulate/blob/master/R/python.R#L1056

I'm not sure why we do this but I'm inclined not to change it at this point, so I would indeed trim the trailing newline from captured Python output.
