### ISSUE TITLE
Move `png` to suggests

### ISSUE THREAD

**Issue by dfalbel** [rstudio/reticulate#1440]
We only depend on `png` for the knitr engine and `knitr` already depends on `png` so it should be safe to move it to suggests.
libpng-devel was the only system lib I had to manually install to test reticulate in a clean container.

**Comment by kevinushey** [comment]
We added `png` to Imports to help support RStudio (to avoid the need to re-prompt the user to install 'png' if they wanted to make plots with reticulate). Can we please keep it there?
