### ISSUE TITLE
Poor performance using threading un python

### ISSUE THREAD

**Issue by YouenL** [rstudio/reticulate#147]
I'm using reticulate (which simplify my life greatly btw) to run a python code with a thread in it. When using reticulate the performance are very very bad (10 times slower than when using directly python).

**Comment by deymos314** [comment]
I have same issue. Is there any reason why this is the case?

**Comment by kevinushey** [comment]
Could you provide a bit of example code that I could try running to observe the difference myself?

**Comment by deymos314** [comment]
It is imposible because of legal reasons. I will try to reproduce this
problem in other case. Thanks

Czw., 8 sie 2019, 17:02 użytkownik Kevin Ushey <notifications@github.com>
napisał:
