### ISSUE TITLE
Reticulate behind proxy

### ISSUE THREAD

**Issue by frcaldeira** [rstudio/reticulate#1472]
Hello,

I'm using reticulate to access Google earth engine.

I'm receving this error:

 Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  requests.exceptions.ProxyError: HTTPSConnectionPool(host='earthengine.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/earthengine-legacy/value:compute?prettyPrint=false&alt=json (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
Run `reticulate::py_last_error()` for details. 

I have defined my proxy in the reviron file like this

HTTPS_PROXY=http://xxxx.xxx.xx:8080
HTTP_PROXY=http://xxxx.xxx.xx::8080

Is there something missing?

Best regards
Francisco

**Comment by t-kalinowski** [comment]
I'm not sure if it applies here, but in the past, we have seen issue that present like this with Conda python installations having ssl requirements that conflict with those of the R process reticulate is running from. 

Can you please try with a virtualenv and see if that fixes the issue?
