### ISSUE TITLE
`imp` module removed on Python 3.12

### ISSUE THREAD

**Issue by danielvartan** [rstudio/reticulate#1492]
Maybe you guys already know this, but if not, here it is:

`reticulate` will not work with Python 3.12 (released on October 2, 2023) because the `imp` module is still being used.

https://github.com/rstudio/reticulate/blob/afb0a22e2661c97f37f593597569e895d7d9a610/inst/config/config.py#L16

You can learn more at [What’s New In Python 3.12](https://docs.python.org/dev/whatsnew/3.12.html).

**Comment by t-kalinowski** [comment]
Thanks, this is fixed now.
