### ISSUE TITLE
Mapping uint32/ulong in numpy arrays

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/reticulate#15]
These came up and `py_ref_to_r` complains. Could we map these to double around here https://github.com/rstudio/reticulate/blob/master/src/python.cpp#L396?

**Comment by jjallaire** [comment]
Could you give me a brief code snippet which exhibits the errors so I can ensure that the change correctly addresses the issue for each type?

**Comment by kevinykuo** [comment]
```
np <- import("numpy")
np$array(c(1, 2), dtype = "uint32")
# Error in py_ref_to_r(x) : 
#   Conversion from numpy array type 6 is not supported
```

**Comment by jjallaire** [comment]
Here's a commit that maps `NPY_UNIT` and `NPY_ULONG` to `NPY_LONG`:

https://github.com/rstudio/reticulate/commit/7ec26f360309d917f8b2dad3c8eed87d746aff84

I do this to be consistent with previous mappings (e.g. `NPY_LONGLONG` to `NPY_LONG`) that attempted to preserve the integer type even at the expense of possible overflow. It occurs to me though that this might be incorrect and we should as you point out be more conservative and map potentially overflowing integer types to `NPY_DOUBLE`.

@bwlewis What's is your take on this?

**Comment by jjallaire** [comment]
Behavior changed in this PR: https://github.com/rstudio/reticulate/pull/17
