### ISSUE TITLE
Better support for Altair compound Chart

### ISSUE THREAD

**Issue by cderv** [rstudio/reticulate#1500]
This was reported at https://github.com/quarto-dev/quarto-cli/issues/7418 but this an issue with knitr engine 

Compound Chart (https://altair-viz.github.io/altair-viz-v4/user_guide/compound_charts.html) won't show, as they will have the same id for all

````markdown
---
title: "Report"
---

```{r}
library(reticulate)
```

# Heading
```{python}
import altair as alt
import pandas as pd

source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

fig1 = alt.Chart(source).mark_bar().encode(
    x='a',
    y='b'
)
fig2 = alt.Chart(source).mark_bar().encode(
    x='a',
    y='b',
    color='b:N'
)
fig3 = alt.Chart(source).mark_bar().encode(
    x='a',
    y='b',
    color='a:N'
)
```

## Chart1 
```{python}
#| label: first
(fig1 | fig2).properties(title="This is the First Chart")
```

## Chart2 
```{python}
#| label: second
(fig2 | fig1).properties(title="This is the Second Chart")
```

## Chart3 
```{python}
#| label: third
(fig2 | fig1 | fig3).properties(title="This is the Third Chart")
```
````

I believe this happens because Altair gives  gives different class than Charts, and so the knitr engine should probably be more open to classes
https://github.com/rstudio/reticulate/blob/5d0a9a52286a173ac8868c1d548b8715247867ae/R/knitr-engine.R#L620-L628

so this is skipped 
https://github.com/rstudio/reticulate/blob/5d0a9a52286a173ac8868c1d548b8715247867ae/R/knitr-engine.R#L702-L732

Probably opening the regex will help, but there could be other expectation not meet maybe. 

Hope this report help fix this

**Comment by plasmak11** [comment]
Just to add the current workaround: Re-rendering it using `vegawidget` after saving the JSON representation in reticulate's python space. This way reassigns a new div id in the new R block, in Quarto.

- Store as `chart1 = fig1.to_json()`
- Render it in R block as `as_vegaspec(py$chart1)`

e.g. Found gist snippet:
https://gist.github.com/ijlyttle/aa314d02b5f7f85702ea2a648393b21f

Confirmed this works.
