### ISSUE TITLE
miniconda_path does not substitute $USER

### ISSUE THREAD

**Issue by nschan** [rstudio/reticulate#1513]
Hello,

I ran noticed a minor issue: `reticulate::miniconda_path()` is not substituting $USER for the actual username. I have set `XDG_DATA_HOME` on an RStudio server to point to a directory like `/mnt/storage/rstudio/$USER`. When using reticulate the miniconda_path is returned as "/mnt/storage/rstudio/$USER/r-miniconda", which is not what I would expect to happed. Is there a better way to set `XDG_DATA_HOME` so the variable gets substituted? 
I am running RStudio server on debian12 and set `XDG_DATA_HOME` using `sudo systemctl edit rstudio-server`.

**Comment by t-kalinowski** [comment]
Thank you for reporting! This is now fixed in the development version of reticulate. You can install with the R command:
```r
remotes::install_github("rstudio/reticulate")
```
