### ISSUE TITLE
Flag a delayed-load module as a promise or lazy

### ISSUE THREAD

**Issue by mkoohafkan** [rstudio/reticulate#1517]
Not sure if this is a `{reticulate}` issue or a `{rlang}` issue, but currently a delayed-load module is not recognized as lazy or as a promise (and it probably should be?). Actually, it doesn't seem like the module object is interpreted correctly, active or not:

```r
library(reticulate)
library(rlang)

re = reticulate::import("re", delay_load = TRUE)

rlang::env_binding_are_lazy(globalenv(), "re")
#> FALSE
rlang::env_binding_are_active(globalenv(), "re")
#> FALSE

# trigger module load
re$match
#> <function match at 0x000001C7B51F7790>
rlang::env_binding_are_lazy(globalenv(), "re")
#> FALSE
rlang::env_binding_are_active(globalenv(), "re")
#> FALSE
```

This is currently causing an [issue with the VSCode-R session watcher](https://github.com/REditorSupport/vscode-R/issues/1466), which immediately forces the loading of the delayed-load module because it does not detect it as either a lazy binding/promise or as an active binding. I'm sure VSCode-R can work around it, but I'm wondering if this is something `{reticulate}`/`{rlang}` wants to handle in any case.

**Comment by t-kalinowski** [comment]
If you trace `trace(reticulate:::initialize_python, quote(print(rlang::trace_back())))`, what is the method being invoked that is forcing reticulate to initialize python?

This is probably unrelated to rlang; R promises are an R language feature, and not used in the implementation of reticulate's delayed module proxies.

**Comment by mkoohafkan** [comment]
The issue is encountered in the [VSCode-R session watcher function](https://github.com/REditorSupport/vscode-R/blob/master/R/session/vsc.R#L270-L355), and specifically [this line](https://github.com/REditorSupport/vscode-R/blob/54f924cd2efa053cb6615903aaa8952f28405f11/R/session/vsc.R#L331C21-L331C52) triggers the evaluation:

```r
# essentially
# obj = reticulate::import("re", delay_load = TRUE)
.DollarNames(obj, pattern = "")
```

But again, this code only gets evaluated because `rlang::env_binding_are_lazy()` and `bindingIsActive()` both return `FALSE` for a delayed-load module. Obviously VSCode-R could add a check to handle `python.builtin.module` and/or `python.builtin.object` objects, but I wonder if there might be general value in having `rlang::env_binding_are_lazy()` return `TRUE` for delayed-load modules.

**Comment by t-kalinowski** [comment]
My understanding is that `rlang::env_bindings_are_lazy()` is using "lazy", not in the general sense as an umbrella term for objects that are not fully realized in some way, rather, in a narrow sense, specifically referring to R *promises*, which can be created with `delayedAssign()`, as a function argument waiting to be evaluated, or similar. Delayed reticulate module proxies are not "lazy", in this narrow meaning of the word.
