### ISSUE TITLE
The figure size option in the Python chunk is not taken into account for the first chunk

### ISSUE THREAD

**Issue by R-CoderDotCom** [rstudio/reticulate#1523]
I am experiencin an issue that might be related to the fix on #1398 available since reticulate 1.31. Now, it seems that `fig.size` and `fig.width` are ignored only for the first python chunk.

The following `.Rmd` will generate the first plot without taking into account the specified sizes:

````
---
title: "Untitled"
output: html_document
date: "2024-01-17"
---

```{r, echo = FALSE, eval = TRUE}
knitr::opts_chunk$set(fig.height = 4, fig.width = 4)
```

```{python, echo = FALSE}
import matplotlib.pyplot as plt

x = [1, 2, 3]

fig, ax = plt.subplots()
ax.bar(x = x, height = x)
plt.show()
```


```{python, echo = FALSE}
import matplotlib.pyplot as plt

x = [1, 2, 3]

fig, ax = plt.subplots()
ax.bar(x = x, height = x)
plt.show()
```

````

![imagen](https://github.com/rstudio/reticulate/assets/67192157/853f5d50-3824-4d90-b402-898b255ee269)

But if a chunk is added importing matplotlib or seaborn the sizes will be correct:

````
---
title: "Untitled"
output: html_document
date: "2024-01-17"
---

```{r, echo = FALSE, eval = TRUE}
knitr::opts_chunk$set(fig.height = 4, fig.width = 4)
```

```{python, echo = FALSE}
import matplotlib.pyplot as plt
```

```{python, echo = FALSE}
import matplotlib.pyplot as plt

x = [1, 2, 3]

fig, ax = plt.subplots()
ax.bar(x = x, height = x)
plt.show()
```


```{python, echo = FALSE}
import matplotlib.pyplot as plt

x = [1, 2, 3]

fig, ax = plt.subplots()
ax.bar(x = x, height = x)
plt.show()
```
````

![imagen](https://github.com/rstudio/reticulate/assets/67192157/61ca0f42-d97b-40f9-a678-528fabe27928)

It seems that this trick only works if matpotlib or seaborn is imported. I have tested that empty chunks doesn't work and printing a value doesn't work.

Reticulate version: 1.34.0
Python version: 3.12.1
rmarkdown version: 2.25
knitr version: 1.45

**Comment by t-kalinowski** [comment]
Thank you for the detailed bug report! This is fixed now on the development branch.
```r
reticulate::install_github("rstudio/reticulate")
```
