### ISSUE TITLE
Pandas DataFrame column with None gets converted to a list type

### ISSUE THREAD

**Issue by tanvach** [rstudio/reticulate#1534]
We've been seeing an odd behavior where a pandas DataFrame column with any None gets converted to a column with list type. Below is how to reproduce with reticulate version 1.35

```
library(reticulate)

repl_python(input = "
import pandas
df = pandas.DataFrame({'col1':[True]})
df_none = pandas.DataFrame({'col1':[True, None]})
")

# Check column types
str(py$df)
str(py$df_none)

OUTPUT:

'data.frame':	1 obs. of  1 variable:
 $ col1: logi TRUE
 - attr(*, "pandas.index")=RangeIndex(start=0, stop=1, step=1)

'data.frame':	2 obs. of  1 variable:
 $ col1:List of 2
  ..$ : logi TRUE
  ..$ : NULL
 - attr(*, "pandas.index")=RangeIndex(start=0, stop=2, step=1)
```

I was told this should have been [fixed](https://github.com/rstudio/reticulate/issues/376) in version 1.31 but I'm still experience this issue.

**Comment by dfalbel** [comment]
We have considered automatically simplifying homogeneous lists of python objects to their atomic vector counterpart in R, but ended up deciding to not do it automatically. The problem is that it's always ambiguous if simplification is expected or not. Eg, imagine if you take a single row of `df_none`, what's the expected behavior if we subset the second row only, eg with:

```
py$df_none[2,]
```

I can be convinced that we should change this behavior, although I think it's likelly that changing the behavior is going to break user's code that already handles the simplification as #376 is a very old issue.

My recommendation is to use Pandas nullable data types to explicitly determine that the column is a boolean column possibly containing missing values. You can do somehting like:

```
df_none['col1'] = df_none['col1'].astype('boolean')
```

You then get the expected `NA`:

```
> py$df_none[2,]
[1] NA
```

**Comment by tanvach** [comment]
Thank you, that makes sense although I would think a simple-ish solution is to make this behavior user selectable via a global setting?

**Comment by t-kalinowski** [comment]
Here is a snippet you can use to simplify logical columns in dataframes. 

``` r
simplify_nullable_logical_columns <- function(df) {
  df[] <- lapply(df, function(col) {
    if (is.list(col)) {
      # bail early if we can't simplify
      for (el in col)
        switch(typeof(el),
               "NULL" = next,
               "logical" = if (length(el) != 1) return(col),
               return(col))

      col <- vapply(col, \(x) if(is.null(x)) NA else x, TRUE,
                    USE.NAMES = FALSE)
    }
    col
  })
  df
}

library(reticulate)

reticulate::py_run_string("
import pandas
df = pandas.DataFrame({
  'col1': [True, None, False, None],
  'col2': [True, False, 1, None],
})")

str(py$df)
#> 'data.frame':    4 obs. of  2 variables:
#>  $ col1:List of 4
#>   ..$ : logi TRUE
#>   ..$ : NULL
#>   ..$ : logi FALSE
#>   ..$ : NULL
#>  $ col2:List of 4
#>   ..$ : logi TRUE
#>   ..$ : logi FALSE
#>   ..$ : int 1
#>   ..$ : NULL
#>  - attr(*, "pandas.index")=RangeIndex(start=0, stop=4, step=1)
str(simplify_nullable_logical_columns(py$df))
#> 'data.frame':    4 obs. of  2 variables:
#>  $ col1: logi  TRUE NA FALSE NA
#>  $ col2:List of 4
#>   ..$ : logi TRUE
#>   ..$ : logi FALSE
#>   ..$ : int 1
#>   ..$ : NULL
#>  - attr(*, "pandas.index")=RangeIndex(start=0, stop=4, step=1)
```

<sup>Created on 2024-02-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

If more users request this we can consider changing the default, but as @dfalbel mentioned, this would be a disruptive change for users with existing code, and there are very accessible workarounds.

**Comment by t-kalinowski** [comment]
I added some regression tests for the current behavior. 

As Daniel suggested in https://github.com/rstudio/reticulate/issues/1534#issuecomment-1956654016, for automatic conversion of pandas columns with `{True, False, None}` to R logical columns, the recommendation is to use the pandas boolean type:

```r
 df['bool_or_None'] = df_none['bool_or_None'].astype('boolean')
```
