### ISSUE TITLE
Reticulate automatically resets RETICULATE_PYTHON variable

### ISSUE THREAD

**Issue by MauricePasternak** [rstudio/reticulate#1536]
# System

OS Name: Ubuntu 22.04.03 LTS
RVersion: 4.3.2
**IMPORTANT**
Also, I use VSCode with the R and R Debugger extensions:
![image](https://github.com/rstudio/reticulate/assets/57411571/76a41d04-562a-4bc6-9550-5704bbe1ef52)

And as part of that, I have `radian` installed as the R terminal when using VSCode. 

All instructions here were followed and have worked seamlessly: https://code.visualstudio.com/docs/languages/r

# Steps to reproduce:

1. Create a virtualenv. I used poetry.

```
>>> poetry new reticulate_bug
Created package reticulate_bug in reticulate_bug
>>> cd reticulate_bug
>>> poetry shell
```

If it makes any difference, my virtualvenv will have its `.venv` folder created at the project's root. In this case the `reticulate_bug` root level folder.

![image](https://github.com/rstudio/reticulate/assets/57411571/5431adcf-60b9-4bbb-a6f2-d1cab337e059)

2. Simply check the `RETICULATE_PYTHON` environment while loading in the library

![image](https://github.com/rstudio/reticulate/assets/57411571/c6ed30d6-9e7f-4982-a6d9-059120a9773b)

There's no reason for it to do that.

Putting a `.Renviron` at the root directory does not assist with preventing this either; `reticulate will just overwrite matters even when the library is not explicitly loaded in:

![image](https://github.com/rstudio/reticulate/assets/57411571/c895d38e-4689-4776-ac32-b1ebdb918ab7)

**Comment by t-kalinowski** [comment]
Radian uses reticulate under the hood. By the time you're presented with the R repl by radian, reticulate has already selected and initialized a Python installation. If you want to use reticulate from radian, you have to point radian at the Python you want it to use before the start of the R session. (E.g, set `RETICULATE_PYTHON` before launching radian, or consult the radian docs for other approaches).

**Comment by MauricePasternak** [comment]
Thanks @t-kalinowski 

I can confirm that taking the following steps/guidelines makes things workable:

1) Uninstall `radian` if it is located in site-packages of any global python interpreter.

2) Installing `radian` once a project's/local virtual environment is activated.

3) For quality-of-life improvement, making a .vscode/settings.json file in that project and putting settings like `r.rterm.linux` to point to the venv's python binary.

Given the above, once the virtualenv is activated, clicking on the `R: (not attached)` button will open up a `radian` terminal in which importing `reticulate` will point to the appropriate python interpreter. 

Fair heads up though, this whole VSCode + `radian` + `reticulate` setup doesn't play nice with Quarto's attempts to render a .qmd file into, say, a presentation. Working without `radian` is recommended there, unfortunately. But that is beyond the scope of this repository. Additionally, it appears it is impossible to have `reticulate` operate with a `jupyter` engine, a `knitr` engine is the only one that will result in bidirectional Python <--> R communication.

Thanks again and cheers!

**Comment by t-kalinowski** [comment]
Thank you for the detailed write-up! This should be very useful as other users encounter similar issues.

**Comment by ggruenhagen3** [comment]
I enjoy using radian, but it's disappointing that we can't use different python versions on-the-fly with it. I hope this issue is solved in the future!
