### ISSUE TITLE
Unsilenceable Index.format deprecation warning with pandas 2.2

### ISSUE THREAD

**Issue by paulimer** [rstudio/reticulate#1537]
Using python 3.11, pandas 2.2 and reticulate 1.34 (the last one in conda), each time I send a dataframe to python (or one is returned, I can't tell), the following warning is displayed : 
`sys:1: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.`
It is not silenceable with `py_suppress_warnings`, and did not happen with pandas 2.1.4.

To reproduce the issue the following R code : 
```r
library(reticulate)
use_condaenv("warning")
warning <- import("warning")

iris_2 <- warning$test_df(iris)
```
python code : 
```py 
import pandas as pd

def test_df(input_df):
    return input_df
```
and conda environment : 
```
name: warning
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - pandas=2.2
    - r-reticulate
```
is sufficient.

**Comment by t-kalinowski** [comment]
Thank you for reporting, this is now fixed in the development version of reticulate.
