### ISSUE TITLE
Error in GitHub Action Virtualenv_create with R-devel and Reticulate 

### ISSUE THREAD

**Issue by pbulsink** [rstudio/reticulate#1544]
Hello, we have a recurrent error with reticulate for rdevel on ubuntu in our github action: 

https://github.com/SCasanova/f1dataR/actions/runs/8149812048/job/22275075253

In particular, trying to create a virtualenv causes the following error:

```
Error in .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version) : 
  invalid non-character version specification 'x' (type: double)
Calls: virtualenv_create ... as.numeric_version -> numeric_version -> .make_numeric_version
```

Other versions of R on the same platform (release and oldrel) and with specified (3.11) or generic (3.x) versions of python pass.
R-Devel on other platforms (windows-latest/macos-latest) with specified (3.11) or generic (3.x) versions of python fail.

Code suffering the error:
```
      - name: setup r-reticulate venv
        shell: Rscript {0}
        run: |
          python_packages <- c("numpy", "fastf1")
          library(reticulate)
          virtualenv_create("r-reticulate", Sys.which("python"))
          virtualenv_install("r-reticulate", python_packages)
          path_to_python <- virtualenv_python("r-reticulate")
          writeLines(sprintf("RETICULATE_PYTHON=%s", path_to_python),
                     Sys.getenv("GITHUB_ENV"))
```

**Comment by t-kalinowski** [comment]
Thanks for reporting.

I beleive the development version of reticulate already has a fix for the latest r-devel. Do you still see the error if you install reticulate from main branch?

We'll have a new CRAN release in a few weeks time.

**Comment by pbulsink** [comment]
Thanks for that advice. I re-ran on GHA with reticulate from github and everything ran correctly. 

For others who may experience the same issue and want to use reticulate from github instead of CRAN, I added the following lines before my setup-reticulate step (after `r-lib/actions/setup-r-dependencies@v2`):

```
      - name: Install remotes
        run: |
          Rscript -e "install.packages('remotes')"

      - name: Install dev reticulate from Github
        run: |
          Rscript -e "remotes::install_github('rstudio/reticulate')"
```

**Comment by t-kalinowski** [comment]
Thanks for reporting. It looks like there are two stray `py_version > 3` comparisons that I didn't update with the initial fix: https://github.com/rstudio/reticulate/blob/74627cdd60dcf4d93345d0ee628644109ae6939c/R/virtualenv.R#L453

However, those lines of code are only evaluated when we're already composing a nicer error message because `pip` or `venv` is missing. Since you've already installed `python3-venv`, something else is also going wrong, which we'll need to investigate.

**Comment by eddelbuettel** [comment]
So I was trying to get a minimal environment going when batch package building.  The displayed `sudo apt install python3-venv` is clearly not enough.  Adding `python3-pip python3-dev python-is-python3` appears to work once, but not when I restarted the container (huh?).   

Could it be that we are running into subtle 'focal vs jammy' differences?

**Comment by eddelbuettel** [comment]
Getting closer, thanks to your fine and focussed commit I was able to poke.  I think the first test passes

```sh
root@78709e774099:/# Rscript -e 'reticulate:::python_has_module("/usr/bin/python3", "pip")'
[1] TRUE
root@78709e774099:/# 
```

but the second was not testing for `venv` present so my R 4.4.1 nagged over the comp with 3 instead of "3".

(This was after

```sh
apt update -qq; apt install r-cran-reticulate python3-pip python3-dev python3-venv python-is-python3
```

in a `rocker/r2u:noble` container.)

**Comment by t-kalinowski** [comment]
The only other thing I could think of is that this `dpkg` check failed because the output of dpkg changed subtly:

https://github.com/rstudio/reticulate/blob/74627cdd60dcf4d93345d0ee628644109ae6939c/R/virtualenv.R#L436


However, I tried in docker containers derived from both `rocker/r2u:noble` and `ubuntu:24.04` and was unable to reproduce the error. `dpkg -l` still gave the expected output, and `reticulate::virtualenv_create()` succeeded without issue after `apt install -y python3-venv` had run.

**Comment by eddelbuettel** [comment]
Yes that works here too.  (Same 22.04 container I still had open)

```sh
root@78709e774099:/# Rscript -e 'any(grepl("\\bpython[0-9.]*-venv\\b", system("dpkg -l", intern = TRUE)))'
[1] TRUE
root@78709e774099:/# 
```

**Comment by t-kalinowski** [comment]
If you can share a Dockerfile where `reticulate::virtualenv_create()` errors, I'll be happy to take a look.

**Comment by eddelbuettel** [comment]
Hm, that command works (after `apt update -qq; apt install r-cran-reticulate python3-pip python3-dev python3-venv python-is-python3`).  So maybe my (much more feeble?) bug report is that the echo'ed line on `sudo apt install python3-venv` is to short?

**Comment by eddelbuettel** [comment]
And the same command I ran a few comments and hours earlier, ie from inside R, now also works.  I must have been missing `python3-dev` I guess?

**Comment by t-kalinowski** [comment]
Thanks. I just pushed an update to improve the error message and mention `python3-dev`.

**Comment by eddelbuettel** [comment]
I presume I could iterate and try to find the minimal set that let's us build the required venv.

(One thing, by the way, I was thinking but have been able to check with your code.  Would having an env that auto-creates the default venv if missing be helpful?)

**Comment by t-kalinowski** [comment]
> Would having an env that auto-creates the default venv if missing be helpful?

Do you mean something like this?
```r
reticulate:::.onLoad <- function(...) {
  ...
  if (!virtualenv_exists("r-reticulate") && 
      !is.null(virtualenv_starter())
    virtualenv_create()
}
```
