### ISSUE TITLE
If both Python 2.x and 3.x are available, reticulate prefers Python 2.x despite being deprecated

### ISSUE THREAD

**Issue by s-u** [rstudio/reticulate#1547]
On most systems both Python 2.x and 3.x are available as `python` and `python3` respectively, but despite Python 2 being deprecated, reticulate will give it preference to Python 3.x. For example:

```
> reticulate::py_discover_config()
python:         /usr/bin/python
[...]
NOTE: Python version was forced by PATH

python versions found: 
 /usr/bin/python3
 /usr/bin/python
```

This is suboptimal since reticulate itself warns that Python 2 is deprecated so it should prefer Python 3.

It requires explicit setting via `use_python` or `RETICULATE_PYTHON` in order to force the use of Python 3 (which is the only version that actually works with `reticulate` since Python 2 will fail with undefined symbols, but that's another story).

Given that the choice is obvious and that `reticulate` already knows that both Python versions are available (see above) it should pick Python 3 over Python 2.

**Comment by eddelbuettel** [comment]
If this is Ubuntu or Debian based consider `sudo apt install python-is-python3`. I have no idea why that is not a default.

**Comment by t-kalinowski** [comment]
I opened a PR which should fix the issue. Thanks for reporting.

I think this was a rare edgecase. It's literally last in the [order of discovery](https://rstudio.github.io/reticulate/articles/versions.html). The default experience for users that don't express a preference for a particular python installation is to create and use a `r-reticulate` virtual env. I think most users eventually end up expressing a preference in one form or another (e.g., by setting `RETICULATE_PYTHON`)
 
When falling back to the PATH, we also explicitly already look for `python3` before `python`: https://github.com/rstudio/reticulate/blob/b1c33d5797b1478ebddf876f0284ac953b086c0d/R/config.R#L339-L340

The only circumstance where we would have prioritized `python` over `python3` would have been if `python3` was the wrong arch or was missing `numpy`, while `python` was both the correct arch and had numpy installed.

**Comment by s-u** [comment]
@t-kalinowski thanks, your comments describe at least part of the logic which is very helpful as it also explains why one version is preferred over the other. Can you, please, document the full login in the help file - e.g. in `?py_discover_config`?

That said, the PR does not change the behavior in the case where `numpy` is available in Python2 and not Python3. In the case that triggered this investigation it was caused by an R package that doesn't use `numpy` so even though all module dependencies of the package were satisfied in Pythoin3 `reticulate` still picked Python2 because of the `numpy` requirement which was in that case unnecessary. I'm ok if this is simply documented (if that is the desired behavior) since then at least the user can fix the problem.
