### ISSUE TITLE
Enable reticulate bin/scripts on PATH

### ISSUE THREAD

**Issue by latot** [rstudio/reticulate#1578]
Hi, all started when I wanted to compile a rust program on windows, then I found reticulate has conda, which is great to install things fast without much user intervention, I was able to compile programs with reticulate!

Now I think would be good a way to expose the executable or even libraries, for example the executable enable them on PATH using ```use_condaenv```, also we actually does not have any way to get the actual binary path from conda (which can changes depending on a lot of things, like the SO).

I don't know which would be the ideal case, but any of them or both would be great to use binaries from conda in a lot easier way.

Thx!

**Comment by t-kalinowski** [comment]
Hi, thanks for reaching out. This is an open-ended question that would probably be better for https://forum.posit.co/. 

Just to clarify a little: Reticulate does not bundle conda. It provides some convenience functions like `install_miniconda()` which will install conda on the system, and it is able to use conda python installations. Also, if you run `use_condaenv()` or `use_virtualenv()`, it will update the R sessions PATH variable by placing the Python environment binaries on the PATH, just like running `source /path/to/venv/bin/activate` does in bash.

**Comment by latot** [comment]
Hi, yes, but this issue is different from that perspective, is not to use only Python, as you says it adds the python path to PATH, but the binaries of conda are in other place, for example in Windows are placed on ```conda_env/Library/bin```, which is the path for this particular SO, Python is in other path.

**Comment by t-kalinowski** [comment]
I believe reticulate places those paths on the PATH as well:

https://github.com/rstudio/reticulate/blob/2e73fb9757e1a207dd257be871413b810077a584/R/conda.R#L1079-L1090

**Comment by latot** [comment]
Sadly is not doing it...

```R
> reticulate::use_condaenv("test2")                                                                                                                                                                                
> Sys.getenv("PATH")
[1] "/home/pipe/.local/share/r-miniconda/condabin:/home/pipe/.local/share/r-miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/17/bin"
```

Adds the actual miniconda paths, but not the path envs.

**Comment by t-kalinowski** [comment]
What output do you expect?

**Comment by t-kalinowski** [comment]
Would you like to submit a PR?

**Comment by latot** [comment]
@t-kalinowski I was tyring to do it, but there is some things that needs to be solved with PATHs.

One part is that the actual dirs are designed for miniconda install of conda.
And... alter the PATH in this way, should also have a way to go out of condaenv, which maybe needs other type of solution.

Would you consider opening this issue again?

**Comment by t-kalinowski** [comment]
Hi @latot, I don't fully understand the feature request. Can you perhaps provide a minimal reproducible example of the current behavior, and describe the changed behavior you are proposing?

**Comment by t-kalinowski** [comment]
Yes, `use_condaenv()` should do the equivalent of `conda activate`, but, if I recall correctly, we run the `activate` command in a separate process and then try to copy over env variables, because of reliability issues we encountered with activation scripts.

**Comment by latot** [comment]
@t-kalinowski here is the issues I found, should I open them independently? or want to check something before?

## Wrong PATH activating env

When in conda we run ```conda activate env``` PATH changes to the next thing:

```
PATH=>/home/pipe/miniconda3/envs/env/bin:/home/pipe/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/17/bin
```

This as first is important ```/home/pipe/miniconda3/envs/env/bin``` because is the one who give us access to the env.

But in R:

```
Sys.getenv("PATH")
[1] "/home/pipe/.local/share/r-miniconda/condabin:/home/pipe/.local/share/r-miniconda/bin:/home/pipe/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/17/bin"
```

The path to the conda env is missing, still is in the base one, this is the first thing I notice and why I open this issue in first place, without this PATH we can't use the apps of the conda env.

## Deactivate

Is pretty important have a deactivate option, and this one has two sides that needs a fix.

### Deactivate from base

We know with ```conda deactivate``` get out of the current env, but is not completely true, in R we need be able to get out from a particular env, and go out to the system env, to achieve that we need this be set on miniconda:

```conda config --set auto_activate_base false```

If not, the last ```conda deactivate```  will always be in base env, which means the base env will be over the system one.

### Deactivate from env

We actually does not have any way to go out of a particular env, which also clean the PATH variable.

## Use conda_env does not change the actual PATH, appends to new ones.

This can be appreciated here:

```R
reticulate::use_condaenv("test2")
reticulate::use_condaenv("test2")
Sys.getenv("PATH")
[1] "/home/pipe/.local/share/r-miniconda/condabin:/home/pipe/.local/share/r-miniconda/bin:/home/pipe/.local/share/r-miniconda/condabin:/home/pipe/.local/share/r-miniconda/bin:/home/pipe/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/17/bin"
```

The right PATH should have only one path to conda base env, and the bin conda file, but they accumulate.

Thx!
