### ISSUE TITLE
Function to know if miniconda is installed

### ISSUE THREAD

**Issue by latot** [rstudio/reticulate#1579]
Hi, actually we can create a cond env, but this happens:

1. If miniconda is not installed, create a conda env will fails because of it
2. If we try to install miniconda, and miniconda is installed will send error and request to use ```force = TRUE``` to overwrite the installation which is not great.

Be able to know if is installed or not helps to install only when does not exists.

**Comment by t-kalinowski** [comment]
These days we gently encourage R users to prefer using virtual environments instead of conda environments, if they are able, due to binary incompatibilities.

If you want to check if a `conda` binary is "findable" by reticulate, you can run:
```r
tryCatch(file.exists(reticulate::conda_binary()), error = function(e) FALSE)
```
