### ISSUE TITLE
how to exit (r-reticulate) environment

### ISSUE THREAD

**Issue by r-scotti** [rstudio/reticulate#1580]
Hello.
Having finished working with Python, I would like to get back to regular R session.
Currently, clicking on the 'Terminal' tab, just after opening RStudio, I see the following:

> (r-reticulate) roberto@latitude-rs:~/Documents/Rwork/AdF_steAnalysis$ 
> [Process completed]
> [Exit code: 129]

I can close the terminal and start a new terminal but the (r-reticulate) prefix remains.
The `reticulate::py_config()` command returns following lines:

> python:         /home/roberto/.virtualenvs/r-reticulate/bin/python
> libpython:      /usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.so
> pythonhome:     /home/roberto/.virtualenvs/r-reticulate:/home/roberto/.virtualenvs/r-reticulate
> version:        3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0]
> numpy:          /home/roberto/.virtualenvs/r-reticulate/lib/python3.8/site-packages/numpy
> numpy_version:  1.24.4

How do you exit the  (r-reticulate) environment?
Many thanks, rs

**Comment by t-kalinowski** [comment]
This is an RStudio IDE setting. You can disable by unchecking the option at: Tools -> 'Global Options' -> Terminal -> 'Enable Python integration'

**Comment by r-scotti** [comment]
Many thanks, just couldn't find it.
