### ISSUE TITLE
Add optional `--override-channels` to all `conda_*` functions that accept `channel=`

### ISSUE THREAD

**Issue by LTLA** [rstudio/reticulate#1583]
When setting up environments via [**basilisk**](https://github.com/Bioconductor/basilisk), I would like to force `conda_create()` and `conda_install()` to only use the channels specified in `channel=`, without any interference from the user's `.condarc`. Some digging suggests that this can be done by setting the `--override-channels` flag in the `conda install/create` calls:

```
  --override-channels   Do not search default or .condarc channels. Requires --channel.
```

Can we have an option in `conda_create()` and `conda_install()` to add this flag in the corresponding system calls to `conda`? This is important to ensure compliance with Anaconda's ToS in a commercial environment, otherwise a user might inadvertently try to pull down packages from the non-free default channels if they have an old `.condarc` file lying around.

I can put together a PR if this is of interest. Seems simple enough, e.g., `restrict_channel = TRUE` would enable the flag.

**Comment by LTLA** [comment]
> A PR would be welcome. I'm guessing you're thinking to make the default `getOption("reticulate.conda.restrict_channels", FALSE)`, so that admins can set it?

Oh. Actually, I was thinking of just providing an extra set of arguments to `conda_create()` and `conda_install()`. This would allow **basilisk** to directly pass `--override-channels` for its `conda_*` calls without interfering with other applications. 

A global option isn't a bad idea and might be useful for our R system admins. But for more general usage in the community, I wouldn't want to impose a global option on all uses of **reticulate** just so that **basilisk** gets consistent builds.

If we had to do globals, I suppose **basilisk** could set the global options before the `conda_*` call, and then unset it afterwards. But that's a little bit awkward compared to just directly passing in the relevant arguments.

> I wonder if it makes sense to make this general purpose / future-proof by allowing usage like

I was hoping you might say that, because I was thinking pretty much along the same lines.

> Have you given any thought to having basilisk manage virtual environments?

Yes, and in fact, the earliest versions of **basilisk** did use `virtualenv` (or `venv`, I forgot which one). But I ended up switching to `conda` as it was easier to get the exact version of Python that was needed. **basilisk** client packages can provision environments involving a variety of Python versions - in the most extreme case, [**crisprScore**](https://github.com/crisprverse/crisprScore) uses both [Python 2 and 3](https://github.com/crisprVerse/crisprScore/blob/devel/R/basilisk.R) environments - and it was too hard to manually install each requested version of Python from the official sources. Windows was particularly difficult; I don't remember the details but I think I lost the fight against the installation wizard.

As for the binary incompatibilities - we have this somewhat under control with a rather crazy fallback system, discussion at Bioconductor/basilisk#20. Not the most elegant solution but you gotta do what you gotta do.

**Comment by t-kalinowski** [comment]
Re venv: thanks for the context. Please do take another look at `reticulate::install_python()`--- as far as I know, today, it works reliably in a variety of contexts for _most_ Python versions, including Windows. (That said, I don't think it will succeed with a request for Python 2 today).

**Comment by LTLA** [comment]
In fact, to provide even more context: at the start, **basilisk** was _also_ installing the its own version of Python from source on Linux and Mac to provide a consistent environment for virtualenv construction. But in the end, I wasn't confident that I could debug Python install failures on other people's machines; `conda` was just a safer choice, as it did most of the work and if it failed I could just pass the buck onto the `conda` installer. 

I don't think I considered `install_python()` at the time, but had I known, perhaps I would have decided differently. Nowadays, it's probably too disruptive to change it, barring a spectacular condapocalypse that forces us to do so. 

Oh well.
