### ISSUE TITLE
Conversion scope does not work in `py_to_r.pandas.core.frame.DataFrame`

### ISSUE THREAD

**Issue by rcannood** [rstudio/reticulate#1591]
With reticulate 1.36.0, [`py_to_r.pandas.core.frame.DataFrame`](https://github.com/rstudio/reticulate/blob/v1.36.0/R/conversion.R#L269) seems to no longer listen to its conversion scope.

This becomes an issue when using the `anndata` R package, which defines a [`py_to_r.pandas.core.indexes.base.Index`](https://github.com/dynverse/anndata/blob/d7687b962011bdf7fcbb1048ed29893e28f6e1bf/R/reticulate_conversions.R#L61) function. As such, a round trip conversion from data.frame to a pandas DataFrame no longer works with reticulate 1.36, whereas this did use to work with reticulate 1.35.

## Minimum reproducible example

```r
# check out reticulate origin/main
devtools::load_all(".")

df <- data.frame(
  row.names = c("s1", "s2"),
  group = c("a", "b")
)
py_to_r(r_to_py(df))
#    group
# s1     a
# s2     b

library(anndata)

py_to_r(r_to_py(df))
# Error: Expected a python object, received a character
```

## Error does not occur with Reticulate v1.35

```r
# check out reticulate v1.35.0
devtools::load_all(".")

df <- data.frame(
  row.names = c("s1", "s2"),
  group = c("a", "b")
)
py_to_r(r_to_py(df))
#    group
# s1     a
# s2     b

library(anndata)

py_to_r(r_to_py(df)) # works as intended
#    group
# s1     a
# s2     b
```

## Proposed solution

This issue is related to dynverse/anndata#28. I _could_ implement a fix in `anndata` by removing the `anndata::py_to_r.pandas.core.indexes.base.Index` function. However, I feel like `reticulate::py_to_r.pandas.core.frame.DataFrame` should not be affected by the existence of the anndata py_to_r function, or am I mistaken?

Thanks for your input!

Kind regards,
Robrecht

**Comment by t-kalinowski** [comment]
Thanks for reporting! I was able to reproduce, and a fix is in main now.

**Comment by rcannood** [comment]
Thanks for the amazingly quick response @t-kalinowski !

Given that reticulate 1.36 was only just released, do you have any idea when do you think we could expect this fix to be released on CRAN?

**Comment by t-kalinowski** [comment]
The plan is to another CRAN release approximately 1 month from now.

**Comment by rcannood** [comment]
Given that this bug completely breaks anndata, would it be possible to create bug fix release sooner than that? :grimacing:

**Comment by t-kalinowski** [comment]
I can submit next week, we'll see if CRAN complains.

**Comment by eddelbuettel** [comment]
It's all good.  You twisted my arm to get RcppArmadillo out 'outside of schedule' now you offering the same to @rcannood and anndata.  Karma comes around and goes around, and we keep the wheels on spinning ...

**Comment by t-kalinowski** [comment]
On CRAN now

**Comment by rcannood** [comment]
🎊 Fantastic! You're a hero!
