### ISSUE TITLE
Mapping string/unicode dtypes in numpy arrays

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/reticulate#16]
Not trying to bring up https://github.com/rstudio/reticulate/issues/2 again, but how much work would it be to support just character arrays (not arbitrary python objects)? I'm trying to wrap https://github.com/ratal/mdfreader to work with industrial sensor log data and sometimes strings come up.

**Comment by jjallaire** [comment]
Is the data type you are looking for here basically a NumPy string array?

**Comment by kevinykuo** [comment]
@jjallaire correct.

**Comment by jjallaire** [comment]
Okay, in your experience do pandas data frames often use `dtype=object` (for variable length strings) or do they more typically stick to a fixed string size?

**Comment by kevinykuo** [comment]
Unfortunately I don't work with Python enough to opine on that, although from browsing SO it seems to often be the case. Are we thinking about upcasting all string types to `object` or finding some reasonable superset of string types?

**Comment by jjallaire** [comment]
I think `string` and `unicode` would be R character vectors, and `object` would be a character vector if all of the elements are strings (otherwise just a list of objects)

**Comment by kevinykuo** [comment]
Sounds good!

**Comment by jjallaire** [comment]
This should be resolved by this commit: https://github.com/rstudio/reticulate/commit/3868a8dc538297bc429375f67f6a5291cb12e0e6

**Comment by kevinykuo** [comment]
@jjallaire this crashes:
```
np <- import("numpy")
np$array(c("a", "b"), dtype = "S256")
```

**Comment by kevinykuo** [comment]
Stack trace:

```
* thread #1: tid = 31749, 0x00007ffff07d3419 libpython3.6m.so`PyBytes_AsStringAndSize(obj=0x0000000000000000, s=0x00007fffffffacd0, len=0x00007fffffffacd8) + 9 at bytesobject.c:1289, name = 'R', stop reason = signal SIGSEGV: invalid address (fault address: 0x8)
    frame #0: 0x00007ffff07d3419 libpython3.6m.so`PyBytes_AsStringAndSize(obj=0x0000000000000000, s=0x00007fffffffacd0, len=0x00007fffffffacd8) + 9 at bytesobject.c:1289

```

**Comment by jjallaire** [comment]
Should be fixed now, thanks for the report!
