### ISSUE TITLE
Need to reinstall reticulate whenever I want to access arcpy

### ISSUE THREAD

**Issue by andrew-caudillo** [rstudio/reticulate#1618]
Hello,
When I try to access arcpy (using the python.exe from ArcPro), I receive an error. Here is my workflow:
```r
library(reticulate)
reticulate::use_python('C://ArcGIS//Pro//bin//Python//envs//arcgispro-py3/python.exe',required = T) #set python
Sys.setenv(PATH = paste("C://ArcGIS//Pro/bin", Sys.getenv("PATH"), sep = ";")) #manually ensure variables are loaded correctly
py_config() #check to see if python environment exists
sa=reticulate::import("arcpy.sa") #try to load spatial analyst
#receive error: Error in py_module_import(module, convert = convert) : ImportError: DLL load failed while importing #_arcgisscripting: The specified procedure could not be found.
```
But, if I restart R, reinstall reticulate, and follow the same steps, "sa" runs succesfully.
```r
install.packages('reticulate')
library(reticulate)
reticulate::use_python('C://ArcGIS//Pro//bin//Python//envs//arcgispro-py3/python.exe',required = T) #set python
Sys.setenv(PATH = paste("C://ArcGIS//Pro/bin", Sys.getenv("PATH"), sep = ";")) #manually ensure variables are loaded correctly
py_config() #check to see if python environment exists
sa=reticulate::import("arcpy.sa") #succesfully import acrpy.sa
```

Is this something that has happened before with anyone? Both my colleague and I are experiencing this issue, so it is not isolated to my machine. We both have to restart R and reinstall reticulate every time we need to use it. We both have Windows machines.

Thank you,

**Comment by t-kalinowski** [comment]
Thanks for opening. I haven't seen this error before. 

I would be very surprised if re-installing is really necessary. My best guess is that reinstalling is forcing some dll's to be reloaded, which is fixing the error.

If you set PATH or any other envvar after initializing Python, the Python session will not see those env vars. You would need to independently also set in Python with `import("os")$environ$update(...)`, or call R's `Sys.setenv()` before initializing Python.

Does swapping the order of your initialization commands fix the issue?

**Comment by andrew-caudillo** [comment]
@t-kalinowski ,
Thank you for getting back.

If I understand correctly, you are saying to do this:

reticulate::use_python('C://ArcGIS//Pro//bin//Python//envs//arcgispro-py3/python.exe',required = T) #set python
Sys.setenv(PATH = paste("C://ArcGIS//Pro/bin", Sys.getenv("PATH"), sep = ";")) #manually ensure variables are loaded correctly
library(reticulate)
sa=reticulate::import("arcpy.sa") #try to load spatial analyst


if that is the case, then no, the issue persists after rearranging my order of operations.

**Comment by t-kalinowski** [comment]
I'm sugesting something different actually:

```r
# make sure you're in a fresh R session.
# in RStudio IDE: rstudioapi::restartSession(clean = TRUE)

library(reticulate)

# set env vars before initializing Python
Sys.setenv(PATH = sprintf("%s;%s", normalizePath("C:/ArcGIS/Pro/bin"), Sys.getenv("PATH"))

# initialize Python
use_python('C:/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/python.exe')

# Confirm the correct Python was initialized
py_config() 

# import desired module
sa <- reticulate::import("arcpy.sa")
```

**Comment by andrew-caudillo** [comment]
@t-kalinowski thank you for the clarification.

The order of operations that you have written worked for me-- there was no error.  I did not know about the order of operations for reticulate.

I appreciate your quick response on this matter!

**Comment by andrew-caudillo** [comment]
hi @t-kalinowski ,
I am encountering this same issue again, even when following your order of operations. If I reinstall reticulate, it fixes the issue.

**Comment by andrew-caudillo** [comment]
I'm not sure how I should be diagnosing these outputs, but they are all valid filepaths.

**Comment by t-kalinowski** [comment]
Can you provide them here? 
Do the values change between when things work and when they don't? 
Where is the missing `_arcgisscripting` actually located?

**Comment by t-kalinowski** [comment]
Note that you can also insert print statements directly in the python module. E.g., if you see that a Python statement like `import _arcgisscripting` is raising an exception, you can navigate to that Python file, and edit it in place by inserting above that line something like:

```python
import sys; print(f"{sys.path=}")
import _arcgisscripting
```

**Comment by andrew-caudillo** [comment]
arcgisscripting is located within the ArcGIS Pro folders. 

Here is an example of what outputs I am getting, specifically from the first import() line you suggested for diagnosing. It seems like it is bringing up a lot of file paths that use python?

C:/ArcGIS/Pro/bin/Python/envs/arcgispro-py3\\Library\\bin;C:\\ArcGIS\\Pro\\bin;C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1\\Library\\bin;C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3;C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Library\\mingw-w64\\bin;C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Library\\usr\\bin;C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Library\\bin;C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Scripts;C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\bin;C:\\Users\\ANDREW~1.BUG\\AppData\\Local\\Temp\\_MEI102962\\pywin32_system32;C:\\ArcGIS\\Pro\\bin\\Python;C:\\ArcGIS\\Pro\\bin\\Python\\Library\\mingw-w64\\bin;C:\\ArcGIS\\Pro\\bin\\Python\\Library\\usr\\bin;C:\\ArcGIS\\Pro\\bin\\Python\\Library\\bin;C:\\ArcGIS\\Pro\\bin\\Python\\Scripts;C:\\ArcGIS\\Pro\\bin\\Python\\bin;C:\\ArcGIS\\Pro\\bin\\Python\\condabin;C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\condabin;C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\Scripts;C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\Library\\bin;c:\\rtools43\\x86_64-w64-mingw32.static.posix\\bin;c:\\rtools43\\usr\\bin;C:\\Program Files\\R\\R-4.3.2\\bin\\x64;C:\\Program Files\\Microsoft MPI\\Bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Amazon\\AWSCLIV2;C:\\Program Files\\dotnet;C:\\GDAL;C:\\Program Files\\GDAL;C:\\Program Files\\TauDEM\\TauDEM5Exe;C:\\Program Files\\WindowsPowerShell\\Scripts;C:\\Users\\foo\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\foo\\.dotnet\\tools;C:\\Program Files\\RStudio\\resources\\app\\bin\\quarto\\bin;C:\\Program Files\\RStudio\\resources\\app\\bin\\postback;C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1;C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1\\Scripts

**Comment by andrew-caudillo** [comment]
if it helps diagnose any issues, this is the line that actually caused my script to fail, according to reticulate.
py_module_import(module, convert = convert)

**Comment by andrew-caudillo** [comment]
Could the issue stem from how python was installed? I did not install from python's website, as I have to use ESRI's version of python to use these modules/functions. I chose this version of python as my interpreter for my R project, as well.

**Comment by andrew-caudillo** [comment]
> arcgisscripting is located within the ArcGIS Pro folders.
> 
> Here is an example of what outputs I am getting, specifically from the first import() line you suggested for diagnosing. It seems like it is bringing up a lot of file paths that use python?
> 
> ```
> C:/ArcGIS/Pro/bin/Python/envs/arcgispro-py3\\Library\\bin;
> C:\\ArcGIS\\Pro\\bin;
> C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1\\Library\\bin;
> C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3;
> C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Library\\mingw-w64\\bin;
> C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Library\\usr\\bin;
> C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Library\\bin;
> C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Scripts;
> C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\bin;
> C:\\Users\\foo~1.BUG\\AppData\\Local\\Temp\\_MEI102962\\pywin32_system32;
> C:\\ArcGIS\\Pro\\bin\\Python;
> C:\\ArcGIS\\Pro\\bin\\Python\\Library\\mingw-w64\\bin;
> C:\\ArcGIS\\Pro\\bin\\Python\\Library\\usr\\bin;
> C:\\ArcGIS\\Pro\\bin\\Python\\Library\\bin;
> C:\\ArcGIS\\Pro\\bin\\Python\\Scripts;
> C:\\ArcGIS\\Pro\\bin\\Python\\bin;
> C:\\ArcGIS\\Pro\\bin\\Python\\condabin;
> C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\condabin;
> C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\Scripts;
> C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\Library\\bin;
> c:\\rtools43\\x86_64-w64-mingw32.static.posix\\bin;
> c:\\rtools43\\usr\\bin;
> C:\\Program Files\\R\\R-4.3.2\\bin\\x64;
> C:\\Program Files\\Microsoft MPI\\Bin;
> C:\\WINDOWS\\system32;
> C:\\WINDOWS;
> C:\\WINDOWS\\System32\\Wbem;
> C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;
> C:\\WINDOWS\\System32\\OpenSSH;
> C:\\Program Files\\Git\\cmd;
> C:\\Program Files\\Amazon\\AWSCLIV2;
> C:\\Program Files\\dotnet;
> C:\\GDAL;
> C:\\Program Files\\GDAL;
> C:\\Program Files\\TauDEM\\TauDEM5Exe;
> C:\\Program Files\\WindowsPowerShell\\Scripts;
> C:\\Users\\foo\\AppData\\Local\\Microsoft\\WindowsApps;
> C:\\Users\\foo\\.dotnet\\tools;
> C:\\Program Files\\RStudio\\resources\\app\\bin\\quarto\\bin;
> C:\\Program Files\\RStudio\\resources\\app\\bin\\postback;
> C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1;
> C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1\\Scripts
> ```
when I reinstall reticulate, the outputs are different. Most of the files live within the ArcGIS Pro folder.


 [1] ""                                                                                              
 [2] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3"                                             
 [3] "C:\\ArcGIS\\Pro\\Resources\\ArcPy"                                                             
 [4] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1\\python39.zip"                                    
 [5] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1\\DLLs"                                            
 [6] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1\\lib"                                             
 [7] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1"                                                  
 [8] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1\\lib\\site-packages"                              
 [9] "C:\\ArcGIS\\Pro\\bin"                                                                          
[10] "C:\\ArcGIS\\Pro\\Resources\\ArcToolbox\\Scripts"                                               
[11] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1\\lib\\site-packages\\Babel-2.11.0-py3.9.egg"      
[12] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1\\lib\\site-packages\\future-0.18.2-py3.9.egg"     
[13] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1\\lib\\site-packages\\pytz-2022.6-py3.9.egg"       
[14] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1\\lib\\site-packages\\pywin32security"             
[15] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\ARCGIS~1\\lib\\site-packages\\sympy-1.9-py3.9.egg"         
[16] "C:\\Users\\foo.foo\\AppData\\Local\\R\\win-library\\4.3\\reticulate\\python" 
[17] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\python39.zip"                               
[18] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\DLLs"                                       
[19] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\lib"                                        
[20] "C:\\Program Files\\RStudio\\resources\\app\\bin"                                               
[21] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3"                                             
[22] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\lib\\site-packages"                         
[23] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\lib\\site-packages\\Babel-2.11.0-py3.9.egg" 
[24] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\lib\\site-packages\\future-0.18.2-py3.9.egg"
[25] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\lib\\site-packages\\pytz-2022.6-py3.9.egg"  
[26] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\lib\\site-packages\\pywin32security"        
[27] "C:\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\lib\\site-packages\\sympy-1.9-py3.9.egg"
