### ISSUE TITLE
Corrupt dataframe when converting from pandas to R

### ISSUE THREAD

**Issue by squidgetx** [rstudio/reticulate#1620]
I can't seem to get basic conversion between pandas and R dataframes working. 

R:
```
library(reticulate)
source_python('python-test.py')
data_records()
```

python-test.py
```
import pandas

def data_records():
    records = [
        {'n': 1},
        {'n': 2}
    ]
    df = pandas.DataFrame.from_records(records)
    print(df)
    return df
```

Output (the first dataframe is from python, showing the pandas correct dataframe, second from R where parsing seems to have failed) 

```
   n
0  1
1  2
      n
1 [1 2]
2  <NA>
Warning message:
In format.data.frame(if (omit) x[seq_len(n0), , drop = FALSE] else x,  :
  corrupt data frame: columns will be truncated or padded with NAs
```

Outputs of 
py_config()
packageVersion('reticulate')
pandas.__version__
and utils::sessionInfo

```
python:         /Users/sylvan/.virtualenvs/r-reticulate/bin/python
libpython:      /Users/sylvan/.pyenv/versions/3.12.0/lib/libpython3.12.dylib
pythonhome:     /Users/sylvan/.virtualenvs/r-reticulate:/Users/sylvan/.virtualenvs/r-reticulate
version:        3.12.0 (main, Oct 14 2023, 15:31:43) [Clang 15.0.0 (clang-1500.0.40.1)]
numpy:          /Users/sylvan/.virtualenvs/r-reticulate/lib/python3.12/site-packages/numpy
numpy_version:  2.0.0

[1] "Reticulate version 1.37.0"
[1] "Pandas version 2.2.2"

R version 4.4.0 (2024-04-24)
Platform: aarch64-apple-darwin22.6.0
Running under: macOS Ventura 13.5

Matrix products: default
BLAS:   /opt/homebrew/Cellar/openblas/0.3.27/lib/libopenblasp-r0.3.27.dylib
LAPACK: /opt/homebrew/Cellar/r/4.4.0_1/lib/R/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] reticulate_1.37.0

loaded via a namespace (and not attached):
 [1] compiler_4.4.0  here_1.0.1      Matrix_1.7-0    rprojroot_2.0.4
 [5] cli_3.6.2       Rcpp_1.0.12     grid_4.4.0      jsonlite_1.8.8
 [9] rlang_1.1.3     png_0.1-8       lattice_0.22-6
```

**Comment by thefabnab** [comment]
I am also seeing something identical using reticulate v1.37.0.

**Comment by t-kalinowski** [comment]
Thanks for reporting, we'll need to do some work to update reticulate for NumPy 2.0. 

For you you can install the previous numpy and pandas versions:
```r
reticulate::py_install(c("pandas<2.2.2", "numpy<2.0"), ignore_installed = TRUE)
```

**Comment by exetico** [comment]
Oh, that's why I couldn't get all my things to work today, even after spending hours on debugging.
As I use conda, I forced numpy + pandas down in version, as recommended, and now everything works again.
```r
reticulate::conda_install(packages = c("pandas<2.2.2", "numpy<2.0"), envname = env_name, ignore_installed = TRUE, conda=conda, pip=TRUE)
```

**Comment by stdp95** [comment]
I am encountering an issue while trying to ensure I am using the latest version of numpy 2.0 with reticulate. Here are the steps I followed:

1. I ran install.packages("reticulate"), hoping it would download and install the latest version.
2. After the installation, I executed the following Python code in my R environment: py_run_string("import nevergrad") I am getting conversion error. 

Despite my efforts, it appears that Reticulate is not updated or correctly configured to support Numpy 2.0. Could you please provide guidance on how to resolve this issue and ensure that the latest version of Reticulate is correctly installed and used?
Going back to Numpy 1.26.3 fixed things for me, but I am looking for a more stabilized solution.

Thank you for your assistance.

**Comment by exetico** [comment]
@stdp95 If you check the history above your post, a fix has just been added to the main branch.

In other words, its just a matter of time, before the next release will be published, and you don't have to force numpy and pandas to a specific version 👍. But you'll have to either fetch the solution from the GitHub repo in R, or wait for the next main release.

With that said: _I'd personally have made the issue open, until a release has been made, but thats for another discussion._
