### ISSUE TITLE
Feature request: export `conda_run2`

### ISSUE THREAD

**Issue by dramanica** [rstudio/reticulate#1635]
`reticulate` provides, in principle, the tools to set up a conda environment that contains software other than python. Would you please consider exporting `conda_run2`, which can then be used as a convenient equivalent to `system2` for system calls to the conda environment? One could obviously resort to a `reticulate:::conda_run2()`, but it would be nicer to be able to work with an officially exported and documented function.

**Comment by t-kalinowski** [comment]
Sure, that seems fine.

Would you like to submit a PR documenting the function for export?

**Comment by dramanica** [comment]
@t-kalinowski Happy to do a PR. I would be inclined to bundle it together with the other `conda-tools` in the `roxygen` docs? it seems the natural place, but it will require adding a couple of params to the manpage (which already has a fair number). Are you happy with that approach? Or do you prefer if I create a standalone manpage for it?

**Comment by t-kalinowski** [comment]
Thank you! I don't have a strong preference. I'd probably document it in a stand-alone page, and make sure it's cross-linked with the other conda functions, with a `@family` tag and/or a `@seealso` tag.
