### ISSUE TITLE
This is not logical

### ISSUE THREAD

**Issue by khharut** [rstudio/reticulate#1643]
https://github.com/rstudio/reticulate/blame/d683b3bc6311c5ebee3504901f8201edb8319341/R/config.R#L469

I think having this type of environment variable hard-coded is not a easy to guess for standard user. Maybe it would be easier to have some function parameter that the user can have access. Please change this logic, otherwise it is really nightmare. Thank you.

**Comment by t-kalinowski** [comment]
Closing in favor of https://github.com/rstudio/reticulate/issues/1644
