### ISSUE TITLE
as.raw method for bytes

### ISSUE THREAD

**Issue by kurthornik** [rstudio/reticulate#1649]
Could you please add an as.raw() method for python.builtin.bytes?  (The as.character() one does not work in case of embedded NULs.)   From previous discussions, this could simply be

  as.raw.python.builtin.bytes <- function(x) import_builtins()$bytearray(x)

Thanks!
-k

**Comment by t-kalinowski** [comment]
The main branch now includes:

- An `as.raw()` method for `python.builtin.bytes`.
- The `as.character()` method for `python.builtin.bytes` now includes a `nul` argument.
- The `as.character()` method for `python.builtin.str` now includes a `nul` argument.

**Comment by kurthornik** [comment]
Great, thanks!
