### ISSUE TITLE
Invalid conda-meta/history path prioritized over configured conda binary

### ISSUE THREAD

**Issue by tl-hbk** [rstudio/reticulate#1654]
When calling `use_python` or `use_condaenv` even if you provide `conda=<path to binary>` the following code path still gets hit

```
use_python -> python_config -> python_munge_path -> get_python_conda_info -> python_info_condaenv_find
```

Some environments I have happened to be created using `python -m conda` which leads to the following being in the history file

```
# cmd: /tmp/conda/lib/python3.8/site-packages/conda/__main__.py create --yes --prefix /tmp/envs/foo --file /tmp/spec-file.txt
```

later calls to `conda_binary` use this bad value instead of whatever was provided to the original `conda` arg.  Could `get_python_conda_info` use `find_conda` first instead of looking through the history file?  That way the option `reticulate.conda_binary` or the environment variable `RETICULATE_CONDA` can be used even when the history file has a bad value.

```
    conda <- find_conda()
    if (is.null(conda)) {
        # not base env, parse conda-meta history to find the conda binary
        # that created it
        conda <- python_info_condaenv_find(root)
    }
```

**Comment by t-kalinowski** [comment]
This sounds reasonable. Would you like to submit a PR?

**Comment by tl-hbk** [comment]
@t-kalinowski I've opened the PR
