### ISSUE TITLE
arithmetic operators for Python objects

### ISSUE THREAD

**Issue by mkoohafkan** [rstudio/reticulate#170]
[Link to SO post](https://stackoverflow.com/questions/49056372/arcpy-map-algebra-from-reticulate)

I came across this issue trying to use the ArcGIS module `arcpy`, but I suspect there are a few other places where this could be an issue. Basically, arithmetic operators for Python objects don't work for their R counterparts unless they can be type converted. 

I was thinking one solution would be to use the S3 system to add methods to the arithmetic operators for the `python.builtin.object` class, which would call the corresponding arithmetic operator function from the `operator` module:

```
`+.default` = .Primitive('+')
`+.python.builtin.object` = function(e1, e2) {
  op = import("operator")
  op$add(e1, e2)
}
`+` = function (e1, e2) UseMethod('+')
```

But converting the R operators to S3 methods seems... drastic. A more moderated approach would be to define a set of Python operators e.g. `%py+%`, `%py-%`, etc. that would use the Python operators instead of the R primitives.

```
`%py+%` = function(e1, e2) {
  op = import("operator")
  op$add(e1, e2)
}
```

But I don't know how we could enforce order of operations with this strategy.

**Comment by jjallaire** [comment]
I don't think using S3 for these overloads is drastic at all. In fact that's what we already do for TensorFlow: https://github.com/rstudio/tensorflow/blob/master/R/generics.R#L78

One issue with S3 is that by default it's only going to dispatch on the first argument so you couldn't do mixed operations that mix e.g. Python integers and integer constants (I think there might be a way to do this with S4 but I'm not sure on the details).

**Comment by nfultz** [comment]
If you provide an `Ops` method, it can dispatch on either. This is what I did for a quick `hyperopt` wrapper, seems to work ok:

https://github.com/njnmco/hopticulate/blob/f7ecfee1fff34be75d4c2c80e7e9554029acf641/R/hopticulate.R#L26-L59

For  Python objects, I found it easier to call dunder methods directly instead of going through the ops package, but maybe that's not really necessary or desirable.

**Comment by dfalbel** [comment]
This has been fixed in https://github.com/rstudio/reticulate/pull/1363
