### ISSUE TITLE
Removal of py_to_r_wrapper breaks rstudio/keras

### ISSUE THREAD

**Issue by jefshe** [rstudio/reticulate#173]
Doing a fresh install of rstudio/keras via ```devtools::install_github``` now breaks as the reticulate package no longer exports the functions it relies on.

Looks like it is due to https://github.com/rstudio/reticulate/pull/113

Is this intentional?

**Comment by jjallaire** [comment]
It's not intentional it was an oversight. 

I've confirmed that PR #174 fixes this (@kevinushey will review and merge shortly)

**Comment by kevinushey** [comment]
Thanks for reporting and sorry for the breakage!
