### ISSUE TITLE
provide traceback for failed `py_run_string` calls?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/reticulate#184]
Suppose I have a Python file with the contents:

``` python
def foo: pass
```

If I try to import this file in an interactive Python session, I get a traceback:

```
>>> import oops.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "oops.py", line 1
    def foo: pass
           ^
SyntaxError: invalid syntax
```

On the other hand, `py_run_string()` only reports the exception text:

```
> reticulate::py_run_string("def foo: pass")
Error in py_run_string_impl(code, local, convert) : 
  SyntaxError: invalid syntax (<string>, line 1)
```

I think it would be useful for `py_run_string()` to provide the traceback for errors as well, or perhaps provide an API that provides the last Python error as a plain Python object.

**Comment by jjallaire** [comment]
I don't think we get a traceback with `py_run_string` (we might if we wrote it to temp file first though?).  Under the hood we call `PyRun_StringFlags` and when inspecting the error we get back (in `py_last_error()` there appears to be no traceback.

BTW you can access the last Python error which occurred by calling the reticulate `py_last_error()` function. In this case you can see that we didn't actually get a traceback.

**Comment by dfalbel** [comment]
This has been fixed in https://github.com/rstudio/reticulate/pull/1343
