### ISSUE TITLE
Minor Clarification in Calling Python from R article

### ISSUE THREAD

**Issue by notesofdabbler** [rstudio/reticulate#189]
The [Calling Python from R](https://rstudio.github.io/reticulate/articles/calling_python.html) has the following snippets

```
main <- import_main()

py <- import_builtins()
py$print('foo')

```
Further down there is the snippet
```
library(reticulate)

py_run_file("script.py")

py_run_string("x = 10")

# access the python main module via the 'py' object
py$x
```
It might be worth mentioning that this snippet works only when the previous snippet is not run. If the previous snippet is run were `py` is assigned from `import_builtins()`, the syntax to use is `main$x` instead of `py$x`

Also in arrays section, the following snippet gives an error
```
a <- np_array(c(1:8), dim = c(2,4), order = "C")
```

**Comment by jjallaire** [comment]
Thanks! Just updated to the docs to address both issues.
