### ISSUE TITLE
Use in Jupyter notebooks?

### ISSUE THREAD

**Issue by dfrankow** [rstudio/reticulate#19]
I'm trying to use reticulate in Jupyter notebooks. I'm new to both.

First, I don't seem to be able to set which python to use. 
Second, I don't seem to be able to capture print output.
Thoughts?

![image](https://cloud.githubusercontent.com/assets/34655/23579101/ca76b7e2-009a-11e7-9e31-df78a8bafa66.png)

**Comment by jjallaire** [comment]
The `use_python`, `use_condaenv`, etc. functions must be used prior to interacting with Python from R (as there can only be one Python interpreter loaded per process). In your example you load one version of Python then attempt to load another, this won't work.

In terms of capturing output, we're doing a standard re-direction of Python std streams (https://github.com/rstudio/reticulate/blob/master/inst/python/rpytools/output.py). My guess is that the way Jupyter handles output is somehow interfering with this.

**Comment by dfrankow** [comment]
Thanks for the quick response!

I have no concrete request, so I will close.

**Comment by dfrankow** [comment]
> In your example you load one version of Python then attempt to load another, this won't work.

That should throw an exception with an appropriate message.

**Comment by jjallaire** [comment]
I think it would be awkward to have this function throw an exception. As currently implemented it's an advisory function to oriented and prioritize the search for Python (i.e. you can actually have multiple calls to `use_python` and all will be tried). Many scripts could therefore include these calls and these scripts might source each other (leading to errors in the scripts that didn't run first).

**Comment by dfrankow** [comment]
What programmatic interface can I use to tell that the function is not performing its advertised side effect (of switching the python)?

**Comment by jjallaire** [comment]
Again, those are advisory functions (you can have multiple of them). They always perform their intended side effect (adding to a list of version locations to scan). In terms of figuring out which version you actually got, you can call py_config() and inspect the `python` member of the list to see what version is actually in use.

**Comment by dfrankow** [comment]
What if I want to run a particular version of python? How do I get that to happen?

**Comment by dfrankow** [comment]
Wait, sorry, I missed your advice (setting then executing), let me try it..

**Comment by dfrankow** [comment]
Works, thank you!
