### ISSUE TITLE
Failure to pick up correct venv version 

### ISSUE THREAD

**Issue by vspinu** [rstudio/reticulate#191]
I have two version of python 3.6 installed on my Ubuntu machine. One in default /usr/bin/ and /usr/lib/ and another compiled from source in `/usr/local/bin/` and `/usr/local/lib/`. The latter has precedence in PATH.

With 

```sh
$ mkvirtualenv -p python3.6 tmp36
$ workon tmp36
$ R
> library(reticulate)
> py_config()
python:         /usr/bin/python
libpython:      /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
pythonhome:     /usr:/usr
version:        2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
numpy:          /usr/lib/python2.7/dist-packages/numpy
numpy_version:  1.11.0

python versions found:
 /home/vspinu/.pyenvs/tmp36/bin/python
 /usr/bin/python
 /usr/bin/python3
 /usr/local/bin/python3
 /home/vspinu/.pyenvs/cv/bin/python
 /home/vspinu/.pyenvs/exp/bin/python
 /home/vspinu/.pyenvs/ml/bin/python
```

Looks like `reticulate` does find all correct versions, but skips the pyenv one and settles on `/usr/bin/python` which is the system default python2.7. 

When setting the version explicitly, paths are identified correctly:

```R
> Sys.setenv("RETICULATE_PYTHON" = "/home/vspinu/.pyenvs/tmp36/bin/python3.6")
> library(reticulate)
> py_config()
python:         /home/vspinu/.pyenvs/tmp36/bin/python3.6
libpython:      /usr/local/lib/libpython3.6m.so
pythonhome:     /usr/local:/usr/local
virtualenv:     /home/vspinu/.pyenvs/tmp36/bin/activate_this.py
version:        3.6.3 (default, Mar 20 2018, 15:29:10)  [GCC 6.2.0 20160901]
numpy:           [NOT FOUND]

NOTE: Python version was forced by RETICULATE_PYTHON
```

To make it even more confusing, I have an old environment lying around (ml) which results into the following error:

```R

> library(reticulate)
> py_config()
Error in py_run_string_impl(paste0("import sys; sys.path.append('", system.file("python",  :
  AttributeError: module 'enum' has no attribute 'IntFlag'
> sys <- import("sys")
Error in py_initialize(config$python, config$libpython, config$pythonhome,  :
  AttributeError: module 'enum' has no attribute 'IntFlag'
> py_discover_config()
python:         /home/vspinu/.pyenvs/ml/bin/python
libpython:      /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so
pythonhome:     /usr:/usr
virtualenv:     /home/vspinu/.pyenvs/ml/bin/activate_this.py
version:        3.6.3 (default, Mar 20 2018, 15:29:10)  [GCC 6.2.0 20160901]
numpy:          /home/vspinu/.pyenvs/ml/lib/python3.6/site-packages/numpy
numpy_version:  1.13.3

python versions found:
 /home/vspinu/.pyenvs/ml/bin/python
 /usr/bin/python
 /usr/bin/python3
 /usr/local/bin/python3
 /home/vspinu/.pyenvs/cv/bin/python
 /home/vspinu/.pyenvs/exp/bin/python
 /home/vspinu/.pyenvs/p36/bin/python
 /home/vspinu/.pyenvs/tmp36/bin/python
```

In this case the python is picked up correctly but the shared library is wrong (it should be `/usr/local/lib/python3.6m.so`). 

Any ideas?

**Comment by jjallaire** [comment]
If no version is explicitly specified, reticulate will prefer a Python environment with NumPy available to one where it's not available (since without NumPy we can't covert R matrices to anything in Python). You'll note that in your tmp36 environment it shows NumPy as not found.

You can get reticulate to see all of your virtual environments even without the `workon` command by setting the  `WORKON_HOME` environment variable to `~/.pyenvs` (see https://rstudio.github.io/reticulate/articles/python_packages.html#virtualenv-installation)

The error you are seeing is traditionally because of crosstalk between different versions of Python (e.g. there is a global `PYTHONPATH` environment variable defined somewhere pointing to a version of Python distinct from the one that is loaded). e.g. see https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

**Comment by vspinu** [comment]
> If no version is explicitly specified, reticulate will prefer a Python environment with NumPy available to one where it's not available (since without NumPy we can't covert R matrices to anything in Python). 

I see. Thanks! Though a warning that a version which has PATH priority was skipped would be generally helpful.

> You can get reticulate to see all of your virtual environments even without the workon command by setting the WORKON_HOME environment variable to ~/.pyenvs

That's nice, but `virtualenv_workon` would be a nice addition. I could put it in .Rprofile of a package without dealing with explicit paths.

> The error you are seeing is traditionally because of crosstalk between different versions of Python

I don't see this error in python proper, only when called from reticulate. These two lines 

```R
python:         /home/vspinu/.pyenvs/ml/bin/python
libpython:      /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so
```

should be

```R
python:         /home/vspinu/.pyenvs/ml/bin/python
libpython:      /usr/local/lib/libpython3.6m.so
```

It might be a messup on my side. Will debug `pm_detect_config` and will be back if I find something.

**Comment by vspinu** [comment]
Well, I tracked it down to `sysconfig.get_config_vars('LIBPL')` so it's indeed how virtenv configured it; not a reticulate issue. Couldn't find other way to fix this but by wiping the vend and re-installing everything from scratch. Thanks for all the input!
