### ISSUE TITLE
Pandas DataFrame and R data.frame translation

### ISSUE THREAD

**Issue by seandavi** [rstudio/reticulate#2]
Wonderful work so far!  Just dreaming of the future...

**Comment by jjallaire** [comment]
If Pandas data frames can be decomposed into NumPy arrays then it should be possible to do this without too much more invention.

**Comment by eddelbuettel** [comment]
Well ... when I once needed to get NumPy into R the only way to do was to wrap an external (C) library as part of [RcppCNPy](https://github.com/eddelbuettel/rcppcnpy).   Maybe there are better ways now, I'd be eager to learn about them either way.

**Comment by terrytangyuan** [comment]
@jjallaire `pandas.DataFrame.as_matrix` is the trick

**Comment by jjallaire** [comment]
As has been pointed out, right now this is possible by decomposing the R and/or Pandas data frame into vector / matrixes. I think this is all we will do for the foreseeable future, as fully handling data frames will involve dealing with character vectors, dates, list columns, etc. and end up being too large of a project.

**Comment by terrytangyuan** [comment]
Makes sense. The handling for those would be very hard to maintain.

**Comment by saurfang** [comment]
Feather / Apache Arrow being a data frame serialization framework that supports both R and Python could be useful here. https://github.com/wesm/feather

I took a stab. Any suggestions are welcomed. I have not extensively tested it yet. https://github.com/saurfang/reticulate.df

**Comment by jjallaire** [comment]
Yes, feather definitely has all of the bits required to do this sorted out. Our plan is to add data frame support to reticulate using the same techniques as feather (sharing code if possible), but not to require a full serialize/deserialize to disk to do the conversion.

**Comment by saurfang** [comment]
That's very exciting. Specifically, are you talking about converting pandas DataFrame to Apache Arrow format (or something similar) in a memory buffer, and reading that into R via Rcpp (to avoid disk serialization/compression and memory copy)? or would this be a more ambitious implementation of a data.frame backend that lives in external memory entirely?

Any rough timeline that you might be working and releasing this?

**Comment by jjallaire** [comment]
Hopefully by the end of this year.

**Comment by shearerp** [comment]
Did this end up working? I'm interested if the R-Python communication can be done with large dataframes without expensive ser/de

**Comment by jjallaire** [comment]
Yes, this is now available: https://rstudio.github.io/reticulate/articles/calling_python.html#data-frames

**Comment by shearerp** [comment]
Neat! Am I to understand that the discussion around arrays (no copies needed) also applies to dataframes?

**Comment by jjallaire** [comment]
No, Pandas data frames created from NumPy arrays automatically make copies of the arrays. So there "no copy" going from R vector to NumPy array but there is ultimately a copy made by Pandas.

**Comment by shearerp** [comment]
But that Pandas copy is memory-to-memory, so at least the disk is never involved?

**Comment by jjallaire** [comment]
Correct, these are all very fast memory to memory copies of contiguous vectors.

**Comment by TheXu** [comment]
> @jjallaire `pandas.DataFrame.as_matrix` is the trick

I found this function works for me

`
pd_df_to_r_df <- function(pandas_df){
  #' # Import python modules
  pd <- reticulate::import("pandas")
  np <- reticulate::import("numpy")
  Convert_dtype <- convert data type for select columns in pandas.dataframe
  #' # Convert Date Columns to Strings
  date_cols <- pandas_df$select_dtypes(include='datetime64')$columns$to_list()
  Convert_dtype(pandas_df, np$str, date_cols, inplace=TRUE)
  #' # Create r data.frame using to_numpy() method in Pandas
  column_names <- pandas_df$columns$to_list()
  #' This will take out names of data frames
  r_df <- pandas_df$to_numpy() %>% as.data.frame()
  names(r_df) <- column_names
  #' # Convert r data.frame date columns to datetime class
  if(is.null(date_cols)){
    r_df[, date_cols] <- lapply(r_df[, date_cols], lubridate::ymd_hms)
  }
  return(r_df)
}
`
