### ISSUE TITLE
Error: invalid version specification

### ISSUE THREAD

**Issue by BobbyTables42** [rstudio/reticulate#204]
Hello all,

Hopefully I am just being bone-headed here, but I cannot reticulate to function at all on my system;

System is running Fedora 27, Linux Kernel 4.15, and I primarily use the system default pyhon3 for my python needs.

Following the documentation, in my bash_profile I have set RETICULATE_PYTHON=/usr/bin/python3

To which I receive this upon using py_config(): "Error: invalid version specification ‘1.15.0.0+6462068’"

Removing the environment variable allows Rstudio to open, but then it has a different error message that it cannot find the shared library libpython2.7.so Now, my system has libpython2.7.so.1.0; I know I could just use a symlink here and see what happens, but, I'd rather not.

Lastly, removing the environment variable, I can load reticulate, use py_discover_config() and it lists python versions on the system as /usr/bin/python and /usr/bin/python3.

restarting the R session and attempting use_python("/usr/bin/python3", require = T) results in the same invalid version specification error as above as would be expected.

Regards,

Bobby

**Comment by BobbyTables42** [comment]
> Removing the environment variable allows Rstudio to open, but then it has a different error message that it cannot find the shared library libpython2.7.so Now, my system has libpython2.7.so.1.0; I know I could just use a symlink here and see what happens, but, I'd rather not.

Confirmed that sym-linking the library allows me to use reticulate with the system python 2.7 installation; still get the odd "Error: invalid version specification"  whenever I try to direct RStudio to use the system python 3.6. 

Any ideas on where this is erring out?

**Comment by jjallaire** [comment]
I think the problem lies with the version of Python that is being reported when we probe for it. The `+` within the version specification isn't expected and the use of the version to deduce the path to libpython is also not working.

What is the output of this command:

```r
system2("/usr/bin/python3", system.file("config/config.py", package = "reticulate"))
```

**Comment by hetong007** [comment]
Encountered the same problem on OS X. I tracked it down and it seems to be caused by `numpy`'s version.

```
> import('os')
Error: invalid version specification ‘1.15.0.0+7459’
```

```
> system2("/usr/bin/python", system.file("config/config.py", package = "reticulate"))
Version: 2.7.10 (default, Feb  7 2017, 00:08:15)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
VersionNumber: 2.7
LIBPL: /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config
LIBDIR: /System/Library/Frameworks/Python.framework/Versions/2.7/lib
PREFIX: /System/Library/Frameworks/Python.framework/Versions/2.7
EXEC_PREFIX: /System/Library/Frameworks/Python.framework/Versions/2.7
Architecture: 64bit
NumpyPath: /Library/Python/2.7/site-packages/numpy-1.15.0.dev0+c7459dd-py2.7-macosx-10.12-intel.egg/numpy
NumpyVersion: 1.15.0.dev0+c7459dd
```

**Comment by jjallaire** [comment]
Excellent! Let me see if I can write some code to work around that. Back with more soon.

**Comment by jjallaire** [comment]
I just made a commit that should more gracefully handle the dev NumPy version: https://github.com/rstudio/reticulate/commit/0b4609cd56d17eb3fb0023a85116f9ad9d871a9e

You can try again with:

```r
devtools::install_github("rstudio/reticulate")
```

**Comment by hetong007** [comment]
Now it works on my case.

**Comment by BobbyTables42** [comment]
I can also confirm this has fixed my issue; thanks for addressing this so quickly.
