### ISSUE TITLE
NPZ Error in py_ref_to_r(x)  

### ISSUE THREAD

**Issue by some-guy1** [rstudio/reticulate#209]
I am not really sure what information to give you:

```
filepath = paste('./dummy_npz/', onefile, sep="")
np <- import("numpy")
npz1 <- np$load(filepath)
npz1$f[["arr_0"]]

```

**Error:**

> Error in py_ref_to_r(x) : 
>   Conversion from numpy array type 20 is not supported
> 

Ok so I can't find any documentation on this via googling.  The python npz numpy file is a large multidimensional.  Any guidance on how to fix this?  Or other information I can provide?

R version 3.4.4
Reticulate 1.60

**Comment by jjallaire** [comment]
It looks like the data you are reading is of type NPY_VOID (which according to this is either a struct or an opaque blob of binary data: https://docs.scipy.org/doc/numpy-1.14.0/reference/c-api.dtype.html#c.NPY_VOID). There's no way for us to have an automatic conversion to R of this sort of data (as it's a custom data structure of some kind) so you'll need to get the data into a more standardized format before conversion.

**Comment by some-guy1** [comment]
Oh ok thanks!
