### ISSUE TITLE
Python commands not running with Ctrl + Enter in RStudio

### ISSUE THREAD

**Issue by mariobecerra** [rstudio/reticulate#212]
In [reticulate's webpage](https://rstudio.github.io/reticulate/articles/rstudio_ide.html) in the Line-by-Line Execution part it is mentioned:

> You can execute code from Python scripts line-by-line using the Run button (or Control+Enter) in the same way as you execute R code line-by-line. RStudio will automatically switch into reticulate’s `repl_python()` mode whenever you execute lines from a Python script

But when I try to do this, it doesn't run. I already updated to RStudio's latest version (1.1.442) and reticulate's latest version (1.6) and I still can't make it work.

**Comment by kevinushey** [comment]
Line-by-line execution requires the latest [daily builds](https://dailies.rstudio.com) (v1.2 branch) of RStudio, as stated at the top of the associated page you linked.

**Comment by mariobecerra** [comment]
Damn, how didn't I see that? This is embarrassing. Thanks a lot for the answer. Sorry for not reading carefully.

**Comment by amjiuzi** [comment]
rstudio Version 1.2.1091, @kevinushey 
```r
> reticulate::repl_python()
Python 3.6.4 (D:\Python\anaconda\python.exe)
Reticulate 1.10 REPL -- A Python interpreter in R.
>>> import pandas as pd
>>> import numpy as np
>>> s = pd.Series([1,3,5,np.nan,6,8,])
>>> print(s)
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
>>> quit
> dates = pd.date_range('20130101',periods=6)
Error in pd.date_range("20130101", periods = 6) : 
  could not find function "pd.date_range"
> print(dates)
Error in print(dates) : object 'dates' not found
```
i run python script bellow, it's ok
```r
reticulate::repl_python()
import pandas as pd
import numpy as np
s = pd.Series([1,3,5,np.nan,6,8,])
print(s)
```
but then when i run(ctrl+enter) thess:
```r
dates = pd.date_range('20130101',periods=6)
print(dates)
```
it reported the error on the top screen, the 'quit'  command occures and runs automatically

**Comment by kevinushey** [comment]
RStudio automatically switches back to R mode if you use Ctrl+Enter to execute a line of code from an R script (file ending in `.R` extension) -- this is done by telling the reticulate REPL to `quit` as you're seeing. Just to confirm, are you writing your Python code in a `.R` script or a separate `.py` script?

**Comment by amjiuzi** [comment]
got it.
i written py code in a .r script yesterday.
thank u 4 yr patience, ^_^ @kevinushey

**Comment by nishuai** [comment]
@kevinushey

**Comment by nishuai** [comment]
OK I see, Rstuido only gets aware when the file is opened, or the file extension gets changed. It only happens when shutting Rstudio without closing the scripting tabs and open Rstudio again. The solution is to change you .py script into .PY, or close the tab and open it again, to let Rstudio know you are tring to play with python. Hope it helps.

**Comment by nishuai** [comment]
@kevinushey I'm not able to reproduce that bug again, sorry for the troubling... it just happend to me for a while and now everything just gets back to normal ...
