### ISSUE TITLE
NameError problem using source_python()

### ISSUE THREAD

**Issue by demillan** [rstudio/reticulate#215]
I have the following py code:

`
import pandas as pd
from pandas.io.json import json_normalize

/* creation of data object using pymongo, json and gridfs packages*/

df = pd.concat((json_normalize(d) for d in data), axis = 0)
`
When I run it in Python (on a Windows VM) it works, but if I try to run it with reticulate, like:

`
use_python(python = "C:/Users/user/Anaconda3/python.exe", required = FALSE)

source_python("script.py")
`

I have the following error:

Error in py_run_file_impl(file, local, convert) :
  NameError: name 'json_normalize' is not defined

Detailed traceback:
  File "<string>", line 31, in <module>
  File "C:\...\ANACON~1\lib\site-packages\pandas\core\reshape\concat.py", line 206, in concat
    copy=copy)
  File "C:\...\ANACON~1\lib\site-packages\pandas\core\reshape\concat.py", line 236, in __init__
    objs = list(objs)
  File "<string>", line 31, in <genexpr>

Thanks for your help.

David.

PD: I've just test the same code with 'PythonInR' and it works.

`
library(data.table)
library(PythonInR)

pyConnect(pythonExePath = "C:/Users/user/Anaconda3/python.exe")

system.time(pyExecfile("script.py"))

dt   <- data.table(pyGet("pandas_df", autoTypecast = TRUE))

pyExit()
`

**Comment by jjallaire** [comment]
It's possible that you are using an older version of reticulate (as we fixed an issue with source_python in the last release). Try updating to v1.6 from CRAN.

Since I couldn't reproduce your original example (as the calls to pymongo, etc. were simply alluded to) I recreated this minimal reproducible example:

```python
import pandas as pd
from pandas.io.json import json_normalize
data = [{'id': 1, 'name': {'first': 'Coleen', 'last': 'Volk'}},
        {'name': {'given': 'Mose', 'family': 'Regner'}},
        {'id': 2, 'name': 'Faye Raker'}]
json_normalize(data)
```

`source_python()` is able to handle this without errors in the latest version of reticulate.

**Comment by JackXueIndiana** [comment]
I am new to reticulate. It seem import("os") works fine but source_python("c:\\myfolder\myscript.py") gives me an error:
 could not find function "source_python"
Why? Here is the code:

install.packages("reticulate")
library(reticulate)
os <- import("os")
os$listdir(".")
source_python("c:\\myfolder\myscript.py")
