### ISSUE TITLE
repl_python() keeps loading Python 2.7 despite Global Variable set in .Rprofile

### ISSUE THREAD

**Issue by dylanjm** [rstudio/reticulate#216]
So I have set a path in my project's .Rprofile to my python3 binary that I would like reticulate to automatically use.

`Sys.setenv(RETICULATE_PYTHON = "/usr/local/bin/python3")`

But when I load up the library and run `repl_python()` it opens up a Python 2.7 repl. Also, when I knit it doesn't use my python3 binary. 

If I set `use_python("/usr/local/bin/python3", required = TRUE)` in my .RMD it will work upon knitting but still everytime I try to open the REPL it opens the wrong version. Am I missing something?

**Comment by kevinushey** [comment]
This works for me in a plain R session:

```
> reticulate::py_config()
python:         /usr/local/bin/python3
libpython:      /usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin/libpython3.6.dylib
pythonhome:     /usr/local/opt/python/Frameworks/Python.framework/Versions/3.6:/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6
version:        3.6.5 (default, Mar 30 2018, 06:41:53)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
numpy:          /usr/local/lib/python3.6/site-packages/numpy
numpy_version:  1.14.2

NOTE: Python version was forced by RETICULATE_PYTHON
```

Is it possible you're loading `reticulate` or implicitly forcing the Python version before the `RETICULATE_PYTHON` environment variable is set?

Here's an example I tried to confirm the environment variable was being used as expected:

```
mkdir -p ~/scratch
cd ~/scratch
echo "Sys.setenv(RETICULATE_PYTHON = '/usr/local/bin/python3')" > .Rprofile
echo "reticulate::py_config()" > test.R
R -f test.R
```

**Comment by dylanjm** [comment]
I just ran the code and received an output exactly like your `py_config()`. So I'm thinking you may have a point. I'm still confused as to why it wouldn't work in a normal workflow setting. For instance, 

1. Fire up Rstudio w/ Current Project that has RETICULATE_PYTHON set. 
2. Create new .RMD file
3. Create R chunk and load `library(reticulate)`
4. Create Python chunk and attempt to send `print("Hello World")` to the console by pressing cmd-enter.
5. See that it started the Python 2.7 REPL
6. Run `use_python("/usr/local/bin/python3", required = TRUE)`.
7. Try running `print("hello world")` again.
8. Opens another Python 2.7 REPL

I'm not sure what I may be doing wrong in this case. Thanks for putting together this awesome package and how attentive you've been on the issues.

**Comment by kevinushey** [comment]
Before step 4 of your example, can you confirm that the `RETICULATE_PYTHON` environment has already been set? What if you call `reticulate::py_config()` in an R chunk before running the Python chunk? E.g. try adding this to your chunk:

```R
Sys.getenv("RETICULATE_PYTHON")
reticulate::py_config()
```

If that still reports Python 2.7, I think there must be some other code somewhere that's implicitly getting `reticulate` to load the wrong Python version -- I'll try to play around a bit more tomorrow to see if I can reproduce, though.

**Comment by harryprince** [comment]
Currently, reticulate does not integrate into Rstudio very well, I hope python can get more support in Rstudio. Global option panel need add a session to configure default python engine path and so on.

**Comment by jjallaire** [comment]
Note that the daily build of RStudio has quite a bit of support for reticulate, see https://rstudio.github.io/reticulate/articles/rstudio_ide.html

I think we'd hesitate to implement the global option panel for Python because this wouldn't be effective for non-RStudio sessions (e.g. R Markdown documents or execution of scripts from the shell). For this sort of thing we always encourage the use of .Rprofile so things work the same both within and an outside of RStudio.

As regards @dylanjm question, there is one Python process per R process (a `use_python()` after Python is already loaded is a no-op).

**Comment by dfrankow** [comment]
Can you just try with Rscript? Perhaps that has a more minimal version of initialization.

For example, I have the difficulty shown below on OS X (10.13.4). Although I don't mess with init (e.g., I have no .Rprofile file), and /usr/local/bin/python is in my path first, reticulate somehow picks out /usr/bin/python. The only way to override is to set RETICULATE_PYTHON in my .Rprofile.

```
$ which python
/usr/local/bin/python
$ Rscript -e 'Sys.which("python"); library(reticulate); sys <- reticulate::import("sys"); sys$executable;  reticulate::py_config()'
                 python 
"/usr/local/bin/python" 
[1] "/usr/bin/python"
python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Oct  6 2017, 22:29:07)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
numpy_version:  1.8.1
sys:            sys

python versions found: 
 /usr/local/bin/python
 /usr/bin/python
```

**Comment by milesaturpin** [comment]
I'm having a similar problem. The `use_python` method is working for me for setting up the python config to 3.6 for running in R code blocks, but when I run python in the python code blocks, it goes back to 2.7. I tried adding a .Rprofile file in my wd with the same line that OP had in his, and then `Sys.getenv("RETICULATE_PYTHON")` 
`reticulate::py_config()`
but when I did that it didn't switch to the right python even in the R blocks.

**Comment by jjallaire** [comment]
You are likely not running the daily build of RStudio, or alternatively are not running the latest version of knitr or reticulate from CRAN.

Documentation on IDE features for reticulate as well as instructions on how to download the daily build of RStudio can be found here: https://rstudio.github.io/reticulate/articles/rstudio_ide.html

**Comment by dfrankow** [comment]
I updated reticulate to 1.6 (latest CRAN), and knitr was already 1.20 (latest CRAN).

I still see reticulate picking out a python different from the one in my path:

```
$ Rscript -e 'Sys.which("python"); packageVersion("reticulate"); library(reticulate); sys <- reticulate::import("sys"); sys$executable;   packageVersion("reticulate"); reticulate::py_config()'
                          python 
"/Users/dan/.pyenv/shims/python" 
[1] ‘1.6’
Warning message:
package ‘reticulate’ was built under R version 3.4.4 
[1] "/usr/bin/python"
[1] ‘1.6’
python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Oct  6 2017, 22:29:07)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
numpy_version:  1.8.1
sys:            sys

python versions found: 
 /Users/dan/.pyenv/shims/python
 /usr/bin/python
 /usr/local/bin/python
```

I'm not going to try daily builds, because it's hard to get them installed into the docker setup where we use them.

It still works for me to force python version with PYTHON_RETICULATE in .Rprofile.

**Comment by jjallaire** [comment]
I'm not sure why it's not picking the version on your path. It *might* be because reticulate doesn't yet support the Python 3 variety of virtualenvs (which it looks like you might be using) because unlike Python 2 virtualenvs they don't offer a way of initializing via Python code (activate_this.py in Python v2).

**Comment by dfrankow** [comment]
Same problem without pyenv:

```
$ Rscript -e 'Sys.which("python"); packageVersion("reticulate"); library(reticulate); sys <- reticulate::import("sys"); sys$executable;   reticulate::py_config()'
                 python 
"/usr/local/bin/python" 
[1] ‘1.6’
Warning message:
package ‘reticulate’ was built under R version 3.4.4 
[1] "/usr/bin/python"
python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Oct  6 2017, 22:29:07)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
numpy_version:  1.8.1
sys:            sys

python versions found: 
 /usr/local/bin/python
 /usr/bin/python
```

It's like it's ignoring the path in favor of the system python.

It would be handy if there were an easy way to debug it.

**Comment by jjallaire** [comment]
Reticulate will prefer version of Python with numpy over ones without.
Perhaps the version on your path doesn’t have numpy?

**Comment by mgei** [comment]
I had the same problem. I tried to add .Rprofile in my working or project directory and restarting R but no. It only worked once I put the .Rprofile in my home directory. Then close RStudio altogether and open it again.

`
echo "Sys.setenv(RETICULATE_PYTHON = '~/anaconda3/envs/py35/bin/python')" > ~/.Rprofile
`

**Comment by rdauria** [comment]
I have python installed in a non default location on a linux system (/u/local/apps/python/2.7.13-shared/bin ). Even when I set the env var RETICULATE_PYTHON the correct version of python is picked up but not the location of its libraries (/u/local/apps/python/2.7.13-shared/lib). Accordingly I had to install on my $HOME/.local both pip and virtualenv (with the pip install pip --user --upgrade). Not only this is a bit wasteful, but creating a virtual environment is also very much wasteful in terms of space. Could one just install the needed packages in their $HOME/.local? 

Also, and more to the point I got the error below when installing umap-learn:

```
> library(reticulate)
> py_install('umap-learn', pip = T, pip_ignore_installed = T) # Ensure the latest version of UMAP is installed
Error in virtualenv_install(envname, packages, ...) :
  unused arguments (pip = T, pip_ignore_installed = T)
> py_install("louvain")
Creating virtual environment 'r-reticulate' ...
Using python: /u/local/apps/python/2.7.13-shared/bin/python2.7
```

Any idea of what is going on?

Thanks

**Comment by kevinushey** [comment]
The `pip` and `pip_ignore_installed` arguments are not accepted by `virtualenv_install()`; they're conda-specific.

You need to provide the environment you're trying to install in, e.g.

```r
py_install("umap-learn", envname = "myenv")
```

and most of these functions are tailored towards interacting with virtualenvs / condaenvs.

**Comment by Demetrio92** [comment]
confirming, that the issue is still present. @mgei answer works fine (make sure you adapt the path if needed)

**Comment by nagdevAmruthnath** [comment]
I had this issue. I cleared the environment and restarted R. Now it works.

**Comment by mdozmorov** [comment]
Installing numpy specifically for python3.7 (see [this comment](https://github.com/rstudio/reticulate/issues/216#issuecomment-382882462) above) worked. Had to use sudo to install:
````
python3.7 -m pip install --upgrade pip
python3.7 -m pip install numpy
````
Need to set variable explicitly:
````
library(reticulate)
Sys.setenv(RETICULATE_PYTHON = "/usr/local/bin/python3.7")
use_python("/usr/local/bin/python3.7", required = TRUE)
````
After that, `repl_python` opens the expected Python 3.7.2 prompt

**Comment by kevinushey** [comment]
FWIW you can use `pip install --user` to force `pip` to install your Python package into a separate user 'library' of packages, which is usually preferable to updating the system packages (and typically should not require `sudo`).
