### ISSUE TITLE
Standardized Python environment and installation workflow?

### ISSUE THREAD

**Issue by ijlyttle** [rstudio/reticulate#218]
I am putting together an R package that wraps a Python package, using reticulate to make the bridge; I have found the [package vignette](https://rstudio.github.io/reticulate/articles/package.html) to be invaluable.

As I show the package around, one of the challenges I am running into (among R users) is the installation on the Python side. I look with envy at `tensorflow::install_tensorflow()` and `keras::install_keras()`. I wonder if the reticulate package could, in time, offer a usethis-style template for package authors to create `foo::install_foo()`.

I confess I have no idea if installation procedures among Python packages are similar enough one-to-another to support such a template, but I thought I might ask. 

Having looked at the effort and know-how put into `tensorflow::install_tensorflow()`, I know that I cannot readily tackle such a thing myself. However, happy to pitch-in as needed!

**Comment by jjallaire** [comment]
In this last release of reticulate we added some `virtualenv_*` installation functions. Docs are here: https://rstudio.github.io/reticulate/reference/virtualenv-tools.html. This compliments the conda functions we already had: https://rstudio.github.io/reticulate/reference/conda-tools.html

This takes the guts of what we do in `install_tensorflow()` and makes it available, albeit in a much less "one" button form. I think what we might need is one level up of function that standardizes on an environment name (e.g. "r-reticulate") and encourages package authors to have their users install packages there. 

I think if we standardized on conda and made `conda_install` automatically create a conda environment as necessary then we could reduce the installation workflow to:

1) Download and install conda

2) `conda_install("r-reticulate", "pythonpkg")`

**Comment by ijlyttle** [comment]
That sounds great to me!

In that case, let me change the name of the issue to be more-descriptive of the general issue.

**Comment by jjallaire** [comment]
I've implemented that change and added some documentation here: https://rstudio.github.io/reticulate/articles/package.html#installing-python-dependencies

Let me know if this looks adequate.

**Comment by ijlyttle** [comment]
This looks super (>>adequate), thanks!
