### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) :    TypeError: float()

### ISSUE THREAD

**Issue by ronencozen** [rstudio/reticulate#220]
Hi,
I am trying to run the RandomForestRegressor from sklearn.ensemble within R stdio.
here in the code.

```
library(reticulate)
use_condaenv("base (root)")

sk <- import("sklearn.ensemble")
rf = sk$RandomForestRegressor(n_estimators = 500, criterion = "mse", random_state = 123)

train_features <- select(train, -c(throughtput))
train_labels <- select(train, throughtput)
rf.fit <- rf$fit(X=train_features, y=train_labels)
```

It produces the following error:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   TypeError: float() argument must be a string or a number, not 'dict'
> 
> Detailed traceback: 
>   File "C:\Users\ronen\ANACON~1\lib\site-packages\sklearn\ensemble\forest.py", line 247, in fit
>     X = check_array(X, accept_sparse="csc", dtype=DTYPE)
>   File "C:\Users\ronen\ANACON~1\lib\site-packages\sklearn\utils\validation.py", line 433, in check_array
>     array = np.array(array, dtype=dtype, order=order, copy=copy)

Here is the data types of  train_features:

> Classes ‘tbl_df’, ‘tbl’ and 'data.frame':200 obs. of  5 variables:
>  $ artifact        : Factor w/ 13 levels
>  $ business_analyst: Factor w/ 9 levels
>  $ developer       : Factor w/ 3 levels
>  $ process_category: Factor w/ 18 levels
>  $ s2e_duration    :Class 'difftime'

I wonder if you can help, based on this info.

**Comment by jjallaire** [comment]
You are passing a data frame into `fit` which is converted into a dictionary (named list of columns). Presumably the `fit` function is expecting a NumPy array/matrix? You may need to convert the data frame to a matrix first (e.g. with `data.matrix()`).

In general mapping Python APIs into R is straightforward but you do need to be aware of data types that don't "just work" and massage them as appropriate. It's hard for us to debug individual cases, this guide provides an overview of the various considerations: https://rstudio.github.io/reticulate/articles/calling_python.html

**Comment by ronencozen** [comment]
Thanks, understood!
