### ISSUE TITLE
RStudio crashes when after Error: C stack usage  17589482212892 is too close to the limit

### ISSUE THREAD

**Issue by dipterix** [rstudio/reticulate#221]
I ran the following code and RStudio crashed :/

```
require(reticulate)
threading = import('threading')
t = threading$Thread(target = function() print(1))
t$start()
```

**Comment by jjallaire** [comment]
You can't run R code on a background thread.

**Comment by dipterix** [comment]
Can I run python code in bg thread then? I mean if I have pure python code containing multi-thread.

**Comment by jjallaire** [comment]
You can run Python code on a background thread but not if it calls back into R.
