### ISSUE TITLE
reticulate imports python2 before python3

### ISSUE THREAD

**Issue by jeffwong-nflx** [rstudio/reticulate#224]
Hi,

I am developing a package `foo` which imports reticulate like this

```
#' Hello
#' @import reticulate
#' @export
myfunc = function() {
  import("mypackage")
  do stuff
}
```

When I use `devtools::load_all()` to test this package, I think reticulate is automatically being set up with python2, perhaps through detection of the roxygen @import reticulate. If I try to overwrite it using `use_python('/usr/local/bin/python3', required = TRUE)`, reticulate will still reference python2. However, if I start with a clean R session and source the function `myfunc` as a R script instead of as a package from devtools, I will be able to use python3. I suspect this is because sourcing it as an inline function does not trigger any kind of reticulate set up, and thus the python version doesn't get set yet.

The behavior I expected was

```
devtools::load_all()
use_python('/usr/local/bin/python3', required = TRUE)
myfunc() # will reference python 2, but should reference python3
```

**Comment by mkoohafkan** [comment]
use the `delay_load` flag in your `import` call. The documentation explains this as well.

**Comment by smilesun** [comment]
no. I have a lot of python paths. Now I get it, it is better to always only have one for reticulate I guess than with numpy installed.

**Comment by dfalbel** [comment]
We have heavily refactored python discovery order in reticulate v1.31. See the discovery rules and configuration options [here](https://rstudio.github.io/reticulate/articles/versions.html#order-of-discovery).
