### ISSUE TITLE
use_python still not working

### ISSUE THREAD

**Issue by sahil-kumar** [rstudio/reticulate#227]
I just did a clean install of OSX and completely wiped everything. From there, I reinstalled Homebrew, installed Python 3, then R and RStudio with the reticulate package. I am still unable to get the python version in use to switch from the default OSX installed Python to use Python 3 instead. After opening up a brand new R Markdown file, I ran the following:

```
library(reticulate)
use_python("/usr/local/bin/python3", required = T)
py_config()
```

with these results:

```
python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Oct  6 2017, 22:29:07)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
numpy_version:  1.8.1

python versions found: 
 /usr/local/bin/python3
 /usr/bin/python
```

Can anyone help?

**Comment by jjallaire** [comment]
reticulate will always prefer a version of Python that includes NumPy to one that doesn't. Does the version at /usr/local/bin/python3 have NumPy?

**Comment by sahil-kumar** [comment]
Yup. I forgot to mention that, sorry!

**Comment by smilesun** [comment]
@jjallaire , that means if we want to use `use_python` or other function to specify python path or virtual environment, we must install numpy to that directory first? Otherwise it won't work?

**Comment by jjallaire** [comment]
Yes, NumPy is always preferred (without that we can't convert matrices nor data frames between Python and R).

**Comment by wush978** [comment]
Dear all,

I try `reticulate` today and feel very frustrated.
I follow the vignettes of `Python Version Configuration` but both functions `use_python` and `use_virtualenv` do not work as expected.
Finally, I find this issue and make thing works.

Is it possible to raise an error if `use_python` or `use_virtualenv` if the numpy is not found? 
Then users will quickly know why `use_python` and `use_virtualenv` does not work and correct it accordingly.

This is just my two cents.

**Comment by kevinushey** [comment]
You likely want `reticulate::use_python("/path/to/python", required = TRUE)`.

**Comment by ras44** [comment]
Thumbs up for @wush978's comment.  While the numpy preference is clearly essential, some feedback via a warning/error to the user would smooth the use of a virtualenv.  In the event that a user has set up a clean virtualenv without numpy installed and then attempts to use that virtualenv, reticulate might want to warn with "numpy not found in virtualenv, loading abc instead" or simply error with "numpy not found in virtualenv abc, please ensure numpy is installed in abc".

Please let me know if I can submit a PR that addresses this.

**Comment by ras44** [comment]
Requirements in addition to the numpy item mentioned above:
- python must be compiled with `--enable-shared` (as mentioned in the [docs](https://rstudio.github.io/reticulate/articles/versions.html))
- depending on where you have installed pythong, set `Sys.setenv(LD_LIBRARY_PATH = "<PATH_TO_PYTHON_INSTALL>/lib")` so that R can find the shared libraries (otherwise error is: "error while loading shared libraries")

**Comment by RobertMyles** [comment]
@wush978  Mine worked well on a Mac by adding:

```
RETICULATE_PYTHON="/usr/local/bin/python3"
```

to my .Renviron file. As soon as you restart R, it will find the correct version (I'm assuming you're using Python3).

**Comment by dfalbel** [comment]
We have heavily refactored python discovery order in reticulate v1.31. See the discovery rules and configuration options [here](https://rstudio.github.io/reticulate/articles/versions.html#order-of-discovery).
