### ISSUE TITLE
`reticulate::import()` imports module. notebook python chunk unable to import same module

### ISSUE THREAD

**Issue by AdamSpannbauer** [rstudio/reticulate#228]
I am trying out reticulate notebook functionality.  In the notebook I am able to import a python module in an R chunk with `import('wordcloud')`.  I then set the next chunk to be python and attempt to load the same module and receive an error.

My notebook input/output shown below.  I import `pandas` just to show the error is unique to the `wordcloud` package.

    ```{r}
    library(reticulate)
    use_python('/usr/local/bin/python3', required = TRUE)
    py_config()
    ```

   

>       python:         /usr/local/bin/python3
>       libpython:      /usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin/libpython3.6.dylib
>       pythonhome:     /usr/local/opt/python/Frameworks/Python.framework/Versions/3.6:/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6
>       version:        3.6.5 (default, Apr  2 2018, 18:15:50)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
>       numpy:          /usr/local/lib/python3.6/site-packages/numpy
>       numpy_version:  1.14.2
> 
>      NOTE: Python version was forced by use_python function

    ```{r}
    import('pandas', as='pd')
    import('wordcloud')
    ```

>     Module(pandas)
>     Module(wordcloud)

    ```{python}
    import pandas as pd
    import wordcloud
    ```
>       Traceback (most recent call last):
>         File "/var/folders/mm/8pz7_cjs569_b898204nq2tm0000gn/T/RtmptAyt3r/chunk-code-63b1405fd74.txt", line 2, in <module>
>           import wordcloud
>       ImportError: No module named wordcloud

**Comment by AdamSpannbauer** [comment]
Also of note.  This issue seemed unique to the `wordcloud` module.  In the same python chunk that originally produced the error I was able to load other 3rd party modules including: `matplotlib`, `seaborn`, & `spacy`.

**Comment by jjallaire** [comment]
My guess is that you are using a version of RStudio that doesn't yet support reticulated R notebooks (so the Python chunk is actually running in a separate process). You will need the daily build of RStudio for this, see: https://rstudio.github.io/reticulate/articles/rstudio_ide.html

**Comment by AdamSpannbauer** [comment]
I hadn't seen that piece of the documentation, and updating to a daily build of RStudio did indeed fix the issue.   Thanks @jjallaire !
