### ISSUE TITLE
source_python() not using global package imports

### ISSUE THREAD

**Issue by pagepiccinini** [rstudio/reticulate#229]
Hello!

I'm trying to run `use_python()` in an `Rmd` document and I've hit the following error. Say I have a python script called `analyze_data.py`  which is:

```
import pandas as pd

def create_data():
    d = {'col1': [1, 2], 'col2': [3, 4]}
    return pd.DataFrame(data=d)

data = create_data()
```
The following fails in the `Rmd` document for the "setup" R chunk:

```
library(reticulate)

source_python("analyze_data.py", convert = FALSE)
```

With the error `NameError: global name 'pd' is not defined`.

However, if I import `pandas` in the function it works. Updated `analyze_data.py` as:

```
def create_data():
    import pandas as pd
    d = {'col1': [1, 2], 'col2': [3, 4]}
    return pd.DataFrame(data=d)

data = create_data()

```

Any idea why?

cc @bcipolli

**Comment by jjallaire** [comment]
This is an artifact of the way we were running the Python code but definitely should work as you expect. I just checked in a change which should resolve this issue.

**Comment by pagepiccinini** [comment]
Thanks! Just tried it and it works perfectly.

**Comment by JackXueIndiana** [comment]
I am new to reticulate. It seem import("os") works fine but source_python("c:\myfolder\myscript.py") gives me anI am new to reticulate. It seem import("os") works fine but source_python("c:\\myfolder\\myscript.py") gives me an error:
**could not find function "source_python"**
Why? Here is the code:
install.packages("reticulate")
library(reticulate)
os <- import("os")
os$listdir(".")
source_python("c:\\myfolder\\myscript.py")
 error:
could not find function "source_python"
Why? Here is the code:
install.packages("reticulate")
library(reticulate)
os <- import("os")
os$listdir(".")
source_python("c:\myfolder\myscript.py")
