### ISSUE TITLE
Support for Python Nix environments

### ISSUE THREAD

**Issue by alexvorobiev** [rstudio/reticulate#23]
Would it be possible to add support for Nix environments? Unlike conda, Nix provides a way to specify the dependencies all the way down to libc in a consistent reproducible manner. On an older system like RHEL-6.x which is still widely used in enterprise environments conda packages break fairly often because of some system shared library being too old. Nix was a lifesaver for us when we needed complex packages like Tensorflow or Keras.

The official documentation:
http://python-on-nix.readthedocs.io/en/latest/index.html
in particular
http://python-on-nix.readthedocs.io/en/latest/tutorial.html#declarative-environment-using-myenvfun
also 
http://datakurre.pandala.org/2015/10/nix-for-python-developers.html

The main site https://nixos.org/nix/

**Comment by jjallaire** [comment]
My guess is that you would be able to use a nix environment without problems so long as you were also running R within that environment (i.e. the reticulate package is just going to discover the correct Python on the PATH or via an explicitly specified Python w/ the RETICULATE_PYTHON environment variable).

**Comment by alexvorobiev** [comment]
Is that also a requirement for `use_condaenv`? I.e. R has to be installed using conda's R channel, correct? Our standard R installation is MS R Open on RHEL6 and we were unable to use it with Anaconda Python (rPython, etc.) because of the incompatibility between shared libraries. If you use  libpythonX.X.so like rPython, reticulate may have similar problem...

**Comment by jjallaire** [comment]
It's not a requirement for use_condaenv (we can just load the libpython
from within a conda environment). The incompatibility between MS R Open and
Anaconda Python is because both link to their own versions of MKL. So conda
environments work fine from CRAN R, but don't work from MS R Open due to
the MKL issue.
