### ISSUE TITLE
`delay_load` is effectively ignored  by `import_from_path()`

### ISSUE THREAD

**Issue by vqv** [rstudio/reticulate#233]
A `delay_load = TRUE` argument to `import_from_path()` fails to have an effect.  `import_from_path()` imports the Python `sys` module to append the given `path`. This has the side effect of initializing Python:
https://github.com/rstudio/reticulate/blob/7c6bc9bd10ef4c040a6f311a6edd2942405dd085/R/python.R#L112-L118
So when the subsequent call to `import()` is made with `delay_load = TRUE`, the logic in `import()` sees that Python has been initialized and ignores `delay_load = TRUE`:

https://github.com/rstudio/reticulate/blob/7c6bc9bd10ef4c040a6f311a6edd2942405dd085/R/python.R#L55-L56

**Comment by jjallaire** [comment]
Good catch! It looks to me like our only good option is to remove the `delay_load` parameter from `import_from_path()` as we can't get around interacting with `sys` here.

**Comment by jjallaire** [comment]
Removed `delay_load` here: https://github.com/rstudio/reticulate/commit/d4a6fb29181d63475b562385ead8dfcbea38b56b

**Comment by vqv** [comment]
I'm developing an R package that uses internal Python code (stored in `src/`) for importing a data structure created by an external Python module.  I could implement the entire conversion in R, but it's much more efficient to do the heavy lifting in Python before marshalling to R.  So I'll need to figure out a workaround to delay loading of my Python code.  It'd be nice if some general advice could be incorporated into the [Using reticulate in an R Package](https://rstudio.github.io/reticulate/articles/package.html) vignette.

**Comment by jjallaire** [comment]
It seems like what you really need to do is ensure that the external Python module you require for the import is discovered by reticulate. So you might do this:

1) Do an `import("foo", delay_load = TRUE)` of whatever Python module you need within your package `onLoad`.

2) Do the `import_from_path` for your internal utility functions on-demand (i.e. wait until the user calls a function that requires it).

**Comment by AlexandreRozier** [comment]
Hi ! I'm having the same problem as vqv, that is I'm trying to build an R package `my-pkg` which has some functions written in Python, and I'd like to be able to delay loading the python module until it gets called by the user (so that users without a Python installation can still use the pure-R part of `my-pkg`.

The python package lives in `inst/py/my_py_pkg`:

```
inst/
    my_py_pkg/
          my_py_module
          __init__.py
```

in `zzz.R` I have:
```# global reference (will be initialized in .onLoad)

sklearn <- NULL

.onLoad <- function(libname, pkgname) {
  # Load libs that my_py_pkg requires
  sklearn <<- reticulate::import("sklearn", delay_load = TRUE)
  ...
}
```

And in my testthat unit tests, calling this works:
```
my_fct_using_reticulate <- function(){
    foo = import_from_path("my_py_module", path = system.file("py", "my_py_pkg", package = packageName()))
    foo$some_py_fct(...)
}
```

But as soon as I'm installing my R package in a new project and calling `my_fct_using_reticulate`, this errors pops up:

`x ModuleNotFoundError: No module named 'models'`

Do you have any tips of how I could get this to work ? Seems like an `import_from_path` with a working `delay_load=TRUE` woud be great :)

**Comment by kevinushey** [comment]
Maybe I'm misunderstanding, but doesn't `my_fct_using_reticulate` require Python to be loaded? That is, you're ultimately loading and using the module within that function. If you need to use something from the module, then Python will need to be initialized.

**Comment by AlexandreRozier** [comment]
Let me simplify my issue: I am dealing with two types of users:
- user1 : Has no python support on his laptop, wishes to use `my_R_pkg` only for its R-based functions
- user2 : Has a working python install, wishes to use `my_R_pkg` for its R-based and Pythin-based functions

A great solution would be to do this:

in `my-R-pkg/my_py_pkg.py`
```
def foo():
   print('bar')
```

in `my-R-pkg/r/zzz.R`

```
sklearn <- NULL
my_py_pkg <- NULL

.onLoad <- function(libname, pkgname) {
  # Lazy loading of the dependencies of my_py_pkg
  sklearn <<- reticulate::import("sklearn", delay_load = TRUE)
  # Lazy loading of my_py_pkg
  my_py_pkg <<- reticulate::import_from_path("my_py_pkg", path = system.file("py", "models", package = packageName()))
}
```

That way, user1 can still use the library if he never calls a Python-requiring function :) 
However, this does not seem to work: 

>Error in py_module_import(module, convert = convert) : 
>ModuleNotFoundError: No module named 'my_py_pkg'

Thanks for your time and for this great library :+1:

**Comment by kevinushey** [comment]
Lazy-loading of Python modules from a specific path is now implemented in the development version of `reticulate` -- if you have a chance, please give it a spin and let me know if you run into any problems. Thanks!

**Comment by AlexandreRozier** [comment]
Great ! Could you provide me with a specific branch implementing the fix ? Seems there is no "dev" branch per se, just bugfixes :)

**Comment by kevinushey** [comment]
It's just implemented on master -- you can test it with:

```
remotes::install_github("rstudio/reticulate")
```

(make sure to restart R after installing the package)
