### ISSUE TITLE
Why is r/R not immediately initialized on the python side?

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/reticulate#235]
I have a use case where I want to:

1) Create a function on the R side, `foo()`.
2) Create a function in a python script that calls `r.foo()`, call it `py_caller()`.
3) In R, use `source_python()` to source that script to gain access to `py_caller()`.
4) In R, call `py$py_caller()`.

I promise there is good reason for this.

The problem is that `r` is not initialized on the python side until a repl is started up. Once I run `repl_python()` and then `quit()` I can access the `r` object (I can tell this is the case because I can see it pop up in `py$r` after I run the repl), but before that I cannot and the code fails with `NameError: name 'r' is not defined`.

It seems that the `repl_python()` calls `eng_python_synchronize_before(globalenv())` which pushes R/r over to the python side. Is there any version of this you could add to `initialize_python()` so that we have immediate access to R from the python side without starting up a repl first?

**Comment by DavisVaughan** [comment]
It's easy enough for me to fake it without you guys having to export anything, but I feel like initializing R immediately might be a useful thing to be doing.

```r
yoink <- function(package, symbol) {
  do.call(":::", list(package, symbol))
}

as_r_value <- function (x) {
    if (inherits(x, "python.builtin.object")) 
        reticulate::py_to_r(x)
    else x
}

# this is essentially eng_python_synchronize_before(globalenv())
export_r <- function(envir = getOption("reticulate.engine.environment")) {
    reticulate::py_run_string("class R(object): pass")
    main <- reticulate::import_main(convert = FALSE)
    R <- main$R
    if (is.null(envir)) {
        .knitEnv <- yoink("knitr", ".knitEnv")
        envir <- .knitEnv$knit_global
    }
    getter <- function(self, code) {
        reticulate::r_to_py(eval(parse(text = as_r_value(code)), envir = envir))
    }
    setter <- function(self, name, value) {
        envir[[as_r_value(name)]] <<- as_r_value(value)
    }
    reticulate::py_set_attr(R, "__getattr__", getter)
    reticulate::py_set_attr(R, "__setattr__", setter)
    reticulate::py_set_attr(R, "__getitem__", getter)
    reticulate::py_set_attr(R, "__setitem__", setter)
    reticulate::py_run_string("r = R()")
}
```

**Comment by jjallaire** [comment]
@kevinushey Could you take a look at this when you come back?

**Comment by kevinushey** [comment]
Thanks for the bug report! We now ensure that the `r` helper object is after Python itself is initialized -- let me know if this does what you need or if I've missed anything.

**Comment by DavisVaughan** [comment]
This is great thanks!
