### ISSUE TITLE
Import python package crash R

### ISSUE THREAD

**Issue by zaxcie** [rstudio/reticulate#236]
Hi,
I have a custom Python library I'd like to be able to use from R.

When I try to use it, it always crash my R. I took a gif in RStudio, but if I run in R console, it shutdown by terminal.

![reticulate-crash1](https://user-images.githubusercontent.com/6867232/39216822-34665a02-47eb-11e8-8bb9-5abdb5655a3f.gif)

```
library(reticulate)
use_condaenv("preproc-dev", required=TRUE)

py_discover_config()
ppp <- import("preprocpype.encoder.single.OneHotEncoder", delay_load = FALSE)

flow = OneHotEncoder

df = data.frame(A=c("a", "b", "c", "a", "a"), B=c("a", "b", "c", "a", "a"))

journal = ppp$Journal()
```

The error is triggered when executing `ppp <- import("preprocpype.encoder.single.OneHotEncoder", delay_load = FALSE)`.

Any ideas?

EDIT: I've tried with the CRAN version of reticulate and also 1.6.0.9002 fetch directly from GitHub.
EDIT2: if I set delay_load at TRUE, R crash when running `flow = OneHotEncoder`

**Comment by kevinushey** [comment]
That likely implies that the Python session itself is crashing when attempting to import the `preprocpype` package. Unfortunately this will be hard for us to diagnose without a reproducible example / access to the package you're attempting to use.
