### ISSUE TITLE
Please add trailing whitespace linting

### ISSUE THREAD

**Issue by bcipolli** [rstudio/reticulate#239]
Seems pretty standard, and it's a pretty bad experience to save a file to contribute, and have 25%+ of the lines show up in the `git diff`. 

i literally had to discard most of the "changes" to `R/python.R`, just to submit a PR, because of all the whitespace stripping.

**Comment by jjallaire** [comment]
Thanks for pointing this out, just made that change (and re-saved all of the source files so that they no longer have any trailing newlines)
