### ISSUE TITLE
Python objects are not created when using reticulate

### ISSUE THREAD

**Issue by Sadegh-Saberian** [rstudio/reticulate#247]
Hi,

I have installed reticulate package and im trying to use it besides my Rscripts. I have set my virtualenv using use_virtualenv() function. however when I use a simple example to test, it seems that the objects which are created by the python code is not accessible using "py". here is my test code:
I would appreciate if you could let me know what might have gone wrong.

Thanks.
````{r}
  library(reticulate)
  use_virtualenv("~/venv", required = T)  
  knitr::knit_engines$set(python = eng_python)
```

```{python}
a = 7
print(a)
```


```{r}
py$a
```
`

**Comment by jjallaire** [comment]
You are probably executing the code in RStudio and not using the daily build of RStudio (note that's listed as requirement here: https://rstudio.github.io/reticulate/articles/rstudio_ide.html)

**Comment by abaghaie** [comment]
I can't find a reference to that requirement on that page, could you explain a bit more?

Thanks
