### ISSUE TITLE
py_to_r still gives error message for conversion

### ISSUE THREAD

**Issue by patil1979** [rstudio/reticulate#249]
Hi team,

I have pulled latest code of reticulate and built on RStudio, I am trying to use same on custom data arriving from python code. This is basically pandas data frame. In previous released version of reticulate I used to face conversion issue and used to get :
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'function' object has no attribute 'as_matrix'
However with latest code I don't see above listed issue but I see new issue as:

Error in py_to_r.default(x$columns$values) : 
  Object to convert is not a Python object 

Below is the stack trace:
5. stop("Object to convert is not a Python object") at conversion.R#31
4. py_to_r.default(x$columns$values) at conversion.R#19
3. py_to_r(x$columns$values) at conversion.R#234
2. py_to_r.pandas.core.frame.DataFrame(dat) at conversion.R#19
1. py_to_r(dat)

Can anyone please guide me as how to get fix for it?
BR
Meru

**Comment by patil1979** [comment]
Unfortunately I can't provide code as it is proprietary. However I can explain the type of data held and experiment that I conducted. The data passed from python code to R script is of Pandas dataframe, with five columns in it: numeric, date, numeric, numeric, numeric. Below is the experiment I carried out: 
1.	On Linux server old version of Reticulate library is present
2.	On server data is passed from python to R script
3.	Passed data is saved in R script
4.	Data transferred to local windows system
5.	On windows system latest version of reticulate library is installed in Rstudio
6.	Transferred data is loaded into R studio (windows system)
7.	Try to apply py_to_r() on loaded data, got error
Today I have got permission to load latest reticulate on above mentioned Linux server, let me try to apply this function on server and get back to you.

**Comment by patil1979** [comment]
Update (10-May-2018):
============
- As mentioned above I could load lasted built library on Linux server and test it. On sample program I am getting following error

 Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'CategoricalDtype' object has no attribute 'ordered' 

Below is the sample code that I used for testing:
#==========
rm(list = ls())
library(reticulate)

x = 4
y = "Value-Time_one"
z= Sys.Date()

ex <- base::data.frame(x, y, z)

x = 5
y = "Value-Time_one"
z= Sys.Date()

ex=rbind(ex,base::data.frame(x,y,z))

print(ex)
print(paste0("Class of ex: ",class(ex)))
print(paste0("Class of x: ",class(ex$x)))
print(paste0("Class of y: ",class(ex$y)))
print(paste0("Class of z: ",class(ex$z)))

ex_py <- r_to_py(ex)
print(paste0("Class of ex_py: ",class(ex_py)))

rex <- py_to_r(ex_py)
#===============

**Comment by kevinushey** [comment]
Your first example appears to work fine for me (with the development version of `reticulate`):

```
> ex
  x              y          z
1 4 Value-Time_one 2018-05-10
2 5 Value-Time_one 2018-05-10
> ex_py
     x               y          z
0  4.0  Value-Time_one 2018-05-10
1  5.0  Value-Time_one 2018-05-10
```

With e.g.

```
> str(rex)
'data.frame':	2 obs. of  3 variables:
 $ x: num  4 5
 $ y: Factor w/ 1 level "Value-Time_one": 1 1
 $ z: POSIXct, format: "2018-05-10" "2018-05-10"
```

And, of course, you won't be able to directly convert a Python object into a `data.frame` -- only R `data.frame` <-> pandas DataFrame conversion is implemented for `data.frame`s specifically; other conversions use NumPy arrays and base R data types when appropriate.

**Comment by harryprince** [comment]
@patil1979 

I have tried your example,

And maybe this is a solution to convert pandas to data.frame?

```
tmp <- ex_py$values %>% reticulate::py_to_r() %>% data.frame() 

colnames(tmp) <- ex_py$columns$values %>% as.vector()
```

Indeed, I think convert pandas to data.table is a better option, which have more similar concepts like index.
