### ISSUE TITLE
Numpy Arrays and R Arrays are printed differently

### ISSUE THREAD

**Issue by pourzanj** [rstudio/reticulate#25]
Say you have a (4,2) array in R, and you convert to Python then print. This works as expected.

```r
> R_4_2 <- array(1:prod(4,2), dim = c(4,2))
#     [,1] [,2]
#[1,]    1    5
#[2,]    2    6
#[3,]    3    7
#[4,]    4    8
> dim(R_4_2)
#[1] 4 2
> Np_4_2 <- np$array(R_4_2)
> Np_4_2
#[[1 5]
# [2 6]
# [3 7]
# [4 8]]
> Np_4_2$shape
#(4, 2)
```
Now say we'd like to extend our original R array so instead of being a single (4,2) matrix we want it to be a 3 (4,2) matrices. In R we tack on the extra dimension to the end of the shape array.

```r
> R_4_2_3 <- array(1:prod(4,2,3), dim = c(4,2,3))
#, , 1
#
#     [,1] [,2]
#[1,]    1    5
#[2,]    2    6
#[3,]    3    7
#[4,]    4    8
#
#, , 2
#
#     [,1] [,2]
#[1,]    9   13
#[2,]   10   14
#[3,]   11   15
#[4,]   12   16
#
#, , 3
#
#     [,1] [,2]
#[1,]   17   21
#[2,]   18   22
#[3,]   19   23
#[4,]   20   24
> dim(R_4_2_3)
#[1] 4 2 3
```
This time when we convert to Numpy the shape is the same, but instead of printing 3 (4,2) matrices, we print 4 (3,2) matrices

```r
> Np_4_2_3 <- np$array(R_4_2_3)
> Np_4_2_3$shape
#(4, 2, 3)
> Np_4_2_3
#[[[ 1  9 17]
#  [ 5 13 21]]
#
# [[ 2 10 18]
#  [ 6 14 22]]
#
# [[ 3 11 19]
#  [ 7 15 23]]
#
# [[ 4 12 20]
#  [ 8 16 24]]]
```
The equivalent shape in numpy that would print out the same way as R would be a (3,4,2). I'm not sure what the best way to solve this. Could we change the default behavior of arrays in R?

**Comment by pourzanj** [comment]
I just found the Vignette on Array in R and Python. My apologies for not seeing that earlier.

It would be nice to have a special function to print an array C-style.

**Comment by jjallaire** [comment]
Glad you found the vignette, this caused much confusion on our end as well until @bwlewis worked it all out!  We'd be happy to take a PR with the array printing behavior you mentioned.
