### ISSUE TITLE
Could not find or load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by rgaiacs** [rstudio/reticulate#253]
I downloaded https://raw.githubusercontent.com/rstudio/reticulate/master/tests/testthat/resources/eng-reticulate-example.Rmd (changed `print` statement to `print` function) and try to convert it using knitr from Rstudio interface but I received

````
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "/usr/lib/rstudio/bin/plugins/platforms".

Available platform plugins are: minimal, offscreen, xcb.
````

as error. Did I missed something?

# Environment

- RStudio Version 1.0.153
- R version 3.5.0 (2018-04-23)
- knitr 1.20
- reticulate 1.7.1
- rmarkdow 1.9

**Comment by kevinushey** [comment]
This appears to be an RStudio rather than `reticulate` issue. However, if you're planning to leverage some of the RStudio IDE features for using `reticulate` I'd recommend installing a daily build from:

https://dailies.rstudio.com

Or at least upgrading to the latest release of RStudio (v1.1.447): https://www.rstudio.com/products/rstudio/download/#download

**Comment by rgaiacs** [comment]
> This appears to be an RStudio rather than `reticulate` issue.

I have a similar problem when calling knitr from the command line and not RStudio.

````
$ Rscript -e "library(knitr); knit('eng-reticulate-example.Rmd')"


processing file: eng-reticulate-example.Rmd
  |..                                                               |   3%
  ordinary text without R code

  |....                                                             |   6%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |......                                                           |   9%
  ordinary text without R code

  |........                                                         |  12%
label: unnamed-chunk-1 (with options) 
List of 1
 $ engine: chr "python"

  |..........                                                       |  15%
  ordinary text without R code

  |............                                                     |  18%
label: unnamed-chunk-2 (with options) 
List of 1
 $ engine: chr "python"

  |..............                                                   |  21%
  ordinary text without R code

  |................                                                 |  24%
label: unnamed-chunk-3 (with options) 
List of 4
 $ fig.width : num 4
 $ fig.height: num 3
 $ dev       : chr "svg"
 $ engine    : chr "python"

This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
zsh: abort (core dumped)  Rscript -e "library(knitr); knit('eng-reticulate-example.Rmd')"
````

Any advice? I try to reinstall matplotlib following reticulate instructions but it didn't work.

**Comment by kevinushey** [comment]
That's very surprising! I'm not sure what could be trying to use Qt in your environment.

**Comment by rgaiacs** [comment]
@kevinushey Thanks for the support, I believe that for some reason the environment that reticulate or RStudio created was corrupted for some reason. I executed

~~~
$ conda env remove -n r-reticulate
$ conda create -n r-reticulate python=3
$ source activate r-reticulate
$ python -m pip install matplotlib
$ Rscript -e "library(knitr); knit('eng-reticulate-example.Rmd')"
~~~

and I had a working version of reticulate. I'm closing this for now. Let me know if you want any pull request to document this.

**Comment by kevinushey** [comment]
Glad to hear you got to the bottom of this! I'm not sure we have a good place for these instructions to land, but at least having the GitHub issue in the history means that others who have similar problems with be able to stumble upon your post.

Perhaps in the future we could consider making things like this part of a lightweight Q&A-style wiki page here on GitHub...

**Comment by asadow** [comment]
Indeed this solution worked for me.
