### ISSUE TITLE
reticulate first call wont recognise local Python installation

### ISSUE THREAD

**Issue by cheTesta** [rstudio/reticulate#256]
After restarting **RStudio** session or quitting and reopening it, first load of `reticulate` does not recognise my local Python installation.

I.e., running `py_available()` outputs states to `FALSE`.

To get things working, each time, I need to run `py_available(initialize = TRUE)`, then I'll get:

    > py_available()
    [1] TRUE

Is anyone having the same issue?

Current R version 3.4.4, knitr 1.20, reticulate 1.7

**Comment by dfalbel** [comment]
We have significantly refactored Python discovery rules in reticulate v1.31. Please find more information [here](https://rstudio.github.io/reticulate/articles/versions.html#order-of-discovery) and open a new issue if the problem still exists.
