### ISSUE TITLE
Python expects list, but R sends scalar

### ISSUE THREAD

**Issue by jeffwong-nflx** [rstudio/reticulate#258]
I'm using a function in python which expects to operate on a list of strings. The variable in R that I pass could look like `c('hello')`, or `c('hello', 'world')`. When the R vector is length 2 or more it will be converted to a list of strings. However, when it is a vector of length 1 it will be sent as a scalar. I know this is an R behavior that length 1 vectors are the same as scalars, but that behavior isn't the same in python. Is there any way to trick R or reticulate into passing a length 1 list?

**Comment by jjallaire** [comment]
Yes, just do this: list("hello")

**Comment by muschellij2** [comment]
I agree and think this can be closed.  Ran into the same issue and `list` should work fine if you know of length 1, but may want to use `as.list` more generally:
``` r
library(reticulate)
x = c("value1", "value2")
r_to_py(x)
#> ['value1', 'value2']
r_to_py(x[1])
#> value1
r_to_py(as.list(x[1]))
#> ['value1']
r_to_py(as.list(x))
#> ['value1', 'value2']
r_to_py(list(x))
#> [['value1', 'value2']]
```

Created on 2018-08-27 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by qdread** [comment]
I also ran into this issue and used `as.list()` as suggested by @muschellij2 which solved the problem.
