### ISSUE TITLE
append all Python class bases to R class attribute

### ISSUE THREAD

**Issue by goldingn** [rstudio/reticulate#26]
When executing a python function with reticulate, class information from the python object is appended to the resulting R object's class attribute. This is done in the CPP function [`py_ref`](https://github.com/rstudio/reticulate/blob/master/src/python.cpp#L229).

If I understand this code correctly, `py_ref` [grabs the `__class__`](https://github.com/rstudio/reticulate/blob/master/src/python.cpp#L247-L248) attribute of the python object (the class of which this is an *instance*), as well as [the parent class](https://github.com/rstudio/reticulate/blob/master/src/python.cpp#L252-L257) from which this class inherits, via the class object's `.__bases__` attribute. **However this is only done for the immediate parent class, not for the full inheritance.**

---

I am working on a port of the [`GPflow`](https://github.com/GPflow/GPflow) Python module, and want to map its nice kernel creation syntax to R. Kernel objects can be added, multiplied etc., and the `GPflow` module enables this by defining addition for all objects of class `Kern`. for example, in python:

```python
import GPflow as gp
k1 = gp.kernels.Constant(1)
k2 = gp.kernels.Bias(1)
k3 = gp.kernels.Cosine(1)
K = k1 + k2 + k3
```
The full class inheritance for these objects is:
`k1`: `object`>`Parentable`>`Parameterized`>`Kern`>`Static`>`Constant`
`k2`: `object`>`Parentable`>`Parameterized`>`Kern`>`Static`>`Constant`>`Bias`
`k3`: `object`>`Parentable`>`Parameterized`>`Kern`>`Stationary`>`Cosine`
The `+` operator is a wrapper around `GPflow.kernels.Add((k1, k2, k3))`, defined in the `Kern` class; it works for any class instance inheriting from `Kern`.

To enable the same syntax in an R port using reticulate, it would be really helpful for `GPflow.kernels.Kern` to be listed in the class attribute for the corresponding R objects, so we can do S3 dispatch. But because only the immediate parent class is returned this isn't currently possible. I.e. in R:

```r
library(reticulate)
gp <- import('GPflow')
k1 <- gp$kernels$Constant(1)
k2 <- gp$kernels$Bias(1)
k3 <- gp$kernels$Cosine(1)
class(k1); class(k2); class(k3)
```
```
[1] "GPflow.kernels.Constant" "GPflow.kernels.Static"   "python.builtin.object"  
[1] "GPflow.kernels.Bias"     "GPflow.kernels.Constant" "python.builtin.object"
[1] "GPflow.kernels.Cosine"     "GPflow.kernels.Stationary" "python.builtin.object" 
```

---

A fix would be to have [this section of `py_ref`](https://github.com/rstudio/reticulate/blob/master/src/python.cpp#L252-L257) recurse through the parent classes, finding their parents (via the `.__bases__` attribute) and adding them to the R object's class attribute, until hitting either `object` or an empty string (`object`'s parent class).

As far as I can tell, there is no sane way of doing this from the reticulate-wrapping GPflow-specific R package.

If that sounds like behaviour you would like (or tolerate) in `reticulate`, I'd be happy to do a PR (though my C++ is decidedly rusty so very happy if someone else wants to do it!).

**Comment by jjallaire** [comment]
Interesting, I was under the impression that `__bases__` would provide the entire hierarchy. Looks like that logic needs to be in a loop up to the top level. I'll try to make that change for the next release.

**Comment by jjallaire** [comment]
It looks like `inspect.getmro` will do the correct traversal: http://stackoverflow.com/questions/1401661/list-all-base-classes-in-a-hierarchy-of-given-class

**Comment by jjallaire** [comment]
@goldingn This PR should address this issue: https://github.com/rstudio/reticulate/pull/31

Could you take a look and let me know if this looks okay to you? (i.e. am I missing any subtleties here)

**Comment by goldingn** [comment]
Yeah, that's perfect. I get:

```r
devtools::install_github('rstudio/reticulate@930b283')
```
```r
library(reticulate)
gp <- import('GPflow')
k1 <- gp$kernels$Constant(1)
k2 <- gp$kernels$Bias(1)
k3 <- gp$kernels$Cosine(1)
class(k1); class(k2); class(k3)
```
```
[1] "GPflow.kernels.Constant"    "GPflow.kernels.Static"      "GPflow.kernels.Kern"       
[4] "GPflow.param.Parameterized" "GPflow.param.Parentable"    "python.builtin.object"     
[1] "GPflow.kernels.Bias"        "GPflow.kernels.Constant"    "GPflow.kernels.Static"     
[4] "GPflow.kernels.Kern"        "GPflow.param.Parameterized" "GPflow.param.Parentable"   
[7] "python.builtin.object"     
[1] "GPflow.kernels.Cosine"      "GPflow.kernels.Stationary"  "GPflow.kernels.Kern"       
[4] "GPflow.param.Parameterized" "GPflow.param.Parentable"    "python.builtin.object" 
```

Thanks!
