### ISSUE TITLE
Change path to Python binary

### ISSUE THREAD

**Issue by jannes-m** [rstudio/reticulate#27]
Dear **reticulate**-developers,

thanks for developing such a fantastic package!

Is it possible to change the path to another Python binary after already having run `py_config` or `py_run_string`?
In my case I would like to point **reticulate** to the QGIS Python binary (which is a bit of a hazzle under Windows). This works, i.e. **reticulate** accepts the QGIS Python binary (mostly to be found under C:\OSGEO4~1\bin\python.exe).

However, before running any **RQGIS** function I would like to check if the correct Python binary is in use. Assuming, the user has not set up correctly the QGIS Python environment, running `py_config ` might point to another Python binary such as Anaconda Python ("...\AppData\Local\CONTIN~1\ANACON~1\python.exe). In this case, I would like to change to the QGIS Python binary. I tried `use_python` but it didn't work. Or is there any other way to find out which Python binary **reticulate** would use at a specific moment but without actually setting it.

**Comment by jjallaire** [comment]
I agree that it would be good to have a "preview" of what the reticulate binding will be. I'll try to add that to the next version. In the meantime you can add the `required = TRUE` flag to `use_python` to fail with an error if it can't find the version specified.

**Comment by jannes-m** [comment]
Thanks for the answer! Until the "preview"-option becomes available, I will use a simple a work-around.

I hope you don't mind another related question. Is it also possible to close (and then again to restart) the connection to Python? This would be rather useful. So far, I always restart R to achieve this.

**Comment by jjallaire** [comment]
No, you can't safely unload and reload the connection to Python (too many
unreversable side effects in the Python interpreter)

**Comment by jjallaire** [comment]
Just exported the `py_discover_config` function here: https://github.com/rstudio/reticulate/commit/4118c57206a5fdf158ce2717fc5fb0957273100f

**Comment by jannes-m** [comment]
Thanks for `py_discover_config`!

**Comment by mxposed** [comment]
@jjallaire could you please elaborate on why is it not possible to close established python session? I think it would be a nice feature to be able to re-initialize python with another binary (version or virtualenv) without restarting R session

**Comment by jjallaire** [comment]
You can't cleanly unload embedded Python and then load another version.
There are too many side effects (e.g. static caches of objects) in embedded
Python to allow for this. It is in-theory possible but in practice there
are many bugs people have discovered (e..g
https://bugs.python.org/issue17408) as most Python C code is not written
with this scenario in mind.

**Comment by mxposed** [comment]
Thank you for the explanation. Is it theoretically possible to initialize python in a forked process and then kill one if there is a need for reload? But I guess the communication would become a lot more complex

**Comment by jjallaire** [comment]
Yes, if we initialize it in a forked process then we've lost the ability to
R and Python to seamlessly share data / context in the foreground process
(the R session).
