### ISSUE TITLE
Cannot import google package

### ISSUE THREAD

**Issue by scm-bryan** [rstudio/reticulate#278]
I have a number of issues, but they're all related, so I'll put them in one issue.  

First off, I can not get reticulate to import the correct numpy.  Even I specify which python and virtualenv to use, I specify which path to use when I import numpy, and py_config and py_discover_config identify the correct numpy, I still import the numpy from the system python. 

I enter the following code:
```R
library("reticulate")
use_python("~/.virtualenvs/r-tensorflow/bin/python", required = TRUE)
use_virtualenv("~/.virtualenvs/r-tensorflow", required = TRUE)
np <- import_from_path("numpy", "~/.virtualenvs/r-tensorflow/local/lib64/python2.7/site-packages/")
np$`__path__`
#[1] "/usr/local/lib64/python2.7/site-packages/numpy"
py_config()
#python:         /home/bryan/.virtualenvs/r-tensorflow/bin/python
#libpython:      /usr/lib64/python2.7/config/libpython2.7.so
#pythonhome:     /usr:/usr
#virtualenv:     /home/bryan/.virtualenvs/r-tensorflow/bin/activate_this.py
#version:        2.7.12 (default, Nov  2 2017, 19:20:38)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
#numpy:          /home/bryan/.virtualenvs/r-tensorflow/local/lib64/python2.7/site-packages/numpy
#numpy_version:  1.14.3
#sys:            sys
#
#NOTE: Python version was forced by use_python function
py_discover_config()
#python:         /home/bryan/.virtualenvs/r-tensorflow/bin/python
#libpython:      /usr/lib64/python2.7/config/libpython2.7.so
#pythonhome:     /usr:/usr
#virtualenv:     /home/bryan/.virtualenvs/r-tensorflow/bin/activate_this.py
#version:        2.7.12 (default, Nov  2 2017, 19:20:38)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
#numpy:          /home/bryan/.virtualenvs/r-tensorflow/local/lib64/python2.7/site-packages/numpy
#numpy_version:  1.14.3
#
#NOTE: Python version was forced by use_python function
```
This does not happen for scipy
```R
sp <- import_from_path("scipy", "~/.virtualenvs/r-tensorflow/local/lib64/python2.7/site-packages/")
sp$`__path__`
#[1] "/home/bryan/.virtualenvs/r-tensorflow/lib64/python2.7/site-packages/scipy"
```
Interestingly, in Python I also seem to be getting the system numpy and scipy (or at least no path is returned).  This does not happen for packages that are not in the system installation.
```Python
import numpy as np
np.__path__
#['numpy']
import scipy as sp
sp.__path__
#['scipy']
import google
google.__path__
#['/home/bryan/.virtualenvs/r-tensorflow/local/lib64/python2.7/site-packages/google', '/home/bryan/.virtualenvs/r-tensorflow/lib64/python2.7/site-packages/google']
```

I actually don't care which numpy is used as long as I can get my desired packages to work, but that is not the case.  I cannot import tensorflow because it can't find the google package, and I cannot import the google package even if I specify its path.  I encounter no problems importing the google package in python (as seen above).
```R
tf <- import("tensorflow")
#Error in py_module_import(module, convert = convert) : 
#  ImportError: No module named google.protobuf
google <- import("google")
#Error in py_module_import(module, convert = convert) : 
#  ImportError: No module named google
google <- import_from_path("google", "~/.virtualenvs/r-tensorflow/local/lib64/python2.7/site-packages/")
#Error in py_module_import(module, convert = convert) : 
#  ImportError: No module named google
```
I would appreciate any help.  Thanks.

I'm using R 3.4.1 on x86_64-redhat-linux-gnu and reticulate_1.7.1.

**Comment by scm-bryan** [comment]
I should add that all of the above was done in RStudio.

I recently ran these commands from R on the command line.  I actually get the right path for numpy when I call
```
np$`__path__`
# [1] "/home/bryan/.virtualenvs/r-tensorflow/lib64/python2.7/site-packages/numpy"
```
but unfortunately the google package is still invisible, even when I use import_from_path.  This prevents me from using tensorflow, so I'm still stuck.

**Comment by scm-bryan** [comment]
I have resolved this problem, so that I can now use tensorflow, but it's unclear why I had to do so many things to get it to work correctly.

I made it so I could import google by adding an __init__.py file to the google folder.  The google package has all its files in another folder called protobuf, which has the __init__.py file.  After adding this file, it also allows me to import tensorflow.  I should add that I could import the google package in python even before I added the __init__.py file.

**Comment by scm-bryan** [comment]
I should also add that some of my packages don't import unless I specify the path. 
```
import("sklearn")
#Error in py_module_import(module, convert = convert) : 
#  ImportError: No module named sklearn
sklearn <- import_from_path("sklearn", "/home/bryan/.virtualenvs/r-tensorflow/lib64/python2.7/dist-packages/")
```

I can't import any packages that are stored in the lib directory (rather than lib64) unless I specify the path.
```
import("pytz")
#Error in py_module_import(module, convert = convert) : 
#  ImportError: No module named pytz
import_from_path("pytz", "/home/bryan/.virtualenvs/r-tensorflow/lib/python2.7/dist-packages/")
#Module(pytz)
```

**Comment by xslates** [comment]
Apparently, the importing issues with RStudio's Reticulate can be solved by installing what's called a daily build --> https://dailies.rstudio.com/  

Related Issue can be found here: https://github.com/rstudio/reticulate/issues/228
