### ISSUE TITLE
reticulate::source_python using python3 does not show console output of the script

### ISSUE THREAD

**Issue by gsgxnet** [rstudio/reticulate#284]
setup is to try the differences between the python versions by a `.Renviron` file in the working directory just containg 1 line:  
`RETICULATE_PYTHON=/usr/bin/python` for the 2.x python and  
`RETICULATE_PYTHON=/usr/bin/python3` for the 3.x python.  

To force a reread of `.Renviron` I did a Restart R after changing its content.
hello-world.py content:
```python
import sys  
print ( "Hello World!" )
print ( "\nfrom Python: " + str(sys.version_info) )
```

results:  
```r
> reticulate::source_python('hello-world.py')
Hello World!

from Python: sys.version_info(major=2, minor=7, micro=15, releaselevel='final', serial=0)
```
change `.Renviron` to python3 (s.a.)  
```r
Restarting R session...

> reticulate::source_python('hello-world.py')
> reticulate::source_python('hello-world.py')
```

as you can see no script output at all from RStudio console.

cross check on bash console:  
```bash
python3 hello-world.py 
Hello World!

from Python: sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

Used RStudio dailies 1.2.675, reticulate 1.7.1 (installed from github). Error found first in reticulate 1.7 from cran.

**Comment by kevinushey** [comment]
This is likely because Python 3's `print()` does not flush output by default. We probably need to do this ourselves after calling `source_python()` explicitly.

**Comment by kevinushey** [comment]
Indeed this is the case:

```
> library(reticulate)
> use_python("/usr/local/bin/python3", required = TRUE)
> source_python("hello.py")
> sys = import('sys')
> sys$stdout$flush()
Hello World!

from Python: sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by gsgxnet** [comment]
Yes similar, if I append `sys.stdout.flush()` to the script the output is shown in the RStudio console. Good workaround, thanks.

**Comment by jjallaire** [comment]
Yes we should definitely do it

**Comment by gsgxnet** [comment]
Works now as expected. 
First after a simple `install_github("rstudio/reticulate")` it did not. After removing the package, reinstalling and then restarting the R session all was fine. May be these steps are necessary as `reticulate` is some kind of preloaded at RStudio start ... May be I made some mistake at my first attempt. May be ...

**Comment by kevinushey** [comment]
Typically, when reinstalling a package containing compiled code, you must restart the R session to ensure the updated set of compiled code is loaded.
