### ISSUE TITLE
calling names() on an OrderedDict crashes the R session

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/reticulate#290]

**Comment by t-kalinowski** [comment]
Actually, i'm not entirely sure what's causing the crash. It's reproducible, and it's from a list of ordered dicts containing nested ordered dicts that is loaded as a pickle file. It I make an ordered dict directly from the R side then calling names works just fine.

**Comment by t-kalinowski** [comment]
Also, `repl_python()` doesn't work if there are not write permissions in the working directory. The error message says it can't save history.

**Comment by kevinushey** [comment]
The crash is likely in `reticulate:::py_dict_get_keys_as_str()`, which would imply the object you're working with has keys that `reticulate` doesn't understand how to convert into strings.

**Comment by kevinushey** [comment]
For the working directory issue, I'll need a reproducible example. (why are you attempting to launch `repl_python()` in a situation where you don't have write access to the working directory anyhow?)

**Comment by t-kalinowski** [comment]
>  (why are you attempting to launch repl_python() in a situation where you don't have write access to the working directory anyhow?)
To debug this issue! was reading data from a non-writable directory, and had temporarily set the wd to that to save typing...

**Comment by t-kalinowski** [comment]
The keys are strings, but the values are sometimes themselves ordered dicts. If I recreate a similar type of object from the R side, then it all works fine. But loading the pickle object with that nested structure crashes the R session a soon as names (or `$` tries to populate the autocomplete list). Running it with R --vanilla in terminal, it produces a seg fault with this error message (trimmed for clarity)
```
 *** caught segfault ***
address 0x8, cause 'memory not mapped'

Traceback:
 1: py_ref_to_r(x)
 2: py_to_r.default(x)
 3: py_to_r(x)
 4: py_maybe_convert(item, py_has_convert(x))
...
```

**Comment by kevinushey** [comment]
Gotcha. If you can provide a small reproducible example, we should be able to investigate further.

**Comment by t-kalinowski** [comment]
Unfortunately, I can't seem to reproduce this without the specific pickle file, and I can't share the pickle file. Closing for now.
