### ISSUE TITLE
With Shiny dataframe gets converted to dictionary in Python

### ISSUE THREAD

**Issue by ggsdc** [rstudio/reticulate#298]
Hello,

I'm testing this library to be used in a Shiny application, right now I'm having a isse trying to pass a data.frame from R to Python.

The main idea is the following:

1. Generate a random data.frame with an `numericInput` in R.
2. Choose a multiplier with another `numeriInput`.
3. Have a python function that multiplies all the columns in the data.frame in Python.

This is not the final aim of the application, just a small example to show the error I am encountering.

This would be the code so you can try and replicate the error.

global.R:
```
library(reticulate)
library(shiny)
library(shinydashboard)
use_virtualenv("./env")
source_python("main.py")
```

The Python enviroment is just a clean virtual enviroment in the same folder as the RStudio project and the .R and .py files. It just has pandas installed, its requirements.txt file would be:

```
numpy==1.14.3
pandas==0.23.0
python-dateutil==2.7.3
pytz==2018.4
six==1.11.0
```
The rest of the scripts are:

ui.R:
```
header <- dashboardHeader(title="Example")

sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("Main Page", tabName="main", icon=icon("info"))
  )
)

body <- dashboardBody(
  tabItems(
    tabItem(
      tabName="main",
      column(numericInput(label=h3("Number of rows"), "rows", value=10),
             br(),
             tableOutput("rows"),
             width=3),
      column(numericInput(label=h3("Multiplier"), "mult", value=1),
             br(),
             tableOutput("dataframe"),
             width=3)
    )
  )
)

dashboardPage(header = header, sidebar = sidebar, body = body)
```

server.R:
```
shinyServer(function(input, output, session){
  
  dfR <- reactive({
    x <-data.frame(a=runif(input$rows,0,100), b=runif(input$rows,0,100), c=runif(input$rows,0,100))
    return(x)
    })
  
  output$rows <- renderTable(dfR())
  
  output$dataframe <- renderTable(mult_df(dfR(), input$mult))
  
})
```

main.py:
```
import pandas as pd

def mult_df(dfA, value):
  import pandas as pd
  dfB = pd.DataFrame.from_dict(dfA) * value
  return dfB

```
With these files it works but as you can see in the python function I have to use `pd.DataFrame.from_dict(dfA)` to convert the input data.frame as it gets interpreted as a dictionary.

If I change the main.py to this:
```
import pandas as pd

def mult_df(dfA, value):
  import pandas as pd
  dfB = dfA * value
  return dfB

```
Then I get the following error that tells me that it is getting interpreted as a dictionary:

```
Listening on http://127.0.0.1:3112
Warning: Error in py_call_impl: TypeError: unsupported operand type(s) for *: 'dict' and 'int'
Stack trace (innermost first):
    83: <Anonymous>
    82: stop
    81: py_call_impl
    80: mult_df
    79: renderTable
    78: func
    77: origRenderFunc
    76: output$dataframe
     1: runApp
```

Finally this is my session info:

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] shinydashboard_0.6.1 reticulate_1.7      
[3] shiny_1.0.5         

loaded via a namespace (and not attached):
 [1] compiler_3.4.0  R6_2.2.2        Matrix_1.2-9   
 [4] htmltools_0.3.6 tools_3.4.0     yaml_2.1.17    
 [7] Rcpp_0.12.15    grid_3.4.0      digest_0.6.15  
[10] jsonlite_1.5    xtable_1.8-2    httpuv_1.3.6.2 
[13] mime_0.5        lattice_0.20-35
```

Any idea why this is happening or what am I doing wrong?

Thanks in advance

**Comment by kevinushey** [comment]
Here's a more minimal reproducible example:

```r
library(reticulate)
py_run_string('
import pandas as pd
def multiply(a, b):
    return a * b

')

main <- import_main()
multiply <- main$multiply

df <- data.frame(x = 1, y = 2, z = 3)
multiply(df, 2)
```

The problem is that `r_to_py()` is not called when converting R objects to Python objects -- I imagine only the lower-level conversion code is being run here. You can of course explicitly request the conversion on the R side with:

```r
multiply(r_to_py(df), 2)
```

@jjallaire do you think we should call the R-level `r_to_py()` function here to convert R objects before calling the associated Python function?

**Comment by jjallaire** [comment]
It does seem like we should be calling the R level `r_to_py()` but we should probably take a closer look at the implications of this before proceeding.

**Comment by ggsdc** [comment]
Thank you for your replies.

Calling `r_to_py()` in the python function call solves the problem, I did not know it had to be done that way.

This can solve my problems, I just have to remember to call it before calling python.

I'll be keeping watch in case you change this.

Thank you very much.

**Comment by jjallaire** [comment]
The trickiness here is that the R implementation of `r_to_py()` is not called from within the C++ code (which instead calls the lower-level C++ version that doesn't do S3 dispatch, see https://github.com/rstudio/reticulate/blob/master/src/python.cpp#L940). 

The C++ version also calls itself recursively (for list types, etc.).

@kevinushey I think the answer here will probably be to have the C++ version called from *only* one place (the main `r_to_py()` dispatcher and all other calls (including ones from the C++ side) need to go through the R version.

One subtlety I can already see: the "py_object" mechanism defined here (https://github.com/rstudio/reticulate/blob/master/src/python.cpp#L951-L955) effectively bypasses S3 dispatch (the py_object attribute being used as a hint to override default dispatching) so the R level would need to be made aware of that and forward to the low level handler in that case.

**Comment by jjallaire** [comment]
PR to address this year: https://github.com/rstudio/reticulate/pull/299

Bears very careful scrutiny though!

Could we run this through the equivalent of the CRAN memory checks?
