### ISSUE TITLE
Document the conversion between R and Python functions/closures

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/reticulate#3]
See title

**Comment by jjallaire** [comment]
We mention it in the table here:
https://github.com/rstudio/reticulate#overview

What else do you think we should add?

On Wed, Feb 8, 2017 at 11:15 AM, Yuan (Terry) Tang <notifications@github.com

**Comment by terrytangyuan** [comment]
Oh I missed it. Great that's good.
