### ISSUE TITLE
Run custom function with input

### ISSUE THREAD

**Issue by rb643** [rstudio/reticulate#315]
Is it possible to use reticulate to run custom python script that require user input directly from R?

say I have a function called plotcustomgraph.py that requires a csv file as input and writes out a pdf, is it somehow possible to call this function from within R using reticulate?

**Comment by jjallaire** [comment]
If Python is asking for user input it's likely using standard tty mechanisms which generally won't work from R. Here I think you want to ask the user's input within R then pass those inputs to the Python code (e.g. as function arguments).

**Comment by rb643** [comment]
So would that look something like this?

py_run_file('plotcustomgraph.py', file.csv)

**Comment by jjallaire** [comment]
No, you would write a Python function, source the script containing the function, then call the function from R. See https://rstudio.github.io/reticulate/articles/calling_python.html#sourcing-scripts

**Comment by t-kalinowski** [comment]
See https://github.com/rstudio/reticulate/issues/485#issuecomment-1613112237 for one way to approach this.
