### ISSUE TITLE
Python Class methods don't seem to be preserved

### ISSUE THREAD

**Issue by Jorisvansteenbrugge** [rstudio/reticulate#316]
If I define a class in a python library, e.g. 
```{python}
class Example():
    def __init__(self, varA):
        self.varA = varA

    def _foo(self):
        print("this is a test")
```
and then import the library in R, and initialize an object:
```{r}
library('reticulate')
example <- import('Example') #simplified

a <- Example$Example(varA) # Works
a$varA  # Works
a$_foo() # does not work
```

Then the constructor works, I can access instance variable `varA`,  but I cannot use the class function `_foo`. Perhaps I am doing something wrong, but I cannot seem to find out how to make it work.

**Comment by jjallaire** [comment]
The problem is that `_foo()` is not a valid R symbol name so you need to use backticks to escape the name:

```r
a$`_foo`()
```

**Comment by Jorisvansteenbrugge** [comment]
Oh you are right, I should have thought of that...
