### ISSUE TITLE
Could not find build tools necessary to build reticulate

### ISSUE THREAD

**Issue by junsbabay** [rstudio/reticulate#326]
While  installing reticulate by the command devtools::install_github("rstudio/reticulate")  ,
 an error occurs：
**Installation failed: Could not find build tools necessary to build reticulate**

The environment  follows:
OS: Centos 6.7
Rstudio Server：Version 0.99.1261 
gcc: 6.1.0

packageVersion("devtools")
[1] ‘1.13.5’

**Comment by jjallaire** [comment]
You could try installing from CRAN instead: `install.packages("reticulate")`. It's not the very latest version but its recent enough.

**Comment by junsbabay** [comment]
I  installed it successfully by `install.packages("reticulate")`.
 However,  I failed to install keras which need the latest version of reticulate by `devtools::install_github("rstudio/keras") `. 

Here is the info:
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘reticulate’ 1.9 is being loaded, but >= 1.9.0.9002 is required
```
Is there any  method to install the latest version of reticulate?

**Comment by jjallaire** [comment]
`devtools::install_github("rstudio/reticulate")` is the way.

You could also try installing Keras from CRAN: `install.packages("keras")`
