### ISSUE TITLE
Python chunks will not execute after use_python()

### ISSUE THREAD

**Issue by Dpananos** [rstudio/reticulate#333]
I've specified a python installation with `use_python()` but R still seems to think I am pointing at a different installation.  Here is a minimal working example

````
---
title: "Untitled"
author: "Demetri Pananos"
date: '2018-08-10'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#setup python.  Has numpy
library(reticulate)
use_python('/Users/demetri/anaconda3/envs/py_nomkl/bin/python')
```

```{python}
import sklearn
```

````

After trying to execute the python cell, I am returned this error

```
Traceback (most recent call last):
  File "/var/folders/_1/hdrhn2y9719c6vnr54tsk2tc0000gn/T/RtmpAmAzJ3/chunk-code-eb33ba2e323.txt", line 1, in <module>
    import sklearn
ImportError: No module named sklearn
```

However, sklearn is installed in that installation 

```
(py_nomkl) Demetris-Retina-MacBook-Pro:~ demetri$ conda list scikit-learn
# packages in environment at /Users/demetri/anaconda3/envs/py_nomkl:
#
# Name                    Version                   Build  Channel
scikit-learn              0.19.1          py36_nomklhde7755b_0  [nomkl]
```

Calling `Sys.which('python')` shows that R is point to `/usr/bin/python` . 

Have I used `use_python` incorrectly?  Is this the intended behaviour?  How can I rectify this problem?

**Comment by skeydan** [comment]
Try ```use_condaenv()``` instead?

**Comment by Dpananos** [comment]
@skeydan Same error occurs when I use `use_condaenv('py_nomkl')`

**Comment by jjallaire** [comment]
This is only going to work in the Preview Release of RStudio v1.2 (https://www.rstudio.com/products/rstudio/download/preview/). What version of RStudio are you running?

**Comment by Dpananos** [comment]
Thank you.  I've downloaded the preview release and can verify it works.
