### ISSUE TITLE
Case where default value of an argument is some object/methods from a module

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/reticulate#34]
`reticulate::py_function_wrapper("tf$contrib$layers$sparse_column_with_keys")` yields:

```
sparse_column_with_keys <- function(column_name, keys, default_value = -1L, combiner = "sum", dtype = tf.string) {
  tf$contrib$layers$sparse_column_with_keys(
    column_name = column_name,
    keys = keys,
    default_value = default_value,
    combiner = combiner,
    dtype = dtype
  )
}
```

Currently`dtype`'s default value is `tf.string`. It would be nice to generate `tf$string` automatically, like the following:

```
sparse_column_with_keys <- function(column_name, keys, default_value = -1L, combiner = "sum", dtype = tf$string) {
...  # save as above
}
```

**Comment by jjallaire** [comment]
Fixed via: https://github.com/rstudio/reticulate/commit/83353fe129bff27a6778001a92d1ae56366ae095

**Comment by terrytangyuan** [comment]
This is kinda trick for edge cases, e.g. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/initializers.py#L31. Also another question is how to generalize this for other python packages. But I understand manual process is necessary anyways.

**Comment by terrytangyuan** [comment]
Maybe just replace any `.` by `$`. Also a question what if we have `import someModule as ...`

**Comment by jjallaire** [comment]
Here's a commit (still on a branch) that does more aggressive conversion:

reticulate::py_function_wrapper("tf$contrib$layers$sparse_column_with_keys")

Then I thought about, "what if the value is a string and it includes a period?" :-(

Also, in the case of `dtypes$` there is no guaranteed that there is a `dtypes` object available to reference.

I think it does indeed come down to the fact that hand editing after the fact will always be necessary to do some cleanup, so we should focus conversion on automating what's time consuming and not sweat if some things aren't handled perfectly.

**Comment by terrytangyuan** [comment]
Yeah totally agree. At least the wrapper generator can save 90% time now.
