### ISSUE TITLE
What is the best way to suppress python error messages?

### ISSUE THREAD

**Issue by zachcp** [rstudio/reticulate#357]
Hi Team Reticulate,

Thanks for this great package!  

I am troubleshooting an issue in the [roto.athena](https://github.com/cloudyr/roto.athena) package where I am using python's `boto` library to check if a remote file has been created.  If the file is not yet available we wait a bit and check again. The absence of the file is therefore expected.  However, when I check for the file and its not there a python error is raised.  I would like to be able to suppress the warning. Any suggestions on the best way to do this?

[see here for original code](https://github.com/cloudyr/roto.athena/blob/master/R/execute-and-save-query.R#L112-L131)

thanks,
zach cp

```r
#  R code wrapping s3 python object
#
try(s3obj <- s3$head_object(Bucket=bucket, Key=s3key))))

if (exists("s3obj")) {
   do.stuff()
 }
```

Until the file exists, this code will generate the following error (which I would like to suppress):

```python
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

**Comment by jjallaire** [comment]
You need to catch and suppress the error in you call to `try()`. e.g. 

```r
s3obj <- try(s3$head_object(Bucket=bucket, Key=s3key), error = function(e) NULL)
if (!is.null(s3job) {
   do.stuff()
}
```

**Comment by jjallaire** [comment]
Is the error occurring during `do.stuff()` or within the `try()`. If within the `try()` I have no idea why the error isn't being caught by R!

**Comment by zachcp** [comment]
I believe its all in the `try()` code:  the `do.stuff()` code is just ` s3$download_file(Bucket = bucket, Key = s3key , Filename = local_filename)`  which downloads the file and it has a print statement that only prints on completion.  I will double check it but I'm fairly confident the issue is in the try block.

Its not a showstopping bug (the code still works) but it unfortunately gives the impression of incorrect behavior. 

Thanks again for your quick help!

**Comment by jjallaire** [comment]
Okay, I would be surprised though if it were in the try() block as there should be no way for that error to escape from there.

**Comment by zachcp** [comment]
After double-checking you are absolutely correct.  The only difference is `tryCatch` :

```
s3obj <- tryCatch(s3$head_object(Bucket=bucket, Key=s3key), error = function(e) NULL)
```

(my bonehead move was sourcing the wrong file...)
