### ISSUE TITLE
repl_python() exits automatically after running a single command

### ISSUE THREAD

**Issue by venpopov** [rstudio/reticulate#358]
I am not able to reproduce what I think is the intended behavior of repl_python(). In the example's I've seen, once you run that in the Rstudio console, you get a python console until you type exit. Instead, when I try it, the console exits automatically to the regular R console after each command. The command's output is not shown at all. Here's an example:

![image](https://user-images.githubusercontent.com/12783882/46155734-fbedd580-c245-11e8-91ba-e183e1e9eda2.png)

In contrast, it works just fine in the base R console, so it's likely some issue with Rstudio:

![image](https://user-images.githubusercontent.com/12783882/46155951-70287900-c246-11e8-8f28-585345aba4d5.png)

I'm using the latest Rstudio (1.2.1009), R 3.5.1, Python 3.6.3, and reticulate 1.10.

**Comment by kevinushey** [comment]
Thanks for taking the time to test! We just published a new version of the preview (https://www.rstudio.com/products/rstudio/download/preview/) that should contain a fix for this issue.

**Comment by venpopov** [comment]
Just tested it - works fine now!

**Comment by harryprince** [comment]
face the same issue.
