### ISSUE TITLE
Using multiple interpreters in a single session

### ISSUE THREAD

**Issue by AndyPL22** [rstudio/reticulate#380]
I've been trying to switch between two Python interpreters using reticulate. As reported in a previous issue, using `use_python` doesn't see to work. jjallaire made a comment to the effect that it was not actually possible to do this within a single session.

https://github.com/rstudio/reticulate/issues/45#issuecomment-293735624

I was wondering if there were any plans to allow this in any future versions of reticulate, or if there existed any workarounds? Would it be possible to switch between interpreters if they were contained in Conda environments, for instance?

Thanks!
Andrew

**Comment by jjallaire** [comment]
No, this just isn't the way embedded Python interpreters work.

**Comment by jjallaire** [comment]
No that's not possible either unfortunately.

**Comment by AndyPL22** [comment]
Ok, thanks for your reply
