### ISSUE TITLE
Python logging: I/O operation on closed file

### ISSUE THREAD

**Issue by grst** [rstudio/reticulate#386]
Messages sent through python's `logging` module result in a `ValueError: I/O operation on closed file` using reticulate from within rmarkdown. 

## Reproducible Example:
**[test.Rmd](https://gist.github.com/grst/a1033d21094524bd08382c275347f213#file-test-rmd)** / [test.html](https://gistpreview.github.io/?a1033d21094524bd08382c275347f213/test.html)
````
```{python}
import logging
l = logging.getLogger('test')
l.addHandler(logging.StreamHandler())
l.setLevel("INFO")
l.info("info")
```
````

```
Rscript -e "rmarkdown::render('test.Rmd', rmarkdown::html_document())"
```

## Full error message
```
## --- Logging error ---
## Traceback (most recent call last):
##   File "/storage/apps/anaconda3/lib/python3.6/logging/__init__.py", line 995, in emit
##     stream.write(msg)
## ValueError: I/O operation on closed file
## Call stack:
##   File "<string>", line 1, in <module>
## Message: 'info'
## Arguments: ()
```

**When the logger does not write to the stream, but prints messages directly, everything works fine**
```
import logging
from logging import Handler

class PrintHandler(Handler):
  def emit(self, record):
    print(self.format(record))
    
l = logging.getLogger('test2')
l.addHandler(PrintHandler())
```

## SessionInfo
```
## R version 3.4.1 (2017-06-30)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: CentOS Linux 7 (Core)
## 
## Matrix products: default
## BLAS: /storage/home/sturm/.conda/envs/single_cell_integration/lib/R/lib/libRblas.so
## LAPACK: /storage/home/sturm/.conda/envs/single_cell_integration/lib/R/lib/libRlapack.so
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_0.12.17    lattice_0.20-35 digest_0.6.16   rprojroot_1.3-2
##  [5] grid_3.4.1      jsonlite_1.5    backports_1.1.2 magrittr_1.5   
##  [9] evaluate_0.11   stringi_1.2.4   Matrix_1.2-14   reticulate_1.10
## [13] rmarkdown_1.10  tools_3.4.1     stringr_1.3.1   yaml_2.2.0     
## [17] compiler_3.4.1  htmltools_0.3.6 knitr_1.20
```

**Comment by kevinushey** [comment]
This is because `reticulate` tries to re-route Python stdout / stderr back to the R process, with the class here:

https://github.com/rstudio/reticulate/blob/813896df16dddea8acf08c25352daa1df0c87414/inst/python/rpytools/output.py#L31-L54

You can avoid this by forcing the Python logging module to use the "true" stdout / stderr; e.g.

```
l.addHandler(logging.StreamHandler(stream=sys.__stderr__))
```

It's also possible that we could improve our output remapper to better handle this case, as well -- although it's not immediately obvious to me why it fails to work in this case.

**Comment by grst** [comment]
The problem is, that sometimes one does not have direct access to the logger object, because it's hidden in some package. My current workaround retrieves all registered loggers and adds a `PrintHandler`: 

```python
def fix_logging():
    """
    Workaround for rstudio/reticulate#386.

    Get all logger instances and add a custom PrintHandler,
    as writing to Stdout doesn't seem to work.
    """
    class PrintHandler(logging.Handler):
        def emit(self, record):
            print(self.format(record))

    for name, logger in logging.Logger.manager.loggerDict.items():
        try:
            logger.handlers = []
            logger.addHandler(PrintHandler())
        except AttributeError:
            pass
```

This seems to work, but I'd really appreciate if this could be fixed within reticulate.

**Comment by grst** [comment]
Just to get this right... If I type `print()` or `sys.stdout.write()`
somewhere within a python chunk, this would also use the `OutputRemap`
to redirect the output to R?
So the error is entirely related to the way the logging module tries
to  interact with the `OutputRemap` instance?

**Comment by kevinushey** [comment]
Right -- in particular, `reticulate` overrides `sys.stdout` and `sys.stderr` with its own classes that remap output back to the R session.

More likely, the class we've provided doesn't conform with one or more of the (implicit?) requirements of the "real" `sys.stdout` object, so we need to fix up our OutputRemap class in some way.

**Comment by kevinushey** [comment]
It looks like I was off-base a bit, initially.

The issue comes down to the way we override stdout / stderr in `py_capture_output()` when evaluating code. I think I have an idea for a fix and will explore tomorrow.
