### ISSUE TITLE
py_to_r

### ISSUE THREAD

**Issue by kasakh** [rstudio/reticulate#387]
I am not sure why `py_to_r` is not working. 

This is the example I am trying: 

```
np <- import("numpy", convert = FALSE)
py_to_r(np$array(c(1,2,3)))
#output is still [1. 2. 3.]
```

**Comment by kasakh** [comment]
This is the output of `py_config()`

python:         C:\Users\xxxx\AppData\Local\CONTIN~1\ANACON~1\python.exe
libpython:      C:/Users/xxxx/AppData/Local/CONTIN~1/ANACON~1/python37.dll
pythonhome:     C:\Users\xxxx\AppData\Local\CONTIN~1\ANACON~1
version:        3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]
numpy:          C:\Users\xxxx\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\numpy\__init__.p

python versions found: 
 C:\Users\xxxx\AppData\Local\CONTIN~1\ANACON~1\python.exe
 C:\Users\xxxx\AppData\Local\Continuum\anaconda3\python.exe

**Comment by kevinushey** [comment]
I'm not able to reproduce. Can you provide more information (e.g. `sessionInfo()`)?

``` r
> library(reticulate)
> np <- import("numpy", convert = FALSE)
> py_to_r(np$array(c(1,2,3)))
[1] 1 2 3
```

**Comment by kasakh** [comment]
This is the output of `sessionInfo()`

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.10

loaded via a namespace (and not attached):
[1] compiler_3.5.1  Matrix_1.2-14   tools_3.5.1     Rcpp_0.12.19    grid_3.5.1      jsonlite_1.5   
[7] lattice_0.20-35
```

**Comment by kasakh** [comment]
As evident, the problem is being caused because `reticulate` is not able to recognize the numpy installation. I had to delete R and Rstudio, remove any residual folders first. I reinstalled the latest R and RStudio, installed the reticulate package. Immediately, run this command `py_install("numpy")`. This solved the problem by creating a new conda env called `r-reticulate`. I had to activate this new conda env before it started working. You may need to install/load again all the required packages in this new env.
