### ISSUE TITLE
How to use the whole numpy as a library?

### ISSUE THREAD

**Issue by mnar53** [rstudio/reticulate#408]
In RStudio, after 
`   numpy <- import("numpy")`
then numpy functions are all available: in fact, after typing numpy$, the list of all functions shows up, with their signatures. I am using BERT to make functions visible to Excel, and for a normal package, e.g. gsl, this function makes it all:

```
usepkg <- function (pkg) {
  env = as.environment(paste0('package:',pkg ))
  lapply( ls(env,pkg ), function(name){
    newname <- paste0( pkg, '.', name )
    cat(paste0(newname, "\n"))
    func <- get( name, envir=env)
    if( is.function( func )){
      assign( newname, func, .GlobalEnv )
    }
  })
}
```
A call like usepkg("gsl") clones the gsl functions in the global environment, and this make them visible to Excel. Unfortunately, the same for numpy bumps on the first line, _'no item called "package:numpy" on the search list'_.

Is it possible to make this working?

**Comment by mnar53** [comment]
@kevinushey:

Sure it helps. It seems is.function() returns also numpy types and other non-functions, so probably the test should be
```

  if (is.function(func))
    if (grepl("func", class(func)[1], fixed=TRUE)) { ......
```
Now i'm struggling how to find, for each functions, their arguments, in order to have the assign done with the full signature. Till now, no luck.

**Comment by kevinushey** [comment]
It's unfortunately not simple. `numpy` complicates things further since some Python functions are really just wrappers to C functions under the hood, and those functions don't expose their arguments to `inspect`:

``` r
> library(reticulate)
> numpy <- import("numpy")
> inspect <- import("inspect")
> inspect$getargspec(numpy$abs)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: <ufunc 'absolute'> is not a Python function 
```

Unfortunately this is just a difficult problem to solve (your best hope is to parse the received arguments from the `numpy` help documentation)

**Comment by mnar53** [comment]
But still RStudio knowns how to do it. I should check its source code, but sure it will not be easy. May be it is easier try to do all the job in python, for example

```
import inspect
 
def describe(obj):
    try:
        return inspect.getargspec(obj).args
    except:
        # from https://tomassetti.me/python-reflection-how-to-list-modules-and-inspect-functions/

        # Built-in functions cannot be inspected by
        # inspect.getargspec. We have to try and parse
        # the __doc__ attribute of the function.
        docstr = obj.__doc__
        args = ''
        if docstr:
            items = docstr.split('\n')
            if items:
                func_descr = items[0]
                s = func_descr.replace(obj.__name__,'')
                idx1 = s.find('(')
                idx2 = s.find(')',idx1)
                if idx1 != -1 and idx2 != -1 and (idx2>idx1+1):
                    args = s[idx1+1:idx2]
        return args


import numpy
print 'arange: ', describe(numpy.arange)
print 'abs: '   , describe(numpy.abs)
print 'any:    ', describe(numpy.any)

```
This produces something like

```
arange:  [start,] stop[, step,], dtype=None
abs:  x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]
any:     ['a', 'axis', 'out', 'keepdims']
```
 I've chosen a ufunc, a built-in and a regular function, in all cases I've at least something to start to work with. I've not checked how to do it, but i'm sure that reticulate can load the describe function and then use it, right?

**Comment by kevinushey** [comment]
RStudio has a private function used for this:

``` r
> .rs.python.getNumpyFunctionArguments
function (object) 
{
    docs <- reticulate::py_get_attr(object, "__doc__")
    if (inherits(docs, "python.builtin.object")) 
        docs <- reticulate::py_to_r(docs)
    pieces <- strsplit(docs, "\n", fixed = TRUE)[[1]]
    first <- pieces[[1]]
    munged <- paste(gsub("[^(]*[(]", "function (", first), "{}")
    parsed <- parse(text = munged)[[1]]
    names(parsed[[2]])
}
```

Looks like your Python implementation basically does what we do at the R level :-)

**Comment by mnar53** [comment]
Thanks, I'll have a look at it!
