### ISSUE TITLE
discrepancies when calculating "e"

### ISSUE THREAD

**Issue by xslates** [rstudio/reticulate#409]
Hi,

While trying to plot the constant "e" in Python chunk using Reticulate in .Rmd I stumbled on this case.

```{python}
def rate(n):
    growth = (1 + 1 / n) ** n
    return growth
    
growth = [rate(n) for n in range(1, 8760)]
print(growth)
```
Returns a list of [2, 1, 1, 1, 1, .....]

<img width="891" alt="screen shot 2018-12-19 at 19 29 26" src="https://user-images.githubusercontent.com/8994002/50240209-74d37800-03c4-11e9-806c-7456b49f8e9c.png">

Yet, running this in the console:

```{r}
(1 + 1 / 8) ** 8
```
Returns 2.566 (which is what one would expect).

What am I missing to adjust this?

My `sessionInfo()`

R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

**Comment by eddelbuettel** [comment]
Int versus double, use

```py
def rate(n):
    growth = (1.0 + 1.0 / n) ** n
    return growth

growth = [rate(n) for n in range(1, 8760)]
print(growth)
```

But this is not really a good question for this forum.

**Comment by xslates** [comment]
Thank you. I understand, I thought maybe I was missing some behavior in the settings of Reticulate or something.
