### ISSUE TITLE
No warning when use_* functions have no effect

### ISSUE THREAD

**Issue by jmcphers** [rstudio/reticulate#418]
### Repro

1. Start a fresh R session.
2. Run `reticulate::use_python("/path/to/pythonA")`
3. Run `reticulate::py_run_string("print sys.version")`
4. Run `reticulate::use_python("/path/to/pythonB")`
5. Run `reticulate::py_run_string("print sys.version")`

### Observe

The Python version has not changed; the second `use_python()` directive has no effect, and the first Python version remains active.

### Expected

I ran into this while testing the reticulate behavior in R notebooks, wherein it seemed like `use_python` wasn't being respected (see https://github.com/rstudio/rstudio/issues/4130). It turns out that I'd been running a Python chunk (which implicitly loaded the default Python) before calling `use_python` -- too late; once a Python version is loaded, you can't change it without a restart. However, it took quite a bit of trial and error to discover why `use_python()` wasn't doing anything.

It seems like the `use_*` family should either: 

1. allow for switching at runtime between Pythons, perhaps with a warning/force flag so that, if Python is already loaded and differs from the requested version, the caller acknowledges that the session will be ended and state cleared in order to switch, or
2. emit a warning when trying to invoke the `use_*` family when Python is already loaded.

**Comment by jjallaire** [comment]
You unfortunately can't switch Python versions at runtime (there isn't really a way around this either as Python versions don't unload well w/o degenerative side effects)

The problem w/ the warning is that if you source a script over and over again (very common) you will be presented with a warning every time you source the script!

There is a `required` flag on `use_python()` which you can use to elevate priority and force printing of a warning if the version isn't found.

**Comment by terrytangyuan** [comment]
Perhaps we should change the default for `required` to be `TRUE` for better user experience, especially for first-time users?

**Comment by jmcphers** [comment]
>  if you source a script over and over again (very common) you will be presented with a warning every time you source the script!

I was thinking that the warning would only be printed if your `use_*` directive is requesting a change in Python versions -- in other words, no warning if you ask it to use the same thing it's currently using. What do you think about that approach?

**Comment by jmcphers** [comment]
> So the philosophy is very much "we'll find the version of Python you need" rather than "tell us where Python is" (thus the choice to make the use functions advisory).

This makes a lot of sense; I think I was just expecting these functions to be more prescriptive than they actually are (and/or getting somewhat confused about the state of the Python session). I think in the next release of the RStudio IDE we could surface more information about the Python session (is it loaded? from where? etc.) in the UI to help people understand what's going on, but short of having more prescriptive variants it doesn't sound like there's any real work to be done in `reticulate` itself.

**Comment by jjallaire** [comment]
I definitely think that we could do a better job educating people about how exactly those functions work as well as the use of `required`.

I think that for RStudio v1.3 we might want to consider a prompted download of miniconda (as that would provide a more standardized baseline than the current "whatever we find on the path" regime).
