### ISSUE TITLE
What is under the hood ?

### ISSUE THREAD

**Issue by nestordemeure** [rstudio/reticulate#42]
Hello,

Is it possible to get some (minimal) documentation on how exactly reticulate works under the hood ?

(Congratulation on developing reticulate, it is an impressive package :) )

**Comment by jjallaire** [comment]
Minimal docs are right here: ;-)

https://github.com/rstudio/reticulate/blob/master/src/python.cpp

**Comment by nestordemeure** [comment]
Minimal indeed, being unfamiliar with R and python C++ interop mechanisms, it is hard to understand.

A short list of the steps taken by the package (without further explanations) would be nice to grasp the concept and be able to tackle the .cpp files :)

**Comment by eddelbuettel** [comment]
"The steps taken by the package": well, that _is_ what the code is for.  

Everybody is busy, and the code still changes a lot at this stage, so you may be asking for something nobody has time to  add. It's not because we're mean, it's just the nature of the beast. Well-crafted  contributions are always welcome, and that can be on the code, test or documentation level.

**Comment by nestordemeure** [comment]
Don't fear being mean. I was just looking for a global view, a shortcut, to understand the code (a short bullet list is enough).
If I end up putting it together, I will submit a pull request with a small paragraph of documentation.

**Comment by jjallaire** [comment]
We basically use R (via Rcpp) to drive the Python C API. Beyond that if you aren't familiar with the R and Python C interop layers there is a lot of context to explain. If you start by studying the r_to_py (https://github.com/rstudio/reticulate/blob/master/src/python.cpp#L902) and py_to_r (https://github.com/rstudio/reticulate/blob/master/src/python.cpp#L585) functions and lookup the docs on the various C functions you should get the hang of it.
