### ISSUE TITLE
Calling Python Function in R Script Returns Empty DataFrame

### ISSUE THREAD

**Issue by lopezj1** [rstudio/reticulate#420]
I have a python script with several functions such as:
```
import pyodbc
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
from matplotlib.lines import Line2D
import matplotlib.patches as mpatches
sns.set(style="darkgrid")
plt.tight_layout

#SQL Server Connection String, works
con = pyodbc.connect(driver = '{SQL Server}',
                     server = 'db\sqlexpress', 
                     database = 'db',
                      )

def mixq(proj, con):
    '''
    (int) -> pandas dataframe
    
    Arguments:
    proj - int containing project #
    con - connection string to database
    
    Output: Dataframe of ASTM compression strength results for project passed into function
    '''
    sql = "SELECT * FROM qrymixquality"

    mix_df = pd.read_sql(sql,con) #<----Need to sort
    mix_df = mix_df[mix_df['Project'].str.contains(str(proj))]
    mix_df.reset_index(inplace=True)
    mix_df.reset_index(inplace=True)
    mix_df.drop(columns ='index', inplace=True)

    return mix_df
```

I'm calling this function in an R script, but it returns an empty dataframe each time.  I've tried modifying the number of columns/types returned by the python dataframe and modified the parameters in the reticulate function source_python, namely envir and convert with no luck.  It would be a huge timesaver to get this working as I can do most of the wrangling in Python and use R just for specific packages not available in Python.  To mitigate this I've been copy the output of python into an excel file then grabbing it in R using the xlsx package.

Any help on this would be appreciated.  The headers are correctly brought into R but not the data.

```
library(reticulate)
library(esquisse)
library(xlsx)
library(qcc)
use_condaenv("C:/Users/jlopez/AppData/Local/Continuum/anaconda3")

py_run_file("C:/Users/jlopez/Documents/python_scripts/TempEffectRuns.py")
source_python("C:/Users/jlopez/Documents/python_scripts/TempEffectRuns.py", envir = globalenv(), convert = FALSE) #python script containing function

#---------------Get Dataframes from Python----------------------------
mix_df <- mixq(40, con)  #use function mixq() from python and store into R dataframe mix_df
```
![image](https://user-images.githubusercontent.com/18203036/51121735-23ad7d00-17e6-11e9-9f56-9a8fa947c32d.png)

Output:
```
> mix_df
Empty DataFrame
Columns: [level_0, Sample ID, Batch Size (kg), Mix Temperature, Mix Humidity, Mix Added, Water Added, Green Density, Paver Height, Ambient Temp (C), Ambient RH (%), Paver Type, Mold, Customer, Project, Experiment, Project/Experiment]
Index: []
> 
```

From python, these are the column types in the dataframe
```
mix_df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 17 columns):
level_0               10 non-null int64
Sample ID             10 non-null object
Batch Size (kg)       10 non-null float64
Mix Temperature       10 non-null float64
Mix Humidity          10 non-null float64
Mix Added             10 non-null float64
Water Added           10 non-null float64
Green Density         5 non-null float64
Paver Height          5 non-null float64
Ambient Temp (C)      10 non-null float64
Ambient RH (%)        10 non-null float64
Paver Type            10 non-null object
Mold                  10 non-null object
Customer              10 non-null object
Project               10 non-null object
Experiment            10 non-null object
Project/Experiment    10 non-null object
dtypes: float64(9), int64(1), object(7)
memory usage: 1.4+ KB
```

I am using the following:
RStudio Version 1.2.1206
R version 3.5.2 (2018-12-20)
Spyder 3.2.8 (Python)
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Windows 10

**Comment by kevinushey** [comment]
It's hard for us to give any concrete advice without a minimally reproducible example.

Do other examples of creating a DataFrame work for you? Or just this particular way of creating your DataFrame?

**Comment by lopezj1** [comment]
Kevin, I just attached a basic example which functions properly, so there must be an issue with the structure/datatypes in my pandas dataframe I'm assuming?  I am pretty new to R, so that is the only way I've tried to create a dataframe.  Although the assignment does not matter, since executing mixq(40, con) returns an empty dataframe, I guess the conversion is failing.

[reticulatetest.zip](https://github.com/rstudio/reticulate/files/2756983/reticulatetest.zip)

**Comment by lopezj1** [comment]
Any suggestions on creating dataframes in different way?

**Comment by kevinushey** [comment]
Do you have any better luck e.g. creating the Pandas DataFrame in the Python global environment (e.g. as a variable called `data`), and then accessing that object with e.g. `py$data`?

**Comment by lopezj1** [comment]
Kevin, that worked! However, I need this function call to be dynamic given inputs from within R.  I noticed now that there is an error now when I try to view variable con in R

![image](https://user-images.githubusercontent.com/18203036/51563430-68768b00-1e5a-11e9-9f11-792d253354f6.png)

It's weird since even though there is an error it is still picking up the header names just no data.  I also tried placing the py$ infront of con with same result.

![image](https://user-images.githubusercontent.com/18203036/51563860-885a7e80-1e5b-11e9-8408-8a424ad555d7.png)

**Comment by kevinushey** [comment]
Interesting! At least this gives us a toe-hold on the issue. Ultimately, I think your original code should work, though. Any chance you can provide a minimally reproducible example (e.g. define a Python function that returns a Pandas DataFrame, that is then imported and run in R) so I might easily copy + paste to reproduce on my own machine?

I'm not sure what might be going on with `View()`, but I'm fairly sure it would only accept R objects in the first place. If you want to view a Python object you likely have to explicitly convert it with `py_to_r()` first (assuming conversion is possible).

**Comment by lopezj1** [comment]
Kevin, I stumbled on the potential source of the issue, but don't understand why it is happening:

If I comment out the following line of code in each function:
```
#csa_df = csa_df[csa_df['Project'].str.contains(str(proj))]
#split_df = split_df[split_df['Project'].str.contains(str(proj))]
```
I am able to get the returned dataframe in R with:
```
csa_df <- py$csa(40, con)  #use function csa() from python and store into R dataframe csa_df
split_df <- py$split(40, con)  #use function split() from python and store into R dataframe split_df 
```

But if I make these lines of code active, it returns an empty dataframe.  Attached is a zip file containing an excel file with the SQL output, a python file with one function, and an R file with pulling in the dataframe.  This way you can reproduce on your end.  If you comment out the .str.contains() line you will see that it function properly, otherwise it does not.
[reticulatetest1.zip](https://github.com/rstudio/reticulate/files/2788250/reticulatetest1.zip)


In python:

```
def csa(proj, con):
    '''
    (int) -> pandas dataframe
    
    Arguments:
    proj - int containing project #
    con - connection string to database
    
    Output: Dataframe of csa compression results for project passed into function
    '''
    sql = "SELECT * FROM qryLabCompressionCSA"

    csa_df = pd.read_sql(sql,con) #<----Need to sort
    #csa_df = csa_df[csa_df['Project'].str.contains(str(proj))]
    csa_df.reset_index(inplace=True)
    csa_df.reset_index(inplace=True)
    csa_df.drop(columns ='index', inplace=True)

    return csa_df
#%%
def split(proj, con):
    '''
    (int) -> pandas dataframe
    
    Arguments:
    proj - int containing project #
    con - connection string to database
    
    Output: Dataframe of split tensile strength results for project passed into function
    '''
    sql = "SELECT * FROM qryLabTensile"

    split_df = pd.read_sql(sql,con) #<----Need to sort
    #split_df = split_df[split_df['Project'].str.contains(str(proj))]
    split_df.reset_index(inplace=True)
    split_df.reset_index(inplace=True)
    split_df.drop(columns ='index', inplace=True)

    return split_df
```

**Comment by kevinushey** [comment]
Here's a standalone example that works fine for me:

``` r
library(reticulate)

py_run_string("
import pandas
import seaborn

iris = seaborn.load_dataset('iris')
species = iris.species
virginica = iris.species.str.contains('virginica')
")

py$iris
py$species
py$virginica
```

Can you build a reproducible example using the built-in `iris` dataset from seaborn?

**Comment by kevinushey** [comment]
Okay, I understand the problem now. The issue is you're passing a floating-point number from R to be used as an index, instead of an integer. When you convert the floating point number to a string, you don't get the index you expect.

```
> library(reticulate)
> py_run_file("reticulatetest.py")
> py$data_load(40)
40.0
[1] String Name   Date   ID    
<0 rows> (or 0-length row.names)
```

Try explicitly converting your ID to integer (`as.integer()`) or using the `L` suffix for integer literals.

**Comment by lopezj1** [comment]
Kevin, that was it! Thanks a lot for the help, this will really save me some time.

**Comment by kevinushey** [comment]
Glad we could get to the bottom of this!
