### ISSUE TITLE
Save Python Module

### ISSUE THREAD

**Issue by 2005m** [rstudio/reticulate#424]
Hi, 
I was wondering if there is a way to save a python module in a rds or RData file after importing it with reticulate::import? 
When i tried to do it, after loading the file in an new R session, I had a <pointer: 0×0>.

Thank you

**Comment by kevinushey** [comment]
Unfortunately no this is not possible.

Your best bet would be to save the Python objects with e.g. [pickle](https://docs.python.org/3/library/pickle.html), and then later load them again with [pickle](https://docs.python.org/3/library/pickle.html) and re-generate the R bindings on demand.
