### ISSUE TITLE
running command had status 1

### ISSUE THREAD

**Issue by InazeaAnazasi** [rstudio/reticulate#425]
I was redirected here from [spacyr](https://github.com/quanteda/spacyr/issues/155). Calling `spacy_install()` gives me 

    Error: Error 1 occurred while checking for python architecture
    In addition: Warning message:
    In system2(python, stdout = TRUE, args = c("-c", shQuote("import sys; import platform;     sys.stdout.write(platform.architecture()[0])"))) :
    running command '"C:\Users\ljsch\AppData\Local\Enthought\Canopy\User/python.exe" -c "import sys;     import platform; sys.stdout.write(platform.architecture()[0])"' had status 1

I followed amatsuo's instructions to check whether the error may be caused by reticulate:

> It seems that the error is coming from reticulate package. I am not sure why this is happening but you might try setting up a conda environment manually and check if you can access to the env from R through reticulate.
> 
> On the console, create a new env by entering:
> 
> `conda create --name testenv python=3.6`
> 
> Then in R
> 
> `library(reticulate)`
> `use_condaenv("testenv")`
> `py_run_string("print(1)")`
> 
> Do you get any error while executing the code above? If you do, I'd recommend posting the issue on the reticulate page.

I got the exact same error from the last command, opening RStudio as an administrator. What may cause the problem?

**Comment by kevinushey** [comment]
What happens if you try to run that same code from a Windows command console?

```
"C:\Users\ljsch\AppData\Local\Enthought\Canopy\User/python.exe" -c "import sys; import platform; sys.stdout.write(platform.architecture()[0])"'
```

**Comment by InazeaAnazasi** [comment]
`ImportError: No module named site`

**Comment by kevinushey** [comment]
https://stackoverflow.com/questions/5599872/python-windows-importerror-no-module-named-site suggests that you need to set the PYTHONHOME environment variable.

**Comment by InazeaAnazasi** [comment]
I got the problem - I had an errant `PATH` variable from an earlier installation of Python - [this blog entry](https://codepunk.io/fatal-python-error-py_initialize-unable-to-load-the-file-system-codec-modulenotfounderror-no-module-named-encodings/) solved it for me. Thanks for your help!
