### ISSUE TITLE
r_to_py does not support python set object

### ISSUE THREAD

**Issue by shuaiwang88** [rstudio/reticulate#438]
is there a way to convert any R object to python's set object?

**Comment by jjallaire** [comment]
Try this:

```r
library(reticulate)
pybuiltins <- import_builtins()
pybuiltins$set(list(1,2,3))
```

**Comment by shuaiwang88** [comment]
> Try this:
> 
> ```r
> library(reticulate)
> pybuiltins <- import_builtins()
> pybuiltins$set(list(1,2,3))
> ```

Thank you so much! It saves my day!
