### ISSUE TITLE
can't find python27.dll when python installed for all users on windows

### ISSUE THREAD

**Issue by jjallaire** [rstudio/reticulate#44]
It's in windows\system and we aren't looking for it there.

**Comment by JimmyG3** [comment]
Ran into the same issue.  Uninstalled Python, then installed Miniconda, [https://conda.io/miniconda.html](url), and it's working now.

**Comment by jjallaire** [comment]
fixed via https://github.com/rstudio/reticulate/commit/71455af538d24ed87d192ac9d11ee3b2f165c79a
