### ISSUE TITLE
use_virtualenv can't find venv/bin?

### ISSUE THREAD

**Issue by zkurtz** [rstudio/reticulate#453]
Context: On OSX with a virtualenv named "venv" and an anaconda installation in the background (outside of venv)

Problem: Importing my python module as `reticulate::import("mymodule")` was complaining about not being able to find matplotlib even after running `use_virtualenv("/Users/me/mypackage/venv")`. This problem occurred in Rstudio but did not occur from a terminal R session initiated inside of the activate virtual environment.

Temporary solution: Basically the same as suggested in https://github.com/rstudio/reticulate/issues/367, which is to tell reticulate to look inside of venv/bin by updating the system PATH before loading the library:
```
vbin = "/Users/me/mypackage/venv/bin"
Sys.setenv(PATH= paste(vbin,Sys.getenv()["PATH"],sep=":"))
library(reticulate) 
```

**Comment by kevinushey** [comment]
Can you run `py_config()` to confirm that reticulate was indeed using the virtual environment as you expected?

**Comment by zkurtz** [comment]
Running `py_config()` showed that it was pointing to a random conda environment. I don't see how my virtualenv could have become associated with that conda env. Anyway, I removed that conda env and now my virtualenv works again with `use_virtualenv`.
