### ISSUE TITLE
converting python hex numbers to R hex

### ISSUE THREAD

**Issue by fkgruber** [rstudio/reticulate#465]
Hi
I'm using a function in python to generate variable integer encoding of a number. The number returns a hex number. 
```
library(reticulate)
goog2 = import("google.protobuf.internal.encoder")
varintbytes = goog2$`_VarintBytes`
> varintbytes(128L)
b'\x80\x01'
```

the problem is that the return object is not an R object:
```
class(varintbytes(128L))
[1] "python.builtin.bytes"  "python.builtin.object"
```

I would like to convert this to the R equivalent:
`"\x80\x01"`

How can I do this?

By the way I tried converting to character but this create a mess:
 

`"b'\\x80\\x01'"`

now I'm unable to remove the double backslashes.

Thanks
FKG

**Comment by kevinushey** [comment]
`reticulate` has a converter for byte arrays, so one simple workaround here would be to convert your object to a `bytearray` object and return that to R:

``` r
library(reticulate)
py_eval("bytearray(b'a\\000b\\000c')")
#> [1] 61 00 62 00 63
```

<sup>Created on 2019-03-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by kevinushey** [comment]
That said, I don't see a reason why we couldn't make this "just work" for regular old `bytes`.

**Comment by fkgruber** [comment]
Thanks! That solves my problem!  I agree that it would be nice if bytes would be converted to R format.
