### ISSUE TITLE
Create a dictionary of numpy arrays

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/reticulate#47]
Is there a way to create a dictionary of numpy arrays? I tried the following but didn't work as expected:

```
> dict(length=matrix(iris$Sepal.Length))
function (x)  .Primitive("length")
Error in py_dict(keys, values, convert = convert) : 
  Unable to convert R object to Python type
```

Basically, I am looking for a way to convert an R data.frame to a dictionary of numpy arrays

**Comment by jjallaire** [comment]
It's because 'length' was getting interpreted as the length function (since we allow python dicts to have non-string keys). Fixed here: https://github.com/rstudio/reticulate/commit/867b7759f02af9c85a65d5ac9a79b8bd56f6fa8c
