### ISSUE TITLE
Conda warnings taken as errors

### ISSUE THREAD

**Issue by dougmet** [rstudio/reticulate#477]
Hi, not sure if this is the right repo, I actually experienced this problem in keras but thought this might be the source.

In conda 4.6.11 [there is a bug](https://github.com/conda/conda/issues/8512#issuecomment-480516713) whereby a deprecation warning is being printed to stderr. This warning isn't a problem to a python user (beyond being annoying) but it's bringing down the R connection.

This seems similar to #65 and I wonder if there's anything that can be done to carry on for warnings, or whether the fix really needs to come from the conda side?

**Comment by jjallaire** [comment]
We have a fix for this here: https://github.com/rstudio/reticulate/commit/01e22ce051c07f9da2d71316691c0a4c9214f902

Could you try installing from master to see whether this resolves the issue on your end?

**Comment by dougmet** [comment]
Apologies, should have tried fresh install from master before posting. That did get me round this issue -- thanks! It's fallen over further down stream, but it's probably a different issue:

```
> keras::install_keras()
Creating r-tensorflow conda environment for TensorFlow installation...
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: ...working... failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/noarch/repodata.json.bz2>
Elapsed: -
```

Works no problem from normal conda (ie conda install keras) mind but by all means close here. Thanks for the quick response!

**Comment by kevinushey** [comment]
Thanks for confirming! We're planning to submit to CRAN soon with a bugfix for this issue.

**Comment by dougmet** [comment]
Just a quick update for future googlers. conda has been updated to get rid of that silly warning, so upgrading conda is an alternative. Also the error I still had above was not related to this at all, but rather a Windows/SSL thing, which broke both pip and conda. By upgrading my git-for-windows installation everything started working again.

**Comment by NayeerSiddiquee** [comment]
Is this issue has been solved? I am facing this warning today.

**Comment by kevinushey** [comment]
It should be resolved as long as you are using either the latest version of reticulate or latest version of conda.
