### ISSUE TITLE
Storing python functions in .RData for packaging

### ISSUE THREAD

**Issue by nutle** [rstudio/reticulate#493]
Just as in an ordinary session, where I am able to ``source_python('py/script.py')``, is it possible to somehow store and load these functions in a custom R package? 

The problems I've encountered so far:
1. Defining ``source_python`` in ``.onLoad`` doesn't seem to work, since reticulate is looking at a local ``py`` dir for the files, but not the inner dirs of the package.
2. Saving sourced functions in an environment, and exporting them to ``data/x.rda`` doesn't seem to work too, since it probably exports a pointer only, but not the whole function.

The main idea I'm looking for here -- hiding all reticulate stuff in the back end inside a custom R package, so that the end user would only need to load the package and run one R wrapper function. Is this possible?

**Comment by jjallaire** [comment]
See https://rstudio.github.io/reticulate/articles/package.html

**Comment by nutle** [comment]
@jjallaire The article seems to only cover wrapping existing packages through import, but not custom scripts. Am I missing something? 

Thanks

**Comment by jjallaire** [comment]
Use import_from_path (and system.file to locate the file within your
installed package):
https://rstudio.github.io/reticulate/reference/import.html

**Comment by nutle** [comment]
@jjallaire Thank you! ``system.file`` seems to do the trick!
