### ISSUE TITLE
Python errors in rmarkdown notebook chunks show: Evaluation error: option error has NULL value.

### ISSUE THREAD

**Issue by danielfrg** [rstudio/reticulate#494]
In a notebook like this:

    ---
    title: "R Notebook"
    output: html_notebook
    ---

    ```{r}
    library(reticulate)
    use_python("/Users/danielfrg/workspace/dinero/.venv/bin/python")
    ```

    ```{python}
    import pandas
    ```
Gives me:

```
Evaluation error: option error has NULL value.
```

Doing it in the R session would give me the error I would be expecting.

```
> pd <- import("pandas")
Error in py_module_import(module, convert = convert) : 
  ImportError: No module named pandas
```

The same thing happens for other Python errors on the notebook cells. Not sure if this is config on my side.

**Comment by davidlieberman** [comment]
Getting the same issues on my end as well

**Comment by Jesse-Kerr** [comment]
Also have the same issue

**Comment by shermstats** [comment]
I'm getting this issue as well, but only when I'm working in an RStudio project.  The exact same code works fine when I'm working outside a project.

**Comment by kevinushey** [comment]
Should be fixed in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/).

**Comment by nehadeshmukh9134** [comment]
Check your rstudio version , library reticulate works fine in the version 1.2.1555.1
