### ISSUE TITLE
Python not detected when using venv with python3

### ISSUE THREAD

**Issue by cboettig** [rstudio/reticulate#495]
I'm on Debian 9 with a nice python3 venv setup which I'd like reticulate to use.  I've installed `python3-venv` and set my `venv` location to a system file, `/opt/venv` which the user also has write access to.  

```
python3 -m venv /opt/venv
```

I've also put the venv python at the top of my PATH.  At the command-line, `python --version` shows python 3.5 as expected (from /opt/venv/bin/python).  From R, `py_discover_config()` also shows this version of python, just as expected:

```
> py_discover_config()
python:         /opt/venv/bin/python
libpython:      [NOT FOUND]
pythonhome:     /usr:/usr
version:        3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]
numpy:          /opt/venv/lib/python3.5/site-packages/numpy
numpy_version:  1.16.3

python versions found: 
 /usr/bin/python3
 /opt/venv/bin/python
 /usr/bin/python
```

But then I run `py_config()` and I just get an error that python cannot be found:

```r
> py_config()
Error in initialize_python(required_module, use_environment) : 
  Python shared library not found, Python bindings not loaded.

```

I believe I am experiencing the same issue as #194, where it seemed `venv` support for python3 had not yet been implemented, but it appears that was resolved by #370.  Perhaps the remaining issue is that `reticulate` cannot use system-level `venv` paths but assumes they are under the user's home path?  (I think that is the gist of the still open #393 which may be the same issue I have, though I couldn't quite follow it). 

Here's `sessionInfo()`:

```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.12

loaded via a namespace (and not attached):
[1] compiler_3.6.0  Matrix_1.2-17   Rcpp_1.0.1      grid_3.6.0     
[5] jsonlite_1.6    lattice_0.20-38
> 
```

Thanks!

**Comment by cboettig** [comment]
Just a follow-up note that the issue persists if I switch to using a home directory-based location, e.g. `py_discover_config()` finds the venv python in my home directory location (`/home/rstudio/.venv/bin/python`): 

```r
> py_discover_config()
python:         /home/rstudio/.venv/bin/python
libpython:      [NOT FOUND]
pythonhome:     /usr:/usr
version:        3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]
numpy:          /home/rstudio/.venv/lib/python3.5/site-packages/numpy
numpy_version:  1.16.3
```

but once again `py_config()` just throws the same error.  Setting `Sys.setenv("RETICULATE_PYTHON"="/home/rstudio/.venv/bin/python")` or `use_python("/home/rstudio/.venv/bin/python")` does not change any of this either.  

Also, I'll just note if I `apt-get install python-virtualenv python-pip` (i.e. Python 2.7 version, not 3.5), `reticulate` has no trouble finding them, it's just that I can't get `reticulate` to work with python3 and `venv`.

**Comment by cboettig** [comment]
Looks like my problem was due to lacking `libpython3-dev`, didn't realize the dev libs were also needed for reticulate, though I suppose that should have been obvious from the error message.  My apologies!

**Comment by stevesolun** [comment]
It can be solved using: 
sudo apt install git libpython3.7-dev

**Comment by lc822** [comment]
I am having exactly this issue on a Mac (Catalina).  What is the solution here?

When I run `py_discover_config()`, I get:
> python:         /Users/lucy/Rprojects/10x/renv/python/virtualenvs/renv-python-3.7.3/bin/python
> libpython:      [NOT FOUND]
> pythonhome:     /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7:/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7
> version:        3.7.3 (default, Apr 24 2020, 18:51:23)  [Clang 11.0.3 (clang-1103.0.32.62)]
> numpy:          /Users/lucy/Rprojects/10x/renv/python/virtualenvs/renv-python-3.7.3/lib/python3.7/site-packages/numpy
> numpy_version:  1.19.0

**Comment by kevinushey** [comment]
@lc822: Are you able to bind to the version of Python provided with Xcode directly? What is the output of the following?

```
python <- "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/bin/python3"
reticulate::use_python(python, required = TRUE)
reticulate::py_config()
```

FWIW, I see:

```
> reticulate::py_config()
python:         /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/bin/python3
libpython:      /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/libpython3.7.dylib
pythonhome:     /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7:/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7
version:        3.7.3 (default, Apr 24 2020, 18:51:23)  [Clang 11.0.3 (clang-1103.0.32.62)]
numpy:          /Users/kevinushey/Library/Python/3.7/lib/python/site-packages/numpy
numpy_version:  1.17.3
```

I wonder if that copy of Python is missing `libpython3.7.dylib` for some reason, or something like that?

**Comment by kevinushey** [comment]
Ultimately though, I would recommend avoiding the version of Python provided by Xcode as it might change as Xcode is updated or changed.

**Comment by lc822** [comment]
Thank you, I have got somewhere to improving the situation, but Seurat still doesn't seem to be able to find the Leiden algorithm.

I added `RETICULATE_PYTHON="/usr/local/bin/python3"` to my ~/.Renviron file to use my Python installation from Homebrew.

And I created a virtual python environment to use with renv and installed the required python packages with pip:
`renv::use_python()`

`reticulate::py_discover_config()` now gives:

> python:         /Users/lucy/R_projects/10x/renv/python/virtualenvs/renv-python-3.8.3/bin/python
> libpython:      /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/config-3.8-darwin/libpython3.8.dylib
> pythonhome:     /usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8:/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8
> version:        3.8.3 (default, Jul  8 2020, 14:27:55)  [Clang 11.0.3 (clang-1103.0.32.62)]
> numpy:          /Users/lucy/R_projects/10x/renv/python/virtualenvs/renv-python-3.8.3/lib/python3.8/site-packages/numpy
> numpy_version:  1.19.0
> 
> NOTE: Python version was forced by RETICULATE_PYTHON

`python:` is pointing to my Python virtual environment, which is where I have installed `leidenalg` and `igraph`.

Any suggestions?

Thanks!
Lucy

`pip freeze` in this virtual environment gives:
> appnope==0.1.0
> backcall==0.2.0
> decorator==4.4.2
> igraph==0.1.11
> ipython==7.16.1
> ipython-genutils==0.2.0
> jedi==0.17.1
> leidenalg==0.8.1
> numpy==1.19.0
> parso==0.7.0
> pexpect==4.8.0
> pickleshare==0.7.5
> prompt-toolkit==3.0.5
> ptyprocess==0.6.0
> Pygments==2.6.1
> python-igraph==0.8.2
> six==1.15.0
> texttable==1.6.2
> traitlets==4.3.3
> wcwidth==0.2.5

However, for some reason, Seurat still can't find the Leiden algorithm.  When I run `FindClusters(object = sample, resolution = 0.3, algorithm = 4)`, I get the error:
> Error: Cannot find Leiden algorithm, please install through pip (e.g. pip install leidenalg).

**Comment by kevinushey** [comment]
What happens if you explicitly try to import the module; e.g.

```
reticulate::import("leidenalg")
```

Does it import successfully?

**Comment by lc822** [comment]
I get the following error:

> Error in py_module_import(module, convert = convert) : 
>   DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.
> 
> Detailed traceback: 
> File "/Users/lucy/R_projects/10x/renv/python/virtualenvs/renv-python-3.8.3/lib/python3.8/site-packages/leidenalg/__init__.py", line 35, in module
>     from .functions import ALL_COMMS
>   File "/Users/lucy/R_projects/10x/renv/python/virtualenvs/renv-python-3.8.3/lib/python3.8/site-packages/leidenalg/functions.py", line 2, in module
>     import igraph as _ig
>   File "/Users/lucy/R_projects/10x/renv/python/virtualenvs/renv-python-3.8.3/lib/python3.8/site-packages/igraph/__init__.py", line 8, in module
>     raise DeprecationWarning("To avoid name collision with the igraph project, "

**Comment by lc822** [comment]
Yes, I get the same warning/error:

> DeprecationWarning                        Traceback (most recent call last)
> ipython-input-1-96c2dbaea590 in module
> ----> 1 import leidenalg
> 
> ~/Documents/R_projects/10x/renv/python/virtualenvs/renv-python-3.8.3/lib/python3.8/site-packages/leidenalg/__init__.py in <module>
>      33 not immediately available in :func:`leidenalg.find_partition`.
>      34 """
> ---> 35 from .functions import ALL_COMMS
>      36 from .functions import ALL_NEIGH_COMMS
>      37 from .functions import RAND_COMM
> 
> ~/Documents/R_projects/10x/renv/python/virtualenvs/renv-python-3.8.3/lib/python3.8/site-packages/leidenalg/functions.py in <module>
>       1 import sys
> ----> 2 import igraph as _ig
>       3 from . import _c_leiden
>       4 from ._c_leiden import ALL_COMMS
>       5 from ._c_leiden import ALL_NEIGH_COMMS
> 
> ~/Documents/PhD/Year_4/Sequencing_data_analysis/R_projects/10x/10x_bloodandliver_MAIT/renv/python/virtualenvs/renv-python-3.8.3/lib/python3.8/site-packages/igraph/__init__.py in <module>
>       6 __license__ = "MIT"
>       7 
> ----> 8 raise DeprecationWarning("To avoid name collision with the igraph project, "
>       9                          "this visualization library has been renamed to "
>      10                          "'jgraph'. Please upgrade when convenient.")
> 
> DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.

**Comment by kevinushey** [comment]
I wonder if the issue here ultimately is that the "wrong" version of `igraph` has been installed? See also:

https://stackoverflow.com/questions/36200707/error-with-igraph-library-deprecated-library

You might need to use something like:

```
pip uninstall igraph
pip install python-igraph
```

to get the "right" version of `igraph` installed.

**Comment by lc822** [comment]
Thank you, yes I had just discovered the same thing and I think it is working now.

These are the steps that I took:
`pip uninstall igraph`
`pip uninstall python-igraph`
`pip install python-igraph`

Thanks very much for your help!

**Comment by divyakapil** [comment]
I am trying to use python in virtual environment but it doesn't work  and  i get following error:

Unable to create process using 'C:\Users\AppData\Local\Microsoft\WindowsApps\Python38\python.exe test.py runserver'
