### ISSUE TITLE
Docs: It would be helpful to have a list of cran packages using reticulate

### ISSUE THREAD

**Issue by henrykironde** [rstudio/reticulate#500]
Developing a package using Reticulate could be challenging. A list of sample Cran packages could save users time when developing packages or when keeping up to date with package changes

**Comment by terrytangyuan** [comment]
There’s already a section “Reverse Dependencies” in https://cran.r-project.org/web/packages/reticulate/index.html. Is this what you want?

**Comment by henrykironde** [comment]
Perfect thank you so much @terrytangyuan
