### ISSUE TITLE
how do i save python config in reticulate

### ISSUE THREAD

**Issue by sebastiangonsal** [rstudio/reticulate#504]
How do i save my current python config so that rstudio picks it and i dont have to set conda/python environment again next time i start rstudio?

**Comment by viebrix** [comment]
One possibility would be to create a Rprofile.site file. See more https://www.statmethods.net/interface/customizing.html and https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html

**Comment by snikumbh** [comment]
See the `RETICULATE_PYTHON` option [here](https://rstudio.github.io/reticulate/articles/versions.html#order-of-discovery). That way, RStudio or R, attaching reticulate will always use the same python (configuration).
