### ISSUE TITLE
on_load in reticulate::import doesnt seem to be called

### ISSUE THREAD

**Issue by sebastiangonsal** [rstudio/reticulate#506]
I am doing the following:

```
> sys <- reticulate::import("sys", delay_load=list(on_load = function(){message(3)}))
```
when i type `sys` on console and access its properties, the module gets loaded but no message gets printed to the console.

**Comment by kevinushey** [comment]
It seems to work for me. Are you by any chance triggering a load of the model through autocompletion? (since R and RStudio both will evaluate things in the module, causing the on_load hook to be run)

**Comment by sebastiangonsal** [comment]
I just wrote down `sys$executable` making sure not to press Tab (in a new session). Nothing got printed.
Btw i am using Rstudio for windows.
