### ISSUE TITLE
py_to_r.collections.OrderedDict does not work when keys are not strings

### ISSUE THREAD

**Issue by skeydan** [rstudio/reticulate#516]
Hi,

I happen to have to convert `OrderedDict`s that look like this:

```
OrderedDict([
(<tensorflow_probability.python.sts.seasonal.Seasonal object at 0x7fd36be7dac8>, 
<tfp.distributions.MixtureSameFamily 'decompose_by_component_1/decompose_from_posterior_marginals/mix_over_posterior_draws/MixtureSameFamily/' batch_shape=[2, 1] event_shape=[12] dtype=float64>), 
(<tensorflow_probability.python.sts.local_linear_trend.LocalLinearTrend object at 0x7fd39c982b70>, 
<tfp.distributions.MixtureSameFamily 'decompose_by_component_1/decompose_from_posterior_marginals/mix_over_posterior_draws_1/MixtureSameFamily/' batch_shape=[2, 1] event_shape=[12] dtype=float64>)
])
```

Unfortunately, this ends up in R as
```
$`<tensorflow_probability.python.sts.seasonal.Seasonal object at 0x7fd36be7dac8>`
NULL

$`<tensorflow_probability.python.sts.local_linear_trend.LocalLinearTrend object at 0x7fd39c982b70>`
NULL
```

Is there a possibility to modify the conversion function

```
function (x) 
{
  keys <- names(x)
  names(keys) <- keys
  lapply(keys, function(key) {
    x[[key]]
  })
}
```

so it works when keys are not strings?

Many thanks!

**Comment by skeydan** [comment]
Unfortunately I don't have an idea for a "quick fix", as it seems we always get the keys as strings 

```
.DollarNames.python.builtin.object <- function(x, pattern = "") {
    ...

  # check for dictionary
  if (inherits(x, "python.builtin.dict")) {

    names <- py_dict_get_keys_as_str(x)
```
and then, there's no way back right? ... but at least here's a simple reprex:

This is a Python file:
```
import tensorflow as tf
import collections

d = collections.OrderedDict()
d[t1] = 1
d[t2] = 2
d
```

Here the output is
```
OrderedDict([(<tensorflow.python.keras.engine.sequential.Sequential object at 0x7f37287ca1d0>, 1), (<tensorflow.python.keras.engine.sequential.Sequential object at 0x7f37287caf28>, 2)])
```

Then in R do:

```
rd <- py$d
rd
```

and we have
```
$`<tensorflow.python.keras.engine.sequential.Sequential object at 0x7f37287ca1d0>`
NULL

$`<tensorflow.python.keras.engine.sequential.Sequential object at 0x7f37287caf28>`
NULL
```

If this is not something we can straightforwardly change, I wonder if anyone has ideas for a workaround?
Thanks!

**Comment by skeydan** [comment]
We found a workaround using 

```
reticulate::py_call(<python function>, arg1, arg2, ...)
```

which does not convert the `OrderedDict` to a named list and so circumvents the problem (thanks @javierluraschi!)

@kevinushey do you think you want to implement this functionality (indexing into `Dict`s by objects, not strings) in `reticulate`?
If it's too time-consuming feel free to close.
Thanks!

**Comment by kevinushey** [comment]
It's not clear to me how this would work, since the equivalent R objects (lists or environments) can only be indexed by strings, not arbitrary objects.

Can you clarify what exactly you want to do and what could change in `reticulate` to accommodate it? What are you hoping:

```
OrderedDict([
(<tensorflow_probability.python.sts.seasonal.Seasonal object at 0x7fd36be7dac8>, 
<tfp.distributions.MixtureSameFamily 'decompose_by_component_1/decompose_from_posterior_marginals/mix_over_posterior_draws/MixtureSameFamily/' batch_shape=[2, 1] event_shape=[12] dtype=float64>), 
(<tensorflow_probability.python.sts.local_linear_trend.LocalLinearTrend object at 0x7fd39c982b70>, 
<tfp.distributions.MixtureSameFamily 'decompose_by_component_1/decompose_from_posterior_marginals/mix_over_posterior_draws_1/MixtureSameFamily/' batch_shape=[2, 1] event_shape=[12] dtype=float64>)
])
```

would be converted to?

**Comment by skeydan** [comment]
It's not that having a named list, indexed by strings, wouldn't be fine on the R side... I was just thinking if there was a way to rewrite the conversion function

```
function (x) 
{
  keys <- names(x)
  names(keys) <- keys
  lapply(keys, function(key) {
    x[[key]]
  })
}
```

in a way that the dict values don't get lost. Here we lose them in the line

```
 x[[key]]
```

because key is a string... I don't know how exactly to achieve this, but what I was having in mind is  a way that leaves the values alone and just modifies (stringifies) the keys. Not sure if this explains it better?

**Comment by kevinushey** [comment]
Okay, I understand what you mean. Code references would help make it clear you were referring to:

https://github.com/rstudio/reticulate/blob/2390fbb1c3e3bf7816747802a7880765315d6099/R/conversion.R#L183-L190

I think we can better handle this case -- let me take a look.

**Comment by skeydan** [comment]
Right - and thanks for taking a look!
