### ISSUE TITLE
please revert https://github.com/rstudio/reticulate/pull/525

### ISSUE THREAD

**Issue by skeydan** [rstudio/reticulate#526]
Hi @kevinushey, 

I'm sorry but that PR leads to pseudo-indeterministic, hard-to-provoke crashes :-(

I have some example code that, dependent on how you set a parameter, either "runs", returns an error from Python, or crashes with ```address 0x7fc4379c8120, cause 'invalid permissions'```.
I don't have a simple reprex, but in case you want that code I can provide it.

My assumption is that depending on the state of the Python program (which is probabilistic intrinsically), something different is returned in the tuple.

I think we would have to revert the change, but in case you had an idea what we could do to make this work correctly, that'd be super awesome. If not, I'll stay with the (not too elegant) workaround I was using before that PR (```my_ordered_dict %>% reticulate::py_to_r() %>% unname()```).

Here is some info from the coredump. Let me know if there's anything I could do to help here, e.g. by poking around some more.

```
#0  0x00007fc4379c8120 in PyTuple_Type () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
[Current thread is 1 (Thread 0x7fc44c907300 (LWP 11172))]
(gdb) backtrace
#0  0x00007fc4379c8120 in PyTuple_Type () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#1  0x00007fc43770bad6 in dict_subscript.lto_priv () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#2  0x00007fc437757059 in PyObject_GetItem () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#3  0x00007fc4376f5376 in _PyEval_EvalFrameDefault () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#4  0x00007fc4378b4284 in _PyEval_EvalCodeWithName () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#5  0x00007fc4377a9680 in _PyFunction_FastCallKeywords () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#6  0x00007fc4376fb0f6 in call_function.lto_priv () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#7  0x00007fc4376f6808 in _PyEval_EvalFrameDefault () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#8  0x00007fc4378b4284 in _PyEval_EvalCodeWithName () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#9  0x00007fc4377a9680 in _PyFunction_FastCallKeywords () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#10 0x00007fc4376fb0f6 in call_function.lto_priv () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#11 0x00007fc4376f6aa0 in _PyEval_EvalFrameDefault () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#12 0x00007fc4378b4284 in _PyEval_EvalCodeWithName () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#13 0x00007fc4377a9680 in _PyFunction_FastCallKeywords () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#14 0x00007fc4376fb0f6 in call_function.lto_priv () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#15 0x00007fc4376f6aa0 in _PyEval_EvalFrameDefault () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#16 0x00007fc4378b4284 in _PyEval_EvalCodeWithName () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#17 0x00007fc4377a9948 in _PyFunction_FastCallDict () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.7m.so
#18 0x00007fc43e9e98ea in py_call_impl (x=..., args=..., keywords=...) at reticulate_types.h:38
#19 0x00007fc43e9d3de9 in _reticulate_py_call_impl (xSEXP=0x5605fe776c48, argsSEXP=<optimized out>, keywordsSEXP=<optimized out>)
    at /home/key/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include/Rcpp/as.h:151
#20 0x00007fc4515f2ed9 in bcEval (body=<optimized out>, rho=<optimized out>, useCache=<optimized out>) at eval.c:7283

```

**Comment by javierluraschi** [comment]
I would favor not reverting this for a while (assuming we are not pushing reticulate to CRAN soon) and figure out if we can reproduce and investigate this crash. I wonder if TensorFlow or Keras tests also crash randomly with this change and if so it would give us a start to investigate, we can report back...

**Comment by skeydan** [comment]
Okay. I'm starting to think the same thing might also happen if it was a list, not a tuple.
I can probably track down the place in the Python code where this happens and change that to a list and see what happens.
Will report back...

**Comment by skeydan** [comment]
Closing this, -- there is no direct connection to the PR. (Not sure yet though whether my problem is related to the Python application in question, specifically, or if there is some connection to how objects are passed between R and Python, will try to find out and possibly come back with another issue or a PR.)
