### ISSUE TITLE
how to upgrade pip package using reticulate

### ISSUE THREAD

**Issue by sebastiangonsal** [rstudio/reticulate#527]
Is there a reticulate function to upgrade a pip package ?

**Comment by kevinushey** [comment]
reticulate has an unexported function, `reticulate:::pip_install`, that installs a package using a user-provided `pip` binary. Is that what you need?

If you're working with a virtual environment, `virtualenv_install()` will also just delegate to `pip_install()`. With Conda environments, my understanding is that one typically wants to install packages with Conda as the regular pip packages may be incompatible though.

**Comment by hchandola** [comment]
I am aware of these functions but I guess they won't upgrade an already installed pip package?

**Comment by sebastiangonsal** [comment]
I looked into pip_install. But it seems to install a pip package. How do i pass the argument --upgrade to this pip package?

**Comment by kevinushey** [comment]
`pip_install()` already does request an upgrade:

```
> reticulate:::pip_install
function(pip, packages, ignore_installed = TRUE) {

  # construct command line arguments
  args <- c("install", "--upgrade")
  if (ignore_installed)
    args <- c(args, "--ignore-installed")
  args <- c(args, packages)

  # run it
  result <- system2(pip, args)
  if (result != 0L) {
    pkglist <- paste(shQuote(packages), collapse = ", ")
    msg <- paste("Error installing package(s):", pkglist)
    stop(msg, call. = FALSE)
  }

  invisible(packages)

}
```

You can also manually execute `system("pip install --upgrade <pkg>")` if you want to take more manual control.
