### ISSUE TITLE
support results = "hold" for python chunks

### ISSUE THREAD

**Issue by Atrebas** [rstudio/reticulate#530]
Would it be possible to support `results = "hold"` in Python chunks so as to have the same behaviour as for R chunks?
Example below. Thank you.

````
---
output: html_document
---

```{r  global_options, echo = FALSE}
knitr::opts_chunk$set(results = "hold")
```

```{r}
print(1)
print(2)
```

```{python}
print(1)
print(2)
```
````

**Comment by asianboii-chen** [comment]
Wow, I'm surprised that it's still not fixed after more than a year.

Do you have a work-around for this issue? Thank you so much in advance if you could help.

**Comment by bradleygrant** [comment]
Having this issue as well, just voicing support for a fix or workaround. Thanks.

**Comment by gn0** [comment]
I would also like to have this added to reticulate if possible. Thank you
