### ISSUE TITLE
package function has to be called twice for module calling reticulate to be loaded

### ISSUE THREAD

**Issue by sebastiangonsal** [rstudio/reticulate#534]
I have authored a package using reticulate. My .onLoad looks like the following:

```
.onLoad <- function(lib, pkg) 
{
  my_package <<- reticulate::import('my_package', delay_load = list(
	priority = 5,
	environment = "conda_env",
    on_error = function(e) {
       stop(e$message)
  }
)
  invisible(NULL)
}
```

I have a function in package which is like the following:
```
create_resource <- my_package$create_resource()
```

The problem is that if i start a new R session, install the package and call the function `create_resource`, I get the following error:

```
Error 9009 occurred running C:\Users\terabyte\AppData\Local\MICROS~1\WINDOW~1\python.exe 
```
I call the function again and voila it works like a charm thereafter.

I think the first error is due to the module being loaded for the first time. But I can't understand why that would happen. The delayed load shouldn't be resulting in something like this.

What can i do to fix it ?

**Comment by kevinushey** [comment]
Can you provide a reproducible example? (is your package available publicly somewhere?)

**Comment by sebastiangonsal** [comment]
Its not currently. I can write together a reproducible example soon enough. Thanks

**Comment by kevinushey** [comment]
I was just able to reproduce this on my Windows machine. It looks like Windows is putting a `python` stub executable on the PATH:

```
> Sys.which("python")
                                                            python 
"C:\\Users\\kevin\\AppData\\Local\\MICROS~1\\WINDOW~1\\python.exe" 
```

When reticulate finds that copy of Python, it gives an error while trying to infer its configuration:

```
> reticulate::py_config()
Error in python_config(python_version, required_module, python_versions) : 
  Error 9009 occurred running C:\Users\kevin\AppData\Local\MICROS~1\WINDOW~1\python.exe 
In addition: Warning message:
In system2(command = python, args = paste0("\"", config_script,  :
  running command '"C:\Users\kevin\AppData\Local\MICROS~1\WINDOW~1\python.exe" "C:/Users/kevin/Documents/R/win-library/3.6/reticulate/config/config.py"' had status 9009
```

If I try to open that file manually, it opens a link in the Microsoft Store for installing Python:

![Screen Shot 2019-06-28 at 12 00 27 PM](https://user-images.githubusercontent.com/1976582/60364945-57e3b700-999c-11e9-9bdc-f9e4528ecb5e.png)

I think `reticulate` needs to guard against this "fake" Python executable being put on the PATH.

**Comment by sebastiangonsal** [comment]
any idea when this gets released to CRAN?

**Comment by sebastiangonsal** [comment]
is there a possible workaround until it gets to CRAN ?

**Comment by jjuanramos** [comment]
How can we get around this? I am having the same problem

**Comment by skeydan** [comment]
This fix is available in the current CRAN release of reticulate.
