### ISSUE TITLE
reticulate ignores environment in delay_load

### ISSUE THREAD

**Issue by sebastiangonsal** [rstudio/reticulate#535]
On windows in rstudio, i do the following:
```
  my_package <<- reticulate::import('my_package', delay_load = list(
    priority = 1,
    environment = "r-package_env"
  ))
```
I end up with `my_package` loaded from a different environment. Why is that ?

In fact. i can put a non existing environment: `environment = "env_doesnt_exist"` and it still loads this package from another environment without an error!

**Comment by jjallaire** [comment]
The environment parameter is for end-users not for package developers (if
you are able to specify an environment name in your package then you'd be
mandating that all users of your package create exactly that environment
name and put all of their python packages into it).

Reticulate is going to scan the system for a Python package of the name you
are importing so it will find it if it's installed. Users generally
customize where to look via the use_* family of functions.

**Comment by sebastiangonsal** [comment]
This is similarly to what has been done for `r-tensorflow`. It gives a function called `install_tensorflow` that installs tensorflow in a conda environment called `r-tensorflow`. Look at [this](https://github.com/rstudio/tensorflow/blob/master/R/package.R#L51) .

Btw i have even tried to do an import on Rstudio as an end user with the package and environment specified and it still imports the package from a different environment.

**Comment by jjallaire** [comment]
Oh right, that argument is fine to use as it's just advisory (user preference will override it).

My guess is that it's failing to load the package within the specified environment for some reason and moving on to another environment. You can use the `reticulate::py_discover_config` to see all of the different environments that are being scanned.

**Comment by sebastiangonsal** [comment]
In a python repl, I am able to load it from the environment that i wanted reticulate to load the package from.

**Comment by kevinushey** [comment]
One common reason that an environment could fail to load is that the PATH is not set up as the environment requires. (This is especially true with Anaconda environments.)

We do make some efforts to set up the PATH appropriately before testing whether a particular Python environment can be loaded, but it's possible we're missing some cases. Either way, the output of `reticulate::py_discover_config()` could be helpful.

**Comment by sebastiangonsal** [comment]
The output of `py_discover_config()` lists all environment including the one from which it is failing to read the package (and loading it from another).

The behavior that I am seeing is that reticulate (despite specifying an environment in `delay_load`), goes over environments in order and loads the package from whatever environment that has the package available. 

Is there a test for this? One way to replicate this is to install numpy's different version in an environment called "abc". Install numpy in an environment called "r-abc". and then do a load like following:
```
np <- reticulate::import("abc", delay_load = list(environment = "r-abc"))
```

And then check for the version

**Comment by hchandola** [comment]
@kevinushey @sebastiangonsal I am hitting this as well. Can you point me to the code in the github repo where the package loading happens?

**Comment by hchandola** [comment]
My issue was that i dont have `numpy` installed in the custom environment and therefore the `delay_load` doesn't work. @kevinushey  can you take a look at #541 ?

**Comment by sebastiangonsal** [comment]
I have the same issue and installing numpy made it work for me.

If we can get the PR in, that would be great too.

**Comment by bgreenwell** [comment]
Is this still an open issue for others? I’m running into the same issue it seems. I’m testing out a new package that uses delay load, but it seems to be ignored and the package will not load u less numpy is available on the default py version. You can see my .onLoad() call here: https://github.com/bgreenwell/ebm/blob/main/R/zzz.R
