### ISSUE TITLE
source_python crashes R from command line

### ISSUE THREAD

**Issue by LeszekF** [rstudio/reticulate#537]
Hi,
I have strange issue. I'm trying to run R script which is using source_python().
This is done on the Windows Server - all works fine for my user, when I'm running same scripts on different user (same privileges) R crashes.
All works fine in RStudio, but not from cmd.

R v.3.6
Python v.3.7
reticulate v.1.2

![obraz](https://user-images.githubusercontent.com/24875551/60437028-b4014200-9c0d-11e9-8ede-4495adc35b26.png)

R code:

```R
print("1")
library(reticulate)
print("2")
source_python("test.py")
print("3")
flights <- read_flights("flights.csv")
print("4")
```

python code:
```python
import pandas
def read_flights(file):
  flights = pandas.read_csv(file)
  flights = flights[flights['dest'] == "ORD"]
  flights = flights[['carrier', 'dep_delay', 'arr_delay']]
  flights = flights.dropna()
  return flights
```

**Comment by kevinushey** [comment]
Sorry, but I'm not able to reproduce.

The most likely cause is that `pandas` failed to load for some reason. You might try inspecting the PATH environment variable to see if there are any differences between RStudio and your R console, since the PATH setting can influence where modules / libraries are loaded.

**Comment by LeszekF** [comment]
Thanks Kevin,
I don't think pandas is a problem here. I tried very simple python, like print('test') and it crashed anyway (without loading libraries). 
I tried to recreate crash i R console and I have this error (this error occurs also for the users to which running R / Python from command line works fine):
![obraz](https://user-images.githubusercontent.com/24875551/60485319-e017d400-9c9c-11e9-9e1a-3fe48f8d1950.png)
Any idea why this error shows up in R console and not in RStudio?

**Comment by LeszekF** [comment]
Ok, I found what was an issue. After changing regional settings to 'Match Windows display language' scripts starts to work fine without crashing.
![obraz](https://user-images.githubusercontent.com/24875551/60496069-5a068800-9cb2-11e9-9d87-b52ffb6fdea8.png)
