### ISSUE TITLE
unit tests do not behave as in R scripts

### ISSUE THREAD

**Issue by f0nzie** [rstudio/reticulate#538]
I have been writing some unit tests for calculation performed within Python with R objects. This R script works fine:

```
library(reticulate)

A <- 100
B <- 250
Ap <- r_to_py(A)
Bp <- r_to_py(B)

py_run_string("ab = r.A*r.B")  # multiply to R objects in Python
print(py$ab)           # return calculated value
py_run_string("")$ab   # returns value  25000
py_eval("ab")          # returns value  25000
py_run_string("print(ab); sys.stdout.flush()")    # returns 25000
py_run_string("print(r.Ap); sys.stdout.flush()")  # returns 100.0
py_run_string("print(r.Bp); sys.stdout.flush()")  # returns 250.0
```

But if I write the unit test `test_print_r_vars_from_python.R`:

```
library(testthat)
library(reticulate)

context("print R values from within Python")

test_that("R objects are multiplied within Python and printed", {
    A <- 100
    B <- 250
    Ap <- r_to_py(A)
    Bp <- r_to_py(B)

    py_run_string("ab = r.A * r.B")  # multiply to R objects in Python
    print(py$ab)  
    py_run_string("")$ab 
    py_eval("ab")          
    py_run_string("print(ab); sys.stdout.flush()")
    py_run_string("print(r.Ap); sys.stdout.flush()")
    py_run_string("print(r.Bp); sys.stdout.flush()")
 })
```

I get the error:
```
test_print_r_vars_from_python.R:14: error: R objects are multiplied within Python and printed
RuntimeEvaluation error: object 'A' not found.
1: py_run_string("ab = r.A * r.B") at ____ test_print_r_vars_from_python.R:14
2: py_run_string_impl(code, local, convert)
```

Am I missing something?

**Comment by kevinushey** [comment]
The `r` object tries to access things from the global environment, by default. Perhaps we should instead make it try to access things from the 'active' executing environment?

**Comment by sundrelingam** [comment]
> The `r` object tries to access things from the global environment, by default. Perhaps we should instead make it try to access things from the 'active' executing environment?

I have a related problem where I'd like to evaluate the python code in a separate environment. For example, executing the following in the global environment works as expected:
```r
library(reticulate)

x <- 1
py_run_string("r.x = 2")

#> x
#[1] 2
```
However, when I try to access an object from a new environment, the python code is "evaluated" in my global environment instead:
```r
library(reticulate)
e <- new.env()
assign("y", 1, e)

eval(py_run_string("r.y = 2"), envir = e)

#> e$y
#[1] 1
#> y
#[1] 2
```
Having the `r` object able to access objects from the current executing environment would be incredibly useful.

**Comment by kevinushey** [comment]
I've made a change that allows `reticulate` to work within `testthat` contexts -- the `r` object now accesses the active test environment.

If you need `reticulate` to work with a particular R environment, you can use:

```
options(reticulate.engine.environment = environment())
```

but it should be set back to `NULL` after doing so.
