### ISSUE TITLE
use `reticulate` with debug-enabled Python

### ISSUE THREAD

**Issue by skeydan** [rstudio/reticulate#539]
Using `reticulate` with a debug-enabled Python throws

```Error in py_initialize(config$python, config$libpython, config$pythonhome,  :
 PyModule_Create2 - /home/key/python/python3.7/lib/libpython3.7m.so: undefined symbol: PyModule_Create2
```

The reason is that what's `PyModule_Create2` in "normal" Python is  `PyModule_Create2TraceRefs` in debug-enabled Python (cf. https://stackoverflow.com/questions/39161202/how-to-work-around-missing-pymodule-create2-in-amd64-win-python35-d-lib).

Simply replacing all 3 occurrences does not work though, as a `tf_config` now results in 

```
*** caught segfault ***
address (nil), cause 'unknown'

Traceback:
1: py_run_string_impl(paste0("import sys; sys.path.append('", system.file("python",     package = "reticulate"), "')"))
2: initialize_python(required_module, use_environment)
3: ensure_python_initialized(required_module = module)
4: import(module)
5: doTryCatch(return(expr), name, parentenv, handler)
6: tryCatchOne(expr, names, parentenv, handlers[[1L]])
7: tryCatchList(expr, classes, parentenv, handlers)
8: tryCatch({    import(module)    TRUE}, error = clear_error_handler(FALSE))
9: py_module_available("tensorflow")
10: tf_config()
```

I don't know how common it is for uses to want to do this, so I've created this issue to

- either ask if we could enable debug support in `reticulate`, or else,
- if someone would like to help with a workaround :-)

Thanks!

**Comment by kevinushey** [comment]
I spent some time looking into this and the biggest challenge is the fact that the Python object layouts differ when using a debug version of Python:

https://github.com/python/cpython/blob/c8e7146de257930ea8d0d4aa74b3a64fcaa79d4b/Include/object.h#L67-L78

Since we copy some structs into `reticulate` we'd need to find some way of choosing the debug vs. release versions of those structs at runtime.

**Comment by skeydan** [comment]
#548 
thanks!
