### ISSUE TITLE
Is there a way to change encoding py_load_object()?

### ISSUE THREAD

**Issue by maksymiuks** [rstudio/reticulate#542]
Hello. 

I have a problem with loading pickle file created under python 2.7. When I try to load it via py_load_object() in env with python 3.7 i get error:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xcb in position 0: ordinal not in range(128)
```

is there a way to overcome it? (Other than using python 2.7 env)

**Comment by kevinushey** [comment]
The `py_load_object()` function is pretty simple:

```
> reticulate:::py_load_object
function(filename, pickle = "pickle") {
  builtins <- import_builtins()
  pickle <- import(pickle)
  handle <- builtins$open(filename, "rb")
  on.exit(handle$close(), add = TRUE)
  pickle$load(handle)
}
```

Perhaps we could augment the function to accept other arguments that can be passed down to `pickle$load()`.

**Comment by maksymiuks** [comment]
It willl much appreciated
