### ISSUE TITLE
call `__getitem__` when python class is indexed with `[]`

### ISSUE THREAD

**Issue by Zelazny7** [rstudio/reticulate#55]
Is there a way to access a classes `__getitem__` method using `[]` notation from within R?

For example:
```
library(reticulate)
pptx <- import("pptx")
prs <- pptx$Presentation()
title_slide_layout <- prs$slide_layouts[0L]
```
This fails with the error:

```
Error in prs$slide_layouts[0L] : 
  object of type 'environment' is not subsettable
```
My current workaround is to call `__getitem__` directly like so:

```
title_slide_layout <- prs$slide_layouts$`__getitem__`(0L)
```

Something like this seems to work OK. I'm not a confident enough programmer to know if this would work well in `reticulate`:

```
`[.python.builtin.object` <- function(obj, i) {
  obj$`__getitem__`(as.integer(i))
}
```

Amazing package!

**Comment by jjallaire** [comment]
Added this behavior here: https://github.com/rstudio/reticulate/commit/ffc8cee40d6b2b23553faba49c6a8e4b83858a0a

Note that I used `[[` rather than `[` because the former does single element indexing whereas the latter can select ranges via logical vectors.
