### ISSUE TITLE
Preserve python function signature for autocompletion

### ISSUE THREAD

**Issue by flying-sheep** [rstudio/reticulate#553]
`py_callable_as_function` converts a callable to an R function, but leaves the formals as `...`:

https://github.com/rstudio/reticulate/blob/7da9ac7ea53b33d5fc2f8dfb2a85d08f1b85f0e0/R/python.R#L1224-L1239

It should be easy to construct some formals via [`inspect.signature()`](https://docs.python.org/3/library/inspect.html#inspect.signature).

Also the repr should be adapted. `<function myfunc>` isn’t super helpful.

**Comment by jjallaire** [comment]
Yes, we have another function (`py_func()`) that does this: https://github.com/rstudio/reticulate/blob/7da9ac7ea53b33d5fc2f8dfb2a85d08f1b85f0e0/R/py_func.R#L19-L50

**Comment by flying-sheep** [comment]
No, other direction.

**Comment by jjallaire** [comment]
Oh, got it. No you are correct we don't currently do it the other direction
(apologize for the confusion)

**Comment by flying-sheep** [comment]
Please mark all those misleading comments as off-topic and reopen this.

**Comment by flying-sheep** [comment]
Hmm. A problem seems to be that we can’t call any python functions from `py_callable_as_function`, as this would result in infinite recursion somehow.

I think `py_to_r.default` might be a good place, as we want to wrap all callables, not just functions.
