### ISSUE TITLE
Can’t get item of custom Mapping

### ISSUE THREAD

**Issue by flying-sheep** [rstudio/reticulate#554]
```r
> adata$obsm[['velocity_umap']]
#Error in py_get_attr_impl(x, name, silent): AttributeError: 'AxisArrays' object has no attribute 'velocity_umap'
#Traceback:
#1. adata$obsm[["velocity_umap"]]
#2. `[[.python.builtin.object`(adata$obsm, "velocity_umap")
#3. py_get_attr_or_item(x, name, TRUE)
#4. py_get_attr(x, name)
#5. py_get_attr_impl(x, name, silent)
> adata$obsm['velocity_umap']
#Error in as.environment(x): invalid 'pos' argument
#Traceback:
#1. adata$obsm["velocity_umap"]
#2. `[.python.builtin.object`(adata$obsm, "velocity_umap")
#3. py_get_attr_or_item(x, name, FALSE)
#4. py_maybe_convert(object, py_has_convert(x))
#5. py_has_convert(x)
> adata$obsm$`__getitem__`('velocity_umap')
#2×540 matrix
#…
```

`` `[[.python.builtin.object` `` calls `py_get_attr_or_item(..., prefer_attr = TRUE)`, and with `prefer_attr = TRUE`, it doesn’t even try to access an item.

Calling ``myobj$`__getitem__`('key')`` isn’t really acceptable, and I don’t think dicts should get special treatment here anyway, but rely on the default behavior

**Comment by kevinushey** [comment]
That shouldn't be the case:

https://github.com/rstudio/reticulate/blob/5a3aecc87717973fee9ae36966ec1658a7a2d07c/R/python.R#L332-L335

In other words, when using `[` or `[[` we prefer `__getitem__()` if available, but fall back to attribute access (for backwards compatibility) otherwise.

A reproducible example would be helpful.

**Comment by kevinushey** [comment]
Oops, I see what's going on. We override that definition immediately after here:

https://github.com/rstudio/reticulate/blob/5a3aecc87717973fee9ae36966ec1658a7a2d07c/R/python.R#L354-L355

Doh. I'll fix that up.

**Comment by kevinushey** [comment]
This still doesn't get to the root issue, which I think is the disparity between `[.python.builtin.object` and `[.python.builtin.dict`. I'm not sure if we want to make any explicit changes since we risk breaking existing code -- but let me know if you have a reproducible example that can help me understand what's going on here.

**Comment by flying-sheep** [comment]
It’s trivial. Just try to use `[[` or `[` on any mapping class that isn’t a `dict` subclass.

I tried to create a reproducible example, but ran either into another bug or a variant of this one:

```
library(reticulate)
py_run_string('
class M:
    def __getitem__(self, k):
        return "M"
')
m <- py_eval('M()')
m[1]
#> Error in as.environment(x) : no item called "M" on the search list
traceback()
#> 5: py_has_convert(x)
#> 4: py_maybe_convert(item, py_has_convert(x))
#> 3: py_get_attr_or_item(x, name, TRUE)
#> 2: `[[.python.builtin.object`(m, 1)
#> 1: m[[1]]
```

**Comment by kevinushey** [comment]
Thanks. The issue here is that we're treating an R object as though it were a Python proxy object.

**Comment by flying-sheep** [comment]
Nice! in your bugfix branch, everything seems to work, including the original code:

```r
> sc <- reticulate::import('scanpy')
> ad <- sc$datasets$paul15()
> sc$pp$recipe_zheng17(ad)
> sc$tl$pca(ad)
> ad$obsm[['X_pca']]
      [,1]        [,2]        [,3]        [,4]       [,5]         [,6]       
 [1,] -1.571113    8.2325611  -1.26337099  2.1519625 -1.9511720    0.64306229
 [2,] -7.895916   -5.2129054  -0.33225664  1.1607169 -0.1309081   -0.01333455
 [3,] 14.634998   -2.1748824   0.30500859 -1.3848221  4.4327774    2.80236864
...
```
