### ISSUE TITLE
Change condaenv during code execution via use_condaenv()

### ISSUE THREAD

**Issue by maksymiuks** [rstudio/reticulate#556]
Hi,

I've found following issue while using `use_condaenv()`. If "connection" with conda was established earlier before with different version of conda env, you cannot change it without restarting R session.

```
> reticulate::py_module_available("numpy")
[1] TRUE
> reticulate::use_condaenv("myenv", required = TRUE)
Error in use_python(conda_env_python, required = required) : 
  Required version of Python 'C:\Users\szyna\Anaconda3\envs\myenv\python.exe' cannot be used because another version of Python ('C:\Users\szyna\ANACON~1\python.exe') is already initialized for this process.
```

From my understanding, it is impossible to change python version using other python version, which is understandable, am I right? If so, can You please add message that solution of following error is restarting R session.

**Comment by kevinushey** [comment]
I've tweaked the error message -- it should provide a clear prescription now.

```
ERROR: The requested version of Python '/usr/bin/python' cannot be used, as
another version of Python ('/usr/local/bin/python') has already been
initialized. Please restart the R session if you need to attach reticulate
to a new version of Python.
Error in reticulate::use_python("/usr/bin/python", required = TRUE) : 
  failed to initialize requested version of Python
```
