### ISSUE TITLE
Multiple python environments

### ISSUE THREAD

**Issue by pslacerda** [rstudio/reticulate#558]
Hi,

How can I use multiple environments so can use differente python instances?

The package I'm importing runs inside a application. I'm really scripting a graphical application, so most functions can't be run in parallel and because of this I can't fully use dplyr. I'm tied on imperative `for` loops.

The `.globals` variable and `main_thread_func()` suggests that it is impossible but I'm asking any way: how can I do something like:

```R
env1 = use_condaenv("conda1")
pkg = env1.import("package")
env2 = use_condaenv("conda2")
# pass?
```

**Comment by kevinushey** [comment]
Unfortunately you can't do this (each R session can bind to only one Python session for its lifetime).

**Comment by pslacerda** [comment]
I really need to use multiple python environments. Can you reopen this issue as a feature request?

**Comment by jjallaire** [comment]
It's not technically possible.

**Comment by pslacerda** [comment]
Are you sure? Can't the main thread belong to its own process?

**Comment by jjallaire** [comment]
Yes we are sure.
