### ISSUE TITLE
Error: R is already initialized

### ISSUE THREAD

**Issue by jburos** [rstudio/reticulate#56]
This is a minor issue I ran into when executing an R script that uses reticulate, in a project that uses `rpy2` to interface with R from python elsewhere.

Posting here in case others come across the same issue.

I have a test function in R called `validate_setup`:

```r
library(reticulate)
validate_setup <- function(verbose = TRUE, test_packages = c('numpy', 'cohorts')) {
  # report on py_config
  if (verbose)
     print(reticulate::py_config())

  # check availability of package(s)
  for (pkg in test_packages) {
    if (verbose)
       print(paste0('checking that ', pkg, ' is available'))
    if (!reticulate::py_available(pkg))
       stop(paste0('python package could not be found: ', pkg))
  }

  # check python initialized
  if (verbose)
     print('checking that python is initialized')
  reticulate::py_config()
  reticulate:::ensure_python_initialized()

  # load package
  for (pkg in test_packages) {
    if (verbose)
      print(paste0('loading ', pkg))
    dummy <- reticulate::import(pkg, convert = FALSE)
  }
  print("setup OK")
}
```

I also have a trivial command-line wrapper script to execute this called `run_validate_setup.R`

I can execute this using in one of two python environments:

1. **testenv1**: includes only cohorts: 

    ```sh
     conda create -n testenv1 python=3 scipy numpy pandas
     source activate testenv1
     pip install cohorts
     Rscript run_validate_setup.R
     ```

2. **testenv2**: includes cohorts & rpy2:

    ```sh
     conda create -n testenv2 --clone testenv1
     source activate testenv2
     pip install rpy2
     Rscript run_validate_setup.R
     ```

In the first virtualenv, I have no problems:

```sh
(testenv1) jacquelineburos@jacki1:~/projects/test-reticulate$ Rscript run_validate_setup.R
python:         /home/jacquelineburos/miniconda3/envs/testenv1/bin/python
libpython:      /home/jacquelineburos/miniconda3/envs/testenv1/lib/libpython3.6m.so
pythonhome:     /home/jacquelineburos/miniconda3/envs/testenv1:/home/jacquelineburos/miniconda3/envs/testenv1
version:        3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
numpy:          /home/jacquelineburos/miniconda3/envs/testenv1/lib/python3.6/site-packages/numpy
numpy_version:  1.12.1

python versions found:
 /home/jacquelineburos/miniconda3/envs/testenv1/bin/python
 /usr/bin/python
 /usr/bin/python3
[1] "checking that numpy is available"
[1] "checking that cohorts is available"
[1] "checking that python is initialized"
[1] "loading numpy"
[1] "loading cohorts"
/home/jacquelineburos/miniconda3/envs/testenv1/lib/python3.6/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
[1] "setup OK"
[1] "Finished"
```

However, in the second I get an error message: `R is already initialized`

```sh
(testenv2) jacquelineburos@jacki1:~/projects/test-reticulate$ Rscript run_validate_setup.R
python:         /home/jacquelineburos/miniconda3/envs/testenv2/bin/python
libpython:      /home/jacquelineburos/miniconda3/envs/testenv2/lib/libpython3.6m.so
pythonhome:     /home/jacquelineburos/miniconda3/envs/testenv2:/home/jacquelineburos/miniconda3/envs/testenv2
version:        3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
numpy:          /home/jacquelineburos/miniconda3/envs/testenv2/lib/python3.6/site-packages/numpy
numpy_version:  1.12.1

python versions found:
 /home/jacquelineburos/miniconda3/envs/testenv2/bin/python
 /usr/bin/python
 /usr/bin/python3
[1] "checking that numpy is available"
[1] "checking that cohorts is available"
[1] "checking that python is initialized"
[1] "loading numpy"
[1] "loading cohorts"
/home/jacquelineburos/miniconda3/envs/testenv2/lib/python3.6/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
R is already initialized
```

It's interesting to me that I only get this error when loading `cohorts`, not `numpy`. Also that this manifests when when running `reticulate::import`, and not on the validation-steps earlier. 

Not surprisingly, if I remove `rpy2` from the `testenv2` condaenv, the error is resolved. 

I recognize that this is a pretty marginal edge case, but again posting here in case it's helpful.

**Comment by jjallaire** [comment]
I think the problem is that **rpy2** wants to initialize it's own instance of the R runtime, and when it's called via reticulate the R runtime is of course already initialized. Unfortunately I don't think we can find a way around this one.

**Comment by jburos** [comment]
This sounds reasonable - though it's strange to me that the error is not _always_ triggered by `rpy2`. 

For example, I don't have any problems sourcing numpy, matplotlib or pandas in the following environment :

```sh
conda create -n testenv3 python=3 scipy numpy pandas matplotlib
source activate testenv3
pip install rpy2
Rscript run_validate_setup2.R
```

Where `run_validate_setup2.R` looks like the following:

```r
#!/usr/bin/env Rscript

# execute script
source('validate_setup.function.R')
validate_setup(verbose = TRUE, test_packages = c('numpy', 'matplotlib'))

print('Finished')
```

If it's OK with you, I'm going to keep working through dependencies of `cohorts` to try to isolate the issue. My thinking is, in the long run, this might help make reticulate more reliable overall.

**Comment by jjallaire** [comment]
Okay, that's fine. There definitely could be something I'm missing here!

On Wed, May 17, 2017 at 1:42 PM, Jacki Buros Novik <notifications@github.com

**Comment by jburos** [comment]
Nope you were right! the error occurs on installing `PyVCF`, one of the dependencies of `cohorts`, since that package uses rpy2 to initializes R in the code, but only if `rpy2` is installed.

e.g. [here](https://github.com/jamescasbon/PyVCF/blob/master/vcf/filters.py#L1):

```py
try:
    from rpy2 import robjects
except:
    robjects = None
```

In general it seems safer to not have rpy2 installed, since otherwise would be hard to know which packages use it or depend on it. But simply installing it doesn't cause a problem _unless_ one of the python packages uses it.

Anyways I feel better (at least) having tracked this down. Agreed with your earlier statement above that it's unlikely that anything can be done to avoid the issue. Circular r->py->r dependencies seem like a bad idea, in general.

**Comment by jjallaire** [comment]
Okay, very glad you got to the bottom of it!

On Wed, May 17, 2017 at 3:01 PM, Jacki Buros Novik <notifications@github.com
