### ISSUE TITLE
External2 C_savehistory error in reticulate::repl_python() for  RStudio latest version (v.1.2.1335)

### ISSUE THREAD

**Issue by gundalav** [rstudio/reticulate#572]
I was trying to run Python Script from within RStudio latest version (v.1.2.1335).

I am following **[this][1]** instruction.

I begin by typing:

     > reticulate::repl_python()

But I get this error: 

    Error in .External2(C_savehistory, file) : No such file or directory

How can I solve this?

  [1]: https://blog.rstudio.com/2018/10/09/rstudio-1-2-preview-reticulated-python/

**Comment by kevinushey** [comment]
What happens when you try to invoke `utils::savehistory()` directly? What is the output of `getwd()`?

**Comment by gundalav** [comment]
I get this message and error:

```
> utils::savehistory()
Error in .External2(C_savehistory, file) : No such file or directory
> getwd()
[1] "/home/ubuntu/storage1/my_analysis"
```

**Comment by kevinushey** [comment]
Then I don't have a good idea as to what's going on -- evidently R is not letting you write to the `.Rhistory` file in `/home/ubuntu/storage1/my_analysis`, but I do not know why.

**Comment by gundalav** [comment]
> Then I don't have a good idea as to what's going on -- evidently R is not letting you write to the `.Rhistory` file in `/home/ubuntu/storage1/my_analysis`, but I do not know why.

I remove the `.Rhistory` file, now it's working. Thanks.

**Comment by matiasandina** [comment]
I found this happen when not having access to root directory. Using `setwd(...)` into a directory with write permission solved the issue

**Comment by bpbraun** [comment]
My issue was that I didn't have read/write permissions for that directory.  Once I changed my permissions, I was good to go.
