### ISSUE TITLE
supply np record array from R

### ISSUE THREAD

**Issue by LGurtner** [rstudio/reticulate#589]
Hello, 
I would like to use the [multimatch module](https://pypi.org/project/multimatch/), but I mainly work in R with Rstudio. In order to use the `doComparison()` function, I need to supply the input data (a nx3 array) as a "record array" (at least that's what the developers of the module do in their [example](https://multimatch.readthedocs.io/en/latest/api.html)).
But R complains about unexpected parenthesis or commas, for example in: `fix_vector1 = np$recfromcsv('MYPATH/MMtrial1.tsv', delimiter='\t', dtype= {'names': ('start_x', 'start_y', 'duration'), 'formats': ('f8', 'f8', 'f8')})`. But it does also complain about unexpected brackets in this: `a = np_array([(1,'ABC'), (2, "DEF")], dtype=[('foo', int), ('bar', 'S4')])`

So my question is: (how) can I supply the record array to the `doComparison()` function? And in general: how does reticulate deal with python arrays that do not only contain numbers and that use bracket differently than how they are used in R?

I have tried to supply `doComparison()` with an R list, matrix, data.frame and tibble of the data without success and I can't imagine what else could be interpreted as a record array. 

Thank you for your help!

Lilla

links on record arrays:
Here is the documentation of structured arrays in [python](https://docs.scipy.org/doc/numpy/user/basics.rec.html)
Here are examples of how other people used the [np.recfromcsv](https://www.programcreek.com/python/example/18482/numpy.recarray)

**Comment by kevinushey** [comment]
You need to supply the R equivalents (using R code syntax) to these Python objects, so e.g.

```
{'names': ('start_x', 'start_y', 'duration'), 'formats': ('f8', 'f8', 'f8')}
```

would likely become

```
dict(names = tuple("start_x", "start_y", "duration"), formats = tuple("f8", "f8", "f8"))
```

Alternatively, you can use `py_eval()` or `py_run_string()`; e.g.

```
py_eval("{'names': ('start_x', 'start_y', 'duration'), 'formats': ('f8', 'f8', 'f8')}", convert = FALSE)
```
