### ISSUE TITLE
conda_install error '"C:\Program"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by lucazav** [rstudio/reticulate#596]
I'm trying to install [mlflow](https://github.com/mlflow/mlflow/tree/master/mlflow/R/mlflow) in RStudio (R 3.6.0). Under the hood it execute the following code:

```
conda = reticulate::conda_binary(conda = "auto")
reticulate::conda_install('mlflow==1.2.0', envname = 'r-mlflow-1.2.0', pip = TRUE, conda = conda)
```
But it ends with the following error:

> C:\Users\Administrator\Documents>conda.bat activate r-mlflow-1.2.0 
> '"C:\Program"' is not recognized as an internal or external command,
> operable program or batch file.
> Could Not Find C:\Program
> 'pip' is not recognized as an internal or external command,
> operable program or batch file.
> Error: Error 1 occurred installing packages into conda environment r-mlflow-1.2.0

It seems an error when quoting path strings containing spaces.
I'm using the package _reticulate_ 1.13.

**Comment by kevinushey** [comment]
Maybe I'm misunderstanding, but doesn't this imply a problem with `conda.bat`? And IIRC use of this was recently encouraged / forced by other changes in conda.

**Comment by lucazav** [comment]
Yes, it seems the full path of _conda.bat_ (containing a space) is not double quoted in the right way

**Comment by skeydan** [comment]
Hi, this looks like the problem was solved; please feel free to reopen otherwise.
