### ISSUE TITLE
R session crashes when virtual environment used from Windows. In Linux it works fine.

### ISSUE THREAD

**Issue by pchtsp** [rstudio/reticulate#597]
Good day!

I know there are quite a few issues that are similar, but I did not find exactly the one with the behavior I have. I think.

I use both a Linux and a Windows machine. I have as close as a setup I can have in both: python 3.6 virtual environments in each, lastest R version in each, etc.

My problem is that `reticulate` in unable to work with my windows virtual environment while it works perfectly with my ubuntu one.

Specs for Windows machine:

* Windows 10.
* python 3.6 in a virtual environment (created using `python -m venv venv`)
* R:

```
    > sessionInfo()
    R version 3.5.1 (2018-07-02)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 18362)

    Matrix products: default

    locale:
    [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] reticulate_1.13

    loaded via a namespace (and not attached):
    [1] compiler_3.5.1  Matrix_1.2-14   tools_3.5.1     Rcpp_0.12.17    grid_3.5.1      jsonlite_1.5   
    [7] lattice_0.20-35
```

Code example:

```r
    library(reticulate)
    use_virtualenv('~/projects/optima/python/venv/', required = TRUE)
    py_discover_config()
    sysp = import('sys')
```

second line produces the following:

    python:         C:/Users/pchtsp/Documents/projects/optima/python/venv//Scripts/python.exe
    libpython:      C:/Users/pchtsp/Documents/projects/optima/python/venv//Scripts/python36.dll
    pythonhome:     C:\Users\pchtsp\DOCUME~1\projects\optima\python\venv
    version:        3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
    Architecture:   64bit
    numpy:          C:\Users\pchtsp\DOCUME~1\projects\optima\python\venv\lib\site-packages\numpy
    numpy_version:  1.16.3

    NOTE: Python version was forced by use_python function

Third line just crashes the r session. Again, in Ubuntu ir works just fine.

**Comment by kevinushey** [comment]
Python virtual environments are unfortunately not supported on Windows. (This should normally produce an R error indicating this rather than a crash, though)

**Comment by pchtsp** [comment]
First of all, thank you for the response. I stopped trying to making it work. I did not find this in any documentation, though. Do you know if there are plans on adding support for virtual environments in windows with reticulate soon? If not, is there any workaround that can make me use my code in windows? 

Thanks again!

**Comment by kevinushey** [comment]
We aren't, unfortunately -- we're considering standardizing on Conda environments instead.

**Comment by pchtsp** [comment]
Is there already support for conda environments in reticulate? If so, is
there any documentation to follow?

That way I can give it a try and migrate.

**Comment by kevinushey** [comment]
Indeed there is. See for example:

https://rstudio.github.io/reticulate/articles/versions.html

The development version of R will also download and install a Miniconda environment by default for new users who haven't explicitly requested a particular Python environment.

**Comment by skeydan** [comment]
More information about the new automatic Miniconda installation here: https://github.com/rstudio/reticulate/blob/master/vignettes/python_dependencies.Rmd

**Comment by Danny-dK** [comment]
Just FYI if people are still looking for info on how to do it. This now works fine on Windows with the latest reticulate install  (I apparently had an older one and it aborted the R session) and Rstudio 1.4. Configure venv as shown in https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/ and follow https://support.rstudio.com/hc/en-us/articles/360023654474-Installing-and-Configuring-Python-with-RStudio
