### ISSUE TITLE
use_condaenv() does not throw error when the specified environment is not present

### ISSUE THREAD

**Issue by SSaishruthi** [rstudio/reticulate#599]
Hi,

`use_condaenv("xxx", required = TRUE)` throws error if the environment `xxx` is not available whereas `use_condaenv("xxx") does not throw any error if the environment `xxx` is not available.

I think `required=TRUE` should be the default when using conda or virtualenv. It may not be necessary for python. Also, adding this information in documentation will help.

**Comment by skeydan** [comment]
This is a much discussed feature which to my knowledge is not easy to change for compatibility reasons.
However, the behavior is visible from the documentation:

```
use_condaenv(condaenv = NULL, conda = "auto", required = FALSE)
```
