### ISSUE TITLE
py_install installs module but py_module_available still false

### ISSUE THREAD

**Issue by kevinegan31** [rstudio/reticulate#600]
Hello,

When I try installing the Python module "PySINDy" using py_install("PySINDy", pip = TRUE) the module seems to install fine. However, when I try using py_module_available("PySINDy") I receive FALSE rather than true. I am unable to import PySINDy as well and am unsure as to why.

Thanks

**Comment by ethanwhite** [comment]
Are you on Windows and if so have you tried upgrading to the current `master`? I ran into a related problem today upgrading to `master` fixed it for me.

**Comment by kevinegan31** [comment]
I am using Mac OSX currently rather than Windows. Is there a master for Mac?

**Comment by ethanwhite** [comment]
You can install the current development version (from the `master` branch) using the `devtools` package:

```r
devtools::install_github('rstudio/reticulate')
```

**Comment by kevinegan31** [comment]
I was able to update reticulate but am still receiving a FALSE message from py_module_available

**Comment by ethanwhite** [comment]
Sounds like this is different from my issue (#601) and since I'm just a user I'll let the devs take it from here. Good luck!

**Comment by vjdivyansh02** [comment]
![image](https://user-images.githubusercontent.com/56982390/67530208-fdedc680-f6db-11e9-9263-eaca905895b0.png)

unable to install development version.

**Comment by vjdivyansh02** [comment]
Firstly I am unable to  install the development version of reticulate

![image](https://user-images.githubusercontent.com/56982390/67530280-39889080-f6dc-11e9-9733-b47cd4a1d565.png)

**Comment by kevinushey** [comment]
You have to unload reticulate before attempting to reinstall it on Windows.

**Comment by vjdivyansh02** [comment]
Secondly I am Facing the same issue, while deploying to shinyapps.io, 
1) Can't change python version
2) Even though I am installing packages use virtualenv_install() the modules are still not available to use.

![image](https://user-images.githubusercontent.com/56982390/67530461-bfa4d700-f6dc-11e9-83fe-846dc3e618e3.png)

**Comment by kevinushey** [comment]
Can you please file that separately at https://github.com/rstudio/rsconnect/issues?

**Comment by vjdivyansh02** [comment]
okay, will do. Also here is what i get when I do it in a brand new R session 

![image](https://user-images.githubusercontent.com/56982390/67530599-3c37b580-f6dd-11e9-9f2f-aa7470de2a05.png)

**Comment by vjdivyansh02** [comment]
> Secondly I am Facing the same issue, while deploying to shinyapps.io,
> 
> 1. Can't change python version
> 2. Even though I am installing packages use virtualenv_install() the modules are still not available to use.
> 
> ![image](https://user-images.githubusercontent.com/56982390/67530461-bfa4d700-f6dc-11e9-83fe-846dc3e618e3.png)

Although I do think that it might be an issue in reticulate and also related to the current issue here. because the modules are being installed but py_module_available shows FALSE. Can that be true?

**Comment by skeydan** [comment]
Hi @kevinegan31 does the problem this issue was opened for still exist?
