### ISSUE TITLE
use_condaenv fails on reruns even if environment hasnt been changed

### ISSUE THREAD

**Issue by sstorey-nephila** [rstudio/reticulate#602]
I have run code once, and use_condaenv works. Then without changing anything, when rerunning use_condaenv (when re-running that codeblock) it does the check and it then throws the error shown below. Note it switches the direction of the final / and thus it appears the string compare of environments fails.

ERROR: The requested version of Python ('C:\Users\JSmith\Anaconda3\envs\r-reticulate\python.exe')
cannot be used, as another version of Python
('C:\users\JSmith\anaconda3\envs\r-reticulate/python.exe') has already been initialized. Please
restart the R session if you need to attach reticulate to a different version of Python.
Error in use_python(conda_env_python, required = required) : 
  failed to initialize requested version of Python

Restarting R session resolved the issue as a workaround but when the environment hasnt been changed ( either through RETICULATE_PYTHON env variable or via use_condaenv ) however this shouldnt be required.

I have used either of the following to set which conda env to use
i. My env variable is set as follows in the .Rprofile
Sys.setenv(RETICULATE_PYTHON="C:\\users\\JSmith\\anaconda3\\envs\\r-reticulate")
ii. use_condaenv('r-reticulate',required=TRUE)

**Comment by kevinushey** [comment]
Looks like this is a bug in `reticulate`, sort of spurned by a surprising yet documented behavior of `normalizePath()`:

```
> normalizePath("~/anaconda3")
[1] "C:\\Users\\kevinushey\\anaconda3"
> normalizePath("~/Anaconda3")
[1] "C:\\Users\\kevinushey\\Anaconda3"
> normalizePath("~/AnAcOnDa3")
[1] "C:\\Users\\kevinushey\\AnAcOnDa3"
```

In other words, on Windows, paths are by default case-sensitive; `normalizePath()` does not try to normalize a path's case to match the "true" casing of the path.

You can work around this by setting the appropriate casing for the path, e.g.

```
Sys.setenv(RETICULATE_PYTHON="C:\Users\JSmith\Anaconda3\envs\r-reticulate")

```
