### ISSUE TITLE
TypeError when passing an argument to a Python function using reticulate

### ISSUE THREAD

**Issue by DanielReedOcean** [rstudio/reticulate#606]
This is a problem that was first posted at Stackoverflow [here](https://stackoverflow.com/questions/58082690/typeerror-when-using-reticulate-package-to-call-a-function-from-python-peakutils) and has been met with resounding silence for almost a fortnight, so I thought I'd try here.

I'm trying to use the Python function `indexes` from the package `peakutils`. The code below works fine.

```
# Load packages
library(data.table)
library(reticulate)

# Set RNG
set.seed(-1)

# Synthetic data function
foo <- function(x) sin(x) * sqrt(x) + rnorm(length(x), 0, 0.1)

# Create data
dt <- data.table(x = seq(0, 10, by = 0.1))
dt$y <- foo(dt$x)

# Import Python library
pu <- import("peakutils")

# Indices pf peaks
ind <- pu$indexes(dt$y, thres = 0.7)
```

Now, when I try to include the argument `min_dist` I get an error:

```
# Indices pf peaks now with a larger minimum distance
ind <- pu$indexes(dt$y, thres = 0.7, min_dist = 3L)
```

> Error in py_call_impl(callable, dots$args, dots$keywords) :
> TypeError: only integer arrays with one element can be converted to an index

It seems like `3L` – and integer array with only one element – is not being recognised as such. Am I passing the argument incorrectly or is something else amiss?

**Comment by kevinushey** [comment]
This is surprising to me as well. I don't see any obvious reason why this is happening but I'll try to look a bit deeper.

**Comment by kevinushey** [comment]
Looks like the answer was simpler than I first thought. The problem is that the R vector is being passed along to the function as a Python list, rather than a NumPy array.

You can get things to work by explicitly creating a numpy array; e.g.

```
library(reticulate)
np <- import("numpy")
pu <- import("peakutils")
data <- rnorm(100)
npdata <- reticulate::np_array(data)
pu$indexes(npdata, thres = 0.7, min_dist = 2L)
```

You can also force the issue by creating an R array explicitly; e.g.

```
library(reticulate)
np <- import("numpy")
pu <- import("peakutils")
data <- rnorm(100)
pu$indexes(as.array(data), thres = 0.7, min_dist = 2L)
```

**Comment by DanielReedOcean** [comment]
Ah, I see. Thanks for solving this so quickly. I assumed that `min_dist` was the problem, but presumably using this argument just manifested the actual problem with the `y` argument.

**Comment by kevinushey** [comment]
Indeed, there is a separate branch that is taken in the code when `min_dist > 1`:

https://github.com/lucashn/peakutils/blob/f1f26011d5832b6caef7abe22e27ab1e82a1a0e6/peakutils/peak.py#L90-L102
