### ISSUE TITLE
offer an option to deactivate miniconda prompt in offline environment

### ISSUE THREAD

**Issue by cderv** [rstudio/reticulate#608]
Our RStudio Servers Pro clusters at my company are in an offline environment. 

Is there already a mechanism to deactivate installation prompt as users won't be able to download miniconda from the web ?

Would it be something you would consider ?

**Comment by jjallaire** [comment]
I think that we should consider in general whether we want the prompt to
happen at all when running on a server (or to allow server admins to opt-in
to the prompt).

**Comment by kevinushey** [comment]
We could add an R option for enabling / disabling the prompt -- would that be sufficient?

The issue can also be avoided by explicitly using `reticulate::use_*()` to request a particular Python environment, but that sounds like it might not be sufficient in all cases.

**Comment by cderv** [comment]
> We could add an R option for enabling / disabling the prompt -- would that be sufficient?

Yes, that would allow a R admin to configure a server wide option to control the default behavior of reticulate. About the default, I wonder if it should not be different on server or personal computer. I think on a server, specifically a RStudio server for multiuser, it is often already all configure and one don't want that each user install its version of conda. An option would definitely allow to configure that.

**Comment by kevinushey** [comment]
How about something like:

```
options(reticulate.miniconda.enabled = FALSE)
```

This could be then placed in a system or site R profile.

Or would an environment variable (e.g. `RETICULATE_MINICONDA_ENABLED = FALSE`) be more appropriate? (since it would then be inherited by child processes, which may be important in some contexts)

**Comment by cderv** [comment]
I believe reticulate already have a few env var to control behavior. Not sure about options. 

Also this have the advantage to be configurable easily on a server outside R files. The child process argument is also to consider. 

Between option and environment variable, I always not sure what is the best. Both way would allow to deactivate the prompt so it feels the need.

**Comment by kevinushey** [comment]
You can now set:

```
RETICULATE_MINICONDA_ENABLED=FALSE
```

to instruct reticulate to turn off its regular Miniconda checks.

**Comment by jjallaire** [comment]
I still wonder whether this shouldn't be the default behavior in server
environments (as it seems like the server admin would want to
control/provision Python).

**Comment by jjallaire** [comment]
Yes, the check for RStudio Server would likely be enough.

I think it could be argued either way (i.e. by not doing it on a server we
may leave some users w/o the ability to install but we'll have less server
admins ticked that we are installing miniconda). I am on the fence here and
am happy doing this or not depending on what you think is best.

**Comment by kevinushey** [comment]
My thought is that there are probably enough users running personal / private servers (effectively treating it like RStudio Desktop) who would still appreciate having the automatic installation + usage of Miniconda.

In general, we put the onus of configuration on to the server administrator, even when that burden is high. I think it's okay to extend that burden a bit more for administrators who need to control what version of Python `reticulate` binds to, as long as we make configuration clear in the documentation.

That said, perhaps a middle ground would be to only use Miniconda when an appropriate version of Anaconda is not already installed or available. Do you think that's reasonable?

**Comment by skeydan** [comment]
Please just disregard my comment if irrelevant, but do we want to suggest installing Miniconda independently of the OS used?

I personally have been using Anaconda for a long time just as a matter of habit, but after finally trying virtualenv I've come to think that on Linux, there is really no need to use Anaconda (or Miniconda). (And I've removed it completely on my machine).

So instead of checking for RStudio Server, or in addition, one could check the OS perhaps?

**Comment by jjallaire** [comment]
The issue is that as soon as we use the system python we get into various
mis or mal-configuration scenarios. If we can use a version of Python known
to us it will reduce the (effective) net exposure to configuration related
bugs we can't easily diagnose or control for.

**Comment by jjallaire** [comment]
I'd agree with the idea that we won't install miniconda if we see that
Anaconda is already there.

**Comment by cderv** [comment]
Regarding Miniconda installation not offered if Anaconda is already set up and running, that is what I would have expected as I reported in #607.

Regarding the default behavior on servers, as a current RStudio Servers admin, having a configuration option I can rely on to change the default behavior if I want to is enough. We already have a lot of default configurations to change, I don't think one more is an issue.  

Possibly, the automatic detection and deactivation would make sense on pro servers for pro customers where servers are often not used as personnal servers "RStudio-Desktop-like". (At least, I think so but I am just one out of many pro users). In that case, I guess the product could just defined the environment variable above as FALSE on RSP, changing reticulate default, that would still be customizable using the same env var. 

However, maybe too much of a cross configuration mess.
