### ISSUE TITLE
py_config reports twice the same versions on windows

### ISSUE THREAD

**Issue by cderv** [rstudio/reticulate#609]
While discovering the new dev version of reticulate with the use of miniconda, I just stumble upon what I think to be an unwanted behavior on windows. 

## Behavior

`py_config` and `py_discover` just reports twice the same python version because it does not get correctly deduplicated as some path are using `/` and others `\\`

``` r
reticulate::py_config()
#> python:         C:/Users/chris/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
#> libpython:      C:/Users/chris/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
#> pythonhome:     C:\Users\chris\AppData\Local\r-miniconda\envs\r-reticulate
#> version:        3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
#> Architecture:   64bit
#> numpy:          C:\Users\chris\AppData\Local\r-miniconda\envs\r-reticulate\lib\site-packages\numpy
#> numpy_version:  1.16.5
#> 
#> python versions found: 
#>  C:/Users/chris/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
#>  C:\Users\chris\AppData\Local\r-miniconda\envs\r-reticulate\python.exe
#>  C:\Users\chris\AppData\Local\r-miniconda\python.exe
```

We see that first and second versions are the same. 
Also, path form different components are returned sometime with `/` and sometimes with `\`.

Let's clarify that everything is working fine then, but I wonder if this should be change or not.

## Analysis

One is found looking a miniconda envpath
``` r
reticulate:::miniconda_envpath("r-reticulate")
#> [1] "C:/Users/chris/AppData/Local/r-miniconda/envs/r-reticulate"
reticulate::miniconda_path()
#> [1] "C:/Users/chris/AppData/Local/r-miniconda"
```

but it explicitly normalizing path with `/`:
https://github.com/rstudio/reticulate/blob/565ba8f117f5fefd0a1038a522411b2cf2128e27/R/miniconda.R#L158

Whereas others versions are reported by conda using `\\`
``` r
reticulate:::python_conda_versions()
#>           name
#> 1  r-miniconda
#> 2 r-reticulate
#>                                                                          python
#> 1                     C:\\Users\\chris\\AppData\\Local\\r-miniconda\\python.exe
#> 2 C:\\Users\\chris\\AppData\\Local\\r-miniconda\\envs\\r-reticulate\\python.exe
```

The third is reported by
``` r
reticulate:::py_versions_windows()
#>       type hive                                  install_path
#> 1 Anaconda  HCU C:\\Users\\chris\\AppData\\Local\\r-miniconda
#>                                             executable_path version arch
#> 1 C:\\Users\\chris\\AppData\\Local\\r-miniconda\\python.exe     3.7  x64
```

Two of them only should be kept when de-duplication happens
https://github.com/rstudio/reticulate/blob/565ba8f117f5fefd0a1038a522411b2cf2128e27/R/config.R#L214-L215

`/` and `\` gets mixed up when printing `py_config` result. It would benefit to be more consitent I guess.

**Comment by kevinushey** [comment]
Thanks -- I believe this should be better handled now. Let me know if you bump into problems.
