### ISSUE TITLE
Using python's input() function.

### ISSUE THREAD

**Issue by rossg5309** [rstudio/reticulate#610]
RStudio locks up when requesting user input with the input() function in a python script. Is there a way to get this to work or just a limitation of the implementation?

**Comment by jjallaire** [comment]
I wonder if we could do this (and call `readline()` from R): https://gist.github.com/turgay/ead6c73386612858301b

**Comment by kevinushey** [comment]
I believe we could. We do a similar trick with `plt.show()` for matplotlib parts.
