### ISSUE TITLE
Python 3.8 no longer uses libpython - (sorry my bad, build python 3.8 with configure --enable-shared and reticulate works)

### ISSUE THREAD

**Issue by dbonner** [rstudio/reticulate#615]
Hi,
I have installed Python 3.8 as an alternate installation on Ubuntu 18.04 (under /opt/Python-3.8.0).  The system is still able to use the default Python that came with Ubuntu.

I created a virtual environment in my home directory with:
python -m venv tf38

I can not get python to initialize in R:

> library(reticulate)
> use_virtualenv("~/tf38")
> py_config()
Error in initialize_python(required_module, use_environment) :
  Python shared library not found, Python bindings not loaded.
> py_discover_config()
python:         /home/daniel/tf38/bin/python
libpython:      [NOT FOUND]
pythonhome:     /usr/local:/usr/local
version:        3.8.0 (default, Oct 20 2019, 16:51:39)  [GCC 7.4.0]
numpy:          /home/daniel/tf38/lib/python3.8/site-packages/numpy
numpy_version:  1.17.3
 
I believe this is because Python 3.8 no longer uses libpython (the file is not included and can not be installed).  

I believe this is relevant (from https://docs.python.org/3/whatsnew/3.8.html):

"On Unix, C extensions are no longer linked to libpython except on Android and Cygwin. When Python is embedded, libpython must not be loaded with RTLD_LOCAL, but RTLD_GLOBAL instead. Previously, using RTLD_LOCAL, it was already not possible to load C extensions which were not linked to libpython, like C extensions of the standard library built by the *shared* section of Modules/Setup. (Contributed by Victor Stinner in bpo-21536.)"

Please patch reticulate() to work with Python 3.8 and Python 3.8 virtual environments which are without libpython.

Many thanks,
Daniel

**Comment by skeydan** [comment]
What output do you get for 

```
ldd ~//tf38/bin/python3
```

? 

Also, how did you install Python 3.8?
For linux, here: https://www.python.org/downloads/release/python-380/ I found the source only and building Python 3.8 from source (setting `rpath`), `reticulate` works fine for me.

**Comment by dbonner** [comment]
Hi Sigrid,
Here's the output:
ldd ~//tf38/bin/python3
        linux-vdso.so.1 (0x00007ffce1fe3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
(0x00007ff48e7e5000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff48e5e1000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1
(0x00007ff48e3de000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff48e040000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff48dc4f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff48efc5000)

I built python 3.8 from source using this tutorial:
https://tecadmin.net/install-python-3-8-ubuntu/
I didn't set rpath.  What's the exact command that includes rpath?
Regards,
Daniel

**Comment by skeydan** [comment]
You could either set it in `configure`, e.g.

```
./configure --enable-shared --prefix=/home/someuser/python/python3.8 LDFLAGS=-Wl,-rpath=/home/someuser/python/python3.8/lib
```

or you could use `patchelf` to change it on the executable after it was built:

```
# assume PREFIX is the location you specified in configure
# don't need to set ORIGIN, will be known automatically
patchelf --set-rpath '${ORIGIN}/../lib' ${PREFIX}/bin/python3.7
```

**Comment by dbonner** [comment]
Sorry I didn't specify a PREFIX in configure.

I issued:

sudo ./configure --enable-optimizations
sudo make altinstall

I think the default prefix directory is /usr/local

So I tried:

sudo patchelf --set-rpath '${ORIGIN}/../lib' /usr/local/bin/python3.8

The output of 'ldd /usr/local/bin/python3.8' remains the same.

reticulate() fails to initialize python and does not find libpython.

I'm not sure where the /lib directory is.

Much appreciated if you can help me.

Daniel

**Comment by dbonner** [comment]
Looking at 'python-config', I think the lib directory is '/usr/local/lib'.
It contains libpython3.8.a
Should I try:
sudo patchelf --set-rpath '/usr/local/lib' /usr/local/bin/python3.8
Daniel

**Comment by dbonner** [comment]
Still not working.

My pythonhome: /usr/local:/usr/local

Does this help?

What is your output in R of:
pyconfig()
and
py_discover_config()
?

**Comment by dbonner** [comment]
My libpython3.8.a file is a static library which reticulate can't work
with. It needs the shared library (.so) .

**Comment by skeydan** [comment]
Hi, I don't know why yours is a static library?

I think it might have gotten that complicated because you were doing it all as root. I was presupposing you extract the tarball somewhere into your home directory, build it there and also install it there (all as a normal user). (For example, PREFIX could be `/home/daniel/python/python3.8`.)

So my commands above are just dependent on local structure, not on where in the file system things end up when you install them "officially".

**Comment by kevinushey** [comment]
You need to configure Python with `--enable-shared`.

**Comment by eddelbuettel** [comment]
Moreover, Python 3.8 is very new.  And for most distros it is very deeply entwined with the system -- so for example Debian doesn't even have it in the 'experiemental' branch yet (and the Debian maintainer is the Ubuntu maintainer, and full-time Canonical employee who is very skilled at this).  So if I were you I would just sit back and wait for the distro to catch up and give it to you (and relatedly, I would not recommended sitting on LTS release -- I update every six months).

But if you really must use 3.8 then in the very narrow sense @kevinushey is spot on:  the error is actually on your end for producing a statically-linked Python.

**Comment by dbonner** [comment]
Many thanks @kevinushey.   I built python 3.8 again with
sudo ./configure --enable-optimizations
sudo make altinstall
All is fixed.  library(reticulate) and usevirtualenv() works.
Hooray!

**Comment by kevinushey** [comment]
Glad to hear it!
