### ISSUE TITLE
Travis documentation

### ISSUE THREAD

**Issue by Ironholds** [rstudio/reticulate#62]
I've been building a package using reticulate and am writing up some notes on how to integrate reticulate-based packages with Travis, since I expect many R developers will only be familiar with R travis procedures and not Python. Any interest in me formalising it, formatting it in the same fashion as reticulate's existing package documentation, and submitting a PR?

**Comment by jjallaire** [comment]
That would be great!

Here is my Travis file for reticulate (note that it doesn't so any pip
installs so is probably much more straightforward than what you are
brewing): https://github.com/rstudio/reticulate/blob/master/.travis.yml

We could either have a new vignette or we could add it to the Packages
vignette (
https://github.com/rstudio/reticulate/blob/master/vignettes/package.Rmd).
Let me know which you think is best.

**Comment by Ironholds** [comment]
I'll write it out and see how long it comes out as? If it's just another section, package vignette - if it's longer I might suggest a new'n.

**Comment by jjallaire** [comment]
Okay, sounds good!

**Comment by fboehm** [comment]
@Ironholds is your .travis.yml file publicly available? I'd love to see it, as I'm working on a R package and running into snags when trying to use Travis CI.
