### ISSUE TITLE
Reticulate seems to overwrite default arguments of python function

### ISSUE THREAD

**Issue by bhagwataditya** [rstudio/reticulate#624]
I am having a situation where reticulate is overwriting the default arguments of a python function

Let me first reproduce the workflow. First, I installed python module [azimuth](https://github.com/MicrosoftResearch/Azimuth) with:

    conda create --name azimuth python=2.7
    conda activate azimuth
    pip install azimuth
    pip install scikit-learn==0.17.1 # not available through conda - required for azimuth

Direct python (in Anaconda prompt) works fine

    python
    import numpy as np
    import azimuth.model_comparison as azi
    array1 = np.array(["TCATGACCAAGAAGCAAGTTGGGGAGGAAA", "CTTCCATACTACTGTTCATCACCAAGGAAG"])
    azi.predict(array1)

       No model file specified, using V3_model_nopos
       azimuth\features\featurization.py:144: FutureWarning: Sorting because non-concatenation axis 
       is not aligned. A future version of pandas will change to not sort by default.
       To accept the future behavior, pass 'sort=False'.
       To retain the current behavior and silence the warning, pass 'sort=True'.
       feat_NX = pandas.concat([feat_NX, NX_onehot], axis=1)

       array([0.6118257 , 0.67375809])

Reticulated python crashes

    require(reticulate)
    use_condaenv('azimuth')
    azi <- import('azimuth.model_comparison', convert=FALSE)
    array1 <- np_array(c("TCATGACCAAGAAGCAAGTTGGGGAGGAAA", "CTTCCATACTACTGTTCATCACCAAGGAAG"))
    azi$predict(array1)

        Error in py_call_impl(callable, dots$args, dots$keywords) : 
        TypeError: object of type 'int' has no len()

        Detailed traceback: 
        File "C:\PROGRA~3\ANACON~1\envs\azimuth\lib\site-packages\azimuth\model_comparison.py", line 518, in predict assert len(aa_cut) > 0, "Make sure that aa_cut is not empty"

Error message and head of the function `predict` show that this happens because the argument `aa_cut=None` is set to some integer value rather the default.

    def predict(seq, aa_cut=None, percent_peptide=None, model=None, model_file=None, pam_audit=True, length_audit=False, learn_options_override=None):

        assert isinstance(seq, (np.ndarray)), "Please ensure seq is a numpy array"
        assert len(seq[0]) > 0, "Make sure that seq is not empty"
        assert isinstance(seq[0], basestring), "Please ensure input sequences are in string format, i.e. 'AGAG' rather than ['A' 'G' 'A' 'G'] or alternate representations"

        if aa_cut is not None:
            assert len(aa_cut) > 0, "Make sure that aa_cut is not empty"
            assert isinstance(aa_cut, (np.ndarray)), "Please ensure aa_cut is a numpy array"
            assert np.all(np.isreal(aa_cut)), "amino-acid cut position needs to be a real number"

Specifying all default arguments explicitly fixes the issue:

    > azi$predict(seq = np_array("TCATGACCAAGAAGCAAGTTGGGGAGGAAA"), aa_cut=NULL, percent_peptide = NULL, model = NULL, model_file = NULL, pam_audit = TRUE, length_audit = FALSE, learn_options_override = NULL)
    No model file specified, using V3_model_nopos
    [0.6118257]

sessionInfo()

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.13

loaded via a namespace (and not attached):
[1] compiler_3.6.1  Matrix_1.2-17   tools_3.6.1     Rcpp_1.0.2      grid_3.6.1      jsonlite_1.6    packrat_0.5.0  
[8] lattice_0.20-38

**Comment by bhagwataditya** [comment]
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.13

loaded via a namespace (and not attached):
[1] compiler_3.6.1  Matrix_1.2-17   tools_3.6.1     Rcpp_1.0.2      grid_3.6.1      jsonlite_1.6    packrat_0.5.0  
[8] lattice_0.20-38

**Comment by kevinushey** [comment]
The signature you are reporting for `predict` does not match what I see:

```
def predict(seq, aa_cut=-1, percent_peptide=-1, model=None, model_file=None, pam_audit=True, length_audit=False, learn_options_override=None):
    """
    if pam_audit==False, then it will not check for GG in the expected position
    this is useful if predicting on PAM mismatches, such as with off-target
    """
```

Is it possible different versions of the `azimuth` package are being used in your two cases?

**Comment by bhagwataditya** [comment]
Hi Kevin, you are right, it is indeed an azimuth (version) issue, and not a reticulate issue. Sorry to take your time. Thanks for checking.
