### ISSUE TITLE
errors in use_python( ,require=T)

### ISSUE THREAD

**Issue by ChickenWangSY** [rstudio/reticulate#625]
hi ,
     when I use `use_python()` to set a new version of python, I got the error information:
```
> use_python("/usr/local/bin/python3",required = T)
Error in use_python("/usr/local/bin/python3", required = T) : 
  Required version of Python '/usr/local/bin/python3' cannot be used because another version of Python ('/Library/Frameworks/Python.framework/Versions/3.7/bin//python3') is already initialized for this process.
In addition: Warning message:
In normalizePath(normalize_python_path(path)$path, winslash = "/") :
  path[1]="/Library/Frameworks/Python.framework/Versions/3.7/bin//python3": No such file or directory
```
actually, i didn't understand  where python configure information correponding with R  were stored in. I had uninstalled my old python in OSX, but `py_configure` showed still the old python configure information : 
```
> py_config()
python:         /Library/Frameworks/Python.framework/Versions/3.7/bin//python3
libpython:      /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/libpython3.7.dylib[NOT FOUND]
pythonhome:     /Library/Frameworks/Python.framework/Versions/3.7:/Library/Frameworks/Python.framework/Versions/3.7
version:        3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52)  [Clang 6.0 (clang-600.0.57)]
numpy:          /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy
numpy_version:  1.16.4

NOTE: Python version was forced by RETICULATE_PYTHON
```
then i just want to set a new python path `/usr/local/bin/python3` by `use_python(, require = T)`, but errors come. if `require` were set `F`, errors disappeared. but the result of `py_config()` didn't change.

so how should I change the python version corresponding to my R?

regards!

so

**Comment by cderv** [comment]
> NOTE: Python version was forced by RETICULATE_PYTHON

Do you have an environment configured somewhere called `RETICULATE_PYTHON`  ? 

This would force `reticulate` to use this version. 
See explanation here: https://rstudio.github.io/reticulate/articles/versions.html#providing-hints

**Comment by ChickenWangSY** [comment]
much thanks for your advise, it's done successfully. 
actually, the file `.Rprofile` were not found and I created it.
