### ISSUE TITLE
Regression using the `as` argument in 1.13

### ISSUE THREAD

**Issue by chyzzqo2** [rstudio/reticulate#631]
With 1.12 i can do

```
require('reticulate')
import('time', as='t')
```

but with 1.13 i get `Evaluation error: evaluation nested too deeply`or `Evaluation error: Evaluation error: C stack usage  7971844 is too close to the limit`

**Comment by kevinushey** [comment]
Thanks for the bug report! I can reproduce this and will try and see what's going on.

**Comment by kevinushey** [comment]
This should be fixed in the development builds of `reticulate`. Thanks for reporting!

**Comment by chyzzqo2** [comment]
Will there be a patch release with this fix? Or do we wait for 0.14?

**Comment by kevinushey** [comment]
It will be part of 0.14 (we're hoping to publish a new release of `reticulate` within the next month or so)
