### ISSUE TITLE
use_miniconda reports twice the same environment but it is the same

### ISSUE THREAD

**Issue by cderv** [rstudio/reticulate#633]
I think this is related to #609 

On windonws, using miniconda and `use_miniconda` or `use_conda`, there is a warning saying that the version asked is not the version loaded , but it is the same. only the `\` differs from `/` in the path. See below

``` r
reticulate::use_miniconda("r-reticulate")
reticulate::import("os")
#> Warning: Python 'C:\Users\chris\AppData\Local\r-miniconda\envs\r-
#> reticulate\python.exe' was requested but 'C:/Users/chris/AppData/
#> Local/r-miniconda/envs/r-reticulate/python.exe' was loaded instead (see
#> reticulate::py_config() for more information)
#> Module(os)
```

Also with `condaenv`
``` r
reticulate::use_condaenv("r-reticulate")
reticulate::import("os")
#> Warning: Python 'C:\Users\chris\AppData\Local\r-miniconda\envs\r-
#> reticulate\python.exe' was requested but 'C:/Users/chris/AppData/
#> Local/r-miniconda/envs/r-reticulate/python.exe' was loaded instead (see
#> reticulate::py_config() for more information)
#> Module(os)
```

I think this comes from `conda_list` that reports path with `\\` but not sure it is just that. 🤔 

``` r
reticulate::conda_list()
#>           name
#> 1  r-miniconda
#> 2 r-reticulate
#>                                                                          python
#> 1                     C:\\Users\\chris\\AppData\\Local\\r-miniconda\\python.exe
#> 2 C:\\Users\\chris\\AppData\\Local\\r-miniconda\\envs\\r-reticulate\\python.exe
```

<sup>Created on 2019-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kevinushey** [comment]
Thanks for the bug report! Should be fixed up on mater now.

(We should likely consider always normalizing paths to use forward slashes, even on Windows.)

**Comment by cderv** [comment]
Glad I can help! 

Yes the default for normalizePath in R is not great. 
That is why I found yihui function in xfun very useful 
https://github.com/yihui/xfun/blob/master/R/paths.R#L46

Maybe you can add such a wrapper to handle path normalization in the package always the same way and not forget to switch default on Windows  ?
