### ISSUE TITLE
Reticulate package (unexpected token)

### ISSUE THREAD

**Issue by RedhaRedha1976** [rstudio/reticulate#634]
I started to use reticulate package for coding and switching between Python and R. I observed however that when saving the Rstudio files, Rstudio highlighted unexpected token concerning the Python part of the code.
Could this lead to mistakes in terms of results obtained when using the reticulate package ?

**Comment by kevinushey** [comment]
Can you be more explicit?

Are you trying to mix both R code and Python code within a single R document? If so, you should instead consider keeping your R code in a `.R` file, and your Python code in a `.py` file, and load your Python code with `source_python()`.

You can also consider using R Markdown, where R and Python chunks will be able to interoperate without issue.

**Comment by RedhaRedha1976** [comment]
Yes I am trying to mix both Python and R in the same R document. In fact when using "Python REPL", as shown (https://rstudio.github.io/reticulate/) the script seems to work correctly. The only thing is that unexpected tokens are mentioned within the text of the Python part of the script when saving the whole script (Python and R mixed) as .R file.

**Comment by kevinushey** [comment]
Ultimately, this is not a supported workflow. If you don't want to see diagnostic errors in RStudio when working in this mode I would recommend disabling diagnostics.

**Comment by jjallaire** [comment]
The best approach here is probably to use an Rmd file:
https://rstudio.github.io/reticulate/articles/r_markdown.html

**Comment by RedhaRedha1976** [comment]
Thank you for your answer.
Redha
