### ISSUE TITLE
Cannot import numpy from anaconda environment when using reticulate

### ISSUE THREAD

**Issue by bjsmith** [rstudio/reticulate#636]
In an R Markdown notebook I have tried to import an environment with numpy. When opening this environment from jupyter notebook, I can import numpy without any errors. But in RMarkdown, using reticulate,

```
```{r setup, include=FALSE}
library(reticulate)
#this fails as well
#use_python("C:\\Users\\besmith\\AppData\\Local\\Continuum\\anaconda2\\envs\\extended_p37\\python.exe")
use_condaenv("extended_p37")


```{python}
import numpy as np

```

I get the error:

```
Traceback (most recent call last):
  File "C:\Users\besmith\AppData\Local\Continuum\anaconda2\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\besmith\AppData\Local\Temp\RtmpAtDZxQ\chunk-code-ac4c064de3d90.txt", line 1, in <module>
    import numpy as np
  File "C:\Users\besmith\AppData\Local\Continuum\anaconda2\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\besmith\AppData\Local\Continuum\anaconda2\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\besmith\AppData\Local\Continuum\anaconda2\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\besmith\AppData\Local\Continuum\anaconda2\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\besmith\AppData\Local\Continuum\anaconda2\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.
```

Any idea why this might be? 

I have installed reticulate via
`devtools::install_github("rstudio/reticulate")`

**Comment by kevinushey** [comment]
I've seen issues like this in the past, when `numpy` was installed using `pip` rather than from the Conda repositories. See also:

https://github.com/numpy/numpy/issues/9272
https://github.com/numpy/numpy/issues/10714

Could that have happened in your case?

I'd also recommend using Anaconda3 rather than Anaconda2, and note that `reticulate` will be dropping support for Python 2 soon as well, as it will be reaching EOL in just 2 months:

https://pythonclock.org/

**Comment by bjsmith** [comment]
I don't recall, but I checked my revision history using `conda list --revisions` and the numpy installation appears there. So I think that means that numpy was installed from conda? I have had to install one or two things with pip, and it's possible I had to reinstall numpy that way. Is there another way to see whether that has happened?

I'll keep your recommendation in mind. Reluctant to upgrade right away as there could be things it could break.

**Comment by ECSTA7Y** [comment]
May be you could install `numpy` by:

```
conda_install("extended_p37", "numpy")
```

However, you could also check if your libraries have been installed by:

```
py_module_available('libraryname') 
```

**Comment by skeydan** [comment]
Hi,

I'm closing this issue; please feel free to reopen if there are still unsolved problems.

**Comment by asifm** [comment]
[This solution ](https://github.com/numpy/numpy/issues/10714#issuecomment-531424038) worked for me.
