### ISSUE TITLE
reticulate tfds.load issue

### ISSUE THREAD

**Issue by TonyFly3000** [rstudio/reticulate#644]
Hi I am facing following problem when I am using reticulate . I guess something wrong with the path in reticulate 

------  code in Rstudio with reticulate pacakge  ---------------------
```
import tensorflow as tf
import tensorflow_datasets as tfds
dataset, metadata = tfds.load('fashion_mnist', as_supervised=True, with_info=True)
```

error message:
```
>>> dataset, metadata = tfds.load('fashion_mnist', as_supervised=True, with_info=True)
NotFoundError: Failed to create a directory: C:/Users/tduan/Documents\tensorflow_datasets\fashion_mnist\1.0.0.incompleteLA5DAW; No such file or directory
```
--------------------  run in python with no problem -------
```
>>> import tensorflow_datasets as tfds
>>> dataset, metadata = tfds.load('fashion_mnist', as_supervised=True, with_info=True)
2019-11-13 17:58:38.266840: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
>>>
```

**Comment by skeydan** [comment]
Hi, 

I cannot reproduce, for me it works given your exact code... Perhaps someone with access to a Windows VM can jump in...

In the meantime, you might be interested to learn that there's an R wrapper for `tfds` as well: 

https://github.com/rstudio/tfds

**Comment by TonyFly3000** [comment]
I found out the problem . I was using old version of Anaconda python.  I install the new version of Anaconda . Its fine now . Thanks .
