### ISSUE TITLE
Plots created by Python chunk saved in wrong location during knit()

### ISSUE THREAD

**Issue by fdetsch** [rstudio/reticulate#645]
I created a sample [.Rmd file](https://github.com/fdetsch/knitr-playground/blob/master/R/plt_show.Rmd) as part of a [repository](https://github.com/fdetsch/knitr-playground) w/.Rproj. The .Rmd contains a Python code chunk that creates a plot.

As long as RStudio Preview Version 1.2.5019 > Tools > Global Options... > R Markdown > Evaluate chunks in directory: Document is set, the document compiles flawlessly (see output [.html]( http://htmlpreview.github.com/?https://github.com/fdetsch/knitr-playground/blob/master/R/plt_show.html)). However, when I change the evaluation location to 'Project' and then `knit()` the document, I get the following error: 

> File plt_show_files/figure-html/pyplot-1.png not found in resource path
> Error: pandoc document conversion failed with error 99
> Execution halted

In addition, a folder plt_show_files/figure-html with a file [pyplot-1.png](https://github.com/fdetsch/knitr-playground/blob/master/plt_show_files/figure-html/pyplot-1.png) in it is created at the root level of the project. I know that plots created by R chunks are rendered correctly despite the evaluation location being set to 'Project'; png files are in that case simply saved to a folder plt_show_files/figure-html relative to the location of the .Rmd. 

Is there any solution to get this working with Python code chunks without setting the evaluation location to 'Document'? Is this even related to **reticulate** or rather a RStudio issue?

Here's my 

```r
[master]> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.6.1   clisymbols_1.2.0 htmltools_0.4.0  tools_3.6.1      rstudioapi_0.10  yaml_2.2.0      
 [7] Rcpp_1.0.3       crayon_1.3.4     rmarkdown_1.16   knitr_1.26       xfun_0.11        digest_0.6.22   
[13] rlang_0.4.1      prompt_1.0.0     evaluate_0.14  
```

**Comment by kevinushey** [comment]
This is more likely an issue with RStudio and its `reticulate` integration rather than `reticulate` itself, but I'll try to verify that and move the issue if appropriate.

**Comment by fdetsch** [comment]
Thanks @kevinushey, appreciate it.

**Comment by cderv** [comment]
There is an issue in Rmarkdown repos that I believe to be related https://github.com/rstudio/rmarkdown/issues/1686
It involves setting `knit_root_dir` in render and the error is the same as you mentioned.

**Comment by kevinushey** [comment]
It looks like this is indeed related to the setting of `knit_root_dir`. I can reproduce by setting:

```
rmarkdown::render("R/plt_show.Rmd", knit_root_dir = getwd())
```

The problem is that directory used by pandoc when converting the file is still the parent directory of the `.Rmd`, rather than the requested `knit_root_dir`.

A similar .Rmd can showcase the issue:

`````
---
title: "knitr::include_graphics()"
output: html_document
---

```{r}
png("plot.png")
plot(1)
dev.off()
```

```{r}
knitr::include_graphics("plot.png")
```
`````

The plot is generated in `knit_root_dir`, but because Pandoc is run in the same directory as the document used, the resource isn't properly discovered.

Fortunately, the fix for `reticulate` is simple -- we just need to normalize the graphics path after we generate it.

**Comment by kevinushey** [comment]
(Note that figures are still generated at the project root, but I think that's ultimately the expected behavior here?)

**Comment by fdetsch** [comment]
Works like a charm, thanks.

**Comment by cderv** [comment]
> (Note that figures are still generated at the project root, but I think that's ultimately the expected behavior here?)

@kevinushey I think the behavior of reticulate python engine maybe different of the R engine regarding plots. From my understanding, R plot are saved to disk in `opts_knit$get('base.dir')`. There is special non exported helper in knitr called `in_base_dir` that is used in `knitr:::save_plot` and in which the plot hook is executed (`knit_hooks$get('plot')`). The figure folder are created [there](https://github.com/yihui/knitr/blob/0daf31be36eed8d8ec0ba51eedee909283afc45d/R/output.R#L538-L542)

This folder is different from `opts_knit$get('root.dir')`. Look at https://yihui.org/knitr/options/ for details. 

So with R, plots are saved in `base.dir` in a relative path controled with `fig.path`. It seems that python plot are saved in `root.dir` (which can be control by `knit_root_dir` argument in render). 

I think you solved the issue of founding python plot saved to disk but there is still the location that may need to be ajusted. Issue rstudio/rmarkdown#1686 seems related to that. 

Here is a reprex to observe the behavioir
```r
content <- "---
title: test plot python
---

```{r plot-r}
plot(1:10)
```

```{python plot-py}
import matplotlib.pyplot as plt
plt.plot(range(10))
```"
dir.create(project_dir <- tempfile("proj"))
dir.create(rmd_dir <- file.path(project_dir, "notebook"))
rmd_file <- file.path(rmd_dir, "test.Rmd")
xfun::write_utf8(content, rmd_file)
# if required, setup RETICULATE_PYTHON. here I used miniconda
reticulate::use_miniconda()
xfun::in_dir(project_dir, 
             rmarkdown::render(rmd_file, 
                               # self_contained to keep r figure 
                               output_format = rmarkdown::html_document(self_contained = FALSE),
                               # root dir will be project_dir
                               knit_root_dir = getwd(),
                               # to reduce noise in reprex
                               quiet = TRUE
                               )
)
# look at figure directories
fs::dir_ls(project_dir, recurse = TRUE, glob = "*/figure-*")
unlink(project_dir, recursive = TRUE)

# they are not in the same directories. 

#' This doesn't not seem in sync with how knitr r engine work. 
#' Let's note that this means this prevent a good cleaning. 
#' When self contained, figures directories should be removed

dir.create(project_dir <- tempfile("proj"))
dir.create(rmd_dir <- file.path(project_dir, "notebook"))
rmd_file <- file.path(rmd_dir, "test.Rmd")
xfun::write_utf8(content, rmd_file)
# if required, setup RETICULATE_PYTHON. here I used miniconda
reticulate::use_miniconda()
xfun::in_dir(project_dir, 
             res <- rmarkdown::render(rmd_file, 
                               # self_contained to keep r figure 
                               output_format = rmarkdown::html_document(self_contained = TRUE),
                               # root dir will be project_dir
                               knit_root_dir = getwd(),
                               # to reduce noise in reprex
                               quiet = TRUE
             )
)
# look at figure directories
fs::dir_ls(project_dir, recurse = TRUE, glob = "*/figure-*")
# Python figures are not cleaned properly
unlink(project_dir, recursive = TRUE)
```

Do you consider this the intended behavior for matplotlib figure ? In my POV, python engine should do as r engine with python figure.
At least, there is currently an adjustment to make to clean correctly the figure when `self_contained = TRUE`. 

I am willing to help on this (by opening new issue if required, or submitting a PR for some changes)

Hope it helps.

**Comment by kevinushey** [comment]
> From my understanding, R plot are saved to disk in opts_knit$get('base.dir').

Unfortunately, the `base.dir` option does not seem to be set when the reticulate engine is invoked.

The closest analog I can see is `knitr::opts_knit$get("output.dir")`.
