### ISSUE TITLE
Numpy import fails to pass simple sanity checks

### ISSUE THREAD

**Issue by scottgigante** [rstudio/reticulate#648]
This is probably an LD_LIBRARY_PATH issue but I can't work it out. I can't import numpy from reticulate, but I can from python. reticulate is a fresh install from github.

```
% R       

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

> reticulate::import("numpy")
Error in py_module_import(module, convert = convert) : 
  RuntimeError: The current Numpy installation ('/home/scottgigante/.local/lib/python3.7/site-packages/numpy/__init__.py') fails to pass simple sanity checks. This can be caused for example by incorrect BLAS library being linked in, or by mixing package managers (pip, conda, apt, ...). Search closed numpy issues for similar problems.

Detailed traceback: 
  File "/home/scottgigante/.local/lib/python3.7/site-packages/numpy/__init__.py", line 218, in <module>
    _sanity_check()
  File "/home/scottgigante/.local/lib/python3.7/site-packages/numpy/__init__.py", line 216, in _sanity_check
    raise RuntimeError(msg.format(__file__))
> reticulate::py_config()
python:         /usr/bin/python
libpython:      /usr/lib/libpython3.7m.so
pythonhome:     /usr:/usr
version:        3.7.3 (default, Mar 26 2019, 21:43:19)  [GCC 8.2.1 20181127]
numpy:          /home/scottgigante/.local/lib/python3.7/site-packages/numpy
numpy_version:  1.17.0
numpy:          /home/scottgigante/.local/lib/python3.7/site-packages/numpy

python versions found: 
 /usr/bin/python
 /usr/bin/python3
 /home/scottgigante/sandbox/bin/python
 /home/scottgigante/sandbox2/bin/python
 /home/scottgigante/testbed/bin/python
```

```
% /usr/bin/python
Python 3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy._sanity_check()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'numpy' has no attribute '_sanity_check'
>>> numpy._sanity_ch
KeyboardInterrupt
```

**Comment by kevinushey** [comment]
Is there anything unique about your Python installation, or the way you've configured your machine, or the way that numpy was installed in that Python environment?

Note that `numpy` defines its `_sanity_check()` function in `__init__`, calls it, then deletes it after. But you could try running that same code and see what you get:

https://github.com/numpy/numpy/blob/1e8e0d7193c2ba11528794c4fd0ed00386daa654/numpy/__init__.py#L236-L260

**Comment by skeydan** [comment]
This looks strange...

```
numpy:          /home/scottgigante/.local/lib/python3.7/site-packages/numpy
numpy_version:  1.17.0
numpy:          /home/scottgigante/.local/lib/python3.7/site-packages/numpy
```

could there be two `numpy` installations?

**Comment by kevinushey** [comment]
https://github.com/numpy/numpy/issues/8577 seems to suggest older Anaconda installations (using MKL) were affected by this.

**Comment by scottgigante** [comment]
I uninstalled my local numpy and it works with the system numpy. To recap what happened for others' benefit:

* not using Anaconda, yes using MKL
* installed a different version of numpy locally from pip, which meant my local numpy was _not_ compiled with MKL

My suspicion is this was the cause. Thanks for the quick follow-up!

**Comment by t-kalinowski** [comment]
Adding this here since this issue comes up first in google search for the warning issued by numpy's "failed to pass sanity check" warning. If you're seeing this, the fix is probably to reinstall numpy:  https://github.com/rstudio/reticulate/issues/1257#issuecomment-1213196996
