### ISSUE TITLE
tf.print never print to chunk output in RMarkdown using rmarkdown::render

### ISSUE THREAD

**Issue by everdark** [rstudio/reticulate#651]
Here is a minimum example:

`test.Rmd`:

````
```{r setup, include=FALSE}
library(reticulate)
use_python(Sys.getenv("PYTHON_PATH"), required=TRUE)
```

```{python}
import sys 
import tensorflow as tf
tf.print(1, output_stream=sys.stdout)
tf.print(1, output_stream=sys.stderr)
tf.print(1, output_stream=tf.compat.v1.logging.error)
```
````
When run with `rmarkdown::render("test.Rmd", output_format="html_notebook")`,
the above output always print to markdown console log instead of the resulting chunk output.

My `sessionInfo`:

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] reticulate_1.13 rmarkdown_1.17

loaded via a namespace (and not attached):
 [1] compiler_3.6.0  Matrix_1.2-17   tools_3.6.0     htmltools_0.4.0
 [5] Rcpp_1.0.3      grid_3.6.0      knitr_1.26      jsonlite_1.6
 [9] xfun_0.11       digest_0.6.22   rlang_0.4.1     lattice_0.20-38
[13] evaluate_0.14
```

My Python version: 3.6.5
TensorFlow version: 2.0.0

Not sure if this is a problem particular to tensorflow or reticulate.

**Comment by skeydan** [comment]
Thanks for reporting! I wonder if this might have to do with `tf.print` being a wrapper around a C++ kernel, see 

https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/ops/logging_ops.py#L382

https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/core/kernels/logging_ops.cc#L120

See also, w.r.t. Jupyter notebooks: https://github.com/tensorflow/community/pull/14/files#diff-6dc73e00aed7c8a7fbc0f53d7981f296R365

Just to characterize this more, things written to `stdout` do not appear at all, while `stderr` output appears below the code chunk (and on the console), but not in the generated html:

```{python}
import sys 
import tensorflow as tf
tf.print(111, output_stream=sys.stdout)
tf.print(222, output_stream=sys.stderr)
```
Output:
```
222
2019-11-20 09:43:36.456836: E tensorflow/core/kernels/logging_ops.cc:174] 333
```

**Comment by skeydan** [comment]
Making the above more precise and comparing the 3 locations

- chunk output (evaluating chunk)
- console ("by product" of evaluating chunk)
- html (obtained from knitting)

```{python}
import sys 
import tensorflow as tf
print(0)
print(1, file=sys.stderr)
tf.print(111, output_stream=sys.stdout)
tf.print(222, output_stream=sys.stderr)
```

### knitting 

- no output from TF

### chunk output

```
222
0
1
```

### console output

```
111
222
```

**Comment by kevinushey** [comment]
Note that if you're using Python 3 you need to explicitly flush output after printing, e.g.

```
print("hello", flush=True)
```

What makes this especially confusing is that some front-ends will auto-flush after output is printed, and this can also depend on how Python is being run (e.g. as a standalone interpreter vs. embedded in a process)

**Comment by skeydan** [comment]
(((Just quick answer, all of the above was using Python 3, and the pure Python `print` did print to chunk output (but not to console)))

I think it might make sense to split this into 2 things, right

- different behavior Python `print` vs TF `print` (try keeping `rmarkdown` out of it)
- different behavior R `print` vs. Python `print` (perhaps an `rmarkdown` issue/interaction)

?

**Comment by kevinushey** [comment]
Yes, I think that makes sense (assuming they are indeed separate issues, which they appear to be)

**Comment by skeydan** [comment]
Trying to formulate a partial hypothesis...
It seems like because `tf.print` immediately flushes the output

https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/core/kernels/logging_ops.cc#L161

our capturing mechanism never gets to see it.
For example, if I do, in `python.R`

```
 # scope output capture
  # capture_stdout <- "stdout" %in% type
  capture_stdout <- FALSE
  # capture_stderr <- "stderr" %in% type
  capture_stderr <- FALSE
  output_tools$start_capture(capture_stdout, capture_stderr)`
```

nothing prints in a Python script **except** the stuff from `tf.print`:

```
Python 3.7.5 (/home/key/.virtualenvs/r-reticulate/bin/python)
Reticulate 1.13.0.9005 REPL -- A Python interpreter in R.
>>> import sys 
>>> import tensorflow as tf
>>> print(sys.stdout)
>>> sys.stdout.__class__
>>> 
>>> tf.print(111, output_stream=sys.stdout)
111
```

Now if I assume that for normal (**non-`stderr`**) `rmarkdown` chunk (**Python** chunk, that is) output to be printed, we need the capturing, it also makes sense that with capturing disabled, all I can see from a chunk like this (as chunk output, not in the console - there I see everything) 

```
import sys 
import tensorflow as tf
sys.stdout.__class__
sys.__stdout__.__class__

print(-777)
tf.print(111, output_stream=sys.stdout)
tf.print(222, output_stream=sys.stderr)
tf.print(333) # default stderr
tf.print(444, output_stream=tf.compat.v1.logging.info)
#tf.print(555, output_stream=sys.__stdout__) ### error

```

is the stderr output:

```
222
333
2019-12-04 10:46:43.475247: I tensorflow/core/kernels/logging_ops.cc:170] 444
```

Consistent with this would be that if I have `tf$print` in an **R** chunk, it will _always_ print, because here we don't need/use the capturing:

```
```{r}
library(reticulate)
library(tensorflow)
sys <- import("sys")
class(sys$stdout)
tf$print(11111, output_stream = sys$stdout)
```

```
[1] "python.builtin.iterator" "_io.TextIOWrapper"       "_io._TextIOBase"        
[4] "_io._IOBase"             "python.builtin.object"  
11111.0
```

I think all in all, this is a consistent explanation assuming that

- for Python chunks, we need to capture in order to display to chunk output (but not console)
- for Python scripts, we need to capture as well
- somehow `stderr` stuff does NOT need to be captured (don't know why)?

If this is correct, I don't see a workaround apart from always printing to `stderr` when using `tf.print`, but in that case, a follow-up question would be (in `rmarkdown`) - is it possible to keep `stderr` output in the knitted html?

**Comment by skeydan** [comment]
From the above analysis, as TF directly writes to `stdout` (`fd` 1) but we only have access to Python's wrapper `sys.stdout`, there's nothing straightforward we could do from our side.

Two things to note...

- `tf.print` output at least appears in the console
- If you use `R` tensorflow, all is good:

```{r}
library(reticulate)
library(tensorflow)
sys <- import("sys")
tf$print(11111, output_stream = sys$stdout)
```

```
11111.0
```

I'm closing the issue but we can reopen any time if new aspects come up.
