### ISSUE TITLE
Unable to reload Python module in R

### ISSUE THREAD

**Issue by louiswang01** [rstudio/reticulate#656]
It happens to me that after updating a Python module, I can't reload that module in R with reticulate, unless I start a new kernel. Is there a way to reload it? If not, would you consider to add this feature in the future?

Example:
```
> library(reticulate)
> use_python("/opt/anaconda/bin/python")
> t <- import("tt")
> t$test()
hi hi
/* tt.py is changed */
> t <- import("tt")
> t$test()
hi hi  # no change
```

**Comment by kevinushey** [comment]
Looks like this is technically possible:

https://docs.python.org/3/library/importlib.html#importlib.reload

**Comment by louiswang01** [comment]
Thanks Kevinushey. Yes it works. I am using Python 2.7 so here is what I do:

```
> library(reticulate)
>  use_python("/opt/anaconda/bin/python")
> t <- import("tt")
> t$say_hi()
hi hi
/* tt is updated */
> builtins <- import_builtins()
> builtins$reload(t)
Module(tt)
> t$say_hi()
hi!  # works!
```
