### ISSUE TITLE
How can't I use interactive python in Rstudio

### ISSUE THREAD

**Issue by Liripo** [rstudio/reticulate#659]
Dear developer:
I can't write python script in Rstudio, and I have installed python.
![image](https://user-images.githubusercontent.com/54770415/69708020-cc7e7580-1135-11ea-8b1a-0c9eec9ea816.png)
Thanks!

**Comment by Liripo** [comment]
The Chinese in the picture means that the specified program could not be found

**Comment by skeydan** [comment]
What version / installation of Python are you using?
E.g., what is the output if you start `python` on the command line?

**Comment by kevinushey** [comment]
This is because you're using Python 3.8 and the version of `reticulate` on CRAN does not yet support it. Please try installing the development version or consider switching back to an older version of Python.

**Comment by Liripo** [comment]
I have solved it, it is caused by my conda not entering the r-reticulate environment. bother。Thanks.

**Comment by Liripo** [comment]
Dear developer:
Sorry, I can import pandas using interactive python on the command line, but I reported an error using reticulate. I have tried reinstalling pandas, Rstudio, and updating reticulate.
![image](https://user-images.githubusercontent.com/54770415/69771071-6a218580-11c6-11ea-932f-424616089773.png)
![image](https://user-images.githubusercontent.com/54770415/69771077-71e12a00-11c6-11ea-875c-9a73095373c3.png)

**Comment by skeydan** [comment]
Can you please post the output of `pd.show_versions()`?

https://github.com/cython/cython/issues/1953

**Comment by Liripo** [comment]
![image](https://user-images.githubusercontent.com/54770415/69788350-488dc180-11f9-11ea-9e37-bdd788f6a2d5.png)
Without that attribute.

**Comment by Liripo** [comment]
This is pd.show_versions():
![image](https://user-images.githubusercontent.com/54770415/69788970-893a0a80-11fa-11ea-8dc8-03fcb8e57653.png)
![image](https://user-images.githubusercontent.com/54770415/69789000-9d7e0780-11fa-11ea-804f-f7a29445e98f.png)
THanks!

**Comment by skeydan** [comment]
Thanks. Can you try updating Cython to 0.29.14? I just tested with that version (and the same pandas version you have), and for me it works fine... Another difference would be though that I'm not using anaconda.

**Comment by Liripo** [comment]
There seems to be no way, my own laptop is also okay, but I do n’t understand why my company ’s computer cannot import the pandas module.Thanks for your help.

**Comment by kevinushey** [comment]
One possibility: on Windows, many modules rely on the PATH being set so that C extensions (DLLs) can be discovered in the appropriate location. The PATH might differ between your RStudio + Anaconda console environments.

Can you share the output of:

```
import os
print(os.environ["PATH"])
```

in each case?
