### ISSUE TITLE
reticulate cannot parse windows registry key to get versions

### ISSUE THREAD

**Issue by adalisan** [rstudio/reticulate#66]
I have anaconda python installation
My registry key tree under HCU/Software is Python/ContinuumAnalytics/Anaconda_4.1.1_64-bit/...
When I try to install tensorflow, I get the following error and message.
I am sad :(
 tensorflow::install_tensorflow("conda")
Error in if (arch == "32") arch <- "i386" else if (arch == "64") arch <- "x64" : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In read_python_versions_from_registry("HCU", key = "ContinuumAnalytics",  :
  Unexpected format for Anaconda version: Anaconda_4.1.1_64-bit

**Comment by jjallaire** [comment]
I made a change to address this a few days ago. Could you try installing
the latest version from GitHub via
devtools::install_github("rstudio/reticulate") to see if the issue is
solved in your setup?

**Comment by uevencodebro** [comment]
Well, this seems to have screwed my entire R installation up...
