### ISSUE TITLE
Feature Request: convert external pointer to capsule with r_to_py

### ISSUE THREAD

**Issue by Marlin-Na** [rstudio/reticulate#660]
I hope to have the functionality to pass an R's external pointer object to python, possibly by converting it into a capsule object. So that

1. the pointer and the underlying data are shared between R and python.
2. R's external pointer object won't be freed while python is still pointing to it.

It would be similar to how memory are shared between numpy array and R's array.

If you think this idea is reasonable, I can try to implement it and submit a PR when I have time.

**Comment by kevinushey** [comment]
I'd be open to a PR. Thanks!
