### ISSUE TITLE
Conda binary not found on macOS due to changed installation location

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/reticulate#661]
When installing Anaconda on macOS Catalina, the default installation location is in `~/opt` according to this [documentation](https://docs.anaconda.com/anaconda/install/mac-os/#installing-on-macos). My experience is that this is also where Miniconda is installed. However, previous versions of macOS would install conda elsewhere, so `reticulate::conda_binary()` won't find it, because `reticulate:::find_conda()`does not look in `~/opt` apparently. So I get this:

```r
reticulate::conda_binary()
#> Error: Unable to find conda binary. Is Anaconda installed?
```

I think this can be fixed by adding simply adding these path to `conda_locations` in [`reticulate:::find_conda()`](https://github.com/rstudio/reticulate/blob/92e03419e49f39bf2c350e764f91816bb47ced47/R/conda.R#L293).

**Comment by kevinushey** [comment]
Looks like this is a recent change in the Anaconda installers.
