### ISSUE TITLE
Error in sys$stdout$flush( ) : attemp to apply non-function

### ISSUE THREAD

**Issue by CHUNGGAK** [rstudio/reticulate#662]
I install reticulate in off-line environment.

`install.packages("E:/Users/DLCG001/reticulate-master",
repos = NULL, type = "source", lib = "E:/Users/DLCG001/Documents/R/win-library/3.6")`

* installing *source* package 'reticulate' ...
** using staged installation
** libs
make: Nothing to be done for 'all'.
installing to E:/Users/DLCG001/Documents/R/win-library/3.6/00LOCK-reticulate-master/00new/reticulate/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'reticulate'
    finding HTML links ... 완료
    PyClass                                 html  
    array_reshape                           html  
    as.character.python.builtin.bytes       html  
    conda-tools                             html  
    configure_environment                   html  
    dict                                    html  
    eng_python                              html  
    import                                  html  
    install_miniconda                       html  
    iterate                                 html  
    miniconda_path                          html  
    miniconda_update                        html  
    np_array                                html  
    py                                      html  
    py_available                            html  
    py_call                                 html  
    py_capture_output                       html  
    py_config                               html  
    py_config_error_message                 html  
    py_del_item                             html  
    py_discover_config                      html  
    py_func                                 html  
    py_function_custom_scaffold             html  
    py_function_wrapper                     html  
    py_get_attr                             html  
    py_get_item                             html  
    py_has_attr                             html  
    py_help                                 html  
    py_id                                   html  
    py_install                              html  
    py_is_null_xptr                         html  
    py_iterator                             html  
    py_last_error                           html  
    py_len                                  html  
    py_list_attributes                      html  
    py_main_thread_func                     html  
    py_module_available                     html  
    py_run                                  html  
    py_save_object                          html  
    py_set_attr                             html  
    py_set_item                             html  
    py_set_seed                             html  
    py_str                                  html  
    py_suppress_warnings                    html  
    py_to_r_wrapper                         html  
    py_unicode                              html  
    py_versions_windows                     html  
    r-py-conversion                         html  
    register_class_filter                   html  
    register_help_topics                    html  
    register_module_help_handler            html  
    register_suppress_warnings_handler      html  
    repl_python                             html  
    reticulate                              html  
    source_python                           html  
    tuple                                   html  
    use_python                              html  
    virtualenv-tools                        html  
    with-as-operator                        html  
    with.python.builtin.object              html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (reticulate)

I succeeded in loading the package.

`library(reticulate)`

But I could not use the function of the package.

`repl_python()`
Error in sys$stdout$flush() : attempt to apply non-function

`py_run_string('i = 5')`
Error in sys$stdout$flush() : attempt to apply non-function

My session information is as below.

`sessionInfo()`

R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Korean_Korea.949  LC_CTYPE=Korean_Korea.949    LC_MONETARY=Korean_Korea.949 LC_NUMERIC=C                
[5] LC_TIME=Korean_Korea.949    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.13.0-9005

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0    rappdirs_0.3.1 Rcpp_1.0.3     jsonlite_1.6  `

My environment variables are as below.

`Sys.getenv('PATH')`
[1] "E:/Users/DLCG001/program/Rtools/bin/;C:\\Program Files\\R\\R-3.6.0\\bin\\x64;C:\\oracle\\product\\12.2.0\\db_1\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\\\;C:\\Program Files\\Java\\jdk1.8.0_121\\bin\\;C:\\Program Files\\apache-maven-3.5.0\\bin\\;C:\\CommonDataModel-master\\Oracle\\VocabImport\\;C:\\CDMV5VOCAB\\;\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Docker Toolbox\\;C:\\Program Files\\WhiteRabbit_v0.5.19\\WhiteRabbit_lib\\;C:\\oracle\\product\\12.2.0\\db_1\\network\\admin\\;;C:\\Program Files\\\\SUT\\bin;$R_HOME$;E:\\Users\\DLCG001\\program\\Microsoft VS Code\\bin;E:\\Users\\DLCG001\\program\\Anaconda3"

And the python version is '3.7.4'.

**Comment by skeydan** [comment]
Is this on Windows Server?

Assuming you are not running this in RStudio, can you try that?

What is the output of

```
sys=import("sys")
sys$stdout
```


https://github.com/rstudio/reticulate/issues/584
https://stackoverflow.com/questions/57357001/reticulate-1-13-error-in-sysstdoutflush-attempt-to-apply-non-function

**Comment by CHUNGGAK** [comment]
Yes. This is on Windows Server 2012.

I run this in RStudio.
And RStudio version is 1.0.143.
Could the problem be caused by old version?

The output is as below.
`Sys = import("sys")
sys$stdout`
NULL

**Comment by CHUNGGAK** [comment]
Yes. This is on Windows Server 2012.

I run this in RStudio.
And RStudio version is 1.0.143.
Could the problem be caused by old version?

The output is as below.
`Sys = import("sys")`
`sys$stdout`
NULL

**Comment by CHUNGGAK** [comment]
Yes. This is on Windows Server 2012.

I run this in RStudio.
And RStudio version is 1.0.143.
Could the problem be caused by old version of RStudio?

The output is as below.
`sys = import("sys")`
`sys$stdout`
NULL

**Comment by skeydan** [comment]
I tried to reproduce, using Windows Server 2019, and it works fine for me.

I'm using the current github version of reticulate, which if it doesn't find a non-system Python, will prompt you to allow installation of Miniconda (which I did). This will currently yield a Python version 3.6.9.

Can you try if this approach works for you too?

**Comment by kevinushey** [comment]
This is where we perform output stream remapping:

https://github.com/rstudio/reticulate/blob/9d973bfc9db12e983e3d64ed0b38cd9b04c10366/inst/python/rpytools/output.py#L123-L127

And here's where we decide whether or not to remap output streams:

https://github.com/rstudio/reticulate/blob/9d973bfc9db12e983e3d64ed0b38cd9b04c10366/R/output.R#L6-L18

What confuses me is that `sys.stdout` and `sys.stderr` are, evidently, `None` on your system but the remap is not happening.

You can also set the environment variable (e.g. in your `.Renviron`)

```
RETICULATE_REMAP_OUTPUT_STREAMS = 1
```

See `?Startup` for more details on `.Renviron`.

**Comment by kevinushey** [comment]
@CHUNGGAK can you also share the result of:

```
reticulate::py_config()
```

in your session?

**Comment by CHUNGGAK** [comment]
@skeydan
There is not the request message of Miniconda installation during installing reticulate package.
I installed Miniconda just in case. But I still get same error.

**Comment by skeydan** [comment]
Hi, as @kevinushey was asking, could you please share the result of:

```
reticulate::py_discover_config()
reticulate::py_config()
```
in a fresh R session?

Probably that newly installed version of Miniconda is not getting used...

**Comment by skeydan** [comment]
Hi,

this should be fixed in the current dev version of `reticulate` (master branch on github).

I'm closing the issue, please feel free to reopen if you still run into problems.
