### ISSUE TITLE
py_module_available("tensorflow") cause illegal operand

### ISSUE THREAD

**Issue by moorugi98** [rstudio/reticulate#667]
Step to reproduce
1) Start R (doesn't matter whether via terminal or via Rstudio and in which conda environment it is)
2) library(reticulate)
3) py_module_available("tensorflow")

Here is the output from the terminal.

> library(reticulate)
> py_module_available("tensorflow")

 *** caught illegal operation ***
address 0x7f942e0a4d99, cause 'illegal operand'

Traceback:
 1: py_module_import(module, convert = convert)
 2: import(module)
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch({    import(module)    TRUE}, error = clear_error_handler(FALSE))
 7: py_module_available("tensorflow")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 

Here is the output of my conda environment:

# packages in environment at /home/minseok/miniconda3/envs/IDA2019:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.8.1                    pypi_0    pypi
astor                     0.8.0                    pypi_0    pypi
ca-certificates           2019.10.16                    0  
certifi                   2019.9.11                py37_0  
cloudpickle               1.2.2                    pypi_0    pypi
decorator                 4.4.1                    pypi_0    pypi
gast                      0.3.2                    pypi_0    pypi
google-pasta              0.1.8                    pypi_0    pypi
grpcio                    1.25.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
markdown                  3.1.1                    pypi_0    pypi
mock                      3.0.5                    pypi_0    pypi
ncurses                   6.1                  he6710b0_1  
numpy                     1.17.4                   pypi_0    pypi
openssl                   1.1.1d               h7b6447c_3  
pip                       19.3.1                   py37_0  
protobuf                  3.10.0                   pypi_0    pypi
python                    3.7.5                h0371630_0  
readline                  7.0                  h7b6447c_5  
setuptools                41.6.0                   py37_0  
six                       1.13.0                   pypi_0    pypi
sqlite                    3.30.1               h7b6447c_0  
tensorboard               1.14.0                   pypi_0    pypi
tensorflow                1.14.0                   pypi_0    pypi
tensorflow-estimator      1.14.0                   pypi_0    pypi
tensorflow-probability    0.7.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0  
werkzeug                  0.16.0                   pypi_0    pypi
wheel                     0.33.6                   py37_0  
wrapt                     1.11.2                   pypi_0    pypi
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3

**Comment by skeydan** [comment]
What's the output of your R `sessionInfo()`?

**Comment by moorugi98** [comment]
> What's the output of your R `sessionInfo()`?


R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
 [1] reticulate_1.13 forcats_0.4.0   stringr_1.4.0   dplyr_0.8.3    
 [5] purrr_0.3.3     readr_1.3.1     tidyr_1.0.0     tibble_2.1.3   
 [9] ggplot2_3.2.1   tidyverse_1.2.1 knitr_1.25     

loaded via a namespace (and not attached):
 [1] rstan_2.19.2       tidyselect_0.2.5   xfun_0.10         
 [4] haven_2.2.0        lattice_0.20-38    colorspace_1.4-1  
 [7] vctrs_0.2.0        generics_0.0.2     htmltools_0.4.0   
[10] stats4_3.6.1       loo_2.1.0          yaml_2.2.0        
[13] pkgbuild_1.0.6     rlang_0.4.1        pillar_1.4.2      
[16] glue_1.3.1         withr_2.1.2        modelr_0.1.5      
[19] readxl_1.3.1       matrixStats_0.55.0 lifecycle_0.1.0   
[22] munsell_0.5.0      gtable_0.3.0       cellranger_1.1.0  
[25] rvest_0.3.5        evaluate_0.14      inline_0.3.15     
[28] labeling_0.3       callr_3.3.2        ps_1.3.0          
[31] parallel_3.6.1     broom_0.5.2        Rcpp_1.0.3        
[34] backports_1.1.5    scales_1.0.0       StanHeaders_2.19.0
[37] jsonlite_1.6       gridExtra_2.3      hms_0.5.2         
[40] digest_0.6.22      stringi_1.4.3      processx_3.4.1    
[43] grid_3.6.1         cli_1.1.0          tools_3.6.1       
[46] magrittr_1.5       lazyeval_0.2.2     crayon_1.3.4      
[49] pkgconfig_2.0.3    zeallot_0.1.0      Matrix_1.2-17     
[52] prettyunits_1.0.2  rsconnect_0.8.15   xml2_1.2.2        
[55] lubridate_1.7.4    assertthat_0.2.1   rmarkdown_1.16    
[58] httr_1.4.1         rstudioapi_0.10    R6_2.4.0          
[61] nlme_3.1-142       compiler_3.6.1

**Comment by skeydan** [comment]
Hm... could you also indicate the output of `py_config()`?
Also, I assume the same happens for any other module?

**Comment by moorugi98** [comment]
> library(reticulate)
> py_config()
python:         /home/minseok/miniconda3/envs/data/bin/python
libpython:      /home/minseok/miniconda3/envs/data/lib/libpython3.7m.so
pythonhome:     /home/minseok/miniconda3/envs/data:/home/minseok/miniconda3/envs/data
version:        3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]
numpy:          /home/minseok/miniconda3/envs/data/lib/python3.7/site-packages/numpy
numpy_version:  1.17.2

python versions found: 
 /usr/bin/python
 /usr/bin/python3
 /home/minseok/miniconda3/envs/data/bin/python
 /home/minseok/miniconda3/envs/forecast/bin/python
 /home/minseok/miniconda3/envs/IDA2019/bin/python
 /home/minseok/miniconda3/envs/nest/bin/python
 /home/minseok/miniconda3/envs/py2/bin/python
 /home/minseok/miniconda3/envs/rein/bin/python
 /home/minseok/miniconda3/bin/python
 /home/minseok/nengo/bin/python

I am not sure what you mean by that it happens for other modules as well?

**Comment by skeydan** [comment]
I meant, if you were asking for a different module, like `numpy` for example?

In case you are comfortable with obtaining a backtrace from a coredump, this would also be very helpful, as I can't reproduce...

**Comment by moorugi98** [comment]
Hello,
asking for different module returns ```TRUE```. 

I am not sure how backtracing works, I will try to look into this and get back to you.

Here is the output by trying to load python from OS.

use_python("/usr/bin/python3", required = TRUE)
ERROR: The requested version of Python ('/usr/bin/python3') cannot be
used, as another version of Python
('/home/minseok/miniconda3/envs/data/bin/python') has already been
initialized. Please restart the R session if you need to attach
reticulate to a different version of Python.
Error in use_python("/usr/bin/python3", required = TRUE) : 
  failed to initialize requested version of Python

**Comment by skeydan** [comment]
Thanks!

Referring to that last point, like the message says, you need to restart the R session before binding to another version of Python (this is always the case - restart R to use a different Python environment than the one that is in use).

However, based on the other info in the issue perhaps we should proceed in a different way, and start "afresh".

Firstly, can you make sure you have the very latest CRAN versions of `reticulate` as well as `tensorflow`:

```
install.packages("reticulate")
install.packages("tensorflow")
```

Then, in a fresh R session, let's install TensorFlow into a new Miniconda environment:

```
tensorflow::install_tensorflow(method = "conda", envname = "r-reticulate")
```

Now, can you share the output of 

```
reticulate::use_condaenv("r-reticulate")
reticulate::py_config()
tensorflow::tf_config()
```

Thanks!

**Comment by moorugi98** [comment]
Hello, sorry for the delayed response. Here is the output after each command line.

reticulate::use_condaenv("r-reticulate")
-> nothing


reticulate::py_config()
->
python:         /home/minseok/miniconda3/envs/r-reticulate/bin/python
libpython:      /home/minseok/miniconda3/envs/r-reticulate/lib/libpython3.6m.so
pythonhome:     /home/minseok/miniconda3/envs/r-reticulate:/home/minseok/miniconda3/envs/r-reticulate
version:        3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)  [GCC 7.3.0]
numpy:          /home/minseok/miniconda3/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.18.0

python versions found: 
 /home/minseok/miniconda3/envs/r-reticulate/bin/python
 /usr/bin/python3
 /usr/bin/python
 /home/minseok/miniconda3/envs/data/bin/python
 /home/minseok/miniconda3/envs/forecast/bin/python
 /home/minseok/miniconda3/envs/IDA2019/bin/python
 /home/minseok/miniconda3/envs/nest/bin/python
 /home/minseok/miniconda3/envs/py2/bin/python
 /home/minseok/miniconda3/envs/rein/bin/python
 /home/minseok/miniconda3/bin/python
 /home/minseok/nengo/bin/python


tensorflow::tf_config()
-> results in error
*** caught illegal operation ***
address 0x7f0200af6820, cause 'illegal operand'

Traceback:
 1: py_module_import(module, convert = convert)
 2: import("tensorflow", delay_load = list(priority = 5, environment = "r-reticulate",     on_load = function() {        register_suppress_warnings_handler(list(suppress = function() {            if (tf_v2()) {                tf_logger <- tf$get_logger()                logging <- reticulate::import("logging")                old_verbosity <- tf_logger$level                tf_logger$setLevel(logging$ERROR)                old_verbosity            } else {                old_verbosity <- tf$logging$get_verbosity()                tf$logging$set_verbosity(tf$logging$ERROR)                old_verbosity            }        }, restore = function(context) {            if (tf_v2()) {                tf_logger <- tf$get_logger()                tf_logger$setLevel(context)            } else {                tf$logging$set_verbosity(context)            }        }))        register_tf_help_handler()        tryCatch(tf$python$util$deprecation$silence()$`__enter__`(),             error = function(e) NULL)    }, on_error = function(e) {        stop(tf_config_error_message(), call. = FALSE)    }))
 3: fun(libname, pkgname)
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch(fun(libname, pkgname), error = identity)
 8: runHook(".onLoad", env, package.lib, package)
 9: loadNamespace(name)
10: getNamespace(ns)
11: asNamespace(ns)
12: getExportedValue(pkg, name)
13: tensorflow::tf_config

**Comment by skeydan** [comment]
That is really strange.
Can you try 

```
conda activate r-reticulate
python
import tensorflow as tf
```

to see if it works from Python?

**Comment by moorugi98** [comment]
Ok, so I am getting the error "Illegal instruction (core dumped)" in Python, so it's a Python problem and not R problem I reckon?

**Comment by skeydan** [comment]
Yes - either the Python built by Anaconda, or TensorFlow (but the latter seems unlikely, given that you're using the official TF 2 build).

As you're on Linux, you can use `virtualenv` instead of `conda` and see if that works:

```
python3 -m venv ~/.virtualenvs/mytestenv
. ~/.virtualenvs/mytestenv/bin/activate
pip install tensorflow
python
> import tensorflow as tf
```

**Comment by moorugi98** [comment]
Hello, I tried creating a ```virtualenv```, but I am still getting a same error. I will try to find an appropriate issue in TensorFlow repo.

**Comment by moorugi98** [comment]
Still getting the same error. I think my laptop is too old and it is not compatible with newer versions of TensorFlow (https://github.com/tensorflow/tensorflow/issues/19584). Thanks for the help.
