### ISSUE TITLE
Knitr engine gives absolute figure paths

### ISSUE THREAD

**Issue by lazappi** [rstudio/reticulate#669]
I have run into an issue with the latest version of `reticulate` (v1.14) where figures are not shown in the rendered HTML because they are inserted with an absolute rather than relative path. I think this might be a result of the call to `normalizePath()` in `eng_python_matplotlib_show()`. According to the docs it can sometimes return an absolute path and I didn't have this problem with `reticulate` v1.13.

I can only reproduce it in a `workflowr` project (example attached [reticulate_fig_path.zip](https://github.com/rstudio/reticulate/files/3978626/reticulate_fig_path.zip), render `index.Rmd` to see output). I think this is related to issue #645 and where the document is rendered. @jdblischak may be able to help out with explaining exactly where `workflowr` does things.

Thanks for your help! I've only started using `reticulate` recently and it's awesome!

**Comment by cderv** [comment]
Hi, 

Can you check with last reticulate dev version ? 
```r
remotes::install_github("rstudio/reticulate")
```

#671 should have fixed this one too.

**Comment by lazappi** [comment]
Yep, looks like it's working now (at least on my toy example)!

Thanks for putting together the fix! 😺

**Comment by leogama** [comment]
Hi! This should be closed 😉

**Comment by kevinushey** [comment]
Thank you for reporting back!
