### ISSUE TITLE
Can't Install Reticulate Package at my Rstudio

### ISSUE THREAD

**Issue by rayfabian-hub** [rstudio/reticulate#672]
Hello, Community.

I'm new in programming and want to try some R package that needs Reticulate to operate.

but instead, I got this Message:

trying URL 'https://cran.cmm.msu.ru/src/contrib/reticulate_1.14.tar.gz'
Content type 'application/x-tar' length 1504849 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

* installing *source* package ‘reticulate’ ...
** package ‘reticulate’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘reticulate’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/reticulate’
Warning in install.packages :
  installation of package ‘reticulate’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/n3/l51wjc856q7_tbt6x4dj3qnc0000gn/T/Rtmp8knBDp/downloaded_packages’

What should I do? can someone help me?

**Comment by kevinushey** [comment]
It looks like you don't have command line tools installed, and because binaries for `reticulate` haven't been built yet the attempt to build from sources fails.

What happens if you run:

```
xcode-select --install
```

from a terminal?

**Comment by rayfabian-hub** [comment]
The problem has been solved. Thank you @kevinushey !
