### ISSUE TITLE
Problem with different versions of python on ubuntu

### ISSUE THREAD

**Issue by mvlp** [rstudio/reticulate#675]
Hi, 
I am trying to use commercial solvers in RStudio (MOSEK and GUROBI). They can be installed on anaconda and used indirectly by the reticulate package. However my RStudio doesn't see my anaconda python directory. I've tried using the "use()" command and modifying the RETICULATE_PYTHON variable but without success. RStudio always accesses the standard ubuntu python (3.5), but he sees that there is another installation in the home directory (py_discover_config). How to leave anaconda installation as default python in RStudio?

`library(reticulate)

py_config()
py_discover_config()
py_config()

reticulate::py_module_available(module = "scipy.sparse")
reticulate::py_module_available(module = "numpy")
reticulate::py_module_available(module = "mosek")`

`py_config()
python:         /usr/bin/python3
libpython:      /usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/libpython3.5m.so
pythonhome:     //usr://usr
version:        3.5.2 (default, Oct  8 2019, 13:06:37)  [GCC 5.4.0 20160609]
numpy:          /usr/lib/python3/dist-packages/numpy
numpy_version:  1.11.0

python versions found: 
 /usr/bin/python3
 /usr/bin/python
 /home/mvlp/anaconda2/bin/python

> py_discover_config()
python:         /usr/bin/python3
libpython:      /usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/libpython3.5m.so
pythonhome:     //usr://usr
version:        3.5.2 (default, Oct  8 2019, 13:06:37)  [GCC 5.4.0 20160609]
numpy:          /usr/lib/python3/dist-packages/numpy
numpy_version:  1.11.0

python versions found: 
 /usr/bin/python3
 /usr/bin/python
 /home/mvlp/anaconda2/bin/python

> py_config()
python:         /usr/bin/python3
libpython:      /usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/libpython3.5m.so
pythonhome:     //usr://usr
version:        3.5.2 (default, Oct  8 2019, 13:06:37)  [GCC 5.4.0 20160609]
numpy:          /usr/lib/python3/dist-packages/numpy
numpy_version:  1.11.0

python versions found: 
 /usr/bin/python3
 /usr/bin/python
 /home/mvlp/anaconda2/bin/python

> reticulate::py_module_available(module = "scipy.sparse")
[1] TRUE
> reticulate::py_module_available(module = "numpy")
[1] TRUE
> reticulate::py_module_available(module = "mosek")
[1] FALSE
`
In addition, these packages checked above are installed on anaconda. My ubuntu version is 16.04.6, RStudio version 1.2.5033. 

>sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C               LC_TIME=pt_BR.UTF-8       
 [4] LC_COLLATE=pt_BR.UTF-8     LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=pt_BR.UTF-8   
 [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.14 CVXR_1.0       

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        lattice_0.20-38   gmp_0.5-13.5      rappdirs_0.3.1   
 [5] R.methodsS3_1.7.1 grid_3.6.2        R6_2.4.1          jsonlite_1.6     
 [9] pracma_2.2.9      Rmpfr_0.7-2       R.oo_1.23.0       R.utils_2.9.2    
[13] Matrix_1.2-18     tools_3.6.2       bit64_0.9-7       bit_1.1-14       
[17] compiler_3.6.2

**Comment by skeydan** [comment]
What exact command are you using to make `reticulate` use `conda`?

It seems  like you don't have any conda environments configured - otherwise, what you'd do would be

```
reticulate::use_condaenv("myenv", required = TRUE)
```

Also, before telling `reticulate` to use a different Python from what's in use, you need to restart the R session.

**Comment by mvlp** [comment]
Sorry, I hadn't configured the environment.

I use the followind commands to configure the enviroment:
`conda create --name r-env python=2.7`
`conda activate r-env`

Before that I run a test on Rstudio:
`reticulate::conda_list()`

>        name                                     python
> 1 anaconda2            /home/mvlp/anaconda2/bin/python
> 2     r-env /home/mvlp/anaconda2/envs/r-env/bin/python

The reticulate package detect correctly the enviroment.

I proceed loading the enviroment:
`Sys.setenv(RETICULATE_PYTHON="/home/mvlp/anaconda2/envs/r-env/bin/python")`
`library(reticulate)`
`reticulate::use_condaenv("r-env", required = TRUE)`

But when I've try to use it I get an fatal error:
py_config()

**Comment by skeydan** [comment]
What is the fatal error?

Also note that it is recommended to switch to Python 3 as soon as possible, see
https://blog.rstudio.com/2019/12/20/reticulate-1-14/

**Comment by mvlp** [comment]
The error code isn't informed, just opens a error window with a "bomb".
I've switch to python 3.7 and now everything works fine.
Thank you so much @skeydan !
Best Regards

**Comment by skeydan** [comment]
great to hear, you're welcome!
