### ISSUE TITLE
Offer a full portable mode for install_miniconda

### ISSUE THREAD

**Issue by cderv** [rstudio/reticulate#681]
While trying the last CRAN version 1.14 on my windows 10 work computer where I did not have admin right, `install_miniconda` prompte me with a box where I need to put an admin credential, which I don't have. I clicked "cancel" twice on the two prompts that opened, and that did the trick. Strange thing is I tried to reproduce but it did not prompt me again using the same command
```r
reticulate::install_miniconda(force = TRUE)
```

Anyway I wanted to share this because I believe the silent installation in `install_miniconda` does not apply a full portable installation and a portable installation mode could be insteresting. I did a little search. 

Here are the flags currently used: 
https://github.com/rstudio/reticulate/blob/43a27fd58310c277ac01e4f315958a1118c920b2/R/miniconda.R#L114-L123

Specifically, there is a `/AddToPath` flag that default to 1 (from the [silent mode doc](https://docs.anaconda.com/anaconda/install/silent-mode/)).  I think it tries to append to system PATH which is not possible. It could maybe write to user environment variable but it does not seem to be the case because I don't get anything in PATH regarding miniconda installation while `/AddToPath=1` by default. I think a portable installation mode could benefit from `/AddToPath=0`, leaving the user adding to PATH or not.

Also, currently, miniconda installation will write to registry. I think a full portable installation should not. There is a hidden flag about registry to no write to it; `/NoRegistry=1`. Look at the options through `.\Miniconda3-latest-Windows-x86_64.exe /?` an this thread https://github.com/conda/conda/issues/1977. Full portable mode could benefit from a `/NoRegistry=1` option for a clean portable installation.

Miniconda installer offers this full portable mode I think `install_miniconda` could use this, mainly for constraint environment, either by default or by a portable option 
```r
install_miniconda(..., portable = TRUE)
```

What do you think ?

**Comment by kevinushey** [comment]
This sounds reasonable to me, although I think we should just make it always portable (never update registry or path)

**Comment by cderv** [comment]
> we should just make it always portable (never update registry or path)

Oh I completely agree with that ! 
It would certainly be enough. Adding the two flags should be the only thing to do is this case I think.
