### ISSUE TITLE
Shiny app crashes in connection with reticulate 

### ISSUE THREAD

**Issue by reyar** [rstudio/reticulate#683]
Dear Rstudio team,

I have a problem. The cause might be reticulate, shiny or an interaction between both. 

Details of my system: 

```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_Germany.1252  LC_CTYPE=English_Germany.1252    LC_MONETARY=English_Germany.1252
[4] LC_NUMERIC=C                     LC_TIME=English_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readr_1.3.1       data.table_1.12.8 mailR_0.4.1       anytime_0.3.6     DT_0.11          
[6] reticulate_1.14   rmarkdown_2.0     shiny_1.4.0      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        pillar_1.4.3      compiler_3.6.2    later_1.0.0       R.methodsS3_1.7.1
 [6] R.utils_2.9.2     tools_3.6.2       zeallot_0.1.0     digest_0.6.23     jsonlite_1.6     
[11] evaluate_0.14     tibble_2.1.3      pkgconfig_2.0.3   rlang_0.4.2       rstudioapi_0.10  
[16] crosstalk_1.0.0   yaml_2.2.0        xfun_0.11         fastmap_1.0.1     rJava_0.9-11     
[21] stringr_1.4.0     knitr_1.26        rappdirs_0.3.1    htmlwidgets_1.5.1 vctrs_0.2.1      
[26] hms_0.5.2         R6_2.4.1          magrittr_1.5      backports_1.1.5   promises_1.1.0   
[31] htmltools_0.4.0   mime_0.8          xtable_1.8-4      httpuv_1.5.2      stringi_1.4.3    
[36] crayon_1.3.4      R.oo_1.23.0      
> 
```

```
> reticulate::py_config()
python:         C:/ProgramData/Anaconda3/python.exe
libpython:      C:/ProgramData/Anaconda3/python37.dll
pythonhome:     C:/ProgramData/Anaconda3
version:        3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/ProgramData/Anaconda3/Lib/site-packages/numpy
numpy_version:  1.15.1

python versions found: 
 C:/Users/---/AppData/Local/Programs/Python/Python37-32/python.exe
 C:/ProgramData/Anaconda3/python.exe
```
**The problem:**
I have a a shiny app calling a python file through py_run_file. When I launch the app the first time in a new R session within Rstudio, it works as expected. After stopping the app and launching it again the second time, it crashes (stops without delivered errors). The third time, it works. The fourth time, it crashes, etc. It does not depend on the content of the python file. Moreover, I can call py_run_file without any problems from the R console in RStudio. Morover, if I call the python file from the R console, after a successful launch of the app (and before a potential non-successful launch), then the problem dissapears (the next launch of the app will be also successful). 

If I start the app from the RGui, it crashes and delivers following error: 

```
Warning: Error in sys$stdout$flush: attempt to apply non-function
  49: py_flush_output
  48: py_run_string
  47: py_inject_r
  46: ensure_python_initialized
  45: py_run_file
  44: <observer> [C:\Users\---\Desktop\Test2/server.R#10]
   1: runApp
```

**reprex**
test.py
```
import numpy as np
a=np.array([1,2,3])

```

server.R
```
library(shiny)
library(reticulate)

shinyServer(function(input, output, session) {
    
  observe({
       py_run_file("test.py")
       output$a<- renderText({paste(py$a)})
     
   })
  
})
```

ui.R
```
library(shiny)

shinyUI(fluidPage(
  
  fluidRow( 
    
    column(12, 
           
      h3("Test"),
      h3(textOutput("a"))
           
           
    )
    
  )
  
))
```

**Further details**
The problem is new, it arrised after an update of the R libraries on the 2. January 2020. The previous update was on 3. December 2019. I have removed and installed the older versions of packages which were updated in this period (for example reticulate) - it did not help. I cannot find the cause of the problem.

Please help!

Thanks.

**Comment by skeydan** [comment]
Hi, can you try installing `reticulate` from github and see if the problem persists?

```
devtools::install_github("rstudio/reticulate")
```

**Comment by reyar** [comment]
Hi, 

thanks for the reply.

I installed reticulate from github. The result:

- Within RGui, the problem dissapears. The app can be launched and runs as expected, after each stop of the process. 

- Within RStudio, the problem still exists: The first launch is ok, the second crashes, the third is ok, the fourth crashes, etc.

**Comment by paulofelipe** [comment]
I'm facing something similar. 
The RStudio crashes when I execute the code below. However, it works on VS Code.

```r
library(reticulate)

transformers <- import('transformers')
tokenizer <- transformers$AlbertTokenizer$from_pretrained('albert-base-v2')
```

Thanks!

**Comment by skeydan** [comment]
@reyar I've found a system where I can reproduce! I'll keep you posted.

**Comment by skeydan** [comment]
Update: I think that the nature of the issue has changed (installation of dev reticulate fixed the stdout-related problem; but now it has become something else.)

From what I've seen by now, these are required components to produce the problem:

- using shiny 
- NOT restarting R between repeated `runApp`s. That probably amounts to saying that Python may not be re-initialized. (So it would also make sense that it works fine repeatedly executing from RGui, but not from RStudio, because RStudio won't reinitialize Python.) 

On the other hand, it doesn't have to be about executing a file, or `py_run_string`.
The same thing - failure on second `runApp()` will happen for anything Python, e.g.

```
a <- r_to_py("a")
```

@kevinushey would you have an idea what could be going on here? Unfortunately it's hard to debug as the error happens inside c++ code; and it only happens on Windows.)

**Comment by reyar** [comment]
﻿Thanks for the update! 

Maybe it is worth mentioning once more that the error is relatively new, appeared on my system the first time after a general R packages update on the 2. January. Unfortunately, I do not have an image of the R package versions which guaranteed a second error-free runApp(). Installing just reticulate 1.13 instead of 1.14 does not solve problem.


> Am 24.01.2020 um 16:28 schrieb Sigrid Keydana <notifications@github.com>:

﻿
Update: I think that the nature of the issue has changed (installation of dev reticulate fixed the stdout-related problem; but now it has become something else.)

From what I've seen by now, these are required components to produce the problem:

using shiny
NOT restarting R between repeated runApps. That probably amounts to saying that Python may not be re-initialized. (So it would also make sense that it works fine repeatedly executing from RGui, but not from RStudio, because RStudio won't reinitialize Python.)
On the other hand, it doesn't have to be about executing a file, or py_run_string.
The same thing - failure on second runApp() will happen for anything Python, e.g.

a <- r_to_py("a")
@kevinushey would you have an idea what could be going on here? Unfortunately it's hard to debug as the error happens inside c++ code; and it only happens on Windows.)

**Comment by kevinushey** [comment]
One thought: does it make a difference if you force `reticulate` to load and initialize Python outside of the `shinyServer()` function call? E.g.

```R
library(shiny)
library(reticulate)

# force init of Python
reticulate::use_python("/path/to/python", required = TRUE)

shinyServer(function(input, output, session) {
    
  observe({
       py_run_file("test.py")
       output$a<- renderText({paste(py$a)})
     
   })
  
})

```

**Comment by skeydan** [comment]
Strangely, it still crashes... I wonder if we'd need to do the opposite ("un-initialize" Python in every `shinyServer` call)?

**Comment by kevinushey** [comment]
Doh. I'll try to take a closer look when I get a chance.

**Comment by kevinushey** [comment]
I'm seeing an issue that I think is related.

If I run the following code in an R terminal:

```R
library(reticulate)
import("sys")
repeat { 1 + 1 }
```

The `repeat` loop will not be interruptible. I suspect Python may be registering some kind of interrupt handler that is conflicting with the regular handler used by R.

**Comment by skeydan** [comment]
I'm not sure I follow, but that may be because I feel like it's 3am :-)))
How does that map to the "repeated runApp() without session restart" case, where we seem to be seeing "one interrupt too much" in a way?
(Maybe it's really just too late ;-))

**Comment by skeydan** [comment]
@kevinushey just noting sth before heading to airport, may be totally irrelevant but...

```
sp <- import("subprocess")
# works fine on linux but on win see below
sp$check_output("ls", shell = TRUE)
# works fine on linux but on win see below
sp$check_output("sleep 10", shell = TRUE)
```

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  OSError: [WinError 6] The handle is invalid

Detailed traceback: 
  File "C:\Users\Administrator\AppData\Local\r-miniconda\envs\r-reticulate\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\Users\Administrator\AppData\Local\r-miniconda\envs\r-reticulate\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Administrator\AppData\Local\r-miniconda\envs\r-reticulate\lib\subprocess.py", line 687, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Users\Administrator\AppData\Local\r-miniconda\envs\r-reticulate\lib\subprocess.py", line 910, in _get_handles
    p2cread = _winapi.GetStdHandle(_winapi.STD_INPUT_HANDLE)
```
---> so perhaps there _is_ a connection to the sys.stdin/out thing??

**Comment by skeydan** [comment]
>> The repeat loop will not be interruptible. I suspect Python may be registering some kind of interrupt handler that is conflicting with the regular handler used by R.

@kevinushey I can't reproduce (on Windows Server)...?
