### ISSUE TITLE
[Discussion] Drop Python 2 Support

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/reticulate#688]
Now that [Python 2 is not being maintained ](https://www.python.org/dev/peps/pep-0373/) anymore since 2019 already ended. Should we consider dropping Python 2 support in reticulate? It will be much easier to maintain once we drop Python 2 support.

cc @jjallaire @kevinushey

**Comment by kevinushey** [comment]
I announced that we will no longer be supporting Python 2.7 in the recent [blog post](https://blog.rstudio.com/2019/12/20/reticulate-1-14/):

> As you may be aware, Python 2.7 is slowly being phased out in favor of Python 3. On January 1st, 2020, Python 2.7 will officially reach end-of-life. To that end, this will be the last reticulate release to officially support Python 2.7 – all future work will focus on supporting Python 3.x. We strongly encourage users of reticulate to update to Python 3 if they have not already.

**Comment by terrytangyuan** [comment]
Thanks for the link! I missed the last section. Sounds good then! Perhaps this issue could be used to track the progress I think.

**Comment by kevinushey** [comment]
FWIW, I don't want to explicitly tear out support for Python 2 just yet; rather, new feature work in `reticulate` shouldn't make large efforts to retain compatibility with Python 2 (unless that work is trivial).

**Comment by terrytangyuan** [comment]
Sounds good. I am closing this issue then.
