### ISSUE TITLE
Config/reticulate should show up in install log

### ISSUE THREAD

**Issue by nfultz** [rstudio/reticulate#692]
I tired adding a `Config/reticulate` section to my DESCRIPTION, and was surprised at the output in 00install.out on winbuilder nextrel - it seems like stderr makes it through, but nothing else?

`00install.out`:

```
* installing *source* package 'hopticulate' ...
** using staged installation
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
Warning: cannot find svn location for rst2pdf===0.93.dev-r0
You are using pip version 9.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
** testing if installed package keeps a record of temporary installation path
* MD5 sums
packaged installation of 'hopticulate' as hopticulate_0.1.0.zip
* DONE (hopticulate)
```

I think for the install log it would be nice to have a `*** reticulate dependencies` section.

**Comment by kevinushey** [comment]
The fact that this code is running during install on winbuilder makes me feel very nervous. Are you accidentally forcing reticulate to load Python when your package is loaded? Can you share your package sources?

I don't think `reticulate` should try to install Python packages during CRAN checks; and especially not if we're not using our own Miniconda environment (which shouldn't exist on CRAN).

**Comment by nfultz** [comment]
The package is here - https://github.com/njnmco/hopticulate

The warning appears only if I have the Config/reticulate block, so I assumed it was doing something during the installation.

**Comment by kevinushey** [comment]
I don't think your usages of `delayedAssign` do what you expect. R will force evaluation of such symbols during package install, and all of those will effectively be evaluated during load. This means your package forces `reticulate` to initialize Python and hence also try to initialize a Python environment, which is not desired here.

You should follow the examples here for delay-loading a Python module: https://rstudio.github.io/reticulate/articles/package.html

**Comment by nfultz** [comment]
I'm fine with delayedAssign evaluating to null in my package. I guess I did not understand that the Config/reticulate feature was implemented through import and not by installing or loading a package.

**Comment by kevinushey** [comment]
No, the use of `Config/reticulate` _does_ download and install Python packages for you. My point is that your package is forcing `reticulate` to be loaded eagerly (when your package is loaded) which you want to avoid.

**Comment by nfultz** [comment]
It works fine for me. 🤷
