### ISSUE TITLE
"memory not mapped" segfault for pandas.read_gbq() in 1.14

### ISSUE THREAD

**Issue by jmthibault79** [rstudio/reticulate#693]
When running equivalent Google BigQuery queries in a Jupyter notebook using pandas.read_gbq(), I observed success while using Python and "kernel died" while using R and Reticulate.

My jupyter.log contains this:
```*** caught segfault ***
address 0x8, cause 'memory not mapped'

Traceback:
1: py_convert_pandas_df(x)
```

I can reliably trigger this problem in Reticulate 1.14 and downgrading to 1.13 reliably resolves it.  Many other similar queries succeed, and I have been unable to determine anything special about the problem query.  Unfortunately the data and query are both sensitive, so I am unable to share them here.

Please let me know how I can provide additional information for debugging this issue.

**Comment by skeydan** [comment]
Could you please provide a minimal reproducible example? Like a data frame on which that would happen? Or some other way to reproduce this?

What Python version and what OS are you using?

Do the data frames on which this happens consistently contain a Date column?

Thanks!

**Comment by jmthibault79** [comment]
I will continue my attempts to find a shareable minimal reproducible example.

Yes, both the successful and failing queries involve dates.  Are there date manipulations I should watch out for?  One part of the query I can share is:
```
CAST(FLOOR(DATE_DIFF(CURRENT_DATE, DATE(p.year_of_birth, p.month_of_birth, p.day_of_birth), MONTH)/12) as INT64) 
BETWEEN @p0_1048 and @p1_1048
```

From my python notebook:
```
!jupyter --version
!python -V
!R --version
!lsb_release -a
```
```
jupyter core     : 4.6.1
jupyter-notebook : 5.7.8
qtconsole        : 4.6.0
ipython          : 7.10.1
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : 0.35.4
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3
Python 2.7.15+
R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

**Comment by jmthibault79** [comment]
Inspired by your Date question, I removed a DATETIME field from my SELECT - and it doesn't segfault!  This does not yet resolve my issue, but it sounds like we're on the right track.

Thank you for looking into this.

**Comment by jmthibault79** [comment]
The successful Python query results had a few `NaT` values in that field.  Restoring the field in the R query and adding `IS NOT NULL` caused it to no longer segfault.

**Comment by jmthibault79** [comment]
In Reticulate 1.13, these values appear as "1677-09-21 00:12:43" which looks like `pd.Timestamp.min`

**Comment by skeydan** [comment]
Thanks a lot for your investigations, that's already pretty informative! I'll try to dig into this next week and see what I can find.

**Comment by skeydan** [comment]
Can you try installing `reticulate` master from github and see if that fixes the error?

```
devtools::install_github("rstudio/reticulate")
```

**Comment by jmthibault79** [comment]
The problem is resolved on master.  Thank you for your quick response!

**Comment by skeydan** [comment]
happy to hear, thanks for testing!
