### ISSUE TITLE
Pytorch gives random results in reticulate

### ISSUE THREAD

**Issue by johanneswaage** [rstudio/reticulate#697]
I'm seeing an issue that has previously been reported (https://github.com/rstudio/reticulate/issues/407#issue-390796282). I'm on RHEL 7

My version of python has been built from source using:

``` bash
./configure --prefix=/opt/python/3.7.6 --with-ensurepip=install --enable-shared --enable-optimizations
make -j 32
sudo make install
```

I've created a virtual environment using 
`renv::use_python(python = "/opt/python/3.7.6/bin/python3.7")`

This creates a virtual environment in the project folder. 
I activate this environment and use pip to install the necessary dependencies.

Here's a print of `reticulate::py_config()`
``` r
python:         /data/analyse_og_indsigt/users/jwa/repos/screenduck/renv/python/virtualenvs/renv-python-3.7.6/bin/python
libpython:      /opt/python/3.7.6/lib/libpython3.7m.so
pythonhome:     /opt/python/3.7.6:/opt/python/3.7.6
version:        3.7.6 (default, Jan  6 2020, 11:37:34)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
numpy:          /data/analyse_og_indsigt/users/jwa/repos/screenduck/renv/python/virtualenvs/renv-python-3.7.6/lib/python3.7/site-packages/numpy
numpy_version:  1.18.1`

NOTE: Python version was forced by RETICULATE_PYTHON`
```
Everything seems to look fine.

If I run the python pytorch script from R using reticulate, or reticulate::repl, prediction results are random.

If I source the script from within the python virtual environment from the command line, results come out correct.

What could be the reason for this? Thanks a bunch.
(I can supply the pytorch python code if needed, but I don't think that's the issue here)

``` r
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Red Hat Enterprise Linux    
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Copenhagen           
 date     2020-01-12                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ! package     * version   date       lib source        
 P assertthat    0.2.1     2019-03-21 [?] RSPM (R 3.5.1)
 P cli           1.1.0     2019-03-19 [?] RSPM (R 3.5.1)
 P crayon        1.3.4     2017-09-16 [?] RSPM (R 3.5.1)
 P jsonlite      1.6       2018-12-07 [?] RSPM (R 3.5.1)
 P packrat       0.5.0     2018-11-14 [?] RSPM (R 3.5.1)
   png           0.1-7     2013-12-03 [1] RSPM (R 3.5.1)
 P rappdirs      0.3.1     2016-03-28 [?] RSPM (R 3.5.1)
 P Rcpp          1.0.2     2019-07-25 [?] RSPM (R 3.5.1)
   renv          0.7.0-125 2020-01-12 [1] local         
 P reticulate    1.14      2019-12-17 [?] RSPM (R 3.5.1)
 P rstudioapi    0.10      2019-03-19 [?] RSPM (R 3.5.1)
 P sessioninfo   1.1.1     2018-11-05 [?] RSPM (R 3.5.1)
 P withr         2.1.2     2018-03-15 [?] RSPM (R 3.5.1)

[1] /data/analyse_og_indsigt/users/jwa/repos/screenduck/renv/library/R-3.5/x86_64-pc-linux-gnu
[2] /tmp/Rtmp0FA4in/renv-system-library

 P ── Loaded and on-disk path mismatch.
```

**Comment by skeydan** [comment]
Thanks for reporting! For starters, just to rule out any influence of using `renv` here, does the same thing happen if you just create a virtualenv without using `renv`?

Also , in the `sessionInfo`, these `Loaded and on-disk path mismatch.` look a bit disconcerting ... do you know how this comes about?

In case these two things don't yield anything useful, I think it would make sense to provide a minimal example for us to reproduce.

**Comment by johanneswaage** [comment]
I disabled renv completely, which solved the `Loaded and on-disk path mismatch` errors:
```r
─ Session info ────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Red Hat Enterprise Linux    
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Copenhagen           
 date     2020-01-13                  

─ Packages ────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] RSPM (R 3.5.1)
 cli           1.1.0   2019-03-19 [1] RSPM (R 3.5.1)
 crayon        1.3.4   2017-09-16 [1] RSPM (R 3.5.1)
 jsonlite      1.6     2018-12-07 [1] RSPM (R 3.5.1)
 packrat       0.5.0   2018-11-14 [1] RSPM (R 3.5.1)
 png           0.1-7   2013-12-03 [1] RSPM (R 3.5.1)
 rappdirs      0.3.1   2016-03-28 [1] RSPM (R 3.5.1)
 Rcpp          1.0.1   2019-03-17 [1] RSPM (R 3.5.1)
 reticulate  * 1.14    2019-12-17 [1] RSPM (R 3.5.1)
 sessioninfo   1.1.1   2018-11-05 [1] RSPM (R 3.5.1)
 withr         2.1.2   2018-03-15 [1] RSPM (R 3.5.1)

[1] /home/jwa/R/x86_64-pc-linux-gnu-library/3.5
[2] /opt/R/3.5.1/lib64/R/library
```

I created a new virtual environment from the command-line. Activating this environment and calling the python script produced the correct results. 
Activating this newly created environment in R with 
```r
reticulate::use_virtualenv("virtual_env/")
reticulate::py_config()
python:         /data/analyse_og_indsigt/users/jwa/repos/screenduck/virtual_env/bin/python
libpython:      /opt/python/3.7.6/lib/libpython3.7m.so
pythonhome:     /opt/python/3.7.6:/opt/python/3.7.6
version:        3.7.6 (default, Jan  6 2020, 11:37:34)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
numpy:          /data/analyse_og_indsigt/users/jwa/repos/screenduck/virtual_env/lib/python3.7/site-packages/numpy
numpy_version:  1.18.1

python versions found: 
 /data/analyse_og_indsigt/users/jwa/repos/screenduck/virtual_env/bin/python
 /usr/bin/python
 /home/jwa/jwa_new_environment/bin/python

```
shows that reticulate correctly picks up the new environment.
However, running the pytorch code from reticulate produces random and wrong results, so no improvement.

The python code:
```python
from danlp.models.ner_taggers import load_ner_tagger_with_flair
from flair.data import Sentence
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

# Load the NER tagger using the DaNLP wrapper
flair_model = load_ner_tagger_with_flair()

sentence = Sentence("Jeg er på vej til New York for at besøge en gammel ven, Donald Trump")

flair_model.predict(sentence)
preds = sentence.to_dict(tag_type='ner')
print("[", preds, "]")
```
The code loads a Danish NLP model, and tries to do named-entity-recognition on the sentence, which translates to "I'm going to New York to visit an old friend, Donald Trump". The correct print of preds should be:
```python
[ {'text': 'Jeg er på vej til New York for at besøge en gammel ven, Donald Trump', 'labels': [], 'entities': [{'text': 'New York', 'start_pos': 18, 'end_pos': 26, 'type': 'LOC', 'confidence': 0.9505029022693634}, {'text': 'Donald Trump', 'start_pos': 56, 'end_pos': 68, 'type': 'PER', 'confidence': 0.9979774951934814}]} ]
```
e.g., a detection of a location and a person. Reticulates gives random predictions with random entities.

To run the python code, you would need to install:
```bash
pip install numpy
pip install flair==0.4.3
pip install danlp
pip install --upgrade scipy h5py pyyaml requests Pillow
```

Thanks again.

**Comment by kevinushey** [comment]
Can you confirm whether your system libraries are all up to date? (That was conjectured to be the root of the problem in https://github.com/rstudio/reticulate/issues/407#issue-390796282, at least.)

You might also try comparing the output of:

```
lsof -p <PID>
```

to see if different system libraries are being loaded in each case. (Perhaps R links to different versions of system libraries than a plain Python installation, and this leads to some sort of issues)

**Comment by johanneswaage** [comment]
I created a lsof output file using `lsof -p <PID>`, using the pid of processes running either a python REPL from reticulate or a bash shell, both using the same virtual environment.

I imported the output into R using the following code
```r
library(readr)
library(magrittr)
library(dplyr)

venv_lsof <- readr::read_delim("lsof_venv.txt", delim = " ", trim_ws = TRUE) %>% 
  select(COMMAND, NAME)

reticulate_lsof <- readr::read_delim("lsof_reticulate.txt", delim = " ", trim_ws = TRUE) %>% 
  select(COMMAND, NAME)

lsof_joined <- full_join(venv_lsof, reticulate_lsof, by = "NAME")
lsof_joined <- lsof_joined %>%  
  rename("venv" = COMMAND.x) %>% 
  rename("reticulate" = COMMAND.y)

reticulate_only <- lsof_joined %>%
  filter(is.na(venv) & !is.na(reticulate)) %>% 
  select(NAME)

venv_only <- lsof_joined %>%
  filter(!is.na(venv) & is.na(reticulate)) %>% 
  select(NAME)
```
Most of the library paths were shared between processes (~80%).
The following processes were unique to the shell-based venv:

|NAME                                                                                 |
|:------------------------------------------------------------------------------------|
|/opt/python/3.7.6/bin/python3.7                                                      |
|/opt/python/3.7.6/lib/python3.7/lib-dynload/readline.cpython-37m-x86_64-linux-gnu.so |

The following were unique to the reticulate-based venv: (most of it seems related to the wrapping R-process)

|NAME                                                                                                                                                         |
|:------------------------------------------------------------------------------------------------------------------------------------------------------------|
|/usr/lib/rstudio-server/bin/rsession                                                                                                                         |
|/data/analyse_og_indsigt/users/jwa/repos/screenduck/virtual_env/lib/python3.7/site-packages/matplotlib/backends/_tkagg.cpython-37m-x86_64-linux-gnu.so       |
|/usr/lib64/libexpat.so.1.6.0                                                                                                                                 |
|/usr/lib64/libXau.so.6.0.0                                                                                                                                   |
|/usr/lib64/libXrender.so.1.3.0                                                                                                                               |
|/usr/lib64/libfontconfig.so.1.11.1                                                                                                                           |
|/usr/lib64/libxcb.so.1.1.0                                                                                                                                   |
|/usr/lib64/libfreetype.so.6.14.0                                                                                                                             |
|/usr/lib64/libXft.so.2.3.2                                                                                                                                   |
|/usr/lib64/libX11.so.6.3.0                                                                                                                                   |
|/usr/lib64/libtcl8.5.so                                                                                                                                      |
|/usr/lib64/libtk8.5.so                                                                                                                                       |
|/opt/python/3.7.6/lib/python3.7/lib-dynload/_tkinter.cpython-37m-x86_64-linux-gnu.so                                                                         |
|/data/analyse_og_indsigt/users/jwa/repos/screenduck/virtual_env/lib/python3.7/site-packages/matplotlib/backends/_backend_agg.cpython-37m-x86_64-linux-gnu.so |
|/data/analyse_og_indsigt/users/jwa/repos/screenduck/virtual_env/lib/python3.7/site-packages/matplotlib/_image.cpython-37m-x86_64-linux-gnu.so                |
|/data/analyse_og_indsigt/users/jwa/repos/screenduck/virtual_env/lib/python3.7/site-packages/matplotlib/_path.cpython-37m-x86_64-linux-gnu.so                 |
|/data/analyse_og_indsigt/users/jwa/repos/screenduck/virtual_env/lib/python3.7/site-packages/kiwisolver.cpython-37m-x86_64-linux-gnu.so                       |
|/data/analyse_og_indsigt/users/jwa/repos/screenduck/virtual_env/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so               |
|/usr/lib64/libpng15.so.15.13.0                                                                                                                               |
|/home/jwa/R/x86_64-pc-linux-gnu-library/3.5/png/libs/png.so                                                                                                  |
|/opt/intel/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin/libmkl_vml_avx2.so                                                                   |
|/opt/intel/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin/libmkl_avx2.so                                                                       |
|/opt/intel/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so                                                                 |
|/opt/intel/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so                                                               |
|/opt/intel/compilers_and_libraries_2019.5.281/linux/compiler/lib/intel64_lin/libiomp5.so                                                                     |
|/opt/intel/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin/libmkl_core.so                                                                       |
|/home/jwa/R/x86_64-pc-linux-gnu-library/3.5/rappdirs/libs/rappdirs.so                                                                                        |
|/home/jwa/R/x86_64-pc-linux-gnu-library/3.5/reticulate/libs/reticulate.so                                                                                    |
|/home/jwa/R/x86_64-pc-linux-gnu-library/3.5/jsonlite/libs/jsonlite.so                                                                                        |
|/home/jwa/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/libs/Rcpp.so                                                                                                |
|/usr/lib64/libnss_sss.so.2                                                                                                                                   |
|/opt/R/3.5.1/lib64/R/library/tools/libs/tools.so                                                                                                             |
|/opt/R/3.5.1/lib64/R/lib/libRlapack.so                                                                                                                       |
|/opt/R/3.5.1/lib64/R/library/stats/libs/stats.so                                                                                                             |
|/opt/R/3.5.1/lib64/R/library/graphics/libs/graphics.so                                                                                                       |
|/opt/R/3.5.1/lib64/R/library/utils/libs/utils.so                                                                                                             |
|/opt/R/3.5.1/lib64/R/library/grDevices/libs/grDevices.so                                                                                                     |
|/usr/lib64/gconv/ISO8859-1.so                                                                                                                                |
|/opt/R/3.5.1/lib64/R/library/methods/libs/methods.so                                                                                                         |
|/usr/lib64/libnss_files-2.17.so                                                                                                                              |
|/usr/lib64/libcap-ng.so.0.0.0                                                                                                                                |
|/usr/lib64/libicudata.so.50.2                                                                                                                                |
|/usr/lib64/libaudit.so.1.0.0                                                                                                                                 |
|/usr/lib64/libgomp.so.1.0.0                                                                                                                                  |
|/usr/lib64/libicui18n.so.50.2                                                                                                                                |
|/usr/lib64/libicuuc.so.50.2                                                                                                                                  |
|/usr/lib64/libquadmath.so.0.0.0                                                                                                                              |
|/usr/lib64/libgfortran.so.3.0.0                                                                                                                              |
|/opt/R/3.5.1/lib64/R/lib/libRblas.so                                                                                                                         |
|/usr/lib64/libglib-2.0.so.0.5600.1                                                                                                                           |
|/usr/lib64/libgthread-2.0.so.0.5600.1                                                                                                                        |
|/usr/lib64/libgobject-2.0.so.0.5600.1                                                                                                                        |
|/usr/lib64/libpam.so.0.83.1                                                                                                                                  |
|/usr/lib64/libuuid.so.1.3.0                                                                                                                                  |
|/opt/R/3.5.1/lib64/R/lib/libR.so                                                                                                                             |
|/opt/R/3.5.1/lib64/R/library/translations/en/LC_MESSAGES/R.mo                                                                                                |

I have a hard time understanding how versions of system libraries could affect one but not the other, if the processes are linking up to the same underlying python libs.

I hope you can find reason is this, using pytorch from reticulate would be extremely helpful.

Regards,
JW

**Comment by johanneswaage** [comment]
If it's any help,

**Comment by skeydan** [comment]
Did you mean to close this?

I was just going to answer that

1) I tried your code/setup, and I get correct results from RStudio

2) Are you running RStudio Server started with an LD_LIBRARY_PATH including `/opt/intel/...`?
Can you instead try running R on the command line - but please also check whether LD_LIBRARY_PATH is set:

```
Sys.getenv("LD_LIBRARY_PATH")
```

**Comment by johanneswaage** [comment]
I can confirm that the code runs correctly through reticulate and the same venv as mentioned using RHEL built-in R from a terminal, but does not work with the compiled-from source R, that RStudio Server is using.

There's no references to `/opt/intel/..` in LD_LIBRARY_PATH for any of the R scenarios.

OK, so getting close to the source of problem, at least! 
We build R from source, basically using the instructions from here: https://support.rstudio.com/hc/en-us/articles/218004217-Building-R-from-source

```r
./configure --prefix=/opt/R/3.5.1 --enable-R-shlib --enable-memory-profiling --with-blas --with-lapack --with-x --with-cairo --with-libpng --with-libtiff --with-jpeglib
make
sudo make install
```

**Comment by kevinushey** [comment]
I wonder if the use of Intel MKL could be a factor here? (I don't immediately recall how to turn it on or off though)

**Comment by johanneswaage** [comment]
Breakthrough @kevinushey !
Removing intel BLAS libs and rebuilding R solved the problem. Thanks for the crazy detective work. IF anyone can, I would really like to know how a matrix algebra library linked to R can affect python at runtime through reticulate?

**Comment by skeydan** [comment]
https://github.com/intel/mkl-dnn/issues/431 ?

(pytorch 1.0 & specific processor & usage of convolutions though - not sure if that would match your setup - but certainly shows such interactions are possible)

**Comment by johanneswaage** [comment]
Indeed!
