### ISSUE TITLE
Feature request: integrate py$help() with R's help()

### ISSUE THREAD

**Issue by fritzo** [rstudio/reticulate#70]
Currently python help messages can be printed to the console via
```r
library(reticulate)
py <- import_builtins()
py$help(py$format)  # Help on `format`, for example.
```
However some python objects have very long documentation. It would be great if `py#help()` could be shown in the RStudio Help window.

Does this seem feasible? I'm happy to attempt a PR if anyone could provide hints.

Thanks for a great package!

**Comment by jjallaire** [comment]
One problem here is that the `?` and `help` methods in R are not S3 methods (so we can't customize their behavior). We could however add a `py_help` function to the reticulate package to at least make it less awkward to request help. What do you think of that idea?

**Comment by fritzo** [comment]
A `py_help` function sounds great!

I realize this FR may seem superficial, but I'm reading the docs of some of the tensorflow functions in your `tensorflow` wrapper and they dump pages of info to the console.
```r
library(reticulate)
library(tensorflow)
py <- import_builtins()
py$help(tf$contrib$distributions$Beta)
```

**Comment by jjallaire** [comment]
I just added py_help to reticulate.

I also noticed the problem with pages of info being dumped to the console.
Let me see if there is anything we can do about that.

**Comment by fritzo** [comment]
Thanks!

**Comment by jjallaire** [comment]
I just changed py_help to use the R file.show function (which will use a
pager like "more" in a terminal and a front-end specific viewer in an
environment like R GUI or RStudio)
