### ISSUE TITLE
pandas can't import 

### ISSUE THREAD

**Issue by Liripo** [rstudio/reticulate#701]
```python
>>> import pandas
AttributeError: type object 'pandas._libs.tslibs.conversion._TSObject' has no attribute '__reduce_cython__'
>>> import os
>>> import pathlib
>>> 
```
but I can import pandas in rstudio's terminal window
![image](https://user-images.githubusercontent.com/54770415/72676970-27976d80-3ad2-11ea-8c00-9b082572cb65.png)
Thanks!

**Comment by skeydan** [comment]
Does the error in the first case occur when executing from `reticulate::repl_python`?
If so, can you do, before that call (that is, from R):

```
reticulate::py_config()
```
