### ISSUE TITLE
XGBoost Not Importing in R Markdown

### ISSUE THREAD

**Issue by tmbluth** [rstudio/reticulate#705]
I've been trying several approaches to loading Python's `xgboost` into an R Markdown Python chunk and have not been able to find a solution.

When loading in `xgboost` I get the `ModuleNotFound` error

{python} chunk
`
import xgboost as xgb
`

I decided to look into where the `xgboost` module was installed and where `reticulate`'s Python was installed and found a mismatch. `reticulate` creates a new environment with Python 3.8.1 where `xgboost` did not get copied over. I tried installing `xgboost` in this environment but can't find examples of anyone doing so and wonder if 3.8.1 is even able to use `xgboost`. However, when trying to use the version of Python where `xgboost` is (3.7.6) I still had no luck. I even tried loading in Python's `xgboost` via R with `reticulate` but got the same error as above. This all can be seen in the image below:

![no_xgboost](https://user-images.githubusercontent.com/19579908/73386532-3af1c800-428c-11ea-9a32-b52f7679b488.PNG)

Now here's the kicker...when I knit the R markdown document it seems to run this just fine:

{r} chunk:
`
xgb <- reticulate::import('xgboost')
`

How can I get Python's version of `xgboost` to work interactively in R Markdown? Am I approaching this the wrong way or is there truly a bug? After searching the internet for this issue it looks like no one else is having a problem so I'm assuming this is a problem in approach.

**Comment by kevinushey** [comment]
Do things work if you force `reticulate` to load your separate environment beforehand; e.g. in a chunk at the start of your document:

`````
```{r}
reticulate::use_python("/path/to/python", required = TRUE)
```
`````

Note that you'll need to run this near the top of your script since Python can only be initialized once in an R session (and you cannot initialize a new, separate Python session without restarting)

**Comment by tmbluth** [comment]
Yep, that did it! Thank you
