### ISSUE TITLE
Feature request: pdb.pm() support

### ISSUE THREAD

**Issue by fritzo** [rstudio/reticulate#71]
I'd like to be able to use the python `pdb` module from R, but it appears that tracebacks are currently lost. This is important, since it can be difficult to reproduce the context of an error outside of R.

Desired behavior Python
```python
>>> import pdb
>>> abs(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bad operand type for abs(): 'NoneType'
>>> pdb.pm()  # Start post-mortem debugger.
<stdin>(1)<module>()
(Pdb) 
>>> locals()
{'__builtins__': <module '__builtin__' (built-in)>, '__name__': '__main__', 'pdb': <module 'pdb' from '/usr/lib/python2.7/pdb.py'>, '__doc__': None, '__package__': None}
>>> 
```
Current behavior in R
```r
> library(reticulate)
> py <- import_builtins()
> pdb <- import('pdb')
> py$abs(NULL)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: bad operand type for abs(): 'NoneType'
> pdb$pm()
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'module' object has no attribute 'last_traceback'

Detailed traceback: 
  File "/usr/lib/python2.7/pdb.py", line 1270, in pm
    post_mortem(sys.last_traceback)
> 
```
Thanks for a great package!

**Comment by jjallaire** [comment]
You are correct that you can't enter an interactive debugger from within R (we don't have a way to start up a mini python repl inside the R repl). However, the tracebacks shouldn't be lost. They should be printed to the terminal unless you are in a version of RStudio that knows how to collect Python tracebacks, in which case they should be available alongside the R traceback in the RStudio traceback view.

**Comment by fritzo** [comment]
Thanks, it indeed sound difficult to support nested repls.
