### ISSUE TITLE
use_condaenv() inconsistent between terminal & rstudio

### ISSUE THREAD

**Issue by drammock** [rstudio/reticulate#713]
On Linux (xubuntu 18.04, R 3.6.2, Rstudio 1.2.5033) if I open a terminal and run R, this all works:

```R
library(reticulate)
conda_version()
# [1] "conda 4.8.2"
use_condaenv("mnedev")
mne <- import("mne")
```

However, if I open Rstudio, 

```R
library(reticulate)
conda_version()
# Error: Unable to find conda binary. Is Anaconda installed?
```

I can still get an environment if I explicitly pass the path to conda, but something is still wrong:

```R
use_condaenv('mnedev', conda='/opt/miniconda3/condabin/conda')
mne <- import("mne")
conda_version()
# Error: Unable to find conda binary. Is Anaconda installed?
```

This seems to have downstream effects on my ability to do package development: `devtools::install_local()` and `devtools::test()` both work in terminal R session but not in Rstudio.

Note (possibly relevant?): I use miniconda to manage my python installations, but I do not manage R or R packages with it. I have only system-level R installations.

**Comment by kevinushey** [comment]
This probably implies that `conda` is on the PATH in your RStudio session but not your R session. You can see how `reticulate` finds Conda if you inspect the source code for `reticulate:::find_conda()`.

Note that in the development version of `reticulate` you can set `options(reticulate.conda_binary = <...>)` to force `reticulate` to use a particular Conda executable.

**Comment by drammock** [comment]
> This probably implies that `conda` is on the PATH in your RStudio session but not your R session.

Wouldn't it be the opposite? 

My `.bashrc` file adds the conda directory to my path. Is there an `.Rstudiorc` file, or similar way to affect PATH for the Rstudio console pane? I poked around in the menus but didn't find it...

**Comment by kevinushey** [comment]
I would check what `Sys.which("conda")` and `which conda` report, and also perhaps inspect the source for `reticulate:::find_conda` to see if you can figure out why it's not working as you expect (since solving this will ultimately require learning more about your environment)

**Comment by drammock** [comment]
terminal:

```
(mnedev) [~] $ which conda
/opt/miniconda3/condabin/conda
(mnedev) [~] $ R --quiet
R> Sys.which("conda")
                           conda 
"/opt/miniconda3/condabin/conda" 
```

Rstudio:

```R
R> Sys.which('conda')
conda 
   "" 
```

Looking at the source of `reticulate:::find_conda` it's obvious why it's not getting picked up: for some reason `find_conda` is checking `~/opt/miniconda[234]` but not checking `/opt/miniconda[234]`. Searching `~/opt` but not `/opt` strikes me as rather an odd choice for Linux systems, as `/opt` is a common target for multi-user installations (and for single users who don't want their home folder full of program files).

Note that, although the terminal reports `/opt/miniconda3/condabin/conda`, it is also located in the corresponding `bin` folder, and `diff /opt/miniconda3/condabin/conda /opt/miniconda3/bin/conda` shows no differences between the two executables. So adding `/opt/...` as well as `~/opt/...` paths to `reticulate:::find_conda` seems like the obvious fix to propose. Shall I make a PR?

**Comment by kevinushey** [comment]
Thanks for taking the time to dig in deeper and provide a diagnosis. I've made now made a fix on master.

**Comment by drammock** [comment]
I confirm that after cloning `reticulate` and running `devtools::install_local()` I can now run `reticulate::conda_version()` in the Rstudio console and it correctly finds my conda installation.  Thanks!

**Comment by kevinushey** [comment]
Thank you!
