### ISSUE TITLE
Strange error message. Reticulate can find conda but not python?

### ISSUE THREAD

**Issue by LaurenceDyer** [rstudio/reticulate#715]
Hi there,

Sorry to bother and hope you can help.

I've been using Seurat lately which depends on the python package umap-learn. Everything has been going fine, until today, where I seem to have broken the connection between python and R.

I've been trying to use reticulate to fix this, but reticulate's python_available returns False, and python_config (Or running runUMAP itself) returns the error:

```
Error in python_config(miniconda_python, NULL, miniconda_python) : 
  Error 2 occurred running /Users/install/Library/r-miniconda/envs/r-reticulate/bin/python 
In addition: Warning message:
In system2(command = python, args = paste0("\"", config_script,  :
  running command ''/Users/install/Library/r-miniconda/envs/r-reticulate/bin/python' "/Users/install/Library/R/3.6/library/reticulate/config/config.py" 2>/dev/null' had status 2
```

If I just try to run py_available(initialise = T), I get a similar message:

```
Warning message:
In system2(command = python, args = paste0("\"", config_script,  :
  running command ''/Users/install/Library/r-miniconda/envs/r-reticulate/bin/python' "/Users/install/Library/R/3.6/library/reticulate/config/config.py" 2>/dev/null' had status 2
```

Can you help give me any more information on what "Error 2" is trying to tell me here?

Any help is greatly appreciated, thanks.

**Comment by kevinushey** [comment]
Looks like you opened then closed this issue -- was that intentional? 

It seems like reticulate is having trouble running its configure script, but unfortunately isn't surfacing much information about what is going wrong.

**Comment by converseg** [comment]
Hello,

I know this has been closed for a while, but I am seeing a similar issue. How was this fixed? 

I am not using `reticulate` directly, but am making a package which uses `tensorflow`. Everything works fine on my machine, but `R CMD check` ran on https://win-builder.r-project.org/ gives the message

`Error 2 occurred when running C:/path/to/r-reticulate/python.exe`

This is the only error I get, but it comes up on any test which calls `tensorflow::`. I'm wondering if there is something I should be doing in the `.onLoad` function to set up `reticulate` correctly.

**Comment by kevinushey** [comment]
My advice would be: don't try to run your package's tests on CRAN, as there's no way to know or guarantee anything about the version of Python installed on their systems.

**Comment by caitsimop** [comment]
Hi there, 
I'm also having the same issue. Some examples of the error:

```
 >py_config()
Error in python_config(python_version, required_module, python_versions) : 
  Error 2 occurred running /path/to/miniconda3/bin/python3 Result too large
In addition: Warning message:
In system2(command = python, args = paste0("\"", config_script,  :
  running command ''/path/to/miniconda3/bin/python3' "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/reticulate/config/config.py" 2>/dev/null' had status 2
```

as well as: 

```
> py_available(initialize=T)
[1] FALSE
Warning message:
In system2(command = python, args = paste0("\"", config_script,  :
  running command ''/path/to/miniconda3/bin/python3' "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/reticulate/config/config.py" 2>/dev/null' had status 2
```
