### ISSUE TITLE
Avoid displaying all intermediate outputs in Rmd

### ISSUE THREAD

**Issue by kcarnold** [rstudio/reticulate#717]
The knitr engine displays all results, not just `stdout` or plots, for all lines. This is surprising because sometimes functions return values for convenience, and it's perfectly valid not to use that result if you don't need it. A real example is the sklearn `fit` function, which returns `self` just to permit easy initialization. Example (taken almost verbatim from some course materials I'm writing):

```{python}
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(analyzer="char")
docs = ["aaa", "ccc", "abc"]
cv.fit(docs)
cv.transform(docs).A
```

When knit, the chunk splits between `fit` and `transform`, interspersing a useless `CountVectorizer(...)` repr. When run as a single chunk, the two outputs appear in sequence.

I was expecting the behavior of Jupyter Notebook:

* Intermediate values are not displayed by default, but can be displayed by wrapping the result in `display` (or `print`).
* Final values are displayed by default but can be suppressed by adding a `;` at the end of the line.

Perhaps you don't want that exact behavior because R works somewhat differently, but at least it would be nice to have some way of suppressing intermediate outputs (e.g., the trailing `;`, which is the first thing I'd tried).

It looks like this might entail some changes here: https://github.com/rstudio/reticulate/blob/master/R/knitr-engine.R#L142

**Comment by kevinushey** [comment]
This was intentional -- we wanted behavior to conform with what happens for R chunks, and in R chunks intermediate output is printed as well.

One way to suppress output would be to assign the result to a variable; e.g.

```
_ = cv.fit(docs)
```

I'm open to having alternate mechanisms for suppressing intermediate output, though (including support for a trailing `;`).

**Comment by kcarnold** [comment]
Thanks, that's what I ended up doing. Unfortunately that silently breaks the use of `_` to refer to the last output (since it shadows the `_` in `builtins`. I don't see that used very often, so maybe that's a trade-off to live with... but using a trailing `;` doesn't conflict with anything and would be what people coming from Jupyter Notebook would expect.

**Comment by kevinushey** [comment]
That's true. I've seen `_` used more often in interactive use of Python when you just want to reference the last value you produced. Either way, let's take this issue as a request for `reticulate` to support the use of a trailing `;` to suppress output for a given line.
