### ISSUE TITLE
Support for Sparse Matrices

### ISSUE THREAD

**Issue by jjallaire** [rstudio/reticulate#72]
Currently the ```x``` object accepted by the Keras ```fit``` function is a 

> Vector, matrix, or array of training data... 

It would be great if there is also support for sparse matrices, as these X matrices can grow very large on disk, although they can be very sparse. For example, the Nietzsche example runs fine on my 32GB RAM laptop, but I run into RAM problems even with twice as many rows. And this is a classic case for a sparse matrix.

@gsimchoni I moved this issue from the Keras repo over here because this is where it would need to be addressed.

**Comment by jjallaire** [comment]
@bwlewis Do you know whether the Matrix package exposes a C API for sparse matrices?

**Comment by eddelbuettel** [comment]
I don't think it does.  The best short-term bet may be to get to the functions from Matrix via Rcpp.

A Google Summer of Code student is currently putting more sparse matrix support into RcppArmadillo.

**Comment by jjallaire** [comment]
What we would need to do is somehow get our hands on the underlying memory and then create a SciPy sparse matrix from it. That said, I don't think Keras currently accepts SciPy sparse matrices (discussion I've seen about the issue seems to center on converting each batch to dense array before feeding it into Keras). 

@gsimchoni Perhaps you could write your own training loop (via [train_on_batch](https://rstudio.github.io/keras/reference/train_on_batch.html) where you go from sparse to dense as required in each iteration?

**Comment by gsimchoni** [comment]
Thank you @jjallaire , this is exactly the advice I got from @dfalbel in the original [issue](https://github.com/rstudio/keras/issues/50).

**Comment by bwlewis** [comment]
@jjallaire I see this is closed, but FYI indeed Matrix does have a C API -- it uses the SuiteSparse package by Tim Davis. You need to  include at least  "Matrix.h"  and "Matrix_stubs.c". See https://github.com/bwlewis/irlba/blob/master/src/irlb.c for an example of a package linking to the Matrix package.

**Comment by eddelbuettel** [comment]
@bwlewis thanks for the SuiteSparse reminder.  That requires external linking, or as Matrix does, embedding of SuiteSparse.  May make for a good test case for RcppArmadillo too.

**Comment by bwlewis** [comment]
@eddelbuettel yeah, in the case of Matrix we have available a curated subset of SuiteSparse that we can simply directly link to. No need to embed again, just link to Matrix.

**Comment by eddelbuettel** [comment]
@bwlewis Yep, which is what lme4 has done all those years -- that was always "exhibit one" of how to access code from another package which provides a cleanly exported API.

**Comment by jjallaire** [comment]
Re-capping, it looks like Keras doesn't currently support Sparse matrices (they just suggest that you use `train_on_batch`. It also looks like Sparse matrix support is in SciPy rather than NumPy, meaning that even if we can get ahold of R's memory there isn't anywhere in NumPy to put it.
