### ISSUE TITLE
reticulate not finding miniconda when using rscript.exe

### ISSUE THREAD

**Issue by GreenGrassBlueOcean** [rstudio/reticulate#725]
I have installed Miniconda in rstudio using `reticulate::install_miniconda()`

When I am trying to use reticulate headless with rscript.exe using the following command:

`
"C:\Program Files\R\R-3.6.2\bin\x64\Rscript.exe" "G:\supertest.R"  
` 

I get the following error:

```
[1] "C:/Windows/System32/config/systemprofile/AppData/Local/r-miniconda"
Error in reticulate::use_miniconda() : Miniconda is not installed.
Use reticulate::install_miniconda() to install Miniconda.
Execution halted


```

When executed in windows it works perfectly returning for `reticulate::miniconda_path()` the following path: `C:/Users/WINUSERNAME/AppData/Local/r-miniconda` is returned.

How can I tell the script to look in the correct user directory instead of the global directory?

the supertest.R looks as follows:

```

.libPaths('') # Cleanup any additional paths the user might have for running as windows Service
.libPaths(c("C:/Users/WINUSERNAME/Documents/R/win-library/3.6", "C:/Program Files/R/R-3.6.2/library"))

paste(reticulate::miniconda_path())
reticulate::use_miniconda()
paste(reticulate::py_config())

```

**Comment by kevinushey** [comment]
The problem here is that Miniconda gets installed into a user-specific directory. I suspect your script is being run with elevated permissions, or by a separate account (e.g. running as administrator?) and so has a different notion of the user "home" directory.

You may want to set the `RETICULATE_MINICONDA_PATH` environment variable to force `reticulate` to look for Miniconda at a specific location.

**Comment by GreenGrassBlueOcean** [comment]
Thanks a lot for your response. 
After some more trying I copied the entire Miniconda directory from `"C:/Windows/System32/config/systemprofile/AppData/Local/r-miniconda"` to `C:/Users/WINUSERNAME/AppData/Local/r-miniconda` and it worked after that. But setting the environment variable is better
