### ISSUE TITLE
reticulate::py_run_file() error in conda 

### ISSUE THREAD

**Issue by chloelulu** [rstudio/reticulate#726]
Hi developer, 
Thanks for your time. Currently I am running python script with reticulate function on linux cluster. However, I always get this error, which never happens on my local computer. It would be highly appreciated if you can help. Thanks.
`> use_condaenv('songbird_env',required = TRUE)`
` > reticulate::py_run_file("run2.py")`
```
Error in py_run_file_impl(file, local, convert) : 
  ImportError: Traceback (most recent call last):
  File "/Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Conda/envs/songbird_env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
```

**Comment by kevinushey** [comment]
It's hard to say. The error seems to imply that Tensorflow in your Conda environment cannot be imported, but it's challenging to know why that would be the case.

**Comment by chloelulu** [comment]
Hi @kevinushey,
Would that be possible with the problem of any path setting? I am so confused. Thanks!

**Comment by skeydan** [comment]
One thing to check would be if TensorFlow runs correctly from Python (in that env).

Can you try running

```
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

```

**Comment by chloelulu** [comment]
Hi @kevinushey ,
Thanks for the help. 
Yes, I can not run the code you provided. It gives the error. 
`Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
 3211264/11490434 [=======>......................] - ETA: 1sTraceback (most recent call last):
  File "/Conda/envs/songbird_env/lib/python3.6/urllib/request.py", line 281, in urlretrieve
    tfp.write(block)
OSError: [Errno 122] Disk quota exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tf.py", line 4, in <module>
    (x_train, y_train),(x_test, y_test) = mnist.load_data()
  File "/Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/keras/datasets/mnist.py", line 49, in load_data
    file_hash='8a61469f7ea1b51cbae51d4f78837e45')
  File "/Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/keras/utils/data_utils.py", line 251, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "/Conda/envs/songbird_env/lib/python3.6/urllib/request.py", line 284, in urlretrieve
    reporthook(blocknum, bs, size)
OSError: [Errno 122] Disk quota exceeded`

**Comment by chloelulu** [comment]
Hi @kevinushey ,
After I clean up my $HOME dir, and the code you suggested can be successfully run. See below:

> Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11493376/11490434 [==============================] - 1s 0us/step
WARNING:tensorflow:From /research/bsi/projects/staff_analysis/m216453/Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2020-02-27 13:13:31.627006: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2020-02-27 13:13:31.637066: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200035000 Hz
2020-02-27 13:13:31.639297: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560ca82f7400 executing computations on platform Host. Devices:
2020-02-27 13:13:31.639315: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-39
OMP: Info #156: KMP_AFFINITY: 40 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 2 packages x 20 cores/pkg x 1 threads/core (40 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 1 
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 core 2 
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 0 core 3 
OMP: Info #171: KMP_AFFINITY: OS proc 8 maps to package 0 core 4 
OMP: Info #171: KMP_AFFINITY: OS proc 10 maps to package 0 core 8 
OMP: Info #171: KMP_AFFINITY: OS proc 12 maps to package 0 core 9 
OMP: Info #171: KMP_AFFINITY: OS proc 14 maps to package 0 core 10 
OMP: Info #171: KMP_AFFINITY: OS proc 16 maps to package 0 core 11 
OMP: Info #171: KMP_AFFINITY: OS proc 18 maps to package 0 core 12 
OMP: Info #171: KMP_AFFINITY: OS proc 20 maps to package 0 core 16 
OMP: Info #171: KMP_AFFINITY: OS proc 22 maps to package 0 core 17 
OMP: Info #171: KMP_AFFINITY: OS proc 24 maps to package 0 core 18 
OMP: Info #171: KMP_AFFINITY: OS proc 26 maps to package 0 core 19 
OMP: Info #171: KMP_AFFINITY: OS proc 28 maps to package 0 core 20 
OMP: Info #171: KMP_AFFINITY: OS proc 30 maps to package 0 core 24 
OMP: Info #171: KMP_AFFINITY: OS proc 32 maps to package 0 core 25 
OMP: Info #171: KMP_AFFINITY: OS proc 34 maps to package 0 core 26 
OMP: Info #171: KMP_AFFINITY: OS proc 36 maps to package 0 core 27 
OMP: Info #171: KMP_AFFINITY: OS proc 38 maps to package 0 core 28 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 1 core 0 
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 1 core 1 
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 1 core 2 
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 1 core 3 
OMP: Info #171: KMP_AFFINITY: OS proc 9 maps to package 1 core 4 
OMP: Info #171: KMP_AFFINITY: OS proc 11 maps to package 1 core 8 
OMP: Info #171: KMP_AFFINITY: OS proc 13 maps to package 1 core 9 
OMP: Info #171: KMP_AFFINITY: OS proc 15 maps to package 1 core 10 
OMP: Info #171: KMP_AFFINITY: OS proc 17 maps to package 1 core 11 
OMP: Info #171: KMP_AFFINITY: OS proc 19 maps to package 1 core 12 
OMP: Info #171: KMP_AFFINITY: OS proc 21 maps to package 1 core 16 
OMP: Info #171: KMP_AFFINITY: OS proc 23 maps to package 1 core 17 
OMP: Info #171: KMP_AFFINITY: OS proc 25 maps to package 1 core 18 
OMP: Info #171: KMP_AFFINITY: OS proc 27 maps to package 1 core 19 
OMP: Info #171: KMP_AFFINITY: OS proc 29 maps to package 1 core 20 
OMP: Info #171: KMP_AFFINITY: OS proc 31 maps to package 1 core 24 
OMP: Info #171: KMP_AFFINITY: OS proc 33 maps to package 1 core 25 
OMP: Info #171: KMP_AFFINITY: OS proc 35 maps to package 1 core 26 
OMP: Info #171: KMP_AFFINITY: OS proc 37 maps to package 1 core 27 
OMP: Info #171: KMP_AFFINITY: OS proc 39 maps to package 1 core 28 
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153662 thread 0 bound to OS proc set 0
2020-02-27 13:13:31.642259: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2020-02-27 13:13:31.668659: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Epoch 1/5
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153939 thread 1 bound to OS proc set 1
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153942 thread 2 bound to OS proc set 2
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153943 thread 3 bound to OS proc set 3
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153944 thread 4 bound to OS proc set 4
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153945 thread 5 bound to OS proc set 5
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153946 thread 6 bound to OS proc set 6
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153947 thread 7 bound to OS proc set 7
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153948 thread 8 bound to OS proc set 8
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153950 thread 9 bound to OS proc set 9
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153951 thread 10 bound to OS proc set 10
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153952 thread 11 bound to OS proc set 11
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153953 thread 12 bound to OS proc set 12
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153954 thread 13 bound to OS proc set 13
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153956 thread 15 bound to OS proc set 15
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153955 thread 14 bound to OS proc set 14
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153957 thread 16 bound to OS proc set 16
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153958 thread 17 bound to OS proc set 17
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153960 thread 19 bound to OS proc set 19
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153959 thread 18 bound to OS proc set 18
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153961 thread 20 bound to OS proc set 20
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153962 thread 21 bound to OS proc set 21
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153963 thread 22 bound to OS proc set 22
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153964 thread 23 bound to OS proc set 23
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153965 thread 24 bound to OS proc set 24
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153967 thread 26 bound to OS proc set 26
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153966 thread 25 bound to OS proc set 25
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153968 thread 27 bound to OS proc set 27
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153969 thread 28 bound to OS proc set 28
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153970 thread 29 bound to OS proc set 29
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153971 thread 30 bound to OS proc set 30
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153972 thread 31 bound to OS proc set 31
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153973 thread 32 bound to OS proc set 32
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153974 thread 33 bound to OS proc set 33
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153975 thread 34 bound to OS proc set 34
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153976 thread 35 bound to OS proc set 35
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153977 thread 36 bound to OS proc set 36
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153978 thread 37 bound to OS proc set 37
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153979 thread 38 bound to OS proc set 38
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153980 thread 39 bound to OS proc set 39
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153981 thread 40 bound to OS proc set 0
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153938 thread 41 bound to OS proc set 1
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153982 thread 42 bound to OS proc set 2
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153984 thread 43 bound to OS proc set 3
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153985 thread 44 bound to OS proc set 4
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153986 thread 45 bound to OS proc set 5
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153987 thread 46 bound to OS proc set 6
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153988 thread 47 bound to OS proc set 7
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153989 thread 48 bound to OS proc set 8
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153990 thread 49 bound to OS proc set 9
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153991 thread 50 bound to OS proc set 10
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153993 thread 51 bound to OS proc set 11
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153996 thread 52 bound to OS proc set 12
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153997 thread 53 bound to OS proc set 13
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 153998 thread 54 bound to OS proc set 14
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154000 thread 55 bound to OS proc set 15
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154001 thread 56 bound to OS proc set 16
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154002 thread 57 bound to OS proc set 17
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154004 thread 59 bound to OS proc set 19
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154003 thread 58 bound to OS proc set 18
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154005 thread 60 bound to OS proc set 20
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154006 thread 61 bound to OS proc set 21
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154007 thread 62 bound to OS proc set 22
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154008 thread 63 bound to OS proc set 23
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154009 thread 64 bound to OS proc set 24
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154010 thread 65 bound to OS proc set 25
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154011 thread 66 bound to OS proc set 26
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154012 thread 67 bound to OS proc set 27
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154013 thread 68 bound to OS proc set 28
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154014 thread 69 bound to OS proc set 29
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154015 thread 70 bound to OS proc set 30
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154016 thread 71 bound to OS proc set 31
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154017 thread 72 bound to OS proc set 32
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154018 thread 73 bound to OS proc set 33
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154019 thread 74 bound to OS proc set 34
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154020 thread 75 bound to OS proc set 35
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154021 thread 76 bound to OS proc set 36
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154022 thread 77 bound to OS proc set 37
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154023 thread 78 bound to OS proc set 38
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154025 thread 80 bound to OS proc set 0
OMP: Info #250: KMP_AFFINITY: pid 153662 tid 154024 thread 79 bound to OS proc set 39
60000/60000 [==============================] - 4s 73us/sample - loss: 0.2942 - acc: 0.9150
Epoch 2/5
60000/60000 [==============================] - 4s 67us/sample - loss: 0.1404 - acc: 0.9580
Epoch 3/5
60000/60000 [==============================] - 4s 65us/sample - loss: 0.1049 - acc: 0.9678
Epoch 4/5
60000/60000 [==============================] - 4s 66us/sample - loss: 0.0863 - acc: 0.9731
Epoch 5/5
60000/60000 [==============================] - 4s 66us/sample - loss: 0.0740 - acc: 0.9762
10000/10000 [==============================] - 0s 39us/sample - loss: 0.0752 - acc: 0.9783

But when run the R code again. Error outputs is 

> Error in py_run_file_impl(file, local, convert) : 
  ImportError: Traceback (most recent call last):
  File "/research/bsi/projects/staff_analysis/m216453/Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/research/bsi/projects/staff_analysis/m216453/Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/research/bsi/projects/staff_analysis/m216453/Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/research/bsi/projects/staff_analysis/m216453/Conda/envs/songbird_env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/research/bsi/projects/staf
Calls: <Anonymous> -> py_run_file_impl
Execution halted

>_<Thanks!

**Comment by skeydan** [comment]
Can you do, on the command line 

```
echo $LD_LIBRARY_PATH

ldd /Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/libtensorflow_framework.so.2
```

and also, in the environment you use for running R (RStudio Server / R?)

```
Sys.getenv("LD_LIBRARY_PATH")
```

Thanks!

**Comment by chloelulu** [comment]
Hi @skeydan ,
`$ echo $LD_LIBRARY_PATH
/usr/local/lib64:/usr/local/lib`

```
ldd /Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/libtensorflow_framework.so.2
ldd: /Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/libtensorflow_framework.so.2: No such file or directory
```

`> Sys.getenv("LD_LIBRARY_PATH")
[1] "/usr/local/biotools/r/R-3.5.2/lib64/R/lib:/usr/local/biotools/r/R-3.5.2/lib:/usr/lib/gcc/x86_64-redhat-linux/4.4.4:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el6_10.x86_64/jre/lib/amd64/server:/mforge/local/biotools/r/R-3.5.2/lib64:/mforge/local/biotools/r/R-3.5.2/lib64/R/lib:/usr/local/lib64:/usr/local/lib"`

**Comment by skeydan** [comment]
Could you try to find the location of `libtensorflow_framework.so.2` on your system (or maybe it's `libtensorflow_framework.so` or something similar) and try to execute the failing command again?

Also, could you test if the R code works if you prepend  `/usr/local/lib64:/usr/local/lib` to the LD_LIBRARY_PATH ? Assuming you start R on the command line, something like 

```
export LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib:$LD_LIBRARY_PATH

# to check
echo $LD_LIBRARY_PATH

# start R
R
```

**Comment by chloelulu** [comment]
Hi @skeydan ,
Thanks!
I have searched, while both files do not exist. 
`find: `libtensorflow_framework.so': No such file or directory`
`find: `libtensorflow_framework.so.2': No such file or directory`
And for the R part, it is ok. 

> echo $LD_LIBRARY_PATH
/usr/local/lib64:/usr/local/lib:/mforge/local/biotools/r/R-3.5.2/lib64:/mforge/local/biotools/r/R-3.5.2/lib64/R/lib:/usr/local/lib64:/usr/local/lib

**Comment by skeydan** [comment]
Regarding the latter, did you try activating the conda env and running your Python file (the way you indicated above) after that modification of LD_LIBRARY_PATH?

**Comment by chloelulu** [comment]
> Regarding the latter, did you try activating the conda env and running your Python file (the way you indicated above) after that modification of LD_LIBRARY_PATH?

@skeydan ,yes, I did that. The same error as before. 

> Error in py_run_file_impl(file, local, convert) : 
  ImportError: Traceback (most recent call last):
  File "/Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Conda/envs/songbird_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Conda/envs/songbird_env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/research/bsi/projects/staf
Calls: <Anonymous> -> py_run_file_impl
Execution halted
