### ISSUE TITLE
Importing submodules?

### ISSUE THREAD

**Issue by dfrankow** [rstudio/reticulate#73]
Suppose I have a package pack with a submodule mod that has a function func. To call func in python:

```
from pack import mod
mod.func()
```

How do I import mod in reticulate, and run func?

**Comment by dfrankow** [comment]
Looks like this works:

```
pack <- import("pack")
pack$mod$func()
```

**Comment by paulrougieux** [comment]
You can also use:

    py_run_string("from pack import mod")
    mod$func()

Which is also working when mod is not defined in `pack/__init__.py`.

**Comment by t-kalinowski** [comment]
You can typically also directly import the submodule, if it is indeed a valid submodule:`reticulate::import("pack.mod")$func()`
(note, the rules changed between python 2 and 3 for what's a valid submodule)
