### ISSUE TITLE
Can't load venvs that aren't in ~/.virtualenvs

### ISSUE THREAD

**Issue by stulacy** [rstudio/reticulate#74]
I've placed my virtual environments in a different folder (\~/virtualenvs as I dont' want them hidden) to the default (~/.virtualenvs), but I'm having problems getting them to load in reticulate.

Running `use_virtualenv("~/virtualenvs/foo", required=T")` works fine, but it evidently hasn't loaded as when I try to use packages that are only installed in this venv they can't load.

Running `py_config()` only displays the virtual environments that I have still in the default folder, but after running the `use_virtualenv()` call `py_discover_config()` correctly indicates that it's found the virtual env.

My `WORKON_HOME` is correctly set to ~/virtualenvs but it doesn't appear that this is being picked up by `reticulate`. From the code, it seems that this is hardcoded in R/config.R on line 110, rather than picking up WORKON_HOME.

**Comment by jjallaire** [comment]
I just added support for `WORKON_HOME` (didn't know about that, thanks for the tip!)

In terms of why it's not binding to the environment specified in `use_virtualenv`, the behavior of the package is that upon the first call to `import` we scan all versions of Python we can find for the package being imported. The version you specified in `use_virtualenv("~/virtualenvs/foo", required=T")` is being scanned *first*, however for whatever reason it's not finding the package.
