### ISSUE TITLE
pandas datetime64[ns] columns with NA-values crash R

### ISSUE THREAD

**Issue by taekeharkema** [rstudio/reticulate#741]
Hi,

Creating a pandas DataFrame with a `datetime64` column that contains NA-values, results in a crash of R ("R Session Error: The previous R session was abnormally terminated due to an unexpected crash"):

```{r}
library(reticulate)
pd <- import("pandas")
pd$DataFrame(dict(a = c(1577836800000000000, 1577836900000000000, NA)), dtype = "datetime64[ns]")
```

The same works for any other `dtype`, or for a data without NA-values.

I'm using
```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.6 (Maipo)
```

with
```
> packageVersion("reticulate")
[1] ‘1.14’
```
and pandas version
```
> py_get_attr(pd, "__version__")
1.0.2
```

**Comment by kevinushey** [comment]
This appears to be fixed in the development version of `reticulate`.

**Comment by taekeharkema** [comment]
It does indeed :). I hadn't checked that. Thanks very much!
