### ISSUE TITLE
use_miniconda() to change path

### ISSUE THREAD

**Issue by thestockman27** [rstudio/reticulate#745]
Hi there, thanks for taking a look.

I have recently been given an Amazon Work Spaces account in order to run machine learning experiments for my employer. My models have gotten a lot beefier lately and the processing time has become a nuisance.

I originally had both my R and python installations set up under my personal drive and have had to copy them over to a shared drive that can be accessed by the AWS account. This however, has caused errors in my path variables. More specifically, when trying to use the keras library I receive error messages referencing a need to install miniconda via reticulate. 

I confirmed an error in the path when running:
`> reticulate::miniconda_path()
[1] "D:/Users/Me/AppData/Local/r-miniconda"`

This references my personal D drive, rather than the shared one that I am now working from.

So my question is, how do I update my path and environment to references the items (r-miniconda) that I have copied over from my personal drive?

EDIT: I have attempted to follow the directions at this [link](https://rstudio.github.io/reticulate/articles/versions.html) but have had no luck.

**Comment by kevinushey** [comment]
You can tell reticulate to use a different path for its own Miniconda installation by setting the `RETICULATE_MINICONDA_PATH` environment variable. For example:

```
Sys.setenv(RETICULATE_MINICONDA_PATH = "/path/to/r-miniconda")
```

**Comment by thestockman27** [comment]
Hi Kevin, I really appreciate your help. It looks like your first suggestion solved my original issue. However, it now appears that my attempts to solve this on my own have mucked up my environment. I am now receiving the following error:

`model <- keras_model_sequential()
Error: Python module tensorflow.python.keras was not found.

Detected Python configuration:

python:         K:/company/me/r-miniconda/python.exe
libpython:      K:/company/me/r-miniconda/python37.dll
pythonhome:     K:/company/me/r-miniconda
version:        3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]
tensorflow:     [NOT FOUND]

NOTE: Python version was forced by RETICULATE_PYTHON`

**Comment by kevinushey** [comment]
> NOTE: Python version was forced by RETICULATE_PYTHON`

Are you sure you want to set `RETICULATE_PYTHON` to point directly at the root `python.exe` executable? Normally you want to use a Python environment. Do things work if you unset `RETICULATE_PYTHON` but leave `RETICULATE_MINICONDA_PATH` set?

**Comment by thestockman27** [comment]
That could certainly be the issue, but I don't think I am doing this properly...

`>Sys.unsetenv(RETICULATE_PYTHON)`

`Error in Sys.unsetenv(RETICULATE_PYTHON) : 
  object 'RETICULATE_PYTHON' not found`

I also tried sys.unsetenv(python) but received the same error.

**Comment by kevinushey** [comment]
The variable name needs to be provided as a string.

```
Sys.unsetenv("RETICULATE_PYTHON")
```

**Comment by thestockman27** [comment]
Bingo.

Had to restart my R session and run 

`Sys.setenv(RETICULATE_MINICONDA_PATH = "K:/company/me/r-miniconda")`

once more, but it seems like everything is running smoothly. Thanks for your help and patience!


Cheers.
