### ISSUE TITLE
Missing /

### ISSUE THREAD

**Issue by paulsendavidjay** [rstudio/reticulate#75]
/ missing between "/usr/local/Cellar/gcc/6.3.0_1" and "bin"

`devtools::install_github("rstudio/reticulate")

Using GitHub PAT from envvar GITHUB_PAT
Downloading GitHub repo rstudio/reticulate@master
from URL https://api.github.com/repos/rstudio/reticulate/zipball/master
Installing reticulate
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  '/private/var/folders/vq/2fchgnps1hxd5j_1jlkvvvnwmh074h/T/RtmpIYx0Ik/devtools73a2a512344/rstudio-reticulate-fcca860'  \
  --library='/Users/dpaulsen/Library/R/3.3/library' --install-tests 

* installing *source* package ‘reticulate’ ...
** libs
/usr/local/Cellar/gcc/6.3.0_1/bin/g++-6 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/dpaulsen/Library/R/3.3/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c RcppExports.cpp -o RcppExports.o
/usr/local/Cellar/gcc/6.3.0_1/bin/g++-6 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/dpaulsen/Library/R/3.3/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c event_loop.cpp -o event_loop.o
/usr/local/Cellar/gcc/6.3.0_1/bin/g++-6 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/dpaulsen/Library/R/3.3/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c libpython.cpp -o libpython.o
/usr/local/Cellar/gcc/6.3.0_1/bin/g++-6 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/dpaulsen/Library/R/3.3/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c python.cpp -o python.o
/usr/local/Cellar/gcc/6.3.0_1bin/g++-6 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o reticulate.so RcppExports.o event_loop.o libpython.o python.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
/bin/sh: /usr/local/Cellar/gcc/6.3.0_1bin/g++-6: No such file or directory
make: *** [reticulate.so] Error 127
ERROR: compilation failed for package ‘reticulate’
* removing ‘/Users/dpaulsen/Library/R/3.3/library/reticulate’
Error: Command failed (1)
`

**Comment by jjallaire** [comment]
Interesting, we don't actually form the path to the compiler (R does).

What happens if you `install_github("RcppCore/Rcpp")`

**Comment by paulsendavidjay** [comment]
Clean install.

**Comment by jjallaire** [comment]
Hmm...no idea why your compiler path is getting munged here.

**Comment by paulsendavidjay** [comment]
maybe a homebrew thing?

**Comment by paulsendavidjay** [comment]
hacky but 
ln -s 6.3.0_1/bin 6.3.0_1bin
is a workaround

**Comment by stvrd** [comment]
Having the same problem.

What do you mean by:

"ln -s 6.3.0_1/bin 6.3.0_1bin    is a workaround"?

**Comment by paulsendavidjay** [comment]
@stvrd  create a symbolic link where the installer is looking for the file
