### ISSUE TITLE
Allow for forge and channels arguments in conda_create

### ISSUE THREAD

**Issue by jtilly** [rstudio/reticulate#751]
Is there a reason that `conda_create` (unlike `conda_install`) does not have the `forge` and `channels` arguments? These arguments are useful to create conda environments that include packages that live in other channels, e.g. conda-forge.

Adding these arguments should be easy. I'd be happy to make a PR.

**Comment by kevinushey** [comment]
No reason -- likely just an oversight. A PR would be appreciated.
