### ISSUE TITLE
Error in r_to_py_impl(x, convert = convert) : Unable to convert R object to Python type

### ISSUE THREAD

**Issue by argeus47** [rstudio/reticulate#756]
I have the following code. Very simple.

```{r matrix}
library(reticulate)
library(Matrix)
N <- 6
set.seed(123)
sparse_mat <- sparseMatrix(
  i = sample(N, N, replace = F),
  j = sample(N, N, replace = F),
  x = runif(N),
  dims = c(N, N)
)
sparse_mat
sparse_mat_py <- r_to_py(sparse_mat)
```
 
```{python}
r.sparse_mat_py
```

![image](https://user-images.githubusercontent.com/64162976/80024079-e50c7500-84b4-11ea-8da7-daf18e3f125e.png)

In theory it should work. But I have the problem that I get the error and I don't know what to do.
Even as I'm learning I don't know how to fix it.
Any suggestion?
Thank you.

**Comment by skeydan** [comment]
Hi,

I'm sorry, I cannot reproduce. The above code runs fine for me:

```
> sparse_mat_py <- r_to_py(sparse_mat)
> sparse_mat_py
  (4, 0)	0.9545036491472274
  (1, 1)	0.04205953353084624
  (0, 2)	0.8895393160637468
  (5, 3)	0.24608773435465991
  (2, 4)	0.8998249704018235
  (3, 5)	0.3279207192827016
```

Which version of `reticulate` are you using?

Can you try installing `reticulate` from github:

```
devtools::install_github("rstudio/reticulate")
```

?

**Comment by argeus47** [comment]
I had to use the following code **Sys.setenv (RETICULATE_PYTHON = "/ usr / bin / python")**

Where the **/usr/ bin/python** is where the installed python is.

that was from the Rstudio console

End up solving it by pure luck the truth. because I unconfigured it with that command and put it back with the correct directory. I guess you were calling python from wrong place.

First locate python from linux console with "which python"

Hope this helps other people with the same error.

**Comment by maximopeoficiales** [comment]
Si como esta en lo correcto eso soluciona el problema, para los que esten en windows seria
"C:\Users\{User}\anaconda3"
en User  varia por el nombre de usuario que tenga en windows.

**Comment by DiegoParba** [comment]
Yes, it is very useful. I've had a lot of problems due to the line "library (reticulated)", but this sentence code works fine for Windows is Sys.setenv (RETICULATE_PYTHON = "C: / Users / LENOVO / anaconda3") in my case

**Comment by HectorCordovaRaga** [comment]
> Yes, it is very useful. I've had a lot of problems due to the line "library (reticulated)", but this sentence code works fine for Windows is Sys.setenv (RETICULATE_PYTHON = "C: / Users / LENOVO / anaconda3") in my case

Hi bro, Im begginer in "R" currently I have exactly this problem and Im not clear in what I need to do.
Could you explain me more about your answer

**Comment by HectorCordovaRaga** [comment]
> Si como esta en lo correcto eso soluciona el problema, para los que esten en windows seria
> "Sys.setenv (RETICULATE_PYTHON = "C:\Users{User}\anaconda3")
> en User varia por el nombre de usuario que tengas en windows.

Disculpa amigo, agradezco tu respuesta, pero no me queda claro lo que tengo que hacer ya que tengo exactamente este problema podrias explicarme un poco mas lo que se debe de hacer o cambiar en esa ruta porfavor
