### ISSUE TITLE
Error loading python packages for reticulate when deploying to shinyapps.io

### ISSUE THREAD

**Issue by jkayode** [rstudio/reticulate#757]
Error in value[[3L]](cond) : invalid version specification ‘20.1b1’
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

I get the above error when deploying my application to shinyapps.io This usually occurs when the python packages for use by reticulate() are being loaded. It looks like reticulate keeps pulling in the pre-released version of pip.

The code used for installing the python libraries:
reticulate::virtualenv_create(envname = "python_env", python = 'python3')
reticulate::virtualenv_install(envname = "python_env", packages = c('PyPDF2', 'treepoem'))
reticulate::use_virtualenv("python_env", required = TRUE)

And the application includes a .Rprofile which contains:
Sys.setenv(RETICULATE_PYTHON = '/home/shiny/.virtualenvs/python_env/bin/python')

I have attached my application log and below is my config:
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
[1] LC_CTYPE=C.UTF-8 LC_NUMERIC=C LC_TIME=C.UTF-8 LC_COLLATE=C.UTF-8 LC_MONETARY=C.UTF-8
[6] LC_MESSAGES=C.UTF-8 LC_PAPER=C.UTF-8 LC_NAME=C LC_ADDRESS=C LC_TELEPHONE=C
[11] LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats graphics grDevices utils datasets methods base

other attached packages:
[1] shiny_1.4.0.2

loaded via a namespace (and not attached):
[1] Rcpp_1.0.4 knitr_1.28 magrittr_1.5 xtable_1.8-4 lattice_0.20-41 R6_2.4.1
[7] rlang_0.4.5 fastmap_1.0.1 httr_1.4.1 tools_3.6.3 shinydashboard_0.7.1 DT_0.13
[13] grid_3.6.3 xfun_0.12 htmltools_0.4.0 askpass_1.1 shinyjs_1.1 openssl_1.4.1
[19] digest_0.6.25 Matrix_1.2-18 later_1.0.0 htmlwidgets_1.5.1 base64enc_0.1-3 promises_1.1.0
[25] rsconnect_0.8.16 curl_4.3 evaluate_0.14 mime_0.9 rmarkdown_2.1 compiler_3.6.3
[31] reticulate_1.15 jsonlite_1.6.1 httpuv_1.5.2

> reticulate::py_discover_config()
python: /home/johnkay/.virtualenvs/r-reticulate/bin/python
libpython: /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so
pythonhome: //usr://usr
version: 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
numpy: [NOT FOUND]

python versions found:

/home/johnkay/.virtualenvs/r-reticulate/bin/python
/usr/bin/python3
/usr/bin/python
/home/johnkay/.virtualenvs/python_env/bin/python
/home/johnkay/treepoem/bin/python

Please I need help to resolve this issue.

[ahrems-logs.txt](https://github.com/rstudio/reticulate/files/4523795/ahrems-logs.txt)

**Comment by kevinushey** [comment]
Thanks for the bug report. This does indeed look like an issue in the way `reticulate` parses `pip`'s version string. I've made in the development version of `reticulate`, but you might want to follow up with the shinyapps.io support team to see if there's a way to work around this.

**Comment by jkayode** [comment]
Is there a way I can use the development version for now?

**Comment by kevinushey** [comment]
You can install the development version of `reticulate` with:

```
install.packages("remotes")
remotes::install_github("rstudio/reticulate")
```

After doing this, I believe the new version of `reticulate` will be used during publish to shinyapps.io -- please feel free to follow up if this does not appear to be the case.

**Comment by jkayode** [comment]
Thanks. The issue has been resolved.

**Comment by kevinushey** [comment]
Great! I am glad to hear it -- thanks for following up.
