### ISSUE TITLE
Use R environment (Python namespace) to isolate python code chunks

### ISSUE THREAD

**Issue by vnijs** [rstudio/reticulate#759]
I'm using knitr and reticulate to render R and python code chunks in a (shiny) website. Works great!

For knitr I set an environment to evaluate R code chunks in. When I do this with python code, chunks the `r.` environment works as expected and is environment specific (see use of `r.x1` in `chunk2` below). However, once you assign something to a variable in any python code chunk, that variable is available in all subsequent python code chunks. 

Sharing (python) environments/namespaces is useful but is there also a way to separate them if needed? Specifically, in the example below it would be great if `chunk2` printed `object 'x1' not found` twice

An extension of the below would be that both `env1` and `env2` have the same parent environment (e.g., `env0`) but python objects created in `env1` or `env2` should "contaminate" the other environments. 

Code example:

    library(reticulate)
    env1 <- new.env()
    env1$x1 <- "x1"
    env2 <- new.env()
    
    chunk1 <- "
    ```{python echo = FALSE}
    x1 = r.x1
    print(x1)
    ```
    "
    
    chunk2 <- "
    ```{python echo = FALSE}
    print(r.x1)
    print(x1)
    ```
    "
    
    output <- knitr::knit(text = chunk1, quiet = TRUE, envir = env1)
    cat(output)
    output <- knitr::knit(text = chunk2, quiet = TRUE, envir = env2)
    cat(output)

Key output:

    > output <- knitr::knit(text = chunk1, quiet = TRUE, envir = env1)
    > cat(output)
    ```
    ## x1
    ```
    > output <- knitr::knit(text = chunk2, quiet = TRUE, envir = env2)
    > cat(output)
    ```
    ## Error in py_call_impl(callable, dots$args, dots$keywords): RuntimeError: Evaluation error: object 'x1' not found.
    ```
    ```
    ## x1
    ```

Possibly related issues:
https://github.com/rstudio/reticulate/issues/538
https://github.com/rstudio/reticulate/issues/523
https://github.com/rstudio/reticulate/issues/341

**Comment by kevinushey** [comment]
By default, all Python chunks get evaluated within the Python main module:

https://github.com/rstudio/reticulate/blob/5533e683ac8f3cecf2525b44be3ec017d3d26630/R/knitr-engine.R#L149-L153

https://github.com/rstudio/reticulate/blob/5533e683ac8f3cecf2525b44be3ec017d3d26630/R/utils.R#L100-L133

We might be able either give this the name of a Python module to use, or some proxy like "local" to indicate "evaluate this in a module independent of `main`".

**Comment by vnijs** [comment]
So that would be like a `py` environment specific to an R environment? Or just separate `py` environments? Thanks

**Comment by vnijs** [comment]
@kevinushey Just checking if there are any planned updates on this issue or if it is further down your priority list at this time ...

**Comment by kevinushey** [comment]
Sorry, I haven't yet had time to look at this. Pull requests would be appreciated :-)

**Comment by vnijs** [comment]
A (somewhat) related question: Is there a way to list and remove python objects from the main module from R? From your code I learned that `py_eval("globals()", convert = FALSE)` can be used to list something like the below.

```
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, 'sys': <module 'sys' (built-in)>, 'R': <class '__main__.R'>, 'r': <__main__.R object at 0x7faa04f34580>, 'x': 3, 'y': 7, 'z': 10}
```

I had hoped that `py_del_item(globals["r"], "x")` might work but that doesn't seem to be the case.

BTW I assume that making changes to the python main modules wouldn't affect other users using the same shiny app on a server right?

**Comment by kevinushey** [comment]
My understanding is that Python "global variables" are really just attributes on the main module, so you can do something like:

```
main <- import_main(convert = FALSE)
py_list_attributes(main)
py_set_attr(main, "x", 1L)
py_del_attr(main, "x")
```

**Comment by vnijs** [comment]
Thanks @kevinushey. Closing
