### ISSUE TITLE
RangeIndex._start deprecated

### ISSUE THREAD

**Issue by tseppelt** [rstudio/reticulate#762]
When passing a pandas data frame from Python to R I get the following warnings:
```
sys:1: FutureWarning: RangeIndex._start is deprecated and will be removed in a future version. Use RangeIndex.start instead
sys:1: FutureWarning: RangeIndex._stop is deprecated and will be removed in a future version. Use RangeIndex.stop instead
sys:1: FutureWarning: RangeIndex._step is deprecated and will be removed in a future version. Use RangeIndex.step instead
```
I'm wondering whether this is because of ll. 316-318 in [R/conversion.R](https://github.com/rstudio/reticulate/blob/master/R/conversion.R).

**Comment by galen211** [comment]
I'm also getting this error in my R `reticulate` environment while using `pd.read_feather()` in python.

**Comment by galen211** [comment]
Seems like the answer is in this issue: [https://github.com/rstudio/reticulate/issues/2](https://github.com/rstudio/reticulate/issues/2)
