### ISSUE TITLE
Invalid Version Error PIP 20.2b1

### ISSUE THREAD

**Issue by afrazelle3** [rstudio/reticulate#769]
Hi, I'm running into a similar issue as #204 but now it appears to be due to the pip update to version 20.2b1 (guessing the "b" is the issue?). I use shinyapps.io and I guess they installed the new beta version of pip on their servers.

Snip of error message is below. Can this be fixed similarly to handle letters instead of + symbols?

Many thanks!

Requirement already up-to-date: pip in /home/shiny/.virtualenvs/khc_two/lib/python3.5/site-packages (20.2b1)
Warning: Error in : invalid version specification ‘20.2b1’

**Comment by afrazelle3** [comment]
Sorry, didn't see #757 . Issue resolved by installing dev version of reticulate and re-deploying app to shinyapps.io

**Comment by kevinushey** [comment]
I've submitted a new version of `reticulate` to CRAN; hopefully it'll be there soon!

**Comment by afrazelle3** [comment]
Thanks! Until then, just really glad the github version takes care of it. Great package by the way, really useful.
