### ISSUE TITLE
Evaluation error: C stack usage  7972596 is too close 

### ISSUE THREAD

**Issue by aaamini** [rstudio/reticulate#772]
I am on R version 4.0.0. Trying to source a python script works for the first time in an R session. But when I source it a second time using `reticulate::source_python` I get the following error message:
<pre>
Error in py_ref_to_r(x) : 
  Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: Evaluation error: C stack usage  7972596 is too close 
</pre>

**Comment by kevinushey** [comment]
Sorry, but without a reproducible example, we cannot help.
