### ISSUE TITLE
Fresh install on Windows 10 giving "Error: Installing Python packages into a virtualenv is not supported on Windows"

### ISSUE THREAD

**Issue by JohnPaulHiggins** [rstudio/reticulate#777]
I initially started by trying to follow this tutorial:
https://docs.rstudio.com/tutorials/user/using-python-with-rstudio-and-reticulate/

However, any attempt to run py_config() resulted in the session fatally crashing.

I abandoned that notion in favor of just trying to get reticulate working outside of any virtual environment. I was still having trouble with py_config() crashing R, so I uninstalled all instances of Python on my system, as well as R and RStudio. I reinstalled Python by way of Miniconda, reinstalled R 3.6.3, and installed RStudio 1.3.

Upon reinstalling reticulate, py_config() now executes successfully:

```
> reticulate::py_config()
python:         C:/Users/jhiggins/Miniconda3/python.exe
libpython:      C:/Users/jhiggins/Miniconda3/python37.dll
pythonhome:     C:/Users/jhiggins/Miniconda3
version:        3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]
```

However, an attempt to call py_install() fails with the aforementioned error:

```
> reticulate::py_install('boto3')
Error: Installing Python packages into a virtualenv is not supported on Windows
```

I see in install.R that this error is triggered by a pair of conditions:

```
# validate method
  if (identical(method, "virtualenv") && is_windows()) {
    stop("Installing Python packages into a virtualenv is not supported on Windows",
         call. = FALSE)
```

However, attempting to pass 'conda' directly in the method parameter results in the same error:

```
> reticulate::py_install('boto3', method = 'conda')
Error: Installing Python packages into a virtualenv is not supported on Windows
```

Also, just to check, I decided to see what py_install_method_detect() might be returning when it auto-resolves method:

```
> reticulate:::py_install_method_detect()
[1] "conda"
```

Needless to say, I'm entirely stymied in light of all that.

Any guidance on next steps or possible troubleshooting measures would be appreciated. Thank you.

**Comment by kevinushey** [comment]
It looks like you've instructed `reticulate` to use your Miniconda installation, but without creating a Conda environment (or virtual environment) that `reticulate` can specifically bind to. I'd suggest creating an environment with e.g. (in a clean session)

```
reticulate::conda_create("my-environment")
reticulate::use_condaenv("my-environment", required = TRUE)
```

**Comment by JohnPaulHiggins** [comment]
That seems to have resolved the issue! Thank you for your help!

**Comment by kevinushey** [comment]
Great! I'm glad to hear it. :-)

**Comment by suzhanhao** [comment]
This post is particularly helpful for win10 users!
