### ISSUE TITLE
Miniconda preference

### ISSUE THREAD

**Issue by dfalbel** [rstudio/reticulate#786]
In an environment in which `conda` is installed and `conda` is in the path,  If I do:

```
install_miniconda()
conda_create("r-reticulate", packages = "python")
```

This will create the environment in the system conda installation. 
Could we prefer our `miniconda` installation in this case? 

I mean checking for `miniconda_exists` here before the conda the system installation?

https://github.com/rstudio/reticulate/blob/bf98324e575d0bd80f6d055cc60dd52240c005ea/R/conda.R#L347-L358

**Comment by kevinushey** [comment]
This sounds reasonable to me.

**Comment by dfalbel** [comment]
I'll send a PR for this
