### ISSUE TITLE
Document the difference in handing character data in Python 2 vs 3.

### ISSUE THREAD

**Issue by bhaskarvk** [rstudio/reticulate#79]
Python 2 wrongly assumes all character data is `latin-1` encoded, so when you call Python methods returning character data from reticulate w/ Py 2.x, you get a R character vector.
But in Python 3 finally the py devs figured it out that not the whole world speaks English and uses `latin-1` char. set ;).
So if you call a Python method returning character data from reticulate w/ Py 3.x you may get a wrapped object for the `bytes` class, which you need to explicitly decode using the proper char. encoding. The onus is on the calling function to know what the encoding is and not have Python erroneously assume the encoding. This is especially true when the python function is calling external APIs, database calls etc. 

This needs to be documented for reticulate users who may be using the package under Py 2.x / 3.x, so that they understand the difference http://python-notes.curiousefficiency.org/en/latest/python3/text_file_processing.html.

**Comment by jjallaire** [comment]
My impression was that most Python 3 APIs try to return Unicode strings. I guess what you are talking about here though are APIs that pass through character data from other systems. We could automatically convert to R character vector in this case -- do you think that would be too aggressive?

**Comment by bhaskarvk** [comment]
Yes exactly! I've already seen than in my docker package, where the data returned is the result of executing the docker SDK wrapping the the docker API.
Auto conversion could be an option, but to be cautious I would advice against it. When you decode for the user using UTF-8 as default 3 things can happen
- Incoming data is indeed encoded in ASCII/UTF-8 in which case everything works (This I suspect is 95% of the times)
- Incoming data is in a encoding that's not UTF-8 and
    - `decode('UTF-8')` throws an error. Which you can catch and then probably just return the bytearray and issue an warning. 
    - `decode('UTF-8'` call succeeds, because even if the encoding is not utf-8 it uses the same code phrases, in which case your call succeeds but you have garbage data.

The last point is what worries me, because you have silent data corruption w/o anyone noticing.

**Comment by jjallaire** [comment]
Now that I've looked back over the source code I realize that there is a good reason for not converting the bytes: these are in many cases used to return raw buffers that aren't strings at all so we can't do any automatic conversion.

I'd be happy to take a PR that adds the appropriate content to the docs to make this more clear and navigable.

**Comment by daroczig** [comment]
FTR what worked for me in such case (eg `boto3` KMS methods returning string literals in Py 2.x but bytes literals in Py 3.x) is transforming the object (let it be string or bytes literals) into `bytearray` and then calling `rawToChar` in R, see eg https://github.com/daroczig/botor/blob/master/R/utils.R#L123

I hope someone might found this useful.
