### ISSUE TITLE
Virtualenvs are hard-coded to be created with the --system-site-packages flag

### ISSUE THREAD

**Issue by mcbex** [rstudio/reticulate#796]
I have an issue with a shinyapps.io application that is no longer able to pip install packages using reticulate. The error I am seeing in the logs is ```ImportError: No module named 'setuptools.build_meta'``` 

I believe it is a result of this open issue with pip: https://github.com/pypa/pip/issues/6264 (Some additional helpful information is provided here by the setuptools maintainers: https://github.com/pypa/setuptools/issues/1694#issuecomment-466010982) 

The application is running on an older version of Ubuntu (Xenial) which ships with older versions of system python packages such as setuptools: https://packages.ubuntu.com/xenial/python-setuptools

Because the reticulate virtualenv is always created with the --system-site-packages flag, the user cannot opt out of including system packages even when running in virtualized environments such as shinyapps.io where they do not have control over the system. 

https://github.com/rstudio/reticulate/blob/a8701771fe759161c76a8e4a81d4ccc506269de1/R/virtualenv.R#L79

It seems as though this flag should not be set since it breaks the isolation from the system packages or it should at least be an optional argument.

**Comment by jjallaire** [comment]
I think that was in there to make sure we got pip & friends? Or perhaps to
make sure we got numpy? That's my speculation, other than that I don't
recall.

**Comment by mcbex** [comment]
@kevinushey yep I suspect that should work!
