### ISSUE TITLE
printing dictionary with integer keys crashes R

### ISSUE THREAD

**Issue by jjallaire** [rstudio/reticulate#8]
Observed on Windows w/ Python 3.5:

```r
py_run_string("x = {0:1, 1:4}")$x 
```

On Mac w/ Python 2.7 an error indicating dictionaries with integer keys aren't supported is thrown.

**Comment by bechhof** [comment]
Is there a convenient way to pass weights to `sklearn` when using reticulate (since the weights require integer keys)? Best I can do is to use `py_run_string` to get, say, a `DecisionTreeClassifier` object with custom weights.

**Comment by jjallaire** [comment]
Both issues fixed here: https://github.com/rstudio/reticulate/commit/21f6ba0c2ff26c3700811b09cb4f52cea5f2bc95
