### ISSUE TITLE
py_to_r() function seems doesn't work. 

### ISSUE THREAD

**Issue by wzrzt** [rstudio/reticulate#80]
I used pandas to create a pandas DataFrame, and then use py_to_r(), 
and then it returned it self as it it. 
![image](https://user-images.githubusercontent.com/12440644/28223576-8a1e5bce-68fe-11e7-8e27-060eefc98334.png)
In fact, RJBC doesn't work well with hive in my company, but python impala works fine. 
But I can just use R not python. So I nead a little python code in my script to help me do the query jobs, and return the query result as dataframe in R for my next work. 
I hope to get help here. Thank you!

**Comment by jjallaire** [comment]
That's correct, there isn't currently support for converting Pandas data frames to/from R data frames. A workaround is to just extract the columns you need as numpy arrays which will in turn be converted to R vectors.

**Comment by wzrzt** [comment]
@jjallaire Thank you for you reply. I imported numpy without the parameter "convert = TRUE", but when I converted one column of  the pandas DataFrame to numpy.array, it is already array in R, and then c() convert it to vector. Still, I didn't find how py_to_r() works. Yet using your workaround method, I wrote a function that convert a pandas DataFrame to vectors column by column, and then make a data.frame. Now it works fine. Thank you again!  
`pandasDF_to_df <- function(pandasDF) {  
     result_data_colnames <- py_numpy$array(pandasDF$columns)  
     result_data.1 <- list()   
    for(i in 1:length(result_data_colnames)) {   
        eval(parse(text=paste0('result_data.1$', result_data_colnames[i], ' = c(py_numpy$array(result_data$', result_data_colnames[i], '))' ))) 
    }   
    result_data.1 <- data.frame(result_data.1, stringsAsFactors = F)   
    return(result_data.1)   
}
`
