### ISSUE TITLE
Can't import newest version of matplotlib due to 'warn' error

### ISSUE THREAD

**Issue by BenjaminSSimpson** [rstudio/reticulate#808]
When importing matplotlib in a new python chunk I repeatedly got an error "Error in py_call_impl(callable, dots$args, dots$keywords) : TypeError: use() got an unexpected keyword argument 'warn'"

This was solved on stack exchange by uninstalling the latest matplotlib and going back to version 3.2. It works fine now but took a while to solve, may be confusing to new people using this great tool as matplotlib is so common.

Hope this helps. Thanks for the great package!

See full details here: 
https://stackoverflow.com/questions/63036394/failure-to-import-python-packages-using-r-markdown

**Comment by kevinushey** [comment]
Thanks for the bug report! This should be resolved in the development version of `reticulate`.

**Comment by alexpghayes** [comment]
I ran into this same bug and use dev `reticulate` solved it for me. Thank you.
