### ISSUE TITLE
Is it possible to turn on convert mode after import?

### ISSUE THREAD

**Issue by nsheff** [rstudio/reticulate#810]
I have a Python object that extends a Dict, but also provides some additional functions, which return basic items like strings.

Right now if you use `reticulate::import(..., convert=TRUE)`, when I create this object, I end up with an R list, which lacks the 'extra functions' that were attached to the python object. This is because reticulate detects that object as a `Dict` and automatically converts it.

So, I use `convert=FALSE`, and then I can access the extra function with `object$function(...)` -- however, I'd like the return of these functions to be automatically converted.

So, what I want auto-conversion to be *off* for the initial object creation, so I get the full python object, but then I want to *turn on* the automatic conversion so that from that object, the function results are all converted.

Is this possible? Here is some code that demonstrates what I mean. If I use `convert=TRUE`, then I lack the `seek` function on my `RefGenConf` object:

```
> mod = reticulate::import("refgenconf", convert=TRUE)
> rgc1 = mod$RefGenConf(Sys.getenv("REFGENIE"))
> class(rgc1)
[1] "list"
> rgc1$seek("t7", "fasta")
Error: attempt to apply non-function
```

But if I use `convert=FALSE`, the function return Python objects instead of R objects by default:

```
> mod = reticulate::import("refgenconf", convert=FALSE)
> rgc2 = mod$RefGenConf(Sys.getenv("REFGENIE"))
> class(rgc2)
 [1] "refgenconf.refgenconf.RefGenConf"  "yacman.yacman.YacAttMap"          
 [3] "attmap.pathex_attmap.PathExAttMap" "attmap.ordattmap.OrdAttMap"       
 [5] "collections.OrderedDict"           "python.builtin.dict"              
 [7] "attmap.attmap.AttMap"              "attmap._att_map_like.AttMapLike"  
 [9] "_abcoll.MutableMapping"            "_abcoll.Mapping"                  
[11] "_abcoll.Sized"                     "_abcoll.Iterable"                 
[13] "_abcoll.Container"                 "python.builtin.object"            
> rgc2$seek("t7", "fasta")
/home/nsheff/code/refgenie_sandbox/t7/fasta/default/t7.fa
> class(rgc2$seek("t7", "fasta"))
[1] "python.builtin.str"        "python.builtin.basestring"
[3] "python.builtin.object"    
> reticulate::py_to_r(rgc2$seek("t7", "fasta"))
[1] "/home/nsheff/code/refgenie_sandbox/t7/fasta/default/t7.fa"
```

I know I can just wrap everything in `py_to_r`, but what I'd like is the happy medium: a function like `rgc$set_convert(TRUE)` so that later functions will now automatically wrap results.

**Comment by kevinushey** [comment]
This is controlled via a field called `convert` on the environment, so something like this should suffice:

```
> sys <- reticulate::import("sys", convert = TRUE)
> sys$argv
[1] "/usr/bin/python3"
> 
> assign("convert", FALSE, envir = sys)
> sys$argv
['/usr/bin/python3']
```

We could expose a helper function for toggling this field, but this should suffice in the meantime.

**Comment by nsheff** [comment]
This doesn't seem to work for my use case. Is it possible that it is not affecting objects that are already created?

**Comment by kevinushey** [comment]
Each Python object gets its own individual convert flag -- it cannot be toggled globally, or for all objects derived from a module, or something like that.

Ultimately, you might just want to have separate module objects; e.g.

```
rgc1 <- reticulate::import("refgenconf", convert = FALSE)
rgc2 <- reticulate::import("refgenconf", convert = TRUE)
```

**Comment by nsheff** [comment]
Ok, I figured it out! I needed to assign convert on the object itself, rather than on the module, like this:

```
rgc2 = mod2$RefGenConf(Sys.getenv("REFGENIE"))
assign("convert", TRUE, envir = rgc2)
rgc2$seek("t7", "fasta")
```

Now it works like I wanted. Thanks for your help!
