### ISSUE TITLE
Error in sys$stdout$flush() : attempt to apply non-function

### ISSUE THREAD

**Issue by leeleavitt** [rstudio/reticulate#815]
I'm working with a variety of machines in my lab. Some computer return this error when i attempt the following code,

`keras = reticulate::import('keras')`

the returned error is
`Error in sys$stdout$flush() : attempt to apply non-function`

The traceback is,
> 5: py_flush_output()
4: py_run_string("class R(object): pass")
3: py_inject_r(envir = globalenv())
2: ensure_python_initialized(required_module = module)
1: reticulate::import("keras")

This is frustrating becuase if I run the same code again,
`keras = reticulate::import('keras')`

It works. 

Unfortunately I don't have the patience to `tryCatch` this to simply run it again.

**Comment by kevinushey** [comment]
This sounds like a bug that should be resolved already in the latest version of `reticulate` on CRAN. What version of `reticulate` is installed on those machines? Can you also share `sessionInfo()`?

**Comment by leeleavitt** [comment]
Hi Kevin, the version is 1.14. Thanks for the fast reply

**Comment by leeleavitt** [comment]
>locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

>attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

>other attached packages:
[1] procPharm_2.0.0

>loaded via a namespace (and not attached):
[1] compiler_3.6.3  rappdirs_0.3.1  Rcpp_1.0.4      reticulate_1.14
[5] jsonlite_1.6.1

**Comment by kevinushey** [comment]
Thanks! The current version of `reticulate` is 1.16, which should have a fix for the issue you're encountering here. I'd recommend updating via `install.packages("reticulate")` if possible.
