### ISSUE TITLE
Cannot use reticulate to load python modules from conda environments when using callr

### ISSUE THREAD

**Issue by mattwarkentin** [rstudio/reticulate#816]
Hi,

My issue is that I am unable to load python modules which exist only in a specific `conda` environment when I am using `{callr}` to run `R` subprocesses. Others don't seem to have this issue (see r-lib/callr#160). I have tried as much as I can to figure this out but I am at a loss for what is the root cause of this.

I have tried to present some reproducible examples of what works and what doesn't, please see below.

In a clean R session:
``` r
Sys.which("python")
#>            python 
#> "/usr/bin/python"
```

In a clean and interactive R session, this works, I can import `keras` and the python version is now the one in the conda env...
```r
reticulate::use_condaenv("r-reticulate", required = TRUE)
keras <- reticulate::import("keras")
Sys.which("python")
```
```
                                       python 
"/opt/anaconda3/envs/r-reticulate/bin/python"
```

Oddly, perhaps, when running a `reprex` as shown below after successfully running the above code, the reprex finds the `r-reticulate` version of python. Something about the working environment seems to be passed to the reprex `callr` session?
```r
reprex::reprex(Sys.which("python"))
```
``` r
Sys.which("python")
#>                                        python 
#> "/opt/anaconda3/envs/r-reticulate/bin/python"
```
I have similarly noticed that restarting the R session does not always unbind the python version, which seems odds to me.

Trying to run the whole thing as a `reprex` which uses `callr` under the hood, it fails...
```r
reprex::reprex({
  reticulate::use_condaenv("r-reticulate", required = TRUE)
  keras <- reticulate::import("keras")
  Sys.which("python")
})
```
```
Rendering reprex...
Error in get_result(output = out, options) : 
  callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
```
```
 Stack trace:

 1. reprex::reprex({ ...
 2. reprex:::reprex_render(r_file, std_file)
 3. callr::r_safe(function(input) { ...
 4. callr:::get_result(output = out, options)
 5. throw(new_callr_error(output, killmsg))

 x callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed 
```

When using `{callr}` directly, I can't load `"keras"` because it is only installed in the conda env `r-reticulate`
``` r
callr::r(
  function() {
    reticulate::import("keras")
  }
)
#> Error: callr subprocess failed: ImportError: No module named keras
```
But even when I try to activate the necessary conda env...
``` r
callr::r(
  function() {
    reticulate::use_condaenv("r-reticulate", required = TRUE)
    keras <- reticulate::import("keras")
  }
)
#> Error in get_result(output = out, options): callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
```
```
 Stack trace:

 1. callr::r(function() { ...
 2. callr:::get_result(output = out, options)
 3. throw(new_callr_error(output, killmsg))

 x callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed 
```

**Comment by kevinushey** [comment]
Do you have any environment variables set that could affect Python on startup (e.g. `PYTHONPATH`, `PYTHONHOME`, or anything else)?

Can you also provide your `sessionInfo()`?

**Comment by mattwarkentin** [comment]
Thanks for the reply @kevinushey. I have tried some of the above code on other machines and it works. So I am going to re-install some things and see whats up. Will report back if this solves the issue.

**Comment by mattwarkentin** [comment]
So I removed all traces of `anaconda` and `conda` from my machine, and this time around I decided to try and use `virtualenv` instead (for several reasons).

After creating a `virtualenv` with `reticulate::virtualenv_create("r-reticulate")` and installing a handful of `python` packages, I ran the following code to no avail...

``` r
library(reticulate)
use_virtualenv("r-reticulate", required = TRUE)
use_python("/Users/matt/.virtualenvs/r-reticulate/bin/python3", required = TRUE)

keras <- import("keras")
#> Error: Python shared library not found, Python bindings not loaded.
#> Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.
Sys.which("python")
#>                                             python 
#> "/Users/matt/.virtualenvs/r-reticulate/bin/python"
```

**Comment by mattwarkentin** [comment]
It does work in `python` from the shell, so I believe it has something to do with `{reticulate}`.
```bash
$ source .virtualenvs/r-reticulate/bin/activate

$ which python
/Users/matt/.virtualenvs/r-reticulate/bin/python

$ python
```
```py
Python 3.7.3 (default, Dec 13 2019, 19:58:14) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
>>> 
```

**Comment by mattwarkentin** [comment]
This may be relevant also...
``` r
library(reticulate)
use_virtualenv("r-reticulate", required = TRUE)
use_python("/Users/matt/.virtualenvs/r-reticulate/bin/python3", required = TRUE)

py_discover_config()
#> python:         /Users/matt/.virtualenvs/r-reticulate/bin/python3
#> libpython:      [NOT FOUND]
#> pythonhome:     /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7:/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7
#> version:        3.7.3 (default, Dec 13 2019, 19:58:14)  [Clang 11.0.0 (clang-1100.0.33.17)]
#> numpy:          /Users/matt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/numpy
#> numpy_version:  1.19.1
#> 
#> NOTE: Python version was forced by use_python function
```

**Comment by kevinushey** [comment]
Do things work with the development version of reticulate?

**Comment by mattwarkentin** [comment]
No, after installing the dev version of `reticulate` from GitHub the same issues persist.

**Comment by kevinushey** [comment]
I think the problem here might just be that the version of Python distributed with Xcode doesn't have a shared library, and so cannot be used by reticulate (even though the standalone interpreter works)

**Comment by mattwarkentin** [comment]
Is that version of python even being used? Shouldn't it be using the python in the virtualenv? In any case, is there a solution to avoid the Xcode python? I'm not sure how to go about fixing this.

**Comment by kevinushey** [comment]
But the virtual environment was evidently created via that Xcode version of Python, so that virtualenv Python is just an encapsulated version of the Xcode Python (assuming I'm understanding everything correctly)

**Comment by mattwarkentin** [comment]
Oh, I see. So should I attempt to re-create the same `virtualenv` but this explicitly specifying which `python` to use (i.e. not the Xcode version)?

**Comment by mattwarkentin** [comment]
So I tried forcing the use of `Python 3.7.3` installed using `pyenv` and it still did not work...
``` r
 library(reticulate)
 use_virtualenv("r-reticulate")
 py_discover_config()
#> python:         /Users/matt/.virtualenvs/r-reticulate/bin/python
#> libpython:      [NOT FOUND]
#> pythonhome:     /Users/matt/.virtualenvs/r-reticulate:/Users/matt/.virtualenvs/r-reticulate
#> version:        3.7.3 (default, Aug 11 2020, 11:11:51)  [Clang 11.0.0 (clang-1100.0.33.17)]
#> numpy:          /Users/matt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/numpy
#> numpy_version:  1.19.1
#> 
#> python versions found: 
#>  /Users/matt/.virtualenvs/r-reticulate/bin/python
#>  /usr/bin/python3
#>  /usr/local/bin/python3
#>  /usr/bin/python
 
keras <- import("keras")
#> Error: Python shared library not found, Python bindings not loaded.
#> Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.
```

**Comment by mattwarkentin** [comment]
This seems problematic also...
``` r
library(reticulate)
use_virtualenv("r-reticulate")
py_discover_config()
#> python:         /Users/matt/.virtualenvs/r-reticulate/bin/python
#> libpython:      [NOT FOUND]
#> pythonhome:     /Users/matt/.virtualenvs/r-reticulate:/Users/matt/.virtualenvs/r-reticulate
#> version:        3.7.3 (default, Dec 13 2019, 19:58:14)  [Clang 11.0.0 (clang-1100.0.33.17)]
#> numpy:          /Users/matt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/numpy
#> numpy_version:  1.19.1
#> 
#> python versions found: 
#>  /Users/matt/.virtualenvs/r-reticulate/bin/python
#>  /Users/matt/.virtualenvs/r-reticulate/bin/python3
#>  /usr/bin/python3
#>  /usr/local/bin/python3
#>  /usr/bin/python
py_available()
#> [1] FALSE
```

**Comment by mattwarkentin** [comment]
Another corner of the internet suggests this is an `--enable-shared` issue, and when checking if this is enable for my python version used by the virtualenv I get...
```py
Python 3.7.3 (default, Dec 13 2019, 19:58:14) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_vars('Py_ENABLE_SHARED')
[0]
>>> 
```

Could this be the issue with `libpython` not being found?

**Comment by mattwarkentin** [comment]
Okay, so I got it working. I ran `reticulate::install_miniconda()`, then I used the `python` binary installed in `"/Users/matt/Library/r-miniconda/envs/r-reticulate/bin/python"` to create the virtualenv:
```r
library(reticulate)
virtualenv_create("r-reticulate", python = "/Users/matt/Library/r-miniconda/envs/r-reticulate/bin/python")
```

and lastly...
``` r
library(reticulate)
use_virtualenv("r-reticulate", required = TRUE)
py_discover_config()
#> python:         /Users/matt/.virtualenvs/r-reticulate/bin/python
#> libpython:      /Users/matt/Library/r-miniconda/envs/r-reticulate/lib/libpython3.6m.dylib
#> pythonhome:     /Users/matt/.virtualenvs/r-reticulate:/Users/matt/.virtualenvs/r-reticulate
#> version:        3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:19:23)  [GCC Clang 10.0.1 ]
#> numpy:          /Users/matt/.virtualenvs/r-reticulate/lib/python3.6/site-packages/numpy
#> numpy_version:  1.19.1
#> 
#> NOTE: Python version was forced by use_python function
import("keras")
#> Module(keras)
```
Still have no idea why I needed the `python` version installed with `miniconda` to finally get virtualenvs to work. Maybe you have some insights into this issue.

**Comment by liutiming** [comment]
I have this issue, too. I do not think it is practical to install miniconda because I am on a cluster and do not have much space in my home directory :(
