### ISSUE TITLE
error when attempting to list Python modules

### ISSUE THREAD

**Issue by kevinushey** [rstudio/reticulate#82]
The following prints an error and occasionally segfaults for me:

```R
library(tensorflow)
tf$app # force load
sys <- import("sys")
sys$modules
```

I see:

```
> library(tensorflow)
> tf$app # force load
Module(tensorflow.python.platform.app)
> sys <- import("sys")
> sys$modules
Error in py_ref_to_r_with_convert(attrib, convert) :
  attempt to set index 787/787 in SET_VECTOR_ELT
Calls: $ ... $.python.builtin.object -> py_ref_to_r_with_convert -> .Call
Execution halted
```

For reference, this is what `sys.modules` looks like on my system, printed using pretty-printing:

```R
library(reticulate)
library(tensorflow)

tf$app # force load
sys <- import("sys", convert = FALSE)
sys$modules

pprint <- import("pprint")
pprint$pprint(sys$modules)
```

[Gist of output](https://gist.github.com/kevinushey/56dea0ae5aaebf4c69cc70b819aeb08f) (attached separately as it's rather large)

**Comment by jjallaire** [comment]
Looks like this error is being thrown by base R inside SET_VECTOR_ELT:

https://github.com/wch/r-source/blob/af7f52f70101960861e5d995d3a4bec010bc89e6/src/main/memory.c#L3446-L3475
