### ISSUE TITLE
install_conda requires elevated privileges

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/reticulate#820]
Running
```r
install.packages('reticulate')
reticulate::install_miniconda()
reticulate::conda_create('r-reticulate')
reticulate::conda_install(packages = "pre-commit")
```
on GitHub actions for macOS (not for windows and linux) with the tidyverse CI gives 

```
NotWritableError: The current user does not have write permissions to a required path.
  path: /usr/local/miniconda/pkgs/cache/b89cf7bf.json
  uid: 501
  gid: 20
If you feel that permissions on this path are set incorrectly, you can manually
change them by executing
  $ sudo chown 501:20 /usr/local/miniconda/pkgs/cache/b89cf7bf.json
In general, it's not advisable to use 'sudo conda'.
```

I don't know if the problem can be circumvented by choosing non-default installation location of conda. I don't think it makes sense to use `chown` to change permissions in the miniconda cache.

Here is the log: https://github.com/lorenzwalthert/test-conda-installer/runs/992932111?check_suite_focus=true
The workflow file is: https://github.com/lorenzwalthert/test-conda-installer/blob/master/.github/workflows/R-CMD-check.yaml

Here is a relevant discussion: https://github.com/conda/conda/issues/7267

**Comment by kevinushey** [comment]
Is setting the `RETICULATE_MINICONDA_PATH` environment variable to path where you have read/write permissions an option?

**Comment by lorenzwalthert** [comment]
Well I thought about it too but it seems to me that won't have any effect since it's by default already under the users home directory. Reason: `reticulate::miniconda_path()` falls back to `reticulate:::miniconda_path_default()` when `RETICULATE_MINICONDA_PATH` is unset, which gives `path.expand("~/Library/r-miniconda")` on mac. It seems as this cache is set up in outside of this scope and for all users, i.e. `/usr/local/miniconda/pkgs/`.

**Comment by lorenzwalthert** [comment]
This is a duplicate of https://github.com/rstudio/reticulate/issues/793, sorry I did not search properly. I now use the dev version of reticulate and the problem disappears.
