### ISSUE TITLE
Reticulate crases RStudio!

### ISSUE THREAD

**Issue by zack77789** [rstudio/reticulate#826]
When importing module from virtual environment (using via reticulate::import()) RStudio crashes

![image](https://user-images.githubusercontent.com/24804698/90975482-4b75d280-e53d-11ea-840a-765c32e7555a.png)

![image](https://user-images.githubusercontent.com/24804698/90974659-eb2f6280-e535-11ea-9b2f-db68885f825f.png)

OS: Windows 10 (64bit)
RStudio Version 1.3.959
R version: R-4.0.2 (64bit)
reticulate 1.16

Restarting RStudio or reinstalling reticulate do not help!

**Comment by kevinushey** [comment]
I believe this is fixed in the development version of `reticulate` -- you can install it via:

```
remotes::install_github("rstudio/reticulate")
```

If you're still having trouble, please let me know.

**Comment by zack77789** [comment]
Works now! Great! Thx!
