### ISSUE TITLE
R encountered fatal error after `reticulate::py_config` and `Sys.setenv()`

### ISSUE THREAD

**Issue by drkamarul** [rstudio/reticulate#827]
Hi all,

I want to run python from my own virtual environment in the RStudio project but RStudio crashes everytime I run `reticulate::py_config()`. Some other people are facing this issue too. 

What is strange is that, 4 months ago it worked for me (see my video on YouTube https://www.youtube.com/watch?v=VsfaIeNbpj8&t=929s. 

I have followed this guide https://docs.rstudio.com/tutorials/user/using-python-with-rstudio-and-reticulate/ to take advantage of the virtual environment in the RStudio project directory. However, RStudio crashes (R encountered fatal error) after I run the `reticulate::py_config()`

![image](https://user-images.githubusercontent.com/6749223/91008847-c90b1280-e611-11ea-8727-a4474bceacd4.png)

These what I have done: 

In Window CMD,  I have set a new virtual environment (.venv) and activated it  

```
(base) D:\testpython>D:\testpython\.venv\Scripts\activate
(.venv) (base) D:\testpython>where pip
D:\testpython\.venv\Scripts\pip.exe
C:\Users\drkim\Anaconda3\Scripts\pip.exe

(.venv) (base) D:\testpython>python
```

After running the codes above, I received this 

```
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation
```

Then, in RStudio, I did these

![image](https://user-images.githubusercontent.com/6749223/91008891-eb9d2b80-e611-11ea-9b82-39785e2e97c8.png)

Then run again this , after restarting RStudio, it crashes

![image](https://user-images.githubusercontent.com/6749223/91009402-1c319500-e613-11ea-9dba-fe6e6b391fca.png)

If however, I commented like this

![image](https://user-images.githubusercontent.com/6749223/91008979-1d15f700-e612-11ea-84cf-ad3a1cff5f24.png)

And start a new session, and agian run reticulate::py_config(), I will get this 

![image](https://user-images.githubusercontent.com/6749223/91009032-4040a680-e612-11ea-8d0e-766d13640807.png)

But this uses python in the `base` environment not my `.venv` environment.

Anyone can help me to run python within the virtual environment?

**Comment by kevinushey** [comment]
Do you see the same issue with the development version of `reticulate`?

**Comment by drkamarul** [comment]
It is solved after using the development version of reticulate. Thanks very much

![image](https://user-images.githubusercontent.com/6749223/91184901-c3035780-e71f-11ea-9dda-8677045b645f.png)
