### ISSUE TITLE
dict() fails with string keys containing numbers

### ISSUE THREAD

**Issue by kevinushey** [rstudio/reticulate#83]
E.g. the following fails:

```R
> dict(feature1 = 1:4)
Warning in FUN(X[[i]], ...) : NAs introduced by coercion
{-2147483648: [1, 2, 3, 4]}
```

Likely due to the regex used here: https://github.com/rstudio/reticulate/blob/master/R/python.R#L487

Should be `^[0-9]+$`?

**Comment by jjallaire** [comment]
Yikes, good catch! Fixed here: https://github.com/rstudio/reticulate
