### ISSUE TITLE
Can't read pickle file + use_conda env error

### ISSUE THREAD

**Issue by MislavSag** [rstudio/reticulate#830]
When I try to import pickle file using pandas:
```
pd <- reticulate::import('pandas')
X_train <- read_pickle_file('X_train.pkl')
```
it returns an error:
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: unsupported pickle protocol: 5 

The same code works in python.

I also discovered one error (I can open a new issue if necessary). If I try to set conda environment:
`reticulate::use_condaenv('base', 'C:/ProgramData/Anaconda3/condabin', required = TRUE)`
it returns an error:
```
Error in system2(conda, args = c("info", "--json"), stdout = TRUE, stderr = FALSE) : 
  '"C:/ProgramData/Anaconda3/condabin"' not found

```
I amusing a new anaconda that uses python 3.8 version

**Comment by gsgxnet** [comment]
regarding your statement part about 'base' - to use the anaconda3 base environment the statement has to crafted as:  

`reticulate::use_condaenv("anaconda3", required = TRUE)`

you can check with `py_config()` later on that `anaconda3` is the name of one environment.

Caveat: This works up until the currently released reticulate 1.16. But not in the development version any more. I will open an issue for that.

**Comment by kevinushey** [comment]
In order for us to further investigate, I think we'd need a reproducible example. Are you able to share a standalone snippet of code that reproduces the issue (without depending on any external data)?

Or, can you share the data object you're using to reproduce here?

**Comment by MislavSag** [comment]
Iy works when I use `use_python` instead of `use_condaenv` and I can read pickle now.
