### ISSUE TITLE
Error in double square bracket

### ISSUE THREAD

**Issue by binxiangni** [rstudio/reticulate#84]
When using python to create a 2-d array, no error is generated.
```
>>> import numpy as np
>>> np.array([[1, 2],[3,4]])
array([[1, 2],
       [3, 4]])
```
However, by use of `reticulate`, an error comes up.
```
> np <- import("numpy")
> np$array([[1, 2],[3,4]])
Error: unexpected '[[' in "np$array([["
```
Did I miss anything when using `reticulate`?

**Comment by terrytangyuan** [comment]
`[[1, 2],[3,4]]` is not R syntax. You need to use `list()` or `c()`
