### ISSUE TITLE
Reticulate Plot

### ISSUE THREAD

**Issue by henry090** [rstudio/reticulate#842]
Hi, Kevin.

I have been searching for a solution to return py plots from R.
In this [post](https://community.rstudio.com/t/reticulate-rstudio-matplotlib/33219), including other issues on community.rstudio I was not able to find an answer to my question. 

Is it possible to return the plots rendered from Jupyter Notebooks to the RStudio viewer/plot section? Because as far as I know/understand Viewer can return Html objects. 

Could you suggest anything? BTW, I am more interested in console solution instead of markdown/notebook.

**Comment by kevinushey** [comment]
PNG plots can be shown in the Plots pane, but we haven't yet wired up HTML plots to the Viewer pane.

**Comment by henry090** [comment]
Thanks for your reply.
