### ISSUE TITLE
Option to modify the np env

### ISSUE THREAD

**Issue by henry090** [rstudio/reticulate#879]
Hi @kevinushey . Is there a way to implement what I want?

```
np = reticulate::import('numpy')
a = reticulate::r_to_py(
  np$array(list(c(5,6,7),c(5,6,7)))
  )

a[0] = reticulate::r_to_py(np$array(c(1,2,3)))
```
Output:

```
Error in a[0] = reticulate::r_to_py(np$array(c(1, 2, 3))) : 
  object of type 'environment' is not subsettable
```

Python:

```
import numpy as np

a = np.array([[5,6,7],[5,6,7]])

a[0] = np.array([1,2,3])
a
```
Output:

```
array([[1, 2, 3],
       [5, 6, 7]])
```

__Is there a way to modify this within a python object because I do not want to convert it to an r object?__

**Comment by kevinushey** [comment]
You likely want `convert = FALSE`; e.g.

```
library(reticulate)
np <- import("numpy", convert = FALSE)
a <- np$array(list(5:7, 5:7))
a$put(0:2, np$array(list(1:3)))
```

Unfortunately we don't have a sub-assignment operator that does what you're expecting here; it could be worth implementing though.

**Comment by henry090** [comment]
Yes! I forgot about the ```convert``` argument. Thanks!
