### ISSUE TITLE
reticulate stopped respecting RETICULATE_AUTOCONFIGURE="0" env var?

### ISSUE THREAD

**Issue by cboettig** [rstudio/reticulate#882]
I have the environmental variable, `RETICULATE_AUTOCONFIGURE="0"`, because I really don't want `reticulate` to keep aggressively forcing me into a conda environment.  I believe this used to work, but recently, running `reticulate::py_discover_config()` is prompting me to install a non-system python via miniconda.  (More frustrating still, if I execute a python script in RStudio, reticulate goes ahead and starts installing miniconda without even bothering to give me the prompt).

```r
> library(reticulate)
> py_discover_config()
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: n
Installation aborted.
python:         /opt/venv/reticulate/bin/python3
libpython:      /usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.so
pythonhome:     /opt/venv/reticulate:/opt/venv/reticulate
version:        3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
numpy:          /opt/venv/reticulate/lib/python3.8/site-packages/numpy
numpy_version:  1.19.4

python versions found: 
 /opt/venv/reticulate/bin/python3
 /usr/bin/python3
 /usr/local/bin/python
 /opt/venv/reticulate/bin/python
> Sys.getenv("RETICULATE_AUTOCONFIGURE")
[1] "0"
```

What am I missing here?  Is there a different way to avoid the miniconda prompt?

I am currently setting the env var `WORKON_HOME` to `/opt/venv` where my (multi-user, shared) virtual environments live, with my intended default one being called `reticulate`.  As you can see above, once I decline the install prompt, reticulate has no trouble detecting the correct environment and no trouble letting me opt into a different virtual env if necessary (which is why I'd rather not set RETICULATE_PYTHON or RETICULATE_PYTHON_ENV).

**Comment by kevinushey** [comment]
You should be able to set `RETICULATE_MINICONDA_ENABLED` to `FALSE` to disable that prompt. Does that work for you?

**Comment by cboettig** [comment]
Thanks @kevinushey, that's perfect.  knew I must have had the config wrong.
