### ISSUE TITLE
TypeError: 'float' object is not iterable

### ISSUE THREAD

**Issue by AprilSong0323** [rstudio/reticulate#888]
I am trying to use networkx module from Python.
Here is the code and error I got. Any suggestions?

nx<-import("networkx")
G1 <- nx$cycle_graph(6)

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: 'float' object is not iterable

Detailed traceback: 
  File "</Users/xxx/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-28>", line 2, in star_graph
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/networkx/utils/decorators.py", line 297, in _nodes_or_number
    nodes = tuple(n)

**Comment by kevinushey** [comment]
When passing objects from R to Python, you often need to be explicit about the object type -- for example,

```
nx<-import("networkx")
G1 <- nx$cycle_graph(6L)
```

using `6L` to ensure an integer literal (as opposed to a `double`) is passed in. You can also use `as.integer(6)` to the same effect.
