### ISSUE TITLE
Error: could not find a Python environment for python

### ISSUE THREAD

**Issue by ShixiangWang** [rstudio/reticulate#898]
I use `py_install()` but get an error which says no Python environment can be found. I tried installing the latest version from Github but still not work

```r
> py_path = "/Users/wsx/anaconda3/bin/python"
> reticulate::use_python(py_path, required = TRUE)
> reticulate::py_module_available("multiprocess")
[1] FALSE
> reticulate::py_install("multiprocess", pip = TRUE)
Error: could not find a Python environment for /Users/wsx/anaconda3/bin/python

> reticulate::py_config()
python:         /Users/wsx/anaconda3/bin/python
libpython:      /Users/wsx/anaconda3/lib/libpython3.7m.dylib
pythonhome:     /Users/wsx/anaconda3:/Users/wsx/anaconda3
version:        3.7.4 (default, Aug 13 2019, 15:17:50)  [Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/wsx/anaconda3/lib/python3.7/site-packages/numpy
numpy_version:  1.19.0

NOTE: Python version was forced by use_python function
```

**Comment by kevinushey** [comment]
This is because you're trying to use your Anaconda installation's Python directly, rather than a Conda environment derived from that installation. You should normally want to create a Conda environment and then instruct `reticulate` to use that environment.

**Comment by ShixiangWang** [comment]
@kevinushey The Anaconda installation's Python provides a base environment. I can use reticulate for calling python but why can't I use it for installing python module with `py_install()` to the base environment? That's strange.
