### ISSUE TITLE
Update python version

### ISSUE THREAD

**Issue by ntluong95** [rstudio/reticulate#900]
I noticed that now reticulate is using Python ver 3.6.1. I would ask how I can update the new version of Python into it or I have to wait when reticulate integrate the new Python version into it.

Thank you

**Comment by kevinushey** [comment]
You can instruct `reticulate` to bind to any version of Python via `reticulate::use_python()`, `reticulate::use_virtualenv()`, and so on. See the documentation at https://rstudio.github.io/reticulate/ for more details.
