### ISSUE TITLE
Specify field within python iterator

### ISSUE THREAD

**Issue by willi3by** [rstudio/reticulate#901]
Hi, 

I am converting some python code to R and have a question about accessing each item when calling an iterator. I have successfully used iterate with my python iteratable, called "groups". However, there are values within each item that I need to access. In my previous python code, i could call something like:
```
for g in groups:
    print(g.name)
```
and the name for each item would print. How do I specify item fields with an R function and iterate? In other words, what is each item referred to in the for loop that I assume iterate is implementing? 

Thanks for your time

**Comment by kevinushey** [comment]
Something like the following works for me:

`````
library(reticulate)

x <- py_eval("
[
  {'key': 1},
  {'key': 2}
]
", convert = FALSE)

vals <- iterate(x, function(el) { el[["key"]] })
vals
`````

Presumedly you just need to tailor the R function passed to `iterate()` to access the elements of `g` as appropriate?

**Comment by willi3by** [comment]
Works great! I misunderstood what is passed when iterate is used, sorry for the confusion. 

Thanks for the quick response!
