### ISSUE TITLE
`py_eval` does not work with the same code strings as `py_run_string` (assignment and imports)

### ISSUE THREAD

**Issue by joelostblom** [rstudio/reticulate#902]
I find that `py_eval` does not work for strings that contain assignment and import statements, weheras `py_run_string` does. This was unexpected since they have a similar call signature and share the same documentation page, but I might just be misunderstanding their use cases.

For example, `py_run_string("x = 3")` works fine and returns a dictionary, but `py_eval("x = 3")` raises this error:

```
Error in py_eval_impl(code, convert) :
  SyntaxError: invalid syntax (reticulate_eval, line 1)
```

My downstream use case for this is to right a knitr source hook that detects if the executed chunk contains an Altair chart and then display it using `as_vegaspec` as a workaround for https://github.com/rstudio/reticulate/issues/711 (and thanks for the recent comment on potential implementation there, exciting!).

I had a look at https://github.com/rstudio/reticulate/blob/master/R/knitr-engine.R and realize that it might not be as simple as passing the chunk source to `py_eval`. However, passing the chunk source to `py_run_string` did work so I thought there might be hope. Unfortunately, `py_run_string` does not seem to store the output value of the chunk, only any variables assigned during execution, so it is not helpful in my case where I want to change the display of the chunk output with the hook.

It would be great if `py_eval` worked with the same input as `py_run_string` or if `py_run_string` automatically stored chunk output in a variable with a special name. The strings I want to run look something like this:

```
"import altair as alt\nimport pandas as pd\ndf = pd.DataFrame({\n    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],\n    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]\n})\nchart1 = alt.Chart(df).mark_bar().encode(\n    alt.X('a:N',title='X-Axis label'),\n    alt.Y('b:Q',title='Y-axis label'))\nchart1.to_json()"
```

**Comment by kevinushey** [comment]
This is expected, as `py_eval()` is basically just a front-end to Python-level `eval()`:

```
$ python -c 'eval("x = 3")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1
    x = 3
      ^
SyntaxError: invalid syntax
```

I should probably make this distinction clear in the documentation.

For your use case, I think the most appropriate way forward would be to bundle a Python module in your package, and then load + use that to accomplish what you need. That way you can write pure Python code and just interface with it from the R level.

**Comment by joelostblom** [comment]
Great, thanks for the pointers! Do you know if there is anyway to use the Python builtin `exec` instead of `eval` via reticulate? I tried the builtins import but run into the following error:

```r
b = reticulate::import_builtins()
b$exec("x = 3")
```

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  SystemError: frame does not exist
```

**Comment by kevinushey** [comment]
You might need to pass globals + locals explicitly; e.g.

```
library(reticulate)
builtins <- import_builtins(convert = TRUE)
globals <- py_run_string("globals()")
b$exec("x = 3", globals, globals)
py$x
```

**Comment by kevinushey** [comment]
I think the issue here is resolved -- it's basically around extra requirements when using eval + exec from reticulate. I've updated the documentation to make this a bit more clear.
