### ISSUE TITLE
py_install on a local library

### ISSUE THREAD

**Issue by Cdk29** [rstudio/reticulate#905]
Hi.

I want to execute something similar to : 

`!pip install --quiet /some/path`

I tried to do : 

`reticulate::py_install(packages="/some/path", pip=TRUE)`

But it did not worked. Is there a way to tell py_install to look for a library in a path?

**Comment by kevinushey** [comment]
Not explicitly from `reticulate`, but you could hack something yourself with something like:

```
config <- reticulate::py_config()
system2(config$python, c("-m", "pip", "install", "--quiet", shQuote("/some/path")))
```

Would that be sufficient?

**Comment by Cdk29** [comment]
@kevinushey thanks, it works perfectly !

I tried to pass instruction using system() too, but it was doing an installation on the global machine, not the virtual environment. Your solution worked like a charm. Thanks.
