### ISSUE TITLE
Error in py_run_file_impl(file, local, convert) :    ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by tressoldi** [rstudio/reticulate#909]
I'm using reticulate within the text package (https://r-text.org/, https://github.com/OscarKjell/text), but after launching one of its function, I got this message: Error in py_run_file_impl(file, local, convert) :    ModuleNotFoundError: No module named 'torch'

This is my py_conf()
python:         C:/Users/Admin.DESKTOP-6E4TROE/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/Admin.DESKTOP-6E4TROE/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/Admin.DESKTOP-6E4TROE/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.12 (default, Dec  9 2020, 00:11:44) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Admin.DESKTOP-6E4TROE/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.19.4

Furthermore, the torch package has been downloaded and available here:
C:/Users/Admin.DESKTOP-6E4TROE/anaconda3/pkgs/pytorch-1.7.1-py3.7_cuda110_cudnn8_0/Lib/site-packages/torch

**Comment by prasiddhigyawali** [comment]
I am having this error too, were you able to work through it?

**Comment by tressoldi** [comment]
Not yet.

**Comment by OscarKjell** [comment]
Hi, 
Could you please try installing a recent version of text. 

```
# install.packages("devtools")
devtools::install_github("oscarkjell/text")

```
And then run: 
```
library(text)
library(reticulate)

# Install text required python packages in a conda environment (with defaults).
text::textrpp_install()

# Show available conda environments.
reticulate::conda_list()

# Initialize the installed conda environment.
# save_profile = TRUE saves the settings so that you don't have to run textrpp_initialize() after restarting R. 
text::textrpp_initialize(save_profile = TRUE)

# Test so that the text package work.
textEmbed("hello")
```

For more details see: http://r-text.org/articles/Extended_Installation_Guide.html

**Comment by tressoldi** [comment]
Fixed !!!!
Thank you for your continous support.

All the best
Patrizio

**Comment by idinov** [comment]
After running the above commands, I get this error:

**Error in py_run_file_impl(file, local, convert) : 
  RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
No module named 'google.protobuf'**

Any suggestions for fixing this? Thanks, in advance.

**Comment by t-kalinowski** [comment]
Does `py_install("protobuf")` fix the issue?
