### ISSUE TITLE
use R option to control whether hidden attributes returned for completions

### ISSUE THREAD

**Issue by kevinushey** [rstudio/reticulate#91]
When experimenting, I often with that the `$` operator also returned 'hidden' methods (those defined with an initial underscore). What do you think about controlling this behavior with some kind of R option?

E.g. `options(reticulate.completion.attributes = <...>)`, with possible values `"all"`, `"public"`?

**Comment by terrytangyuan** [comment]
I think it's a good idea. Oftentimes there are many hidden methods showing up in the completion which increases the time that I need to scroll down to find the method I actually want to use.

**Comment by jjallaire** [comment]
I agree. I in fact I think we should just not ever include "_" prefixed
objects in completions. I'll make this change after the next CRAN release.

**Comment by jjallaire** [comment]
It looks to me like these should already be filtered out here: https://github.com/rstudio/reticulate/blob/master/R/python.R#L377

Do you have an example where I could see this happening?

It looks like we currently don't filter leading underscores in dictionaries. Perhaps you are seeing this in a dictionary?
