### ISSUE TITLE
py_config() and Python initialization consistently failing **on first call only**

### ISSUE THREAD

**Issue by mmuurr** [rstudio/reticulate#916]
Relevant language and package versions:
* R 4.0.3
* python 2.7.16 (Mac OS X's system default)
* reticulate 1.18

In a fresh R session, this has been happening to me:
```r
reticulate::py_config()
# Error in py_call_impl(callable, dots$args, dots$keywords) :
#  AttributeError: 'module' object has no attribute '__import__'
#
# Detailed traceback:
#   File "/usr/local/lib/R/4.0/site-library/reticulate/python/rpytools/loader.py", line 13, in initialize
#     _import = builtins.__import__

reticulate::py_config()
# python:         /usr/bin/python
# libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
# pythonhome: /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
# version:        2.7.16 (default, Dec 13 2019, 18:00:32)  [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s
# numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
# numpy_version:  1.8.0

# python versions found:
# /usr/bin/python3
# /usr/bin/python
```
... i.e. on the first `py_config()` call I get an error. Making the same `py_config()` call immediately afterwards succeeds, and it appears I can load Python modules just fine. (Though I haven't yet rigorously tested Python code to make sure the Python environment is properly functioning, because of the package problem described below.)

In an interactive R session, this would be fine (if not annoying/weird), but this is suddenly breaking a package of mine where `.onLoad()` includes adding a reticulate/Python object into the package's namespace (via reticulate's `import_from_path` with some package-embedded Python code).

One could conceivably around this by ensuring a successful reticulate initialization before loading the package, but the "testing if installed package can be loaded..." phase of building/installing the package is failing (naturally), since it only knows to try to initialize reticulate once.

**Comment by kevinushey** [comment]
I think this should be fixed in the development version of `reticulate`, which I'm hoping to submit to CRAN soon.

**Comment by mmuurr** [comment]
Confirmed: the dev version 1cd9bd1fa94f9a1a37d7e709e35b681f60ef6615 solves this. (Though until it's on CRAN, any other packages depending on reticulate will likely fail in end-users' hands -- unless, of course, they're also grabbing reticulate from github.)

Cheers!

**Comment by mmuurr** [comment]
Actually ... there seems to be another problem, though perhaps they're related? Because it's an issue with a different part of the `loader.py` file, I've just opened the issue separately [here](917).

**Comment by kevinushey** [comment]
I think this should also be resolved in the development version of `reticulate` now.

**Comment by dormeir999** [comment]
I'm experiencing something similar:
 
![image](https://user-images.githubusercontent.com/17915074/104849433-42254200-58f2-11eb-9fae-b7e6e54a7b1f.png)

**Comment by kevinushey** [comment]
Do you also see this in the development version of `reticulate`?

```
remotes::install_github("rstudio/reticulate")
```
