### ISSUE TITLE
Support miniforge helpers

### ISSUE THREAD

**Issue by gvelasq** [rstudio/reticulate#920]
[Miniforge](https://github.com/conda-forge/miniforge/) is a minimal installer for `conda`, maintained by the [`conda-forge`](https://conda-forge.org/#about) organization and sponsored by NumFOCUS, which is community-led, sets `conda-forge` as the default channel, and notably supports ARMv8 64-bit (aarch64), which may be helpful for users with M1 Macs.

I confirmed that `use_condaenv()` works with miniforge installed using Homebrew. Would you consider building helper functions for miniforge similar to those for miniconda? (e.g., `install_miniforge()`, `miniforge_path()`, `miniforge_update()`, and `use_miniforge()`?)

**Comment by njtierney** [comment]
Just wanted to chime in that this would be really helpful!

At the moment it looks like installing tensorflow on M1 macs will require miniforge (based on https://gist.github.com/juliasilge/035d54c59436604d6142ebebf29aa224)

**Comment by kevinushey** [comment]
I think (for now, at least) I'll have the existing miniconda helpers just re-route to miniforge on arm64.

**Comment by kevinushey** [comment]
Implemented with https://github.com/rstudio/reticulate/commit/0caf511f7fe5357f758ca7cb67513f5ba54a6f6a. Once miniconda starts producing arm64 builds, we'll see if we can switch reticulate back.

**Comment by mingdeyu** [comment]
Would it be possible to add an option to `install_miniconda()` that allows users to choose between miniconda and miniforge? I found in some cases miniforge is more robust and less likely to cause issues when installing itself, envs and packages.
