### ISSUE TITLE
Avoid installation of ceratin python packages

### ISSUE THREAD

**Issue by max-poltora** [rstudio/reticulate#926]
Is there any way to avoid installation of particular python packages using reticulate? 
For instance, is there any way to repeat this piece of python code: 
`virtualenv -p /usr/bin/python3 venv/py3 --verbose --no-setuptools`

Something like:
`reticulate::virtualenv_create("myenv", python="/usr/bin/python3", packages =  c("no-setuptools"))`

**Comment by kevinushey** [comment]
Not currently. Is there a reason why you want to do this?

**Comment by max-poltora** [comment]
@kevinushey, thank you for responding to this issue. I guess, you know the details already. But to make it transparent for others, the problem I am facing is setuptools compatibility with Python 3.5 (it is described explicitely in the issue #2541 [here](https://github.com/pypa/setuptools/issues/2541)).

**Comment by max-poltora** [comment]
@kevinushey, thank you for reacting rapidly on raised issue. The following code worked in my case:
```
devtools::install_github("rstudio/reticulate")
reticulate::virtualenv_create("myenv", python="/usr/bin/python3")
reticulate::virtualenv_install("myenv", packages = c("setuptools==50.3.2", ignore_installed = TRUE)
```
