### ISSUE TITLE
Automatic search path for conda

### ISSUE THREAD

**Issue by uptakeyeli** [rstudio/reticulate#93]
This is more of a suggestion. I'm running into issues with `conda="auto"`,
when `"~/anaconda2/bin/conda"` is the path to conda. I would like to keep useing "auto" in my code, so wonder if one could add `"~/anaconda2/bin/conda"` as one of the search path for conda executable

Specifically, below line, `https://github.com/rstudio/reticulate/blob/master/R/use_python.R#L233`
add an extra line of `path.expand(`"~/anaconda2/bin/conda")`.

As a more general solution, an implementation searching for `"~/anaconda*/bin/conda"` or `"~/*/bin/cond"` in general for conda executable would be ideal.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/rstudio/reticulate/commit/62a6c865a168a6136d59f00b58f6861e8a966f7b

I implemented the more straightforward literal search for anaconda2, etc. I'll also see if I can make it a bit more general as you suggested.
