### ISSUE TITLE
Error in installing package on shinyapps.io

### ISSUE THREAD

**Issue by edwinleechiahong** [rstudio/reticulate#932]
Hi, I've been running the same codes to publish an App onto shinyapps.io for a few months now and it has been running smoothly up until 220121. This morning (250121) when I tried to access the app, I ran into the following error: 

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/shiny/.virtualenvs/python_environment/lib/python3.5/site-packages/pip/__main__.py", line 21, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/shiny/.virtualenvs/python_environment/lib/python3.5/site-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
Error in value[[3L]](cond) : 
  Error installing package(s): 'pandas', 'numpy', 'scipy', 'scikit-learn'
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>

I've tried searching for the error above but could not find anything on it. 
Any help on this would be much appreciated!

**Comment by kevinushey** [comment]
The problem here appears to be that the version of `pip` installed is not actually compatible with Python 3.5 -- it's trying to use [f-strings](https://www.python.org/dev/peps/pep-0498/) but those are only available with Python 3.6 and newer.

**Comment by dblodgett-cycling** [comment]
Is this something that should be raised with shinyapps.io folks? Not clear to me if we can downgrade to a pip that is compatible with 3.5 or if it needs to be done on their side.

**Comment by kevinushey** [comment]
Just chatted with the shinyapps.io team and they're on top of it -- there's a thread here tracking progress. https://community.rstudio.com/t/post-for-tracking-python-3-5-update-for-shinyapps-io/93710
