### ISSUE TITLE
shiny-reticulate problem

### ISSUE THREAD

**Issue by sheenaseven** [rstudio/reticulate#935]
I have a question about the shiny-reticulate problem. After I updated the new reticulate, I encountered the following issue. How can I solve the problem in shiny published sever?
R version: 4.0.3
httpuv version: 1.5.
shiny version: 1.5.0

Warning in options(stringsAsFactors = T) :
virtualenv: python35_env
Gu, Z. circlize implements and enhances circular visualization
  OS reports request to set locale to "zh_CN.utf-8" cannot be honored
Collecting pandas==0.24.1
  Using cached pandas-0.24.1.tar.gz (11.8 MB)
Requirement already satisfied: sklearn in /home/shiny/.virtualenvs/
Collecting sklearn
Requirement already satisfied: xgboost==0.90 in /home/shiny/.virtualenvs/
  Using cached sklearn-0.0-py2.py3-none-any.whl
Collecting xgboost==0.90
Killed
**Error in value[[3L]](cond) : 
  Error installing package(s): 'pandas==0.24.1', 'sklearn', 'xgboost==0.90'**

**Comment by kevinushey** [comment]
This appears to be a shinyapps.io issue, not reticulate.

> Killed

This indicates the process was killed for some reason (likely running out of memory). Please file an issue at https://community.rstudio.com/c/shiny/8.
