### ISSUE TITLE
Autocomplete fails for R object in Python RMD code chunks

### ISSUE THREAD

**Issue by slopp** [rstudio/reticulate#943]
I am seeing an issue where inside a reticulated RMD, RStudio’s tab complete within a Python code chunk for the magic `r.` object doesn’t do what I expect. It shows some methods, e.g. `r.__class__`,  but doesn’t autocomplete any of the objects inside the R environment.

The RMD renders (and code chunk runs) just fine

In contrast, the autocomplete in a R code chunk for the `py$` object does do what I expect and shows all R objects.

I've reproduced this on https://github.com/rstudio/reticulate/commit/e2f72f1f01186467e82d3c01109516b312e722f3 and on CRAN 1.18.

**Comment by kevinushey** [comment]
This should now be resolved in the development version of RStudio.
