### ISSUE TITLE
Which class should I have in R so that its gets converted to int class in python environment.

### ISSUE THREAD

**Issue by yogesh-bansal** [rstudio/reticulate#945]
I want to pass 10^18 as an argument to a python module's function which expects the argument as int. I have tried having the value as numeric, integer64(from bit64), bigz(from gmp), But nothing is passed as int to python environment. Any ideas on how I can achieve this in R environment by not changing anything in python side?

**Comment by kevinushey** [comment]
Here's one way forward:

```
library(reticulate)
builtins <- import_builtins(convert = FALSE)
px <- builtins$int(10^18)
```

Does that do what you need?

**Comment by yogesh-bansal** [comment]
Thanks, Didn't knew we could actually pass the python objects as arguments when calling python functions from R.
This solved the issue.
