### ISSUE TITLE
Cannot install all packages of python

### ISSUE THREAD

**Issue by featherduino** [rstudio/reticulate#959]
installation successful for a gcp package but cannot import it somehow 
![Screenshot 2021-02-19 at 9 32 03 PM](https://user-images.githubusercontent.com/17808683/108541062-06720380-7308-11eb-8a68-f54f44d734d1.png)

**Comment by kevinushey** [comment]
Does `import("gcp")` work? Note that the Conda package and the actual Python module can have different names.

**Comment by featherduino** [comment]
yeah true i tried something else and it worked 
the name is different
