### ISSUE TITLE
Reticulate's python ignores DYLD_LIBRARY_PATH env variable

### ISSUE THREAD

**Issue by kirillseva** [rstudio/reticulate#96]
Tried with both conda and virtualenv on Mac OS X 10.12. Sourcing the virtualenv and importing keras works in python, but not with the `keras` package.

Cross-posting the issue here, feel free to close either of those.
https://github.com/rstudio/keras/issues/115

I'd be happy to volunteer to fix this issue, but I don't know where to start - any suggestions?

**Comment by kirillseva** [comment]
Found a similar issue for Ubuntu in this repo, but looks like Mac's issue has something to do with SIP.
https://github.com/nteract/nteract/issues/1523

**Comment by kirillseva** [comment]
For what it's worth, linking cuda's dylibs into /usr/local/lib didn't help either

**Comment by kirillseva** [comment]
For what it's worth I'm really confused now
```
library(reticulate)
osenviron
os <- import("os")
os$environ$get("DYLD_LIBRARY_PATH")
[1] "/usr/local/cuda/lib:/usr/local/cuda/lib:/Developer/NVIDIA/CUDA-8.0/lib"
```

And yet
```
GAUSS> import("tensorflow")
Error in py_module_import(module, convert = convert) :
  ImportError: Traceback (most recent call last):
  File "/Users/kirillseva/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/kirillseva/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/kirillseva/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dlopen(/Users/kirillseva/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/kirillseva/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/
```

**Comment by jjallaire** [comment]
This is not a reticulate issue as we have nothing to do with how shared libraries are resolved once we get past the Python shared library itself. This is handled at the operating system level and as you correctly surmise has to do with the various environment variables that control where shared libraries are loaded from. Here's an extensive discussion of your error condition on the TensorFlow repo:

https://github.com/tensorflow/tensorflow/issues/6729

Note that if you are running within RStudio or R GUI then you don't automatically get all of the environment variables set in e.g. ~/.bash_profile. You need to either launch RStudio or R GUI from a Terminal or do this: https://support.shotgunsoftware.com/hc/en-us/articles/219042108-Setting-global-environment-variables-on-OS-X

**Comment by jjallaire** [comment]
Also note that you need to set DYLD_LIBRARY_PATH, LD_LIBRARY_PATH, etc. *prior to* the creation of the process rather than within it. The python side may have worked because those environment variables are sourced into a shell which then executes the python interpreter.

**Comment by kirillseva** [comment]
I am launching R from terminal, and I tried putting Sys.setenv in my ~/.Rprofile, and even setting the env variable on the python side using reticulate and os$environ.

It does indeed look like something Mac specific, but I can't wrap my head around why using python with r-tensorflow virtualenv works fine, but launching Python from reticulate does not, given the same starting conditions

**Comment by kirillseva** [comment]
How does reticulate create its Python process? It probably doesn't take my env when it does this, and doesn't source ~/.zshrc

**Comment by jjallaire** [comment]
It doesn't create a "Python process", it loads Python into the R process.
Sys.setenv as os$environ are too late (they are set after the R process is
launched).

From reading the GitHub issue, it looks like even if you get the
environment variable issues sorted there is still SIP to consider

**Comment by kirillseva** [comment]
Yeah, that's what it looks like. I start R from the same environment that
can use direct import in Python, so it has exactly the same environment at
start time. I'd love to keep SIP, but if it's R and no sip vs writing
python and SIP - we all know what the right choice is.

I'll try disabling it and will reply to this thread.

If only nvidia would care about convenience of their library distribution...
