### ISSUE TITLE
Reticulate + Shiny + Rmarkdown 

### ISSUE THREAD

**Issue by reyar** [rstudio/reticulate#965]
I cannot call an object created in a R chunk (a data.frame) into a python chunk. All within a Shiny app. 

Could it be an environment problem?! 

Minimal reproducible shiny app is enclosed.

Thanks. 
[Shiny-reticulate-rmarkdown.zip](https://github.com/rstudio/reticulate/files/6075922/Shiny-reticulate-rmarkdown.zip)

**Comment by ivanfedchak** [comment]
Hi Reyar,

I have the same issue with calling an R object in Python within shiny session. 
Can you share ideas how you solve it? Thanks!

**Comment by reyar** [comment]
> Hi Reyar,
> 
> I have the same issue with calling an R object in Python within shiny session.
> Can you share ideas how you solve it? Thanks!

Sure, this was my solution:

```
# Send df to Python 
## Call Python environment 
main <- import_main()
## Replace NA with NaN to be converted correctly by reticulate 
df_cat[is.na(df_cat)] <- NaN
## Add data frame to Python environment 
main$df_cat <- r_to_py(df_cat)
```
