### ISSUE TITLE
Automatic python dependency configuration

### ISSUE THREAD

**Issue by willi3by** [rstudio/reticulate#986]
Hi,

I am trying to set up automatic configuration of python dependencies for an R package I am developing. I have added the reticulate config to the Description file and added an import to the onLoad function in a file in the R folder, but it does not seem to be automatically loading. 

Here is the description file:
```
Package: ambraSDKrv2
Type: Package
Title: Interface from R to AMBRA SDK
Version: 0.2.0
Author: Brady Williamson, PhD
Maintainer: Brady Williamson <willi3by@ucmail.uc.edu>
Description: More about what it does (maybe more than one line)
    Use four spaces when indenting paragraphs within the Description.
Config/reticulate:
  list(
    packages = list(
      list(package = "ambra_sdk")
    )
  )
License: GPL-3
Encoding: UTF-8
LazyData: true
Imports: 
    reticulate
```

And here is the .onLoad function (written in zzz.R in the R folder within the package):
```
.OnLoad <- function(libname, pkgname) {
  reticulate::configure_environment(pkgname)
  ambra <<- reticulate::import("ambra_sdk")
}
```

I am using the following versions:
R - 4.0.3
Rstudio - 1.4.904
reticulate - 1.18-9008
python - 3.7

Any guidance is greatly appreciated. Let me know if you need any more info. 

Thanks!

**Comment by kevinushey** [comment]
```
.OnLoad <- function(libname, pkgname) {
  reticulate::configure_environment(pkgname)
  ambra <<- reticulate::import("ambra_sdk")
}
```

Is that a typo perchance? Should that be `.onLoad` instead of `.OnLoad` (note the lower-case `o`)

**Comment by willi3by** [comment]
Indeed it was, I feel ridiculous... sorry for wasting your time, I greatly appreciate the response!

**Comment by kevinushey** [comment]
No worries! Happens to the best of us :-)
