### ISSUE TITLE
Pass a parameter to Python via R by Reticulate library

### ISSUE THREAD

**Issue by KamalAlipour** [rstudio/reticulate#99]
Here is my code in Python:
import venpy
model = venpy.load(myModelName)
landUseMatrix=model.result(names=['land use matrix'])
 
It's working, but if I run it with RStudio by following codes, unexpected Error: unexpected '[' in the last statement occurs . I'll appreciate any hint.

Here is my code in RStudio:
library(reticulate)
venpy<- import("venpy") 
model = venpy$load(myModelName)
landUseMatrix<-model$result(names =['land use matrix'], vtype=NULL)

**Comment by jjallaire** [comment]
You are using Python array literal syntax, try this instead:

```r
model$result(names = c('land use matrix'), vtype=NULL)
```

**Comment by KamalAlipour** [comment]
Thank you so much for your fast answer.
