### ISSUE TITLE
Virtualenv not recognized or used

### ISSUE THREAD

**Issue by vhpietil** [rstudio/reticulate#991]
I make a virtual environment and install a module there. Then I try to use that environment but the module is not available

However, I am able to verify that my base environment does not have holidays-module but myenv does

#Example

library(reticulate)
virtualenv_create("myenv", packages = "holidays")
#> Using Python: /usr/bin/python3.8
#> Creating virtual environment 'myenv' ... Done!
#> Installing packages: 'pip', 'wheel', 'setuptools', 'holidays'
#> Virtual environment 'myenv' successfully created.
use_virtualenv("myenv")
holi <- import("holidays")
#> Error in py_module_import(module, convert = convert): ModuleNotFoundError: No module named 'holidays'
#> 
#> Detailed traceback: 
#>   File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 19, in _import_hook
#>     module = _import(

sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.1 LTS
#> 
#> Matrix products: default
#> BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] reticulate_1.18
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.6        lattice_0.20-41   digest_0.6.27     assertthat_0.2.1 
#>  [5] grid_4.0.3        jsonlite_1.7.2    magrittr_2.0.1    reprex_1.0.0     
#>  [9] evaluate_0.14     highr_0.8         stringi_1.5.3     rlang_0.4.10     
#> [13] cli_2.3.0         rstudioapi_0.13   fs_1.5.0          Matrix_1.2-18    
#> [17] rmarkdown_2.6     tools_4.0.3       stringr_1.4.0     glue_1.4.2       
#> [21] xfun_0.21         yaml_2.2.1        compiler_4.0.3    htmltools_0.5.1.1
#> [25] knitr_1.31

py_discover_config()
#> python:         /usr/bin/python3
#> libpython:      /usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.so
#> pythonhome:     //usr://usr
#> version:        3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
#> numpy:          /home/pietvil/.local/lib/python3.8/site-packages/numpy
#> numpy_version:  1.19.5
#> 
#> NOTE: Python version was forced by RETICULATE_PYTHON

**Comment by kevinushey** [comment]
You probably want:

```
use_virtualenv("myenv", required = TRUE)
```

**Comment by vhpietil** [comment]
Unfortunately that does not help

library(reticulate)
use_virtualenv("myenv", required = TRUE)
holi <- import("holidays")
# Error in py_module_import(module, convert = convert) : 
# ModuleNotFoundError: No module named 'holidays'

**Comment by vhpietil** [comment]
Few updates:
Example above was run in Rstudio server running in a container on an ec2 instance. It works fine when I run it in Rstudio on my local Windows laptop.

Virtual environment works fine, if I create the virtual environment using these steps https://support.rstudio.com/hc/en-us/articles/360023654474-Installing-and-Configuring-Python-with-RStudio and add `Sys.setenv(RETICULATE_PYTHON = "myenv/bin/python")` to my .Rprofile.

**Comment by vhpietil** [comment]
I managed to fix the problem by removing environment variable RETICULATE_PYTHON first.

Sys.unsetenv("RETICULATE_PYTHON")

**Comment by kevinushey** [comment]
That makes sense. `RETICULATE_PYTHON` overrides any other Python request so if you have that set any calls to `use_python()` are effectively ignored.
