### ISSUE TITLE
knitr could change name of internal wrap() function while exporting it

### ISSUE THREAD

**Issue by cderv** [rstudio/reticulate#993]
@yihui I believe the change in https://github.com/yihui/knitr/commit/db7345ba1414c75ac0d050598cba965b40a9dce7 for https://github.com/yihui/knitr/issues/1853 will break **reticulate** python engine

Currently it is using the unexported `wrap` function 
https://github.com/rstudio/reticulate/blob/c0d4821ceb596d680700b40f7319c97c7d5a9ff3/R/knitr-engine.R#L455-L461

Exporting the function will help remove this trick, but changing its name will require adaptation. 
@kevinushey I open this issue so that the change that will happen we'll be correctly taken into account here.

**Comment by yihui** [comment]
`wrap()` is still an internal function in **knitr** after this change. It's not removed (and won't be removed without extreme caution), so it won't really break **reticulate**. Anyway, I do recommend using `knitr::engine_output()` instead of `knitr:::wrap()`, and just sent a PR #994.
